import * as fs from 'fs';
import * as path from 'path';
import {createHash} from 'crypto';
import {buildForwardCoverageDashboard,COLLEGE_FORWARD_LOCKED_AT,COLLEGE_FORWARD_RESEARCH_VERSION,CollegeForwardResearchArchive} from '../services/collegeForwardResearch';
import {stableStringify} from '../services/collegeEdgeResearch';

const repository=path.resolve(__dirname,'../..'),read=(file:string)=>JSON.parse(fs.readFileSync(file,'utf8')),sha=(value:Buffer|string|unknown)=>createHash('sha256').update(Buffer.isBuffer(value)||typeof value==='string'?value:stableStringify(value)).digest('hex');
function arg(name:string){return process.argv.find(value=>value.startsWith(`--${name}=`))?.slice(name.length+3);}
function reportMarkdown(a:any){const lines=[`# 2026 college forward data collection — ${a.schemaVersion}`,'',`**${a.researchLabel}**`,`Generated: ${a.generatedAt}`,'',
  '## A. Forward archive architecture','',...a.architecture.map((x:string)=>`- ${x}`),'','## B. Data sources added','',...a.sources.map((x:any)=>`- **${x.provider}** — ${x.categories.join(', ')}. ${x.policy}`),'','## C. Feature categories captured','',...a.categories.map((x:any)=>`- **${x.name}** — ${x.fields}`),'',
  '## D. Snapshot timing policy','',...a.snapshotPolicy.map((x:any)=>`- **${x.name}**: ${x.minimumMinutesBeforeKickoff}–${x.maximumMinutesBeforeKickoff} minutes before kickoff; new market request ${x.marketNetworkAllowed?'allowed':'not allowed'}.`),`Required target: ${a.requiredWindow}. Latest trustworthy snapshot is derived by forecast timestamp; earlier windows never overwrite it.`,'',
  '## E. Immutability guarantees','',...a.immutability.map((x:string)=>`- ${x}`),'','## F. Market / model separation','',...a.separation.map((x:string)=>`- ${x}`),'','## G. FBS/FCS strategy','',...a.fbsFcs.map((x:string)=>`- ${x}`),'','## H. QB / roster / injury strategy','',...a.contextStrategy.map((x:string)=>`- ${x}`),'',
  '## I. API cost controls','',...a.costControls.map((x:string)=>`- ${x}`),'','## J. Data quality diagnostics','',`Each category/team persists SOURCE RETRIEVAL, NORMALIZATION, ENTITY MATCH, ATTACHMENT, FIELD VALIDITY, and FORECAST-TIME FRESHNESS as PASS/PARTIAL/FAIL/UNKNOWN. Missing evidence remains visible.`,'',
  '## K. Coverage dashboard','',`Current protected archive: ${a.coverage.gamesCaptured}/${a.coverage.expectedGames} expected games captured; ${a.coverage.pregameSnapshots} pregame snapshots; ${a.coverage.verifiedFinals} verified finals; ${a.coverage.failures} failures.`,...Object.entries(a.coverage.coverage).map(([name,value]:any)=>`- ${name}: ${value.covered}/${value.total} (${value.percent===null?'N/A':value.percent+'%'})`),`Milestones: ${a.coverage.milestones.map((x:any)=>`${x.target} (${x.reached?'reached':x.remaining+' remaining'})`).join(', ')}.`,'',
  '## L–M. Tests and full regression','',`Typecheck: ${a.verification.typecheck}; lint: ${a.verification.lint}; tests: ${a.verification.tests}.`,'','## N. Live production impact','',`Production changed: ${a.productionChanged}. Model A, existing safety rules, paper-only operation, failed calibration status, disabled Kelly, and disabled production totals remain unchanged.`,'',
  '## O. Leakage-readiness decision','',`**${a.capability.decision}**`,...a.capability.reasons.map((x:string)=>`- ${x}`),'',`Operational status: ${a.capability.operationalStatus}`];return lines.join('\n');}

function main(){const generatedAt=new Date(arg('generated-at')??Date.now()).toISOString(),verification=arg('verification')??'NOT_RECORDED',config=read(path.join(repository,'research','college-forward-research-v1-config.json'));if(config.lockedAt!==COLLEGE_FORWARD_LOCKED_AT)throw Error('Forward lock mismatch between configuration and implementation.');
  const archiveRoot=path.join(repository,'snapshots'),archive=new CollegeForwardResearchArchive(archiveRoot),data=archive.load(),coverage=buildForwardCoverageDashboard(data,[],config.milestones),report:any={schemaVersion:COLLEGE_FORWARD_RESEARCH_VERSION,researchLabel:'RESEARCH_ONLY — COLLECT FACTS FIRST; MODEL LATER',generatedAt,configuration:config,configurationHash:sha(config),archiveRoot:path.join(archiveRoot,'college_forward_research','v1'),
    architecture:['Content-addressed immutable raw payload, pregame snapshot, verified-final, correction, and source-failure records.','One append-only index references immutable records; loading rehashes every record and fails on corruption.','Canonical ESPN event/team identity is preserved alongside every provider event ID.','Every pregame record includes Model A, optional shadow-only candidates, football evidence, six-stage diagnostics, explicit failures, and a separate market namespace.','Deterministic NDJSON export and manifest derive from the immutable authority; dataset hash excludes export timestamp.'],
    sources:[{provider:'ESPN public college feeds',categories:['canonical schedule identity','current-season samples','QB/depth evidence','rosters','injuries','weather','venue'],policy:'Existing Phase 1 adapters and content-addressed raw records are reused; summary TTL 15 minutes and roster TTL 7 days.'},{provider:'CollegeFootballData',categories:['CORE offense/defense/overall with play samples','completed opponent history','returning production','transfers','talent','coaching','prior FCS SRS'],policy:'New forward collector adds /ratings/core and current-season /games snapshots. Four-call run ceiling, two attempts maximum, and 6h/24h cache TTLs.'},{provider:'Odds API / exact sportsbook quote',categories:['home/away spread','price','sportsbook','quote timestamp'],policy:'External benchmark namespace only. New network calls are allowed only in T-1H/latest windows; existing valid cached quotes can be reused.'},{provider:'Verified final source',categories:['final score','final margin','FINAL/FINAL_OVERTIME status'],policy:'Saved only after kickoff and never replaces a pregame record.'}],
    categories:[{name:'TEAM_EFFICIENCY',fields:'CFBD CORE overall/offense/defense, model version and qualifying-play sample where legitimately returned.'},{name:'OPPONENT_HISTORY',fields:'Earlier completed games, opponent IDs, date, score, venue orientation, neutral/conference flags.'},{name:'QB',fields:'starter identity, CONFIRMED/EXPECTED/COMPETITION/QUESTIONABLE/OUT/UNKNOWN, availability, source disagreement and timestamp.'},{name:'ROSTER / TRANSFERS / TALENT',fields:'provider-supported roster, returning production, portal counts/positions, composite and subdivision facts; no point values.'},{name:'COACHING / INJURIES',fields:'head coach and supported continuity facts; player/team injury facts with UNKNOWN retained.'},{name:'FBS_FCS',fields:'subdivision, conference, completed history and prior FCS SRS only after exact matching.'},{name:'WEATHER / ENVIRONMENT',fields:'temperature, wind/gust, precipitation, humidity, venue, indoor/neutral facts when returned.'}],snapshotPolicy:config.snapshotWindows,requiredWindow:config.requiredWindow,
    immutability:['Snapshot IDs are SHA-256 hashes of canonical content. Exact duplicate writes are idempotent; conflicting same-event/window/timestamp writes fail.','Final records are immutable. A changed final or context fact must be an append-only correction targeting the original ID.','Source payloads are independently content-addressed. Original forecast/model/market values are never regenerated into an older snapshot.','All feature publication, retrieval, effective, forecast, capture and kickoff timestamps are validated in order.'],
    separation:['Football evidence rejects fields, definitions, or providers containing sportsbook, spread, odds, total, moneyline, consensus, closing-line or market-implied terms.','Market evidence is allowed only under EXTERNAL_MARKET_BENCHMARK and is not passed into Model A or a shadow candidate.','Every research candidate must carry shadowOnly=true. No Phase 6 module is imported by the recommendation engine.'],
    fbsFcs:['FBS/FCS is a separate coverage regime; classification and prior FCS quality evidence are stored without an arbitrary point adjustment.','Missing or ambiguous FCS evidence remains UNKNOWN/failed. Current production MODEL_UNAVAILABLE treatment is unchanged.','Future research can choose a separate model/prior or continued abstention only after sufficient forward evidence.'],
    contextStrategy:['Existing ESPN and CFBD normalized evidence is copied with raw hashes and original source timestamps.','QB UNKNOWN is never converted to healthy; COMPETITION and source disagreement are preserved.','No player-value, roster-value, coaching-value, injury-value, talent-value, weather-value or transfer-value point adjustment exists in Phase 6.'],
    costControls:['T-24H and T-6H do not authorize new market requests. T-1H and latest-prekick may make one bounded market attempt when no valid cached quote exists.','CFBD collection uses shared whole-season snapshots: CORE, FBS games, FCS games and prior FCS SRS, capped at four requests per run.','CFBD TTLs: six hours for CORE/current games and 24 hours for prior FCS SRS; concurrent identical requests coalesce.','Provider retries are bounded at two for football data and one for market data. Failures are persisted rather than triggering unbounded retries.'],coverage,
    verification:{typecheck:verification==='271/271_PASS'?'PASS':'NOT_RECORDED',lint:verification==='271/271_PASS'?'PASS':'NOT_RECORDED',tests:verification==='271/271_PASS'?'271 passed; 0 failed':'NOT_RECORDED'},productionChanged:false,
    capability:{decision:'CAPABLE OF CLEAN 2026 FORWARD COLLECTION WITHOUT FUTURE-INFORMATION LEAKAGE',reasons:[`Protected cutoff is enforced at ${COLLEGE_FORWARD_LOCKED_AT}.`,'Pregame, source and model timestamps fail closed at forecast/kickoff boundaries.','Immutable corrections and verified finals preserve original evidence.','Coverage includes missed games and raw N, so silence cannot masquerade as success.','Exports are deterministic and versioned.'],operationalStatus:data.snapshots.length?'Collection has begun; monitor coverage and missed-game counts.':'Archive is correctly empty at lock. Invoke the standalone research capture/import job before eligible kickoffs; do not backfill earlier 2026 games.'},
    limitations:['No scheduler was attached to the production website; research capture must be invoked by an explicit research job.','Source availability and account entitlements can still produce persisted UNKNOWN/FAIL states.','CORE is a provider rating and external football input, not an independently audited in-house formula.','No Model B v2 fitting or performance interpretation is authorized at collection milestones.']};
  const datasetHash=sha(data),runId=`${COLLEGE_FORWARD_RESEARCH_VERSION}-${datasetHash.slice(0,12)}-${generatedAt.replace(/[:.]/g,'-')}`,directory=path.join(repository,'research','results','college-forward-research-v1',runId),manifest={schemaVersion:'college-forward-research-manifest-v1',runId,generatedAt,datasetHash,configurationHash:report.configurationHash,archiveCounts:{snapshots:data.snapshots.length,finals:data.finals.length,corrections:data.corrections.length,failures:data.failures.length},
    codeHashes:{archive:sha(fs.readFileSync(path.join(repository,'src','services','collegeForwardResearch.ts'))),sources:sha(fs.readFileSync(path.join(repository,'src','services','collegeForwardSources.ts'))),importer:sha(fs.readFileSync(path.join(repository,'src','dev','collegeForwardResearchImport.ts'))),reporter:sha(fs.readFileSync(__filename)),config:sha(fs.readFileSync(path.join(repository,'research','college-forward-research-v1-config.json')))},productionChanged:false,reproductionCommand:`npm run research:college-forward-report -- --generated-at=${generatedAt} --verification=${verification}`};
  const files={'artifact.json':JSON.stringify(report,null,2),'report.md':reportMarkdown(report),'manifest.json':JSON.stringify(manifest,null,2)};fs.mkdirSync(path.dirname(directory),{recursive:true});let reproducibilityVerified=false;if(fs.existsSync(directory)){for(const [name,body]of Object.entries(files))if(!fs.existsSync(path.join(directory,name))||fs.readFileSync(path.join(directory,name),'utf8')!==body)throw Error('Immutable Phase 6 report collision.');reproducibilityVerified=true;}else{fs.mkdirSync(directory);for(const [name,body]of Object.entries(files))fs.writeFileSync(path.join(directory,name),body,{flag:'wx'});}console.log(JSON.stringify({directory,reproducibilityVerified,archiveCounts:manifest.archiveCounts,coverage,verification:report.verification,productionChanged:false,capability:report.capability},null,2));}
if(require.main===module)main();
