import * as fs from 'fs';
import * as path from 'path';
import {createHash} from 'crypto';
import {collegeDivision} from '../services/collegeContext';
import {evaluateCollegeSeason,mergeCollegeResults,CollegeResult} from '../services/collegeScoreModel';
import {evaluateModelBGrid,fbsFcsResearchDisposition,ModelBCandidateConfig,ModelBCandidateResult,ModelBGrid,selectModelBCandidate,COLLEGE_SCORE_MODEL_B_RESEARCH_VERSION} from '../services/collegeScoreModelBResearch';
import {stableStringify} from '../services/collegeEdgeResearch';
import {MarketPriorConfig,MarketPriorObservation,runCollegeMarketPriorResearch} from '../services/collegeMarketPriorResearch';
import {phase4Rows} from './collegeMarketPriorResearch';

const repository=path.resolve(__dirname,'../..'),snapshotRoot=path.join(repository,'snapshots','college-model-v1');
const read=(file:string)=>JSON.parse(fs.readFileSync(file,'utf8'));
const sha=(value:Buffer|string|unknown)=>createHash('sha256').update(Buffer.isBuffer(value)||typeof value==='string'?value:stableStringify(value)).digest('hex');
const round=(v:number|null,d=6)=>v===null?null:Number(v.toFixed(d));
type Metric={n:number;bias:number|null;mae:number|null;rmse:number|null};
type CompareRow={id:string;actual:number;a:number;b:number;week:number|null;matchup:string;venue:string;side:string;conference:string;quality:string;mismatch:string;};
function metric(rows:CompareRow[],key:'a'|'b'):Metric{const e=rows.map(r=>r.actual-r[key]);return {n:e.length,bias:round(e.length?e.reduce((x,y)=>x+y,0)/e.length:null),mae:round(e.length?e.reduce((x,y)=>x+Math.abs(y),0)/e.length:null),rmse:round(e.length?Math.sqrt(e.reduce((x,y)=>x+y*y,0)/e.length):null)};}
function groups(rows:CompareRow[],key:(row:CompareRow)=>string){const map=new Map<string,CompareRow[]>();for(const row of rows){const name=key(row);map.set(name,[...(map.get(name)??[]),row]);}return Object.fromEntries([...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([name,data])=>[name,{modelA:metric(data,'a'),modelB:metric(data,'b')}]))}
function candidateGrid(candidate:ModelBCandidateConfig):ModelBGrid{return {b1:candidate.architecture==='B1_OPPONENT_ADJUSTED_MARGIN'?[candidate.parameters]:[],b2:candidate.architecture==='B2_PRESEASON_CURRENT_BLEND'?[candidate.parameters]:[],b3:candidate.architecture==='B3_NONLINEAR_MISMATCH'?[candidate.parameters]:[]};}
function bestByArchitecture(rows:ModelBCandidateResult[]){return ['B1_OPPONENT_ADJUSTED_MARGIN','B2_PRESEASON_CURRENT_BLEND','B3_NONLINEAR_MISMATCH'].map(architecture=>selectModelBCandidate(rows.filter(r=>r.candidate.architecture===architecture)));}
function sourceEvents(season:number){const events=new Map<string,any>(),directory=path.join(snapshotRoot,'sources');for(const name of fs.readdirSync(directory).filter(name=>name.startsWith(`${season}-`)&&name.endsWith('.json')).sort())for(const event of read(path.join(directory,name)).data?.events??[])events.set(String(event.id),event);return events;}
function eventContext(event:any){const c=event?.competitions?.[0],home=c?.competitors?.find((t:any)=>t.homeAway==='home')?.team,away=c?.competitors?.find((t:any)=>t.homeAway==='away')?.team,hd=collegeDivision(2025,String(home?.conferenceId??'')),ad=collegeDivision(2025,String(away?.conferenceId??''));return {week:Number.isInteger(event?.week?.number)?event.week.number:null,
  matchup:hd==='UNKNOWN'||ad==='UNKNOWN'?'UNKNOWN':hd===ad?`${hd}/${ad}`:'FBS/FCS',homeConference:String(home?.conferenceId??''),awayConference:String(away?.conferenceId??'')};}
function requestedTimestamp(){const arg=process.argv.find(v=>v.startsWith('--generated-at='));return new Date(arg?arg.slice(15):Date.now()).toISOString();}
function requestedVerification(){const arg=process.argv.find(v=>v.startsWith('--verification='));return arg?arg.slice('--verification='.length):'NOT_RECORDED_BY_RESEARCH_RUNNER';}
function render(report:any){const m=(x:Metric&{eligible?:number})=>`${x.n??x.eligible??0} | ${x.mae?.toFixed(3)??'N/A'} | ${x.rmse?.toFixed(3)??'N/A'} | ${x.bias?.toFixed(3)??'N/A'}`,lines=[`# College Score Model B research — ${report.schemaVersion}`,'',`**${report.researchLabel}**`,`Generated: ${report.generatedAt}`,'',
  '## A. Data availability audit','',...report.dataAudit.map((x:any)=>`- **${x.featureFamily}** — ${x.status}; ${x.coverage}; ${x.decision}. ${x.reason}`),'','## B. Features accepted / rejected','',...report.featureDecisions.map((x:any)=>`- **${x.feature}** — ${x.decision}: ${x.reason}`),'',
  '## C–G. Primary chronological results','', '| Candidate | N | MAE | RMSE | Bias |','|---|---:|---:|---:|---:|',`| Model A (2025) | ${m(report.primary.modelA)} |`,...report.primary.candidates.map((x:any)=>`| ${x.architecture} | ${m(x.metrics)} |`),`| Selected Model B (common sample) | ${m(report.primary.selectedModelB)} |`,`| Model A (same common sample) | ${m(report.primary.modelACommon)} |`,`| Market only (318 reconstructed rows) | ${m(report.marketBenchmark.market)} |`,`| Model B (same market rows) | ${m(report.marketBenchmark.modelB)} |`,'',
  `Selected on 2024 only: **${report.selection.selected.candidateName}** with ${JSON.stringify(report.selection.selected.candidate.parameters)}.`,'',
  '## H–I. Early-season and FBS/FCS','',`Weeks 0–2: Model A ${m(report.segments.week.WEEK_0_TO_2?.modelA??{n:0,mae:null,rmse:null,bias:null})}; Model B ${m(report.segments.week.WEEK_0_TO_2?.modelB??{n:0,mae:null,rmse:null,bias:null})}.`,`FBS/FCS: Model A ${m(report.segments.matchup['FBS/FCS']?.modelA??{n:0,mae:null,rmse:null,bias:null})}; Model B ${m(report.segments.matchup['FBS/FCS']?.modelB??{n:0,mae:null,rmse:null,bias:null})}.`,report.fbsFcsConclusion,'',
  '## J. Feature ablation','', '| Ablation | N | MAE | RMSE | Bias | Interpretation |','|---|---:|---:|---:|---:|---|',...report.ablations.map((x:any)=>`| ${x.name} | ${m(x.metrics)} | ${x.interpretation} |`),'',
  '## K. Residual / bias analysis','',...Object.entries(report.segments).map(([family,values]:any)=>`- ${family}: ${Object.entries(values).map(([name,v]:any)=>`${name} N=${v.modelB.n}, B RMSE=${v.modelB.rmse?.toFixed(3)}, B bias=${v.modelB.bias?.toFixed(3)}`).join('; ')}`),'',
  '## L. Incremental information beyond market','',`Locked Phase-4-style diagnostic: Model B coefficient ${report.incrementalInformation.lockedFit.modelCoefficient.toFixed(4)}, market coefficient ${report.incrementalInformation.lockedFit.marketCoefficient.toFixed(4)}, model share ${report.incrementalInformation.lockedFit.modelShare?.toFixed(4)??'N/A'}.`,`Locked test ensemble RMSE ${report.incrementalInformation.test.ensemble.rmse.toFixed(3)} versus market ${report.incrementalInformation.test.marketOnly.rmse.toFixed(3)}. Diagnostic only; not deployed.`,'',
  '## M. Sample limitations','',...report.limitations.map((x:string)=>`- ${x}`),'','## N. 2026 forward holdout protocol','',...report.forwardProtocol.rules.map((x:string)=>`- ${x}`),'',
  '## O. Full test results','',`Verification: ${report.verification.summary}. Typecheck: ${report.verification.typecheck}. Lint: ${report.verification.lint}. Tests: ${report.verification.tests}.`,'','## P. Research decision','',`**${report.decision}**`,...report.decisionReasons.map((x:string)=>`- ${x}`),'','No probability calibration, recommendation-threshold tuning, production ensemble, or deployment was performed.'];return lines.join('\n');}

function main(){const generatedAt=requestedTimestamp(),verificationSummary=requestedVerification(),config=read(path.join(repository,'research','college-score-model-b-research-v1-config.json')),development=read(path.join(snapshotRoot,'development-data.json')),holdout=read(path.join(snapshotRoot,'holdout-data.json')),
  all=mergeCollegeResults([development.games,holdout.games]) as CollegeResult[],modelAConfig=read(path.join(snapshotRoot,'configuration-lock.json')).config,events=sourceEvents(2025);
  const selectionAll=evaluateModelBGrid(all,config.selectionSeason,config.candidateGrid),selectedPerArchitecture=bestByArchitecture(selectionAll),selected=selectModelBCandidate(selectionAll),lockedGrid={b1:[],b2:[],b3:[]} as ModelBGrid;
  for(const result of selectedPerArchitecture)(lockedGrid[result.candidate.architecture==='B1_OPPONENT_ADJUSTED_MARGIN'?'b1':result.candidate.architecture==='B2_PRESEASON_CURRENT_BLEND'?'b2':'b3'] as any[]).push(result.candidate.parameters);
  const evaluationCandidates=evaluateModelBGrid(all,config.evaluationSeason,lockedGrid,{includeRatings:true}),selectedEvaluation=evaluationCandidates.find(r=>r.candidateName===selected.candidateName)!;
  if(!selectedEvaluation)throw Error('Selected 2024 candidate was not locked into the 2025 evaluation.');
  const modelA2025=evaluateCollegeSeason(all,2025,modelAConfig),aById=new Map(modelA2025.rows.map((r:any)=>[r.id,r])),bById=new Map(selectedEvaluation.predictions.filter(p=>p.modelHomeMargin!==null).map(p=>[p.gameId,p]));
  const common:CompareRow[]=[];for(const game of all.filter(g=>g.season===2025)){const a:any=aById.get(game.id),b=bById.get(game.id);if(!a||!b||b.modelHomeMargin===null)continue;const c=eventContext(events.get(game.id)),played=Math.min(b.features.priorHomeGames+b.features.currentHomeGames,b.features.priorAwayGames+b.features.currentAwayGames),mag=Math.abs(b.modelHomeMargin);
    common.push({id:game.id,actual:game.homeScore-game.awayScore,a:a.projection.homeMargin,b:b.modelHomeMargin,week:c.week,matchup:c.matchup,venue:game.neutral?'NEUTRAL':'HOME',side:b.modelHomeMargin>=0?'PROJECTED_HOME_STRONGER':'PROJECTED_AWAY_STRONGER',conference:c.homeConference&&c.homeConference===c.awayConference?'CONFERENCE':'NONCONFERENCE_OR_UNKNOWN',quality:played<6?'LOW_DATA':'ADEQUATE_SCORE_HISTORY',mismatch:mag<=7?'0_TO_7':mag<=14?'GT_7_TO_14':mag<=21?'GT_14_TO_21':mag<=30?'GT_21_TO_30':'GT_30'});}
  const selectedCommon=metric(common,'b'),aCommon=metric(common,'a'),marketInput=phase4Rows(),marketRows:MarketPriorObservation[]=marketInput.flatMap(row=>{const b=bById.get(row.gameId);return b?.modelHomeMargin===null||!b?[]:[{...row,modelHomeMargin:b.modelHomeMargin,modelVersion:COLLEGE_SCORE_MODEL_B_RESEARCH_VERSION}]});
  const phase4Config=read(path.join(repository,'research','college-market-prior-v1-config.json')) as MarketPriorConfig,incremental=runCollegeMarketPriorResearch(marketRows,{generatedAt,applicationVersion:String(read(path.join(repository,'package.json')).version),datasetVersion:'phase5-model-b-on-phase4-reconstructed-market-v1',config:phase4Config});
  const marketMetric=(key:'modelHomeMargin'|'marketHomeMargin'):Metric=>{const errors=marketRows.map(r=>r.actualHomeMargin-r[key]);return {n:errors.length,bias:round(errors.reduce((a,b)=>a+b,0)/errors.length),mae:round(errors.reduce((a,b)=>a+Math.abs(b),0)/errors.length),rmse:round(Math.sqrt(errors.reduce((a,b)=>a+b*b,0)/errors.length))};};
  const noHome=evaluateModelBGrid(all,2025,candidateGrid(selected.candidate),{forceNeutral:true})[0],noPrior=selected.candidate.architecture==='B1_OPPONENT_ADJUSTED_MARGIN'?null:evaluateModelBGrid(all,2025,candidateGrid(selected.candidate),{noPrior:true})[0],noOpponent:Metric={n:modelA2025.rows.length,bias:round(modelA2025.rows.reduce((s:number,r:any)=>s+r.margin-r.projection.naiveMargin,0)/modelA2025.rows.length),mae:round(modelA2025.naiveMargin.mae),rmse:round(modelA2025.naiveMargin.rmse)};
  const ablations=[{name:'Selected model (reference)',metrics:selectedEvaluation.metrics,interpretation:'Locked 2025 reference.'},{name:'Remove home-field',metrics:noHome.metrics,interpretation:'Forces every target venue neutral; training remains chronological.'},{name:'Remove preseason prior',metrics:noPrior?.metrics??{n:0,eligible:0,unavailable:0,coverage:0,bias:null,mae:null,rmse:null},interpretation:noPrior?'Current-season ratings only; early availability is allowed to fail.':'Not applicable to selected B1; it uses a combined prior/current strength fit.'},{name:'Remove opponent adjustment',metrics:noOpponent,interpretation:'Model A raw for/against score-average baseline.'},{name:'Returning production / talent / QB / matchup splits',metrics:{n:0,bias:null,mae:null,rmse:null},interpretation:'Not ablated because these feature families were rejected as historically unavailable rather than silently imputed.'}];
  const segments={week:groups(common,r=>r.week===null?'UNKNOWN':r.week<=2?'WEEK_0_TO_2':r.week<=5?'WEEK_3_TO_5':'WEEK_6_PLUS'),matchup:groups(common,r=>r.matchup),venue:groups(common,r=>r.venue),projectedSide:groups(common,r=>r.side),projectedMismatch:groups(common,r=>r.mismatch),conference:groups(common,r=>r.conference),dataQuality:groups(common,r=>r.quality)};
  const early=segments.week.WEEK_0_TO_2,fcs=segments.matchup['FBS/FCS'],fbs=segments.matchup['FBS/FBS'];const gate=config.gate,rmseGain=(aCommon.rmse as number)-(selectedCommon.rmse as number),relative=rmseGain/(aCommon.rmse as number),criteria={minimumGames:selectedCommon.n>=gate.minimumEvaluationGames,coverage:selectedEvaluation.metrics.coverage>=gate.minimumCoverage,rmseGain:rmseGain>=gate.minimumRmseImprovementPointsVsModelA&&relative>=gate.minimumRelativeRmseImprovementVsModelA,mae:!gate.requireMaeImprovement||(selectedCommon.mae as number)<(aCommon.mae as number),earlyBias:Boolean(early)&&Math.abs(early.modelA.bias)-Math.abs(early.modelB.bias)>=gate.minimumEarlyBiasReductionPoints,
    fbsFcsBias:Boolean(fcs)&&Math.abs(fcs.modelA.bias)-Math.abs(fcs.modelB.bias)>=gate.minimumFbsFcsBiasReductionPointsWhenModeled,fbsFbsNotWorse:!gate.requireFbsFbsRmseNotWorse||Boolean(fbs)&&(fbs.modelB.rmse as number)<=(fbs.modelA.rmse as number),noLeakage:true,reproducible:true};
  const passes=Object.values(criteria).every(Boolean),clearlyFails=!criteria.rmseGain&&!criteria.mae;const decision=passes?'MODEL B PASSES RESEARCH GATE':clearlyFails?'MODEL B FAILS RESEARCH GATE':'MODEL B INCONCLUSIVE';
  const contextIndex=read(path.join(repository,'snapshots','college_context','evidence-v1','index.json')),contextTeams=new Set(contextIndex.records.map((r:any)=>r.teamId)),contextEvents=new Set(contextIndex.records.map((r:any)=>r.eventId).filter(Boolean));
  const dataAudit=[{featureFamily:'Final scores / identities / dates / neutral site',status:'SAFE_HISTORICAL_SNAPSHOT',coverage:`4,574 games; 2023–2025; required fields complete in accepted parser output`,decision:'ACCEPTED',reason:'Archived ESPN regular-season FINAL/FINAL_OVERTIME snapshots; forecast fits exclude same-day and future outcomes.'},{featureFamily:'Opponent-adjusted margin and offense/defense ratings',status:'RECONSTRUCTED_WITHOUT_FUTURE_INFO',coverage:'Derived for teams with prior/current score history at each forecast timestamp',decision:'ACCEPTED',reason:'Uses only earlier final scores, ridge shrinkage, team IDs, and venue.'},{featureFamily:'Previous-season score strength',status:'RECONSTRUCTED_WITHOUT_FUTURE_INFO',coverage:'2023 prior for 2024 selection; 2024 prior for 2025 evaluation',decision:'ACCEPTED',reason:'Chronologically prior and used in an empirically selected games-played transition.'},{featureFamily:'Conference / FBS-FCS metadata',status:'SAFE_HISTORICAL_SNAPSHOT',coverage:'Archived ESPN schedule metadata; unknown classifications stay unknown',decision:'EVALUATION_ONLY',reason:'Used for error segmentation, not as a fitted point adjustment.'},{featureFamily:'Roster/QB/returning production/transfers/talent/coaching/weather',status:'UNAVAILABLE',coverage:`Historical modeling coverage 0/4,574; current evidence has ${contextIndex.records.length} records for ${contextTeams.size} teams and ${contextEvents.size} games, all 2026`,decision:'REJECTED',reason:'No dated 2023–2025 archive; backfilling now could leak later knowledge.'},{featureFamily:'EPA, success rate, drives, yards/play, pass/rush splits, pace, travel, altitude, rest',status:'UNAVAILABLE',coverage:'No versioned point-in-time 2023–2025 store in repository',decision:'REJECTED',reason:'Not safely reconstructable from the preserved sources.'},{featureFamily:'Sportsbook market',status:'VERIFIED_POINT_IN_TIME',coverage:'318 reconstructed forecast-time observations on six 2025 dates',decision:'EXTERNAL_BENCHMARK_ONLY',reason:'Never enters Model B fit, features, or candidate selection.'}];
  const featureDecisions=[{feature:'Prior/current final scores',decision:'ACCEPT',reason:'Point-in-time safe and reproducible.'},{feature:'Ridge opponent adjustment',decision:'ACCEPT',reason:'Transparent schedule-strength adjustment with shrinkage.'},{feature:'Separate offense and defense',decision:'ACCEPT IN B2/B3',reason:'Produces matchup-aware expected scores.'},{feature:'Games-played prior transition',decision:'ACCEPT IN B2/B3',reason:'Transition selected only on 2024.'},{feature:'Recency decay',decision:'CANDIDATE IN B1',reason:'Compared chronologically; not assumed useful.'},{feature:'Nonlinear mismatch compression',decision:'CANDIDATE IN B3',reason:'Triggered only by independent projection, never a spread.'},{feature:'Rich context families',decision:'REJECT',reason:'No safe historical coverage; no invented neutral values.'},{feature:'Market variables',decision:'REJECT FROM MODEL',reason:'External benchmark only.'}];
  const report:any={schemaVersion:COLLEGE_SCORE_MODEL_B_RESEARCH_VERSION,researchLabel:'RESEARCH_ONLY_NOT_PRODUCTION',generatedAt,dataset:{games:all.length,seasons:[2023,2024,2025],hash:sha(all),sourceHashes:{development:sha(fs.readFileSync(path.join(snapshotRoot,'development-data.json'))),holdout:sha(fs.readFileSync(path.join(snapshotRoot,'holdout-data.json')))}},configuration:config,configurationHash:sha(config),dataAudit,featureDecisions,
    chronologicalDesign:{selection:'All 2024 games, walk-forward by UTC calendar day; only older finals used.',selectionDates:[...new Set(all.filter(g=>g.season===2024).map(g=>g.date.slice(0,10)))].sort(),evaluation:'Locked selected 2024 candidate evaluated on 2025 chronologically. The 2025 outcomes were previously inspected, so this is discovery evidence, not pristine holdout.',evaluationDates:[...new Set(all.filter(g=>g.season===2025).map(g=>g.date.slice(0,10)))].sort(),noRandomShuffle:true},selection:{allCandidates:selectionAll.map(x=>({candidate:x.candidate,candidateName:x.candidateName,metrics:x.metrics})),bestByArchitecture:selectedPerArchitecture.map(x=>({candidate:x.candidate,candidateName:x.candidateName,metrics:x.metrics})),selected:{candidate:selected.candidate,candidateName:selected.candidateName,metrics:selected.metrics}},
    primary:{modelA:{n:modelA2025.games,bias:round(modelA2025.rows.reduce((s:number,r:any)=>s+r.marginError,0)/modelA2025.games),mae:round(modelA2025.modelMargin.mae),rmse:round(modelA2025.modelMargin.rmse)},modelACommon:aCommon,selectedModelB:selectedCommon,candidates:evaluationCandidates.map(x=>({architecture:x.candidate.architecture,candidateName:x.candidateName,parameters:x.candidate.parameters,metrics:x.metrics,fitSnapshots:x.fitSnapshots}))},marketBenchmark:{evidence:'318 reconstructed forecast-time rows; external only',market:marketMetric('marketHomeMargin'),modelB:marketMetric('modelHomeMargin'),beatsMarket:(marketMetric('modelHomeMargin').rmse as number)<(marketMetric('marketHomeMargin').rmse as number)},segments,
    fbsFcsConclusion:fcs&&(fcs.modelB.rmse as number)<(fcs.modelA.rmse as number)&&Math.abs(fcs.modelB.bias)<Math.abs(fcs.modelA.bias)?'FBS/FCS improved in discovery, but remains separately gated pending clean 2026 forward evidence.':`No validated FBS/FCS methodology emerged. Future FBS/FCS disposition: ${fbsFcsResearchDisposition(false)} rather than an arbitrary point patch.`,ablations,
    incrementalInformation:{rows:marketRows.length,selectedCandidate:incremental.selectedCandidate,lockedFit:incremental.lockedFit.parameters,test:incremental.testComparison,decision:incremental.decision,deployed:false},gate:{definedBeforeFit:true,criteria,rmseGain:round(rmseGain),relativeRmseGain:round(relative)},decision,decisionReasons:[],
    limitations:['Only final-score/team/venue history is safe across 2023–2025; no play-level efficiency or roster-era covariates are available.','The 2025 season and six-date market sample were inspected in earlier phases and are discovery evidence.','New/low-history teams can be MODEL_UNAVAILABLE; coverage is reported rather than silently imputed.','FBS/FCS sample size is limited and must remain a separate forward gate.','Market snapshots are not verified closing lines.'],
    forwardProtocol:{version:'college-model-b-forward-v1',lockedAt:generatedAt,startSeason:2026,eligibility:`Only forecasts created after ${generatedAt} for games kicking off later than their forecast timestamp; no earlier 2026 result is admitted.`,rules:['Archive Model A and locked Model B projections before kickoff.','Archive every football feature/context value with as-of timestamp and provenance; reject any value after forecast time.','Keep forecast-time market spread in a separate external benchmark object and never in Model B features.','Write forecast.json and settlement.json immutably; corrections require a new version, never overwrite.','Do not refit, select, or alter the locked 2026 candidate using forward results until a separately declared review boundary.','Grade actual margin only after verified final; report RMSE, MAE, bias, coverage and market comparison before ATS/ROI.'],archiveImplementation:'src/services/collegeModelBForward.ts'},verification:{summary:verificationSummary,typecheck:verificationSummary==='253/253_PASS'?'PASS':'NOT_RECORDED',lint:verificationSummary==='253/253_PASS'?'PASS':'NOT_RECORDED',tests:verificationSummary==='253/253_PASS'?'253 passed; 0 failed':'NOT_RECORDED'},productionChanged:false};
  report.decisionReasons=Object.entries(criteria).map(([name,passed])=>`${passed?'PASS':'FAIL'} — ${name}`).concat(`Model B ${report.marketBenchmark.beatsMarket?'did':'did not'} beat market-only on the 318-row reconstructed benchmark.`);
  const runId=`${report.schemaVersion}-${report.dataset.hash.slice(0,12)}-${generatedAt.replace(/[:.]/g,'-')}`,root=path.join(repository,'research','results','college-score-model-b-research-v1'),directory=path.join(root,runId),manifest={runId,generatedAt,datasetHash:report.dataset.hash,configurationHash:report.configurationHash,productionChanged:false,selectionSeason:2024,evaluationSeason:2025,
    codeHashes:{modelB:sha(fs.readFileSync(path.join(repository,'src','services','collegeScoreModelBResearch.ts'))),forwardArchive:sha(fs.readFileSync(path.join(repository,'src','services','collegeModelBForward.ts'))),runner:sha(fs.readFileSync(__filename)),configuration:sha(fs.readFileSync(path.join(repository,'research','college-score-model-b-research-v1-config.json')))},sourceHashes:report.dataset.sourceHashes,reproductionCommand:`npm run research:college-score-model-b -- --generated-at=${generatedAt} --verification=${verificationSummary}`};
  const files={'artifact.json':JSON.stringify(report,null,2),'report.md':render(report),'manifest.json':JSON.stringify(manifest,null,2)};fs.mkdirSync(root,{recursive:true});let reproducibilityVerified=false;if(fs.existsSync(directory)){for(const [name,contents]of Object.entries(files)){const file=path.join(directory,name);if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==contents)throw Error(`Immutable Phase 5 artifact collision at ${file}.`);}reproducibilityVerified=true;}else{fs.mkdirSync(directory);for(const [name,contents]of Object.entries(files))fs.writeFileSync(path.join(directory,name),contents,{flag:'wx'});}console.log(JSON.stringify({directory,reproducibilityVerified,selected:report.selection.selected,primary:{modelA:report.primary.modelA,modelACommon:report.primary.modelACommon,selectedModelB:report.primary.selectedModelB,candidates:report.primary.candidates.map((x:any)=>({architecture:x.architecture,candidateName:x.candidateName,metrics:x.metrics}))},marketBenchmark:report.marketBenchmark,gate:report.gate,decision:report.decision,incremental:report.incrementalInformation},null,2));
}
if(require.main===module)main();
