import * as path from 'path';
import {NFL_FORWARD_POLICY,NflForwardTrigger} from '../config/nflForwardPolicy';
import {LiveNflForwardCollectorAdapter} from '../services/nflForwardCollectorRuntime';
import {buildNflOperationalStatus,NflForwardOperationalCollector} from '../services/nflForwardOperations';
import {NflForwardArchive} from '../services/nflForwardResearch';

function option(name:string){const prefix=`--${name}=`;return process.argv.slice(2).find(value=>value.startsWith(prefix))?.slice(prefix.length);}
async function main(){const root=path.resolve(option('root')??process.env.NFL_FORWARD_RESEARCH_ROOT??path.join(process.cwd(),'research','nfl-forward-archive')),trigger=(option('trigger')??'MANUAL') as NflForwardTrigger,dryRun=process.argv.includes('--dry-run');if(process.argv.includes('--status')){const manualOnly=process.env.NFL_FORWARD_COLLECTION_MODE!=='scheduled';console.log(JSON.stringify(buildNflOperationalStatus(root,Date.now(),{scheduler:process.env.NFL_FORWARD_SCHEDULER_CONFIGURED==='true',durableStorage:process.env.NFL_FORWARD_DURABLE_STORAGE==='git',collectionMode:manualOnly?'MANUAL_ONLY':'SCHEDULED'}),null,2));return;}if(process.argv.includes('--verify')){console.log(JSON.stringify(new NflForwardArchive(root).verify(),null,2));return;}if(process.argv.includes('--export')){console.log(JSON.stringify(new NflForwardArchive(root).export(new Date().toISOString()),null,2));return;}if(!['SCHEDULED_0700_CT','SCHEDULED_1400_CT','MANUAL'].includes(trigger))throw Error('Invalid NFL trigger.');const key=option('idempotency-key')??process.env.NFL_FORWARD_IDEMPOTENCY_KEY??(dryRun?'dry-run':undefined);if(trigger==='MANUAL'&&!key)throw Error('Manual collection requires --idempotency-key.');const collector=new NflForwardOperationalCollector(root,new LiveNflForwardCollectorAdapter()),result=await collector.run({trigger,dryRun,idempotencyKey:key});console.log(JSON.stringify({...result,policy:{version:NFL_FORWARD_POLICY.version,protectedCutoff:NFL_FORWARD_POLICY.protectedCutoff}},null,2));if(!dryRun&&result.status==='FAILED')process.exitCode=1;}
main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exitCode=1;});
