import assert from 'node:assert/strict';
import {test} from 'node:test';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {BoundedForwardSourceCache} from '../services/collegeForwardSources';
import {buildForwardCoverageDashboard,COLLEGE_FORWARD_CORRECTION_VERSION,COLLEGE_FORWARD_FINAL_VERSION,COLLEGE_FORWARD_RESEARCH_VERSION,CollegeForwardResearchArchive,exportForwardResearchDataset,FootballCategory,ForwardDiagnostic,ForwardFeatureEvidence,NewForwardResearchSnapshot,REQUIRED_FORWARD_CATEGORIES,selectForwardSnapshotWindow,validateForwardSnapshot} from '../services/collegeForwardResearch';

const H='a'.repeat(64),forecast='2026-09-12T17:00:00.000Z',kickoff='2026-09-12T18:00:00.000Z';
function diagnostics():ForwardDiagnostic[]{return REQUIRED_FORWARD_CATEGORIES.flatMap(category=>['1','2'].map(teamId=>({category,teamId,forecastAt:forecast,stages:{SOURCE_RETRIEVAL:'UNKNOWN',NORMALIZATION:'UNKNOWN',ENTITY_MATCH:'UNKNOWN',ATTACHMENT:'UNKNOWN',FIELD_VALIDITY:'UNKNOWN',FORECAST_TIME_FRESHNESS:'UNKNOWN'},availableFields:0,expectedFields:1,notes:['fixture']})));}
function feature(category:FootballCategory,teamId:string,field:string,value:unknown):ForwardFeatureEvidence{return{category,teamId,field,value,definition:'football fact',units:null,sampleSize:null,season:2026,gamesIncluded:[],effectiveAt:'2026-09-12T16:50:00.000Z',forecastAt:forecast,validity:'VALID',freshness:'FRESH',source:{provider:'Fixture Football',providerRecordId:teamId,url:'https://example.com/football',retrievedAt:'2026-09-12T16:55:00.000Z',publishedAt:null,rawPayloadHash:H}};}
function snapshot():NewForwardResearchSnapshot{return{schemaVersion:COLLEGE_FORWARD_RESEARCH_VERSION,partition:'FORWARD_VALIDATION_2026',window:'T1H',capturedAt:forecast,forecastAt:forecast,identity:{canonicalEventId:'401-test',providerEventIds:{ESPN:'401-test',Odds:'odds-test'},season:2026,week:2,kickoff,home:{canonicalId:'1',name:'Home',subdivision:'FBS',conference:'A'},away:{canonicalId:'2',name:'Away',subdivision:'FCS',conference:'B'},neutralSite:false,conferenceGame:false,venue:{id:'10',name:'Field',indoor:false}},applicationRelease:'2.1.0',featureSchemaVersion:'college-forward-feature-v1',modelA:{status:'PROJECTED',forecastAt:forecast,modelVersion:'A',dataVersion:'scores-v1',homeScore:28,awayScore:21,homeMargin:7,historyHash:H},shadowModels:[{shadowOnly:true,status:'MODEL_UNAVAILABLE',forecastAt:forecast,modelVersion:'B2',candidateId:'research',homeScore:null,awayScore:null,homeMargin:null,inputEvidenceHash:H}],footballEvidence:[feature('QB','1','qb.status','UNKNOWN'),feature('QB','2','qb.status','CONFIRMED'),feature('FBS_FCS','1','classification','FBS'),feature('FBS_FCS','2','classification','FCS')],diagnostics:diagnostics(),failures:[],market:{namespace:'EXTERNAL_MARKET_BENCHMARK',sportsbook:'Book',market:'spreads',homeSpread:-3,homePrice:-110,awaySpread:3,awayPrice:-110,quoteTimestamp:'2026-09-12T16:58:00.000Z',retrievedAt:'2026-09-12T16:59:00.000Z',providerEventId:'odds-test',rawPayloadHash:H,acquisition:'NETWORK',requestAttempts:1}};}
function temp(prefix:string){return fs.mkdtempSync(path.join(os.tmpdir(),prefix));}

test('protected forward dataset rejects pre-lock snapshots',()=>{const row=snapshot();row.forecastAt='2026-09-07T12:44:59.000Z';row.capturedAt=row.forecastAt;assert.throws(()=>validateForwardSnapshot(row),/predates/);});
test('pregame cutoff rejects capture at or after kickoff',()=>{const row=snapshot();row.capturedAt=kickoff;assert.throws(()=>validateForwardSnapshot(row),/cutoff/);});
test('post-forecast source evidence cannot leak',()=>{const row=snapshot();row.footballEvidence[0].source.retrievedAt='2026-09-12T17:01:00.000Z';assert.throws(()=>validateForwardSnapshot(row),/Post-forecast/);});
test('content-addressed snapshots are immutable and exact duplicates are idempotent',()=>{const root=temp('cf-forward-');try{const archive=new CollegeForwardResearchArchive(root),row=snapshot(),first=archive.capture(row),second=archive.capture(row);assert.equal(first.created,true);assert.equal(second.created,false);assert.equal(first.snapshotId,second.snapshotId);assert.equal(archive.load().snapshots.length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('conflicting duplicate event/window/forecast is rejected',()=>{const root=temp('cf-duplicate-');try{const archive=new CollegeForwardResearchArchive(root),row=snapshot();archive.capture(row);assert.throws(()=>archive.capture({...row,applicationRelease:'2.1.1'}),/Conflicting duplicate/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('corrections append evidence without altering the original',()=>{const root=temp('cf-correction-');try{const archive=new CollegeForwardResearchArchive(root),original=archive.capture(snapshot()),correction={schemaVersion:COLLEGE_FORWARD_CORRECTION_VERSION as typeof COLLEGE_FORWARD_CORRECTION_VERSION,targetType:'SNAPSHOT' as const,targetId:original.snapshotId,recordedAt:'2026-09-13T01:00:00.000Z',reason:'Provider correction',evidence:{field:'qb.status',value:'CONFIRMED'},source:{provider:'Fixture Football',providerRecordId:'x',url:'https://example.com/final',retrievedAt:'2026-09-13T00:59:00.000Z',publishedAt:null,rawPayloadHash:H}},saved=archive.appendCorrection(correction);assert.equal(saved.created,true);assert.equal(archive.appendCorrection(correction).created,false);assert.equal(archive.load().snapshots[0].footballEvidence[0].value,'UNKNOWN');assert.equal(archive.load().corrections.length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('canonical event identity rejects duplicate teams',()=>{const row=snapshot();row.identity.away.canonicalId='1';assert.throws(()=>validateForwardSnapshot(row),/Duplicate team/);});
test('QB UNKNOWN is preserved and unsupported status is rejected',()=>{const row=snapshot();assert.doesNotThrow(()=>validateForwardSnapshot(row));assert.equal(row.footballEvidence[0].value,'UNKNOWN');row.footballEvidence[0].value='HEALTHY';assert.throws(()=>validateForwardSnapshot(row),/Invalid QB status/);});
test('FBS/FCS regime and classification coverage are explicit',()=>{const root=temp('cf-fcs-');try{const archive=new CollegeForwardResearchArchive(root),row=snapshot();for(const teamId of ['1','2'])for(const category of REQUIRED_FORWARD_CATEGORIES)if(!row.footballEvidence.some(e=>e.teamId===teamId&&e.category===category))row.footballEvidence.push(feature(category,teamId,`${category}.fixture`,true));archive.capture(row);const dashboard=buildForwardCoverageDashboard(archive.load(),[{canonicalEventId:'401-test',kickoff,season:2026,week:2,homeSubdivision:'FBS',awaySubdivision:'FCS',neutralSite:false,conferenceGame:false}]);assert.equal(dashboard.regime.fbsFcs,1);assert.deepEqual(dashboard.coverage.fcs,{covered:1,total:1,percent:100});}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('market fields cannot enter football evidence or use early-window network calls',()=>{const row=snapshot();row.footballEvidence.push(feature('TEAM_EFFICIENCY','1','sportsbookSpread',-3));assert.throws(()=>validateForwardSnapshot(row),/Market evidence contaminated/);const early=snapshot();early.window='T24H';assert.throws(()=>validateForwardSnapshot(early),/external market/);early.market!.acquisition='CACHE';early.market!.requestAttempts=0;assert.doesNotThrow(()=>validateForwardSnapshot(early));});
test('source failures are content-addressed, deduplicated and retained',()=>{const root=temp('cf-failure-');try{const archive=new CollegeForwardResearchArchive(root),failure={provider:'CFBD',requestCategory:'TEAM_EFFICIENCY',canonicalEventId:'401-test',teamId:'1',failedAt:'2026-09-12T16:00:00.000Z',errorClass:'RATE_LIMIT' as const,attempts:2,retryState:'RETRY_EXHAUSTED' as const,finalAvailability:'UNAVAILABLE' as const,message:'HTTP 429'};assert.equal(archive.logFailure(failure).created,true);assert.equal(archive.logFailure(failure).created,false);assert.equal(archive.load().failures[0].errorClass,'RATE_LIMIT');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('bounded source cache reuses fresh responses and coalesces concurrent calls',async()=>{let calls=0,now=Date.parse(forecast);const cache=new BoundedForwardSourceCache(async()=>{calls++;return{ok:true,status:200,json:async()=>({value:1})};},()=>now,async()=>{},4),[a,b]=await Promise.all([cache.request('core','https://example.com/core',1000),cache.request('core','https://example.com/core',1000)]),c=await cache.request('core','https://example.com/core',1000);assert.equal(calls,1);assert.equal(a.cached,false);assert.equal(b.payload&&typeof b.payload==='object',true);assert.equal(c.cached,true);});
test('snapshot window policy is deterministic and excludes started games',()=>{const policies=[{name:'T24H' as const,minimumMinutesBeforeKickoff:1080,maximumMinutesBeforeKickoff:1800,marketNetworkAllowed:false},{name:'T1H' as const,minimumMinutesBeforeKickoff:30,maximumMinutesBeforeKickoff:90,marketNetworkAllowed:true}];assert.equal(selectForwardSnapshotWindow(Date.parse(kickoff)-60*60_000,Date.parse(kickoff),policies),'T1H');assert.equal(selectForwardSnapshotWindow(Date.parse(kickoff),Date.parse(kickoff),policies),null);});
test('coverage reports raw N, percentages, missed games and milestones',()=>{const root=temp('cf-coverage-');try{const archive=new CollegeForwardResearchArchive(root);archive.capture(snapshot());const expected=[{canonicalEventId:'401-test',kickoff,season:2026 as const,week:2,homeSubdivision:'FBS' as const,awaySubdivision:'FCS' as const,neutralSite:false,conferenceGame:false},{canonicalEventId:'missing',kickoff,season:2026 as const,week:2,homeSubdivision:'FBS' as const,awaySubdivision:'FBS' as const,neutralSite:false,conferenceGame:false}],d=buildForwardCoverageDashboard(archive.load(),expected);assert.equal(d.gamesCaptured,1);assert.equal(d.gamesMissed,1);assert.equal(d.capturePercent,50);assert.equal(d.bySeason['2026'].captured,1);assert.equal(d.bySlate['2026-09-12'].missed,1);assert.equal(d.milestones[0].remaining,49);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('schema versioning fails closed',()=>{const row:any=snapshot();row.schemaVersion='college-forward-research-v2';assert.throws(()=>validateForwardSnapshot(row),/schema/);});
test('shadow forecasts cannot escape shadow-only isolation',()=>{const row:any=snapshot();row.shadowModels[0].shadowOnly=false;assert.throws(()=>validateForwardSnapshot(row),/shadow mode/);});
test('verified final is immutable and a changed score requires correction',()=>{const root=temp('cf-final-');try{const archive=new CollegeForwardResearchArchive(root),saved=archive.capture(snapshot()),final={schemaVersion:COLLEGE_FORWARD_FINAL_VERSION as typeof COLLEGE_FORWARD_FINAL_VERSION,canonicalEventId:'401-test',recordedAt:'2026-09-13T00:05:00.000Z',sourceTimestamp:'2026-09-13T00:04:00.000Z',provider:'ESPN',providerEventId:'401-test',status:'STATUS_FINAL' as const,homeScore:31,awayScore:21,actualHomeMargin:10,rawPayloadHash:H};assert.equal(archive.archiveFinal(final).created,true);assert.equal(archive.archiveFinal(final).created,false);assert.throws(()=>archive.archiveFinal({...final,homeScore:30,actualHomeMargin:9}),/append a correction/);assert.equal(archive.load().snapshots[0].snapshotId,saved.snapshotId);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('deterministic exports preserve dataset hash and exact bytes',()=>{const root=temp('cf-export-source-'),out=temp('cf-export-output-');try{const archive=new CollegeForwardResearchArchive(root);archive.capture(snapshot());const first=exportForwardResearchDataset(root,out,'2026-09-13T02:00:00.000Z'),bytes=fs.readFileSync(path.join(first.directory,'dataset.ndjson'),'utf8'),second=exportForwardResearchDataset(root,out,'2026-09-13T02:00:00.000Z');assert.equal(first.created,true);assert.equal(second.created,false);assert.equal(first.datasetHash,second.datasetHash);assert.equal(fs.readFileSync(path.join(second.directory,'dataset.ndjson'),'utf8'),bytes);}finally{fs.rmSync(root,{recursive:true,force:true});fs.rmSync(out,{recursive:true,force:true});}});
