import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {
  actualCaptureSemantics,buildForwardOperationalStatus,centralScheduledInstant,
  CollegeForwardOperationalCollector,ForwardCollectorAdapter,ForwardDiscoveredGame,
  ForwardOperationsStore,scheduledCaptureEventId,
} from '../services/collegeForwardOperations';
import {COLLEGE_FORWARD_RESEARCH_VERSION,CollegeForwardResearchArchive,NewForwardResearchSnapshot,REQUIRED_FORWARD_CATEGORIES} from '../services/collegeForwardResearch';

const HASH='a'.repeat(64);
const root=()=>fs.mkdtempSync(path.join(os.tmpdir(),'college-forward-operations-'));
function game(id='game-1',kickoff='2026-09-09T00:00:00.000Z',status:ForwardDiscoveredGame['status']='SCHEDULED'):ForwardDiscoveredGame{return{canonicalEventId:id,originalScheduledKickoff:kickoff,latestVerifiedKickoff:status==='POSTPONED'?null:kickoff,status,homeSubdivision:'FBS',awaySubdivision:'FBS',missingCriticalEvidence:10,scheduleSource:{provider:'TEST_SCHEDULE',retrievedAt:'2026-09-07T12:50:00.000Z',rawPayloadHash:HASH},payload:{recommendation:'PASS'}};}
function snapshot(item:ForwardDiscoveredGame,at:string):NewForwardResearchSnapshot {const home='home-'+item.canonicalEventId,away='away-'+item.canonicalEventId,diagnostics=REQUIRED_FORWARD_CATEGORIES.flatMap(category=>[home,away].map(teamId=>({category,teamId,forecastAt:at,stages:{SOURCE_RETRIEVAL:'UNKNOWN' as const,NORMALIZATION:'UNKNOWN' as const,ENTITY_MATCH:'UNKNOWN' as const,ATTACHMENT:'UNKNOWN' as const,FIELD_VALIDITY:'UNKNOWN' as const,FORECAST_TIME_FRESHNESS:'UNKNOWN' as const},availableFields:0,expectedFields:1,notes:['test']})));return{schemaVersion:COLLEGE_FORWARD_RESEARCH_VERSION,partition:'FORWARD_VALIDATION_2026',window:'ACTUAL_PREKICK',capturedAt:at,forecastAt:at,identity:{canonicalEventId:item.canonicalEventId,providerEventIds:{TEST:item.canonicalEventId},season:2026,week:2,kickoff:item.latestVerifiedKickoff!,home:{canonicalId:home,name:'Home',subdivision:item.homeSubdivision,conference:'A'},away:{canonicalId:away,name:'Away',subdivision:item.awaySubdivision,conference:'B'},neutralSite:false,conferenceGame:false,venue:{id:null,name:null,indoor:null}},applicationRelease:'test',featureSchemaVersion:'test',modelA:{status:'MODEL_UNAVAILABLE',forecastAt:at,modelVersion:'model-a',dataVersion:'data',homeScore:null,awayScore:null,homeMargin:null,historyHash:null},shadowModels:[],footballEvidence:[],diagnostics,failures:[],market:null};}
class Adapter implements ForwardCollectorAdapter {captureCalls:string[]=[];constructor(public games:ForwardDiscoveredGame[],private clock:()=>number,public deferred:string[]=[],private fail=false){}async discover(){return{games:this.games,requests:2,cacheHits:1,failures:[]};}plan(games:ForwardDiscoveredGame[]){return games.length?[{provider:'CFBD',category:'FACTS',scope:'all',cache:'MISS' as const,maximumRequests:4,priority:1}]:[];}async prepare(){return{state:{},metrics:{apiRequests:5,cacheHits:2,cfbdRequests:4,marketRequests:1},deferred:this.deferred,failures:[]};}async capture(item:ForwardDiscoveredGame){this.captureCalls.push(item.canonicalEventId);if(this.fail)throw Error('capture failed');return snapshot(item,new Date(this.clock()).toISOString());}}
async function runOnce(args:{now:string;games?:ForwardDiscoveredGame[];trigger?:'SCHEDULED_0700_CT'|'SCHEDULED_1400_CT'|'MANUAL';dryRun?:boolean;deferred?:string[];fail?:boolean;rootDir?:string;key?:string}){let clock=Date.parse(args.now);const adapter=new Adapter(args.games??[game()],()=>clock,args.deferred,args.fail),dir=args.rootDir??root(),collector=new CollegeForwardOperationalCollector(dir,adapter,()=>clock),result=await collector.run({trigger:args.trigger??'SCHEDULED_0700_CT',dryRun:args.dryRun??false,idempotencyKey:args.key});return{result,adapter,dir,setClock:(value:string)=>{clock=Date.parse(value);}};}

test('7:00 AM Central resolves correctly during CDT',()=>assert.equal(centralScheduledInstant('2026-09-07',7),'2026-09-07T12:00:00.000Z'));
test('2:00 PM Central resolves correctly during CDT',()=>assert.equal(centralScheduledInstant('2026-09-07',14),'2026-09-07T19:00:00.000Z'));
test('CST changes both scheduled UTC instants without changing local protocol',()=>{assert.equal(centralScheduledInstant('2026-12-07',7),'2026-12-07T13:00:00.000Z');assert.equal(centralScheduledInstant('2026-12-07',14),'2026-12-07T20:00:00.000Z');});
test('morning capture persists trigger and exact hours to kickoff',async()=>{const {result,dir}=await runOnce({now:'2026-09-08T12:00:00.000Z'});assert.equal(result.observations[0].status,'CAPTURED');const row=new CollegeForwardResearchArchive(dir).load().snapshots[0];assert.equal(row.operational?.trigger,'SCHEDULED_0700_CT');assert.equal(row.operational?.hoursToKickoff,12);});
test('afternoon capture persists afternoon trigger',async()=>{const {dir}=await runOnce({now:'2026-09-08T19:00:00.000Z',trigger:'SCHEDULED_1400_CT'});assert.equal(new CollegeForwardResearchArchive(dir).load().snapshots[0].operational?.trigger,'SCHEDULED_1400_CT');});
test('early kickoff is skipped by afternoon run',async()=>{const {result,adapter}=await runOnce({now:'2026-09-08T19:00:00.000Z',trigger:'SCHEDULED_1400_CT',games:[game('early','2026-09-08T16:00:00.000Z')]});assert.equal(result.observations[0].status,'SKIPPED_STARTED');assert.equal(adapter.captureCalls.length,0);});
test('evening game keeps immutable morning and afternoon snapshots',async()=>{const dir=root();let clock=Date.parse('2026-09-08T12:00:00.000Z'),adapter=new Adapter([game()],()=>clock),collector=new CollegeForwardOperationalCollector(dir,adapter,()=>clock);await collector.run({trigger:'SCHEDULED_0700_CT',dryRun:false});clock=Date.parse('2026-09-08T19:00:00.000Z');await collector.run({trigger:'SCHEDULED_1400_CT',dryRun:false});const rows=new CollegeForwardResearchArchive(dir).load().snapshots;assert.equal(rows.length,2);assert.deepEqual(rows.map(row=>row.operational?.hoursToKickoff),[12,5]);});
test('manual capture uses the same core and persists MANUAL',async()=>{const {dir,adapter}=await runOnce({now:'2026-09-07T22:00:00.000Z',trigger:'MANUAL',key:'workflow-123'});assert.equal(adapter.captureCalls.length,1);assert.equal(new CollegeForwardResearchArchive(dir).load().snapshots[0].operational?.trigger,'MANUAL');});
test('manual capture requires an idempotency key',()=>assert.throws(()=>scheduledCaptureEventId('MANUAL',Date.now()),/idempotency/));
test('duplicate scheduled retry is idempotent',async()=>{const dir=root(),first=await runOnce({now:'2026-09-08T12:00:00.000Z',rootDir:dir}),second=await runOnce({now:'2026-09-08T12:05:00.000Z',rootDir:dir});assert.equal(second.result.idempotentRetry,true);assert.equal(new CollegeForwardResearchArchive(dir).load().snapshots.length,1);assert.equal(first.result.captureEventId,second.result.captureEventId);});
test('kickoff update preserves original and uses latest trustworthy kickoff',async()=>{const dir=root();await runOnce({now:'2026-09-08T12:00:00.000Z',rootDir:dir,games:[game('moved','2026-09-09T00:00:00.000Z')]});await runOnce({now:'2026-09-08T19:00:00.000Z',rootDir:dir,trigger:'SCHEDULED_1400_CT',games:[game('moved','2026-09-09T01:00:00.000Z')]});const latest=new CollegeForwardResearchArchive(dir).load().snapshots.at(-1)!;assert.equal(latest.operational?.originalScheduledKickoff,'2026-09-09T00:00:00.000Z');assert.equal(latest.operational?.latestVerifiedKickoff,'2026-09-09T01:00:00.000Z');});
test('postponed game is retained as evidence but not captured',async()=>{const {result}=await runOnce({now:'2026-09-08T12:00:00.000Z',games:[game('postponed','2026-09-09T00:00:00.000Z','POSTPONED')]});assert.equal(result.observations[0].status,'SKIPPED_POSTPONED');});
test('canceled game stops future capture',async()=>{const {result}=await runOnce({now:'2026-09-08T12:00:00.000Z',games:[game('canceled','2026-09-09T00:00:00.000Z','CANCELED')]});assert.equal(result.observations[0].status,'SKIPPED_CANCELED');});
test('CFBD four-request cap and one market request are observable',async()=>{const {result}=await runOnce({now:'2026-09-08T12:00:00.000Z'});assert.equal(result.metrics.cfbdRequests,4);assert.equal(result.metrics.marketRequests,1);});
test('deferred budget work is explicit and not silently dropped',async()=>{const {result}=await runOnce({now:'2026-09-08T12:00:00.000Z',deferred:['game-1']});assert.equal(result.observations[0].status,'DEFERRED');assert.deepEqual(result.deferred,['game-1']);});
test('PASS games are collected because betting selection is not an eligibility input',async()=>{const item=game();(item.payload as any).recommendation='PASS';const {result}=await runOnce({now:'2026-09-08T12:00:00.000Z',games:[item]});assert.equal(result.observations[0].status,'CAPTURED');});
test('conceptual windows are not fabricated for an actual T-12 capture',()=>{const item=game(),value=actualCaptureSemantics('2026-09-08T12:00:00.000Z',item.latestVerifiedKickoff!,'SCHEDULED_0700_CT','capture',centralScheduledInstant('2026-09-08',7),item);assert.equal(value.hoursToKickoff,12);assert.equal(value.conceptualWindows.T6H,'NOT_SCHEDULED_FOR_CAPTURE');assert.equal(value.conceptualWindows.T1H,'NOT_SCHEDULED_FOR_CAPTURE');});
test('failed expected scheduled capture is distinguished from an unscheduled conceptual window',async()=>{const {result,dir}=await runOnce({now:'2026-09-08T12:00:00.000Z',fail:true});assert.equal(result.observations[0].status,'FAILED');const status=buildForwardOperationalStatus(dir,Date.parse('2026-09-08T13:00:00.000Z'),{scheduler:true,durableStorage:true});assert.equal(status.missedScheduledCaptures,1);});
test('post-kickoff capture fails closed even if adapter returns a snapshot',async()=>{const item=game('late','2026-09-08T12:01:00.000Z'),dir=root();let clock=Date.parse('2026-09-08T12:00:00.000Z');class Slow extends Adapter{async capture(row:ForwardDiscoveredGame){clock=Date.parse('2026-09-08T12:02:00.000Z');return snapshot(row,new Date(clock).toISOString());}}const result=await new CollegeForwardOperationalCollector(dir,new Slow([item],()=>clock),()=>clock).run({trigger:'SCHEDULED_0700_CT',dryRun:false});assert.equal(result.observations[0].status,'FAILED');assert.equal(new CollegeForwardResearchArchive(dir).load().snapshots.length,0);});
test('protected cutoff rejects earlier collection',async()=>{await assert.rejects(()=>runOnce({now:'2026-09-07T12:44:59.000Z'}),/protected/);});
test('operations and snapshots survive store re-instantiation',async()=>{const {dir}=await runOnce({now:'2026-09-07T12:50:00.000Z'});assert.equal(new ForwardOperationsStore(dir).runs().length,1);assert.equal(new CollegeForwardResearchArchive(dir).load().snapshots.length,1);});
test('dry run reports work without mutating either authority',async()=>{const {result,dir}=await runOnce({now:'2026-09-07T12:50:00.000Z',dryRun:true});assert.equal(result.observations[0].status,'WOULD_CAPTURE');assert.equal(new ForwardOperationsStore(dir).runs().length,0);assert.equal(new CollegeForwardResearchArchive(dir).load().snapshots.length,0);});
test('health is NOT_CONFIGURED until scheduler and durable authority are active',()=>{const status=buildForwardOperationalStatus(root(),Date.parse('2026-09-07T13:00:00.000Z'),{scheduler:false,durableStorage:true});assert.equal(status.health,'NOT_CONFIGURED');});
