import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as child from 'child_process';
import {buildForwardMonitoringReport,classifyScheduledRun,aggregateSixStages,auditFutureLeakage,auditMarketContamination,snapshotCoverage,snapshotTiming} from '../services/collegeForwardMonitoring';
import {COLLEGE_FORWARD_OPERATIONS_VERSION,ForwardOperationalRun,ForwardOperationsStore} from '../services/collegeForwardOperations';
import {COLLEGE_FORWARD_CORRECTION_VERSION,COLLEGE_FORWARD_RESEARCH_VERSION,CollegeForwardResearchArchive,FootballCategory,NewForwardResearchSnapshot,REQUIRED_FORWARD_CATEGORIES} from '../services/collegeForwardResearch';

const H='a'.repeat(64),forecast='2026-09-08T12:00:00.000Z',kickoff='2026-09-09T00:00:00.000Z';
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'forward-monitoring-'));
test('published workflow has exactly two Central schedules, shared authority, secret checks and correct working-directory paths',()=>{const file=path.resolve(__dirname,'..','..','..','.github','workflows','college-forward-collector.yml'),workflow=fs.readFileSync(file,'utf8');assert.equal((workflow.match(/- cron:/g)??[]).length,2);assert.match(workflow,/cron: '0 7 \* \* \*'/);assert.match(workflow,/cron: '0 14 \* \* \*'/);assert.equal((workflow.match(/timezone: 'America\/Chicago'/g)??[]).length,2);assert.match(workflow,/working-directory: sports-betting-engine/);assert.match(workflow,/ODDS_API_KEY is not configured/);assert.match(workflow,/CFBD_API_KEY is not configured/);assert.match(workflow,/FORWARD_RESEARCH_ROOT:/);assert.match(workflow,/--trigger=\$\{\{ steps\.protocol\.outputs\.trigger \}\}/);assert.match(workflow,/git add research\/forward-archive/);assert.doesNotMatch(workflow,/git add sports-betting-engine\/research/);assert.match(workflow,/\[skip render\]/);});
test('authoritative forward snapshots are never hidden by the legacy snapshots ignore rule',()=>{const repository=path.resolve(__dirname,'..','..','..'),candidate='sports-betting-engine/research/forward-archive/college_forward_research/v1/snapshots/durable-check.json',result=child.spawnSync('git',['check-ignore','-q',candidate],{cwd:repository});assert.equal(result.status,1);});
test('live forward adapter disables legacy CFBD fanout and uses only the bounded dedicated source',()=>{const file=path.resolve(__dirname,'..','services','collegeForwardCollectorRuntime.ts'),source=fs.readFileSync(file,'utf8');assert.match(source,/new CollegeContextIngestion\(this\.root,this\.get,this\.now,''\)/);assert.doesNotMatch(source,/new CollegeContextIngestion\(this\.root,this\.get,this\.now,undefined\)/);});
function snapshot(id='game-1',trigger:'SCHEDULED_0700_CT'|'SCHEDULED_1400_CT'|'MANUAL'='SCHEDULED_0700_CT',homeSubdivision:'FBS'|'FCS'='FBS',awaySubdivision:'FBS'|'FCS'='FBS'):NewForwardResearchSnapshot {const home=`home-${id}`,away=`away-${id}`,diagnostics=REQUIRED_FORWARD_CATEGORIES.flatMap(category=>[home,away].map(teamId=>({category,teamId,forecastAt:forecast,stages:{SOURCE_RETRIEVAL:'PASS' as const,NORMALIZATION:'PASS' as const,ENTITY_MATCH:'PASS' as const,ATTACHMENT:'PASS' as const,FIELD_VALIDITY:'PASS' as const,FORECAST_TIME_FRESHNESS:'PASS' as const},availableFields:1,expectedFields:1,notes:[]}))),feature=(category:FootballCategory,teamId:string,field:string,value:unknown)=>({category,teamId,field,value,definition:'Independent football fact.',units:null,sampleSize:1,season:2026 as const,gamesIncluded:[],effectiveAt:forecast,forecastAt:forecast,validity:'VALID' as const,freshness:'FRESH' as const,source:{provider:'TEST_PROVIDER',providerRecordId:teamId,url:'https://example.test/data',retrievedAt:forecast,publishedAt:forecast,rawPayloadHash:H}}),footballEvidence=[home,away].flatMap(teamId=>[feature('OPPONENT_HISTORY',teamId,'current.gamesPlayed',1),feature('TEAM_EFFICIENCY',teamId,'offensive.rushEfficiency',1),feature('TEAM_EFFICIENCY',teamId,'defensive.passEfficiency',1),feature('QB',teamId,'qb.status','CONFIRMED'),feature('ROSTER',teamId,'roster.returningProduction',0.5),feature('TRANSFERS',teamId,'transfers.net',0),feature('TALENT',teamId,'talent.rank',50),feature('COACHING',teamId,'coaching.headCoach','Coach'),feature('INJURIES',teamId,'injuries.count',0),feature('FBS_FCS',teamId,'classification',teamId===home?homeSubdivision:awaySubdivision),feature('WEATHER',teamId,'weather.temperatureF',70)]);return{schemaVersion:COLLEGE_FORWARD_RESEARCH_VERSION,partition:'FORWARD_VALIDATION_2026',window:'ACTUAL_PREKICK',capturedAt:forecast,forecastAt:forecast,identity:{canonicalEventId:id,providerEventIds:{ESPN:id},season:2026,week:2,kickoff,home:{canonicalId:home,name:'Home',subdivision:homeSubdivision,conference:'A'},away:{canonicalId:away,name:'Away',subdivision:awaySubdivision,conference:'B'},neutralSite:false,conferenceGame:false,venue:{id:'1',name:'Field',indoor:false}},applicationRelease:'test',featureSchemaVersion:'test',modelA:{status:'PROJECTED',forecastAt:forecast,modelVersion:'A',dataVersion:'D',homeScore:28,awayScore:21,homeMargin:7,historyHash:H},shadowModels:[],footballEvidence,diagnostics,failures:[],market:null,operational:{trigger,captureEventId:`capture-${id}-${trigger}`,captureTimestamp:forecast,scheduledFor:trigger==='MANUAL'?null:forecast,originalScheduledKickoff:kickoff,latestVerifiedKickoff:kickoff,minutesToKickoff:720,hoursToKickoff:12,scheduleStatus:'SCHEDULED',scheduleSource:{provider:'ESPN',retrievedAt:forecast,rawPayloadHash:H},conceptualWindows:{T24H:'NOT_SCHEDULED_FOR_CAPTURE',T6H:'NOT_SCHEDULED_FOR_CAPTURE',T1H:'NOT_SCHEDULED_FOR_CAPTURE',LATEST_PREKICK:'NOT_SCHEDULED_FOR_CAPTURE'}}};}
function run(id:string,trigger:'SCHEDULED_0700_CT'|'SCHEDULED_1400_CT'|'MANUAL',status:ForwardOperationalRun['status']='SUCCESS',observationStatus:ForwardOperationalRun['observations'][number]['status']='CAPTURED'):Omit<ForwardOperationalRun,'runId'>{const date='2026-09-08',suffix=trigger==='SCHEDULED_0700_CT'?'0700':trigger==='SCHEDULED_1400_CT'?'1400':'manual';return{schemaVersion:COLLEGE_FORWARD_OPERATIONS_VERSION,captureEventId:trigger==='MANUAL'?`manual-${id}`:`${date}-${suffix}-ct`,trigger,scheduledFor:trigger==='MANUAL'?null:trigger==='SCHEDULED_0700_CT'?'2026-09-08T12:00:00.000Z':'2026-09-08T19:00:00.000Z',startedAt:trigger==='SCHEDULED_1400_CT'?'2026-09-08T19:01:00.000Z':'2026-09-08T12:01:00.000Z',completedAt:trigger==='SCHEDULED_1400_CT'?'2026-09-08T19:02:00.000Z':'2026-09-08T12:02:00.000Z',dryRun:false,status,observations:[{eventId:id,originalScheduledKickoff:kickoff,latestVerifiedKickoff:kickoff,scheduleStatus:'SCHEDULED',status:observationStatus,snapshotId:null,minutesToKickoff:720,message:'test',homeSubdivision:'FBS',awaySubdivision:'FBS'}],requestPlan:[{provider:'TEST_PROVIDER',category:'FACTS',scope:'slate',cache:'MISS',maximumRequests:1,priority:1}],metrics:{apiRequests:1,cacheHits:0,cfbdRequests:0,marketRequests:0},deferred:[],providerFailures:[],discoveryFailures:[],idempotentRetry:false};}
function seeded(){const root=temp(),archive=new CollegeForwardResearchArchive(root),saved=archive.capture(snapshot()),store=new ForwardOperationsStore(root),value=run('game-1','SCHEDULED_0700_CT');value.observations[0].snapshotId=saved.snapshotId;store.append(value);return{root,archive,store,saved};}

test('scheduled verification reports completed run evidence',()=>{const {root}=seeded(),report=buildForwardMonitoringReport(root,'2026-09-08T20:30:00.000Z');assert.equal(report.scheduledRunEvidence[0].status,'SUCCESS');assert.equal(report.scheduledRunEvidence[0].snapshotsCreated,1);});
test('unobserved first schedule is never fabricated as successful',()=>assert.equal(classifyScheduledRun('SCHEDULED_1400_CT','2026-09-08',Date.parse('2026-09-08T21:00:00Z'),[]),'AWAITING_FIRST_SCHEDULED_EXECUTION'));
test('a missing later scheduled run is a workflow failure',()=>{const earlier={runId:'x',...run('game-0','SCHEDULED_1400_CT')} as ForwardOperationalRun;assert.equal(classifyScheduledRun('SCHEDULED_1400_CT','2026-09-09',Date.parse('2026-09-09T21:00:00Z'),[earlier]),'WORKFLOW_FAILURE');});
test('dataset and regime counts use eligible universe independently of selections',()=>{const {root}=seeded(),report=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z');assert.equal(report.counts.gamesWithAtLeastOneValidPregameSnapshot,1);assert.equal(report.eligibleUniverse.captureRatePercent,100);assert.equal(report.counts.regime.fbsFbs,1);});
test('coverage uses transparent PASS PARTIAL FAIL UNKNOWN counts',()=>{const row=snapshot(),coverage=snapshotCoverage({...row,snapshotId:'id'});assert.equal(coverage.MODEL_A,'PASS');assert.equal(coverage.QB_EVIDENCE,'PASS');assert.equal(coverage.MARKET_QUOTE,'UNKNOWN');});
test('six-stage aggregation preserves every diagnostic stage',()=>{const row=snapshot(),result:any=aggregateSixStages(row.diagnostics);assert.equal(result.SOURCE_RETRIEVAL.PASS,20);assert.equal(result.ATTACHMENT.PASS,20);});
test('provider report distinguishes requests from usable feature attachments',()=>{const {root}=seeded(),provider=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z').providerReliability.find(row=>row.provider==='TEST_PROVIDER')!;assert.equal(provider.requests,0);assert.ok(provider.usableFeatureAttachments>0);});
test('entity matching is reported at team level',()=>{const {root}=seeded(),quality=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z').entityMatchQuality;assert.equal(quality.teamsSuccessfullyMatched,2);assert.equal(quality.matchPercent,100);});
test('snapshot timing distributions are trigger-specific',()=>{const row={...snapshot(),snapshotId:'id'},result=snapshotTiming([row]);assert.equal(result.morning.n,1);assert.equal(result.morning.medianMinutes,720);assert.equal(result.afternoon.n,0);});
test('market contamination is detected in independent football evidence',()=>{const row={...snapshot(),snapshotId:'id'};row.footballEvidence[0].field='sportsbook.spread';assert.equal(auditMarketContamination([row]).status,'MARKET_CONTAMINATION');});
test('future information leakage is detected by retrieval timestamp',()=>{const row={...snapshot(),snapshotId:'id'};row.footballEvidence[0].source.retrievedAt='2026-09-08T12:00:01Z';assert.equal(auditFutureLeakage([row]).status,'LEAKAGE_VIOLATION');});
test('append-only corrections expose original and correction hashes',()=>{const {root,archive,saved}=seeded();archive.appendCorrection({schemaVersion:COLLEGE_FORWARD_CORRECTION_VERSION,targetType:'SNAPSHOT',targetId:saved.snapshotId,recordedAt:'2026-09-08T13:00:00Z',reason:'Source clarification',evidence:{note:'append only'},source:{provider:'TEST',providerRecordId:'1',url:'https://example.test',retrievedAt:'2026-09-08T12:59:00Z',publishedAt:null,rawPayloadHash:H}});const audit=buildForwardMonitoringReport(root,'2026-09-08T13:01:00Z').correctionAudit;assert.equal(audit.count,1);assert.equal(audit.records[0].previousHash,saved.snapshotId);});
test('failed expected capture is classified separately from no eligible games',()=>{const value={runId:'x',...run('game-1','SCHEDULED_1400_CT','DEGRADED','FAILED')} as ForwardOperationalRun;assert.equal(classifyScheduledRun('SCHEDULED_1400_CT','2026-09-08',Date.parse('2026-09-08T21:00:00Z'),[value]),'PROVIDER_FAILURE');});
test('FBS/FCS remains a separate research regime',()=>{const root=temp(),archive=new CollegeForwardResearchArchive(root),saved=archive.capture(snapshot('cross','MANUAL','FBS','FCS')),value=run('cross','MANUAL');value.observations[0].snapshotId=saved.snapshotId;value.observations[0].awaySubdivision='FCS';new ForwardOperationsStore(root).append(value);const report=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z');assert.equal(report.counts.regime.fbsFcs,1);assert.equal(report.modelBV2Readiness.fbsFcs.ready,false);});
test('Model A and market error reporting is suppressed below N 25',()=>{const {root}=seeded(),report=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z');assert.equal(report.modelAForward.status,'SUPPRESSED_MINIMUM_N');assert.equal(report.modelAForward.mae,null);assert.equal(report.marketForward.rmse,null);});
test('milestones and Model B v2 gate start closed',()=>{const {root}=seeded(),report=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z');assert.equal(report.milestones[0].target,25);assert.equal(report.milestones[0].reached,false);assert.equal(report.modelBV2Readiness.fbsFbs.ready,false);assert.equal(report.datasetStatus,'COLLECTING');});
test('monitoring report is deterministic for the same archive and timestamp',()=>{const {root}=seeded(),a=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z'),b=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z');assert.deepEqual(a,b);});
test('dataset hash changes when immutable archive gains a snapshot',()=>{const {root,archive}=seeded(),a=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z').datasetHash;archive.capture(snapshot('game-2','MANUAL'));const b=buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z').datasetHash;assert.notEqual(a,b);});
test('archive hash tampering fails closed before a report is produced',()=>{const {root,saved}=seeded(),file=path.join(root,'college_forward_research','v1','snapshots',`${saved.snapshotId}.json`),value=JSON.parse(fs.readFileSync(file,'utf8'));value.identity.home.name='Tampered';fs.writeFileSync(file,JSON.stringify(value,null,2));assert.throws(()=>buildForwardMonitoringReport(root,'2026-09-08T12:30:00Z'),/integrity/);});
