import assert from 'node:assert/strict';
import {test} from 'node:test';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {CollegeResult} from '../services/collegeScoreModel';
import {evaluateModelBGrid,fbsFcsResearchDisposition,gamesPlayedPriorWeight,ModelBGrid} from '../services/collegeScoreModelBResearch';
import {CollegeModelBForwardArchive,CollegeModelBForwardSnapshot,validateModelBForwardSnapshot} from '../services/collegeModelBForward';

function history():CollegeResult[]{const rows:CollegeResult[]=[];for(let i=0;i<120;i++){const day=1+(i%27),month=1+Math.floor(i/27),home=i%2===0;rows.push({id:`h${i}`,date:`2024-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}T18:00:00.000Z`,season:2024,homeId:home?'A':'B',awayId:home?'B':'A',homeName:home?'A':'B',awayName:home?'B':'A',homeScore:home?38:17,awayScore:home?14:35,neutral:false});}return rows;}
function target(id='t',home='A',away='B',neutral=false,score=28):CollegeResult{return {id,date:'2025-08-30T18:00:00.000Z',season:2025,homeId:home,awayId:away,homeName:home,awayName:away,homeScore:score,awayScore:14,neutral};}
const grid:ModelBGrid={b1:[{ridge:20,previousSeasonWeight:1,halfLifeDays:null}],b2:[],b3:[]};
function snapshot():CollegeModelBForwardSnapshot{return {schemaVersion:'college-model-b-forward-v1',gameId:'401-test',kickoff:'2026-09-12T18:00:00.000Z',forecastAt:'2026-09-12T12:00:00.000Z',modelAVersion:'A',modelAHomeMargin:3,modelBVersion:'B',modelBCandidate:'B1',modelBHomeMargin:4,
  features:{priorStrength:{value:1.2,asOf:'2026-09-12T11:59:00.000Z',provenance:'archived final scores',availability:'SAFE_HISTORICAL_SNAPSHOT'}},context:{neutral:{value:false,asOf:'2026-09-12T11:59:00.000Z',provenance:'ESPN event identity',availability:'VERIFIED_POINT_IN_TIME'}},externalMarketBenchmark:{homeSpread:-3.5,americanPrice:-110,capturedAt:'2026-09-12T11:58:00.000Z',source:'external benchmark'}};}

test('games-played prior weight decreases monotonically',()=>{assert.equal(gamesPlayedPriorWeight(4,0),1);assert.equal(gamesPlayedPriorWeight(4,4),.5);assert.ok(gamesPlayedPriorWeight(4,8)<.5);});
test('early season B2 uses prior and no-prior ablation abstains',()=>{const b2:ModelBGrid={b1:[],b2:[{ridge:20,transitionGames:4}],b3:[]},games=[...history(),target()];assert.equal(evaluateModelBGrid(games,2025,b2)[0].predictions[0].status,'PROJECTED');assert.equal(evaluateModelBGrid(games,2025,b2,{noPrior:true})[0].predictions[0].status,'MODEL_UNAVAILABLE');});
test('Model B opponent adjustment identifies stronger team',()=>{const result=evaluateModelBGrid([...history(),target()],2025,grid)[0];assert.equal(result.predictions[0].status,'PROJECTED');assert.ok((result.predictions[0].modelHomeMargin as number)>0);});
test('chronological fitting excludes target and later scores',()=>{const before=evaluateModelBGrid([...history(),target('t','A','B',false,28)],2025,grid)[0].predictions[0].modelHomeMargin;const after=evaluateModelBGrid([...history(),target('t','A','B',false,99)],2025,grid)[0].predictions[0].modelHomeMargin;assert.equal(before,after);});
test('deterministic reproduction returns identical result',()=>{const games=[...history(),target()];assert.deepEqual(evaluateModelBGrid(games,2025,grid),evaluateModelBGrid(games,2025,grid));});
test('missing team identity returns MODEL_UNAVAILABLE',()=>{const result=evaluateModelBGrid([...history(),target('new','A','NEW')],2025,grid)[0].predictions[0];assert.equal(result.status,'MODEL_UNAVAILABLE');assert.equal(result.modelHomeMargin,null);});
test('neutral site removes learned home-field component',()=>{const home=evaluateModelBGrid([...history(),target('home')],2025,grid)[0].predictions[0].modelHomeMargin as number;const neutral=evaluateModelBGrid([...history(),target('neutral','A','B',true)],2025,grid)[0].predictions[0].modelHomeMargin as number;assert.notEqual(home,neutral);});
test('ablation metrics change when home-field is removed',()=>{const games=[...history(),target('home')],reference=evaluateModelBGrid(games,2025,grid)[0].metrics,ablated=evaluateModelBGrid(games,2025,grid,{forceNeutral:true})[0].metrics;assert.notEqual(reference.rmse,ablated.rmse);});
test('requested fit snapshots preserve coefficients and ratings',()=>{const result=evaluateModelBGrid([...history(),target()],2025,grid,{includeRatings:true})[0];assert.equal(result.fitSnapshots.length,1);assert.ok((result.fitSnapshots[0].fits.margin?.strength.length??0)>0);});
test('FBS/FCS without validated methodology abstains',()=>{assert.equal(fbsFcsResearchDisposition(false),'MODEL_UNAVAILABLE');assert.equal(fbsFcsResearchDisposition(true),'PROJECT');});
test('forward feature timestamp must not exceed forecast',()=>{const value=snapshot();value.features.priorStrength.asOf='2026-09-12T12:01:00.000Z';assert.throws(()=>validateModelBForwardSnapshot(value),/Future information/);});
test('sportsbook data is forbidden inside Model B feature families',()=>{const value=snapshot();value.features.sportsbookSpread={value:-3.5,asOf:'2026-09-12T11:00:00.000Z',provenance:'book',availability:'VERIFIED_POINT_IN_TIME'};assert.throws(()=>validateModelBForwardSnapshot(value),/Sportsbook contamination/);});
test('external market stays separate and must be forecast-time safe',()=>{const value=snapshot();assert.doesNotThrow(()=>validateModelBForwardSnapshot(value));value.externalMarketBenchmark.capturedAt='2026-09-12T12:01:00.000Z';assert.throws(()=>validateModelBForwardSnapshot(value),/after forecast/);});
test('forward archive is idempotent but immutable',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'model-b-forward-'));try{const archive=new CollegeModelBForwardArchive(root),value=snapshot();assert.equal(archive.archiveForecast(value).created,true);assert.equal(archive.archiveForecast(value).created,false);assert.throws(()=>archive.archiveForecast({...value,modelBHomeMargin:5}),/Immutable/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('settlement is separate, final, and cannot overwrite forecast',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'model-b-settle-'));try{const archive=new CollegeModelBForwardArchive(root),value=snapshot();archive.archiveForecast(value);const result={schemaVersion:'college-model-b-settlement-v1' as const,gameId:value.gameId,settledAt:'2026-09-13T00:00:00.000Z',actualHomeMargin:7,finalStatus:'STATUS_FINAL_OVERTIME' as const,source:'verified final'};assert.equal(archive.settle(result).created,true);assert.equal(archive.settle(result).created,false);assert.throws(()=>archive.settle({...result,actualHomeMargin:8}),/Immutable/);assert.equal(JSON.parse(fs.readFileSync(path.join(root,value.gameId,'forecast.json'),'utf8')).modelBHomeMargin,4);}finally{fs.rmSync(root,{recursive:true,force:true});}});
