import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {createHash} from 'crypto';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';
import {canonicalNflGame,canonicalPlayer,nflExplicitScheduleState,resolvePropPlayer} from '../services/nflForwardIdentities';
import {parseOfficialInactives,resolveGameDayAvailability} from '../services/nflGameDayAvailability';
import {boundedLastVerifiedPregameQuotes,makeDiagnostic,NewNflForwardSnapshot,NFL_PLAYER_CATEGORIES,NFL_TEAM_CATEGORIES,NflForwardArchive,validateNflForwardSnapshot} from '../services/nflForwardResearch';

const hash=(value:unknown)=>createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
const at='2026-09-09T12:00:00.000Z',kickoff='2026-09-10T00:00:00.000Z';
function espnEvent(status:any={type:{name:'STATUS_SCHEDULED',state:'pre',completed:false}}){return{id:'401999001',date:kickoff,season:{year:2026,type:2},week:{number:1},status,competitions:[{neutralSite:false,venue:{id:'1',fullName:'Test Stadium',indoor:false,address:{country:'USA'}},competitors:[{homeAway:'away',team:{id:'10',displayName:'Away Foxes',abbreviation:'AWY'}},{homeAway:'home',team:{id:'20',displayName:'Home Bears',abbreviation:'HME'}}]}]};}
const game=canonicalNflGame(espnEvent(),at);
const player=canonicalPlayer({id:'100',name:'Alex Example Jr.',teamId:game.home.canonicalTeamId,teamName:game.home.name,position:'QB',status:'Active',rookie:true,previousTeamId:'espn-team:30',previousPosition:'RB'},at);
function snapshot():NewNflForwardSnapshot{const diagnostics=[...NFL_TEAM_CATEGORIES.flatMap(category=>[game.home,game.away].map(team=>makeDiagnostic('TEAM',category,team.canonicalTeamId,at,0,1))),...NFL_PLAYER_CATEGORIES.map(category=>makeDiagnostic('PLAYER',category,player.canonicalPlayerId,at,0,1))],source={provider:'ESPN',url:'https://example.test/data',providerRecordId:null,retrievedAt:at,effectiveAt:at,rawPayloadHash:hash('source')};return{schemaVersion:'nfl-forward-research-v1',evidenceClass:'LIVE_FORWARD',capturedAt:at,forecastAt:at,trigger:'MANUAL',captureEventId:'manual-test-1',scheduledFor:null,minutesToKickoff:720,hoursToKickoff:12,game,players:[player],footballEvidence:[{scope:'TEAM',entityId:game.home.canonicalTeamId,category:'ROSTER',field:'roster.player_count',value:53,source,validity:'VALID',freshness:'FRESH'}],diagnostics,inactiveEvidence:{state:'SEASON_PENDING',source:{...source,provider:'NFL.com'},players:[{canonicalPlayerId:player.canonicalPlayerId,state:'STATUS_PENDING',reason:'Not published.'}]},gameMarkets:[{kind:'GAME',canonicalGameId:game.canonicalGameId,canonicalPlayerId:null,market:'spreads',participant:game.home.name,side:game.home.name,line:-3,price:-110,sportsbook:'Book',providerEventId:'odds-1',quoteTimestamp:at,captureTimestamp:at,rawPayloadHash:hash('market'),label:'CONTEMPORANEOUS_QUOTE'}],propMarkets:[{kind:'PROP',canonicalGameId:game.canonicalGameId,canonicalPlayerId:player.canonicalPlayerId,market:'player_pass_yds',participant:player.name,side:'Over',line:250.5,price:-110,sportsbook:'Book',providerEventId:'odds-1',quoteTimestamp:at,captureTimestamp:at,rawPayloadHash:hash('market'),label:'CONTEMPORANEOUS_QUOTE'}],propUniverse:[{market:'player_pass_yds',participant:player.name,state:'PROP_MARKET_AVAILABLE',canonicalPlayerId:player.canonicalPlayerId,modelState:'MODEL_AVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:'STATUS_PENDING',projection:247.2,projectionVersion:'existing-v1'}],model:{gameProjection:{status:'MODEL_UNAVAILABLE',homeScore:null,awayScore:null,homeMargin:null,version:'existing-v1'}},apiUsage:[{provider:'Odds',requests:1,estimatedCredits:10,actualCredits:10,cacheHits:0,retries:0,failures:0,deferred:[]}],failures:[]};}

test('canonical NFL game preserves required identity and venue fields',()=>{assert.equal(game.canonicalGameId,'espn:401999001');assert.equal(game.home.canonicalTeamId,'espn-team:20');assert.equal(game.away.canonicalTeamId,'espn-team:10');assert.equal(game.seasonType,'REG');assert.equal(game.neutralSite,false);assert.equal(game.international,false);});
test('international and neutral-site identity are explicit',()=>{const event=espnEvent();event.competitions[0].neutralSite=true;event.competitions[0].venue.address.country='GBR';const row=canonicalNflGame(event,at);assert.equal(row.neutralSite,true);assert.equal(row.international,true);});
test('explicit status mapping accepts only explicit terminal semantics',()=>{assert.equal(nflExplicitScheduleState(espnEvent({type:{name:'STATUS_FINAL_OVERTIME',state:'post',completed:true}})),'FINAL');assert.equal(nflExplicitScheduleState(espnEvent({type:{name:'STATUS_FINAL',state:'pre',completed:false}})),'UNKNOWN');assert.equal(nflExplicitScheduleState(espnEvent({type:{name:'STATUS_POSTPONED',state:'pre'}})),'POSTPONED');assert.equal(nflExplicitScheduleState(espnEvent({type:{name:'STATUS_CANCELED',state:'post'}})),'CANCELED');assert.equal(nflExplicitScheduleState(espnEvent({type:{name:'STATUS_ABANDONED',state:'post'}})),'ABANDONED');});
test('canonical player preserves rookie, team change, position change and effective time',()=>{assert.equal(player.rookie,'YES');assert.equal(player.teamChange,'CHANGED');assert.equal(player.positionChange,'CHANGED');assert.equal(player.effectiveAt,at);});
test('suffix-normalized prop player resolves to current game roster',()=>{assert.equal(resolvePropPlayer('Alex Example', [player], game).player?.canonicalPlayerId,player.canonicalPlayerId);});
test('duplicate player names fail closed',()=>{const duplicate={...player,canonicalPlayerId:'espn-player:101',providerPlayerIds:{ESPN:'101'},teamId:game.away.canonicalTeamId};assert.equal(resolvePropPlayer('Alex Example',[player,duplicate],game).player,null);assert.match(resolvePropPlayer('Alex Example',[player,duplicate],game).reason!,/Duplicate/);});
test('absent prop player remains unresolved',()=>assert.equal(resolvePropPlayer('Nobody Listed',[player],game).player,null));

test('season-pending official page never infers ACTIVE',()=>{const page=parseOfficialInactives('<p>Please check back soon for NFL Inactive Reports for this Season</p>',at),result=resolveGameDayAvailability(page,{homeTeam:game.home.name,awayTeam:game.away.name},{name:player.name,team:game.home.name});assert.equal(page.pageState,'SEASON_PENDING');assert.equal(result.state,'STATUS_PENDING');});
test('unverified official page returns UNKNOWN',()=>{const page=parseOfficialInactives('<html>changed format</html>',at);assert.equal(resolveGameDayAvailability(page,{homeTeam:game.home.name,awayTeam:game.away.name},{name:player.name,team:game.home.name}).state,'STATUS_UNKNOWN');});
test('complete official list verifies inactive and active separately',()=>{const html=`<script id="__NFL_INACTIVES_DATA__">${JSON.stringify({sourceTimestamp:at,games:[{id:'nfl-1',homeTeam:game.home.name,awayTeam:game.away.name,complete:true,inactivePlayers:[{id:'100',name:player.name,team:game.home.name}]}]})}</script>`,page=parseOfficialInactives(html,at);assert.equal(resolveGameDayAvailability(page,{providerGameId:'nfl-1',homeTeam:game.home.name,awayTeam:game.away.name},{providerPlayerId:'100',name:player.name,team:game.home.name}).state,'INACTIVE_VERIFIED');assert.equal(resolveGameDayAvailability(page,{providerGameId:'nfl-1',homeTeam:game.home.name,awayTeam:game.away.name},{name:'Other Player',team:game.home.name}).state,'ACTIVE_VERIFIED');});
test('partial official list is rejected rather than used to infer active',()=>{const html=`<script id="__NFL_INACTIVES_DATA__">${JSON.stringify({games:[{id:'1',homeTeam:'H',awayTeam:'A',complete:false,inactivePlayers:[]}]})}</script>`;assert.equal(parseOfficialInactives(html,at).pageState,'MALFORMED_OR_UNVERIFIED');});

test('valid forward snapshot passes complete persisted diagnostic contract',()=>assert.match(validateNflForwardSnapshot(snapshot()).contentHash,/^[a-f0-9]{64}$/));
test('protected cutoff rejects reconstructed earlier capture',()=>{const row=snapshot(),before=new Date(Date.parse(NFL_FORWARD_POLICY.protectedCutoff)-1).toISOString();row.capturedAt=before;row.forecastAt=before;row.minutesToKickoff=(Date.parse(kickoff)-Date.parse(before))/60000;row.hoursToKickoff=row.minutesToKickoff/60;assert.throws(()=>validateNflForwardSnapshot(row),/cutoff/);});
test('post-kickoff snapshot fails closed',()=>{const row=snapshot();row.capturedAt=kickoff;row.forecastAt=kickoff;row.minutesToKickoff=0;row.hoursToKickoff=0;assert.throws(()=>validateNflForwardSnapshot(row),/post-kickoff/);});
test('future-retrieved football evidence is a leakage violation',()=>{const row=snapshot();row.footballEvidence[0].source.retrievedAt='2026-09-09T12:00:01.000Z';assert.throws(()=>validateNflForwardSnapshot(row),/LEAKAGE_VIOLATION/);});
test('future-effective football evidence is a leakage violation',()=>{const row=snapshot();row.footballEvidence[0].source.effectiveAt='2026-09-09T12:00:01.000Z';assert.throws(()=>validateNflForwardSnapshot(row),/LEAKAGE_VIOLATION/);});
test('market-contaminated football feature fails closed',()=>{const row=snapshot();row.footballEvidence[0].field='sportsbook.spread';assert.throws(()=>validateNflForwardSnapshot(row),/MARKET_CONTAMINATION/);});
test('market contamination does not reject separately labeled market evidence',()=>assert.doesNotThrow(()=>validateNflForwardSnapshot(snapshot())));
test('future quote is rejected',()=>{const row=snapshot();row.propMarkets[0].quoteTimestamp='2026-09-09T12:01:00.000Z';assert.throws(()=>validateNflForwardSnapshot(row),/future market/);});
test('missing six-stage category is rejected',()=>{const row=snapshot();row.diagnostics=row.diagnostics.filter(d=>!(d.scope==='TEAM'&&d.entityId===game.home.canonicalTeamId&&d.category==='WEATHER'));assert.throws(()=>validateNflForwardSnapshot(row),/Missing team diagnostic/);});

test('immutable archive survives reopening and verifies hashes',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-forward-'));try{const first=new NflForwardArchive(root).capture(snapshot());assert.equal(first.created,true);const reopened=new NflForwardArchive(root);assert.equal(reopened.load().snapshots.length,1);assert.equal(reopened.verify().status,'PASS');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('same capture event retry deduplicates',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-forward-'));try{const archive=new NflForwardArchive(root),first=archive.capture(snapshot()),second=archive.capture(snapshot());assert.equal(first.snapshotId,second.snapshotId);assert.equal(second.status,'RETRY_DUPLICATE');assert.equal(archive.load().snapshots.length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('different manual capture key preserves new point-in-time observation',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-forward-'));try{const archive=new NflForwardArchive(root),one=snapshot(),two=snapshot();two.captureEventId='manual-test-2';two.capturedAt='2026-09-09T12:01:00.000Z';two.forecastAt=two.capturedAt;two.minutesToKickoff=719;two.hoursToKickoff=719/60;two.diagnostics=two.diagnostics.map(d=>({...d,forecastAt:two.forecastAt}));two.footballEvidence=two.footballEvidence.map(e=>({...e,source:{...e.source,retrievedAt:two.forecastAt,effectiveAt:two.forecastAt}}));two.inactiveEvidence={...two.inactiveEvidence,source:{...two.inactiveEvidence.source,retrievedAt:two.forecastAt,effectiveAt:two.forecastAt}};two.gameMarkets=two.gameMarkets.map(q=>({...q,quoteTimestamp:two.forecastAt,captureTimestamp:two.forecastAt}));two.propMarkets=two.propMarkets.map(q=>({...q,quoteTimestamp:two.forecastAt,captureTimestamp:two.forecastAt}));archive.capture(one);assert.equal(archive.capture(two).status,'NEW_POINT_IN_TIME_SNAPSHOT');assert.equal(archive.load().snapshots.length,2);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('schedule changes, finals, player stats and settlement evidence are append-only kinds',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-forward-'));try{const archive=new NflForwardArchive(root);archive.capture(snapshot());for(const kind of ['schedule_changes','final_results','player_final_stats','settlement_evidence'] as const)assert.equal(archive.append(kind,{recordedAt:at,gameId:game.canonicalGameId,value:kind}).created,true);assert.equal(archive.load().index.records.length,4);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('deterministic export hash ignores export time',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-forward-'));try{const archive=new NflForwardArchive(root);archive.capture(snapshot());assert.equal(archive.export(at).datasetHash,archive.export('2026-09-09T13:00:00.000Z').datasetHash);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('PROP_NOT_POSTED is valid and distinct from provider failure',()=>{const row=snapshot();row.propMarkets=[];row.propUniverse=[{market:'player_receptions',participant:'',state:'PROP_NOT_POSTED',canonicalPlayerId:null,modelState:'MODEL_UNAVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:'STATUS_PENDING',projection:null,projectionVersion:null}];assert.doesNotThrow(()=>validateNflForwardSnapshot(row));});
test('provider outage is MARKET_UNAVAILABLE rather than PROP_NOT_POSTED',()=>{const row=snapshot();row.propMarkets=[];row.propUniverse=[{market:'player_receptions',participant:'',state:'MARKET_UNAVAILABLE',canonicalPlayerId:null,modelState:'MODEL_UNAVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:'STATUS_UNKNOWN',projection:null,projectionVersion:null}];row.failures=[{provider:'Odds',category:'MARKET',message:'unavailable',at}];assert.doesNotThrow(()=>validateNflForwardSnapshot(row));});
test('bounded late quote is labeled last verified pregame rather than closing',()=>{const row={snapshotId:'x',componentHashes:{},...snapshot()} as any,quotes=boundedLastVerifiedPregameQuotes([row]);assert.ok(quotes.length>0);assert.ok(quotes.every(quote=>quote.label==='LAST_VERIFIED_PREGAME_QUOTE'));});
