import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'crypto';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';
import {buildNflCriticalFeatureHealth,buildNflFeatureScorecard,buildNflForwardRows,createNflForwardFeature,detectNflFeatureChanges,NFL_FEATURE_SCORECARD_CATEGORIES,NFL_NEXT_MODEL_DATA_GATES,NFL_PHASE4_PROVIDER_COST_AUDIT,NflForwardFeatureRecord,nflCaptureWindow,nflForwardSampleLabel,nflPositionImportanceGroup,nflRestFeatures,NflRequestDeduplicator,normalizeNflForwardRole,rawShare,unavailableNflFeature,validateNflForwardFeature,validateNflTargetRecord,validateWeatherForecast} from '../services/nflForwardFeatures';
import {makeDiagnostic,NewNflForwardSnapshot,NFL_PLAYER_CATEGORIES,NFL_TEAM_CATEGORIES,NflForwardArchive} from '../services/nflForwardResearch';
import {NflCollectorAdapter,NflForwardOperationalCollector} from '../services/nflForwardOperations';

const at='2026-09-09T12:00:00.000Z',kickoff='2026-09-10T00:00:00.000Z',hash=(value:string)=>createHash('sha256').update(value).digest('hex'),integrity={SOURCE_RETRIEVAL:'PASS' as const,NORMALIZATION:'PASS' as const,ENTITY_MATCHING:'PASS' as const,CONTEXT_ATTACHMENT:'PASS' as const,FIELD_VALIDITY:'PASS' as const,FRESHNESS:'PASS' as const};
function feature(overrides:Partial<Parameters<typeof createNflForwardFeature>[0]>={}):NflForwardFeatureRecord{return createNflForwardFeature({gameId:'espn:1',teamId:'espn-team:1',playerId:null,category:'TEAM_VOLUME',field:'team.offensive_snaps',captureTimestamp:at,forecastTimestamp:at,kickoffTimestamp:kickoff,source:'ESPN',sourceTimestamp:'2026-09-08T00:00:00.000Z',retrievalTimestamp:at,rawEvidenceReference:hash('raw'),normalizedValue:64,numerator:64,denominator:null,qualityState:'VERIFIED',freshnessState:'FRESH',integrity,correctionOf:null,notes:[],...overrides});}
function snapshot(record=feature()):NewNflForwardSnapshot{const game={canonicalGameId:'espn:1',providerGameIds:{ESPN:'1'},season:2026 as const,seasonType:'REG' as const,week:1,away:{canonicalTeamId:'espn-team:2',name:'Away',abbreviation:'AWY'},home:{canonicalTeamId:'espn-team:1',name:'Home',abbreviation:'HOM'},scheduledKickoff:kickoff,venue:{id:'v1',name:'Venue',indoor:false},neutralSite:false,international:false,status:'SCHEDULED' as const},player={canonicalPlayerId:'espn-player:10',providerPlayerIds:{ESPN:'10'},name:'Quarter Back',teamId:game.home.canonicalTeamId,position:'QB',season:2026 as const,effectiveAt:at,rookie:'NO' as const,newTeam:'NO' as const,teamChange:'UNCHANGED' as const,positionChange:'UNCHANGED' as const},diagnostics=[...NFL_TEAM_CATEGORIES.flatMap(category=>[game.home,game.away].map(team=>makeDiagnostic('TEAM',category,team.canonicalTeamId,at,0,1))),...NFL_PLAYER_CATEGORIES.map(category=>makeDiagnostic('PLAYER',category,player.canonicalPlayerId,at,0,1))],source={provider:'NFL.com',url:'https://example.test',providerRecordId:null,retrievedAt:at,effectiveAt:at,rawPayloadHash:hash('inactive')};return{schemaVersion:'nfl-forward-research-v1',evidenceClass:'LIVE_FORWARD',capturedAt:at,forecastAt:at,trigger:'MANUAL',captureEventId:'manual-phase4',scheduledFor:null,minutesToKickoff:720,hoursToKickoff:12,captureWindow:'6-24H',game,players:[player],footballEvidence:[],featureRecords:[record],featureEvents:[],featureCoverage:buildNflFeatureScorecard([record],{TEAM_VOLUME:1}),criticalFeatureHealth:buildNflCriticalFeatureHealth({startingQb:'PARTIAL',gameIdentity:'PASS',kickoff:'PASS',marketIdentity:'FAIL',injuryInactiveEvidence:'PARTIAL',currentSeasonTeamSample:'PARTIAL'}),diagnostics,inactiveEvidence:{state:'SEASON_PENDING',source,players:[{canonicalPlayerId:player.canonicalPlayerId,state:'STATUS_PENDING',reason:'Pending'}]},gameMarkets:[],propMarkets:[],propUniverse:[],model:{gameProjection:null},apiUsage:[],failures:[]};}

test('feature records persist all six programmatic integrity stages at forecast time',()=>{const row=feature();assert.deepEqual(Object.keys(row.integrity).sort(),['CONTEXT_ATTACHMENT','ENTITY_MATCHING','FIELD_VALIDITY','FRESHNESS','NORMALIZATION','SOURCE_RETRIEVAL']);assert.equal(row.forecastTimestamp,at);assert.equal(row.captureTimestamp,at);assert.equal(row.minutesToKickoff,720);});
test('actual capture windows use strict descriptive boundaries',()=>{assert.equal(nflCaptureWindow(1441),'>24H');assert.equal(nflCaptureWindow(1440),'6-24H');assert.equal(nflCaptureWindow(360),'1-6H');assert.equal(nflCaptureWindow(60),'<1H');assert.throws(()=>nflCaptureWindow(0));});
test('content-addressed feature validation rejects tampering',()=>{const row=feature();(row as any).normalizedValue=65;assert.throws(()=>validateNflForwardFeature(row),/hash mismatch/);});
test('future feature retrieval is rejected',()=>assert.throws(()=>feature({retrievalTimestamp:'2026-09-09T12:00:01.000Z'}),/FUTURE_LEAKAGE/));
test('future source publication is rejected',()=>assert.throws(()=>feature({sourceTimestamp:'2026-09-09T12:00:01.000Z'}),/FUTURE_LEAKAGE/));
test('market fields cannot contaminate independent football features',()=>assert.throws(()=>feature({field:'team.sportsbook_spread'}),/MARKET_CONTAMINATION/));
test('market namespace remains separate and explicit',()=>assert.doesNotThrow(()=>feature({category:'MARKET',field:'market.spread',normalizedValue:{spread:-3}})));
test('target share preserves raw targets and team passing denominator',()=>assert.deepEqual(rawShare(8,32,'TARGET_SHARE'),{numerator:8,denominator:32,share:.25,label:'TARGET_SHARE'}));
test('carry share preserves raw carries and team rush denominator',()=>assert.deepEqual(rawShare(12,24,'CARRY_SHARE'),{numerator:12,denominator:24,share:.5,label:'CARRY_SHARE'}));
test('snap calculation never becomes route participation',()=>{const row=feature({playerId:'espn-player:10',category:'SNAPS',field:'player.snap_share',normalizedValue:rawShare(48,64,'SNAP_SHARE'),numerator:48,denominator:64});assert.equal((row.normalizedValue as any).share,.75);assert.equal(row.category,'SNAPS');});
test('invalid opportunity numerator and denominator fail closed',()=>assert.throws(()=>feature({numerator:65,denominator:64}),/numerator/));
test('route unavailability is explicit and contains no synthesized value',()=>{const row=unavailableNflFeature({gameId:'espn:1',teamId:'espn-team:1',playerId:'espn-player:10',category:'ROUTES',field:'player.route_participation',captureTimestamp:at,kickoffTimestamp:kickoff,reason:'ROUTE_DATA_UNAVAILABLE'});assert.equal(row.normalizedValue,null);assert.equal(row.qualityState,'UNAVAILABLE');assert.equal(row.integrity.SOURCE_RETRIEVAL,'FAIL');});
test('pregame weather rejects a forecast published after forecast time',()=>assert.throws(()=>validateWeatherForecast({forecastTimestamp:'2026-09-09T12:01:00.000Z',retrievalTimestamp:at,forecastAt:at,kickoffTimestamp:kickoff,temperatureF:70,windMph:5,gustMph:10,precipitationProbability:20,precipitationType:'rain',humidity:50,indoor:false}),/WEATHER_FUTURE/));
test('pregame weather with unknown issuance time remains explicitly partial',()=>assert.equal(validateWeatherForecast({forecastTimestamp:null,retrievalTimestamp:at,forecastAt:at,kickoffTimestamp:kickoff,temperatureF:70,windMph:5,gustMph:null,precipitationProbability:null,precipitationType:null,humidity:null,indoor:false}).quality,'SOURCE_TIMESTAMP_UNKNOWN'));
test('rest features calculate short week, bye, Thursday and prior overtime without weights',()=>{const short=nflRestFeatures({kickoffTimestamp:'2026-09-13T17:00:00Z',priorKickoffs:[{kickoff:'2026-09-08T00:00:00Z',final:true,overtime:true,away:true,international:false}]});assert.equal(short.shortWeek,true);assert.equal(short.previousGameOvertime,true);const bye=nflRestFeatures({kickoffTimestamp:'2026-09-17T17:00:00Z',priorKickoffs:[{kickoff:'2026-09-03T17:00:00Z',final:true,overtime:false,away:false,international:false}]});assert.equal(bye.byeWeek,true);assert.equal(bye.thursday,true);});
test('QB starter change is timestamped and linked to both evidence records',()=>{const old=feature({category:'QB',field:'qb.projected_starter',normalizedValue:'espn-player:10'}),next=feature({category:'QB',field:'qb.projected_starter',normalizedValue:'espn-player:11',rawEvidenceReference:hash('new')});const event=detectNflFeatureChanges([old],[next],at)[0];assert.equal(event.type,'QB_STARTER_CHANGED');assert.equal(event.previousRecordId,old.recordId);assert.equal(event.currentRecordId,next.recordId);});
test('QB inactive and unresolved transitions retain exact event semantics',()=>{const old=feature({category:'QB',field:'qb.status',normalizedValue:'QUESTIONABLE'}),inactive=feature({category:'QB',field:'qb.status',normalizedValue:'INACTIVE_VERIFIED',rawEvidenceReference:hash('inactive2')}),unresolved=feature({category:'QB',field:'qb.status',normalizedValue:'UNRESOLVED',rawEvidenceReference:hash('unknown')});assert.equal(detectNflFeatureChanges([old],[inactive],at)[0].type,'QB_INACTIVE_VERIFIED');assert.equal(detectNflFeatureChanges([inactive],[unresolved],at)[0].type,'QB_STARTER_UNRESOLVED');});
test('depth and role changes produce immutable change events',()=>{const old=feature({playerId:'espn-player:10',category:'DEPTH_CHART',field:'player.depth_order',normalizedValue:2}),next=feature({playerId:'espn-player:10',category:'DEPTH_CHART',field:'player.depth_order',normalizedValue:1,rawEvidenceReference:hash('depth')});assert.equal(detectNflFeatureChanges([old],[next],at)[0].type,'DEPTH_ORDER_CHANGE');const unknown=feature({playerId:'espn-player:10',category:'PLAYER_ROLE',field:'player.role',normalizedValue:'UNKNOWN'}),known=feature({playerId:'espn-player:10',category:'PLAYER_ROLE',field:'player.role',normalizedValue:'WR2',rawEvidenceReference:hash('role')});assert.equal(detectNflFeatureChanges([unknown],[known],at)[0].type,'UNKNOWN_TO_CONFIRMED');});
test('injury evidence remains a player-scoped point-in-time feature',()=>{const row=feature({playerId:'espn-player:10',category:'INJURIES',field:'player.practice_and_game_status',normalizedValue:{practice:'LIMITED',designation:'QUESTIONABLE'}});assert.equal(row.playerId,'espn-player:10');assert.equal(row.pointInTimeClassification,'PREGAME_KNOWN');});
test('injury reporting classifies position importance without assigning point values',()=>{assert.equal(nflPositionImportanceGroup('QB'),'QB');assert.equal(nflPositionImportanceGroup('LT'),'OL');assert.equal(nflPositionImportanceGroup('OT'),'OL');assert.equal(nflPositionImportanceGroup('OLB'),'EDGE');assert.equal(nflPositionImportanceGroup('FS'),'S');});
test('forward role states use the declared QB RB WR and TE vocabulary',()=>{assert.equal(normalizeNflForwardRole('QB','STARTER_UNVERIFIED'),'QB1');assert.equal(normalizeNflForwardRole('RB','PASSING_DOWN_BACK'),'PASSING_DOWN');assert.equal(normalizeNflForwardRole('WR','SLOT'),'SLOT');assert.equal(normalizeNflForwardRole('TE','BLOCKING_HEAVY'),'BLOCKING_HEAVY');assert.equal(normalizeNflForwardRole('TE','WR1'),'UNKNOWN');});
test('coverage scorecard includes every required category with raw counts and no weighted score',()=>{const rows=buildNflFeatureScorecard([feature()],{TEAM_VOLUME:2,QB:2});assert.deepEqual(rows.map(row=>row.category),NFL_FEATURE_SCORECARD_CATEGORIES);assert.equal(rows.find(row=>row.category==='TEAM_VOLUME')!.status,'PARTIAL');assert.equal(rows.find(row=>row.category==='QB')!.status,'FAIL');assert.equal('weightedScore' in (rows as any),false);});
test('critical health uses deterministic requirement states and counts only',()=>{const row=buildNflCriticalFeatureHealth({startingQb:'PASS',gameIdentity:'PASS',kickoff:'PASS',marketIdentity:'PASS',injuryInactiveEvidence:'PARTIAL',currentSeasonTeamSample:'UNKNOWN'});assert.equal(row.status,'PARTIAL');assert.deepEqual(row.counts,{pass:4,partial:1,fail:0,unknown:1});assert.match(row.authorizationBasis,/DETERMINISTIC/);});
test('request deduplicator coalesces concurrent work and safely reuses cache',async()=>{let calls=0,clock=1;const cache=new NflRequestDeduplicator(()=>clock),load=async()=>{calls++;await Promise.resolve();return{value:7};},[one,two]=await Promise.all([cache.get('team:1',100,load),cache.get('team:1',100,load)]);assert.equal(calls,1);assert.deepEqual(one.value,two.value);assert.equal(two.cacheHit,true);clock=102;await cache.get('team:1',100,load);assert.equal(calls,2);});
test('provider audit adds no new paid provider and preserves explicit existing odds cap',()=>{assert.equal(NFL_PHASE4_PROVIDER_COST_AUDIT.find(row=>row.provider==='Dedicated route/depth/injury vendor')!.requestPattern,'not enabled');assert.match(String(NFL_PHASE4_PROVIDER_COST_AUDIT.find(row=>row.provider==='The Odds API')!.estimatedPaidCredits),/0-200/);});
test('postgame targets stay separate and cannot masquerade as pregame features',()=>{const row=validateNflTargetRecord({gameId:'espn:1',teamId:null,playerId:null,recordedAt:'2026-09-10T04:00:00Z',kickoffTimestamp:kickoff,source:'ESPN_FINAL',sourceTimestamp:'2026-09-10T03:30:00Z',rawEvidenceReference:hash('final'),field:'final_total',value:47,classification:'POSTGAME_TARGET_ONLY',correctionOf:null});assert.equal(row.classification,'POSTGAME_TARGET_ONLY');assert.throws(()=>validateNflTargetRecord({...row,recordedAt:at} as any));});
test('settlement targets append outside pregame snapshots',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-phase4-target-'));try{const archive=new NflForwardArchive(root);archive.capture(snapshot());const result=archive.appendTarget({gameId:'espn:1',teamId:null,playerId:null,recordedAt:'2026-09-10T04:00:00Z',kickoffTimestamp:kickoff,source:'ESPN_FINAL',sourceTimestamp:'2026-09-10T03:30:00Z',rawEvidenceReference:hash('final-target'),field:'final_margin',value:3,classification:'POSTGAME_TARGET_ONLY',correctionOf:null});assert.equal(result.created,true);assert.equal(archive.load().snapshots[0].featureRecords?.length,1);assert.equal(archive.load().index.records[0].kind,'forward_targets');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('deterministic row builder preserves forecast time and empty target slots',()=>{const snap=snapshot(),stored={snapshotId:hash('snapshot'),componentHashes:{},...snap},one=buildNflForwardRows([stored]),two=buildNflForwardRows([stored]);assert.equal(one.datasetHash,two.datasetHash);assert.equal(one.gameRows[0].forecastTimestamp,at);assert.deepEqual(one.playerGameRows[0].targets,[]);});
test('row builder rejects a feature attached to a different forecast timestamp',()=>{const snap=snapshot(),row=snap.featureRecords![0];(row as any).forecastTimestamp='2026-09-09T11:00:00.000Z';assert.throws(()=>buildNflForwardRows([{snapshotId:hash('snapshot'),...snap} as any]),/ROW_LEAKAGE/);});
test('feature components are immutable, reopenable and hash verified',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-phase4-'));try{const archive=new NflForwardArchive(root),result=archive.capture(snapshot());assert.equal(result.created,true);const reopened=new NflForwardArchive(root);assert.equal(reopened.verify().status,'PASS');const saved=reopened.load().snapshots[0];assert.equal(saved.featureRecords?.length,1);assert.ok(saved.componentHashes.forwardFeatures.length===1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('manual operational collection reports feature and API summaries from archived snapshots',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-phase4-run-')),adapter:NflCollectorAdapter={discover:async()=>({games:[{gameId:'espn:1',kickoff,status:'SCHEDULED',missingIdentity:0,payload:null}],requests:1,failures:[]}),plan:()=>[{provider:'ESPN',category:'FEATURES',maximumRequests:1,estimatedCredits:0,priority:1,scope:'game'}],prepare:async()=>({state:null,apiUsage:[{provider:'ESPN',requests:1,estimatedCredits:0,actualCredits:0,cacheHits:0,retries:0,failures:0,deferred:[]}],failures:[],deferred:[]}),capture:async(_game,_prepared,meta)=>({...snapshot(),captureEventId:meta.captureEventId})};try{const run=await new NflForwardOperationalCollector(root,adapter,()=>Date.parse(at)).run({trigger:'MANUAL',dryRun:false,idempotencyKey:'phase4-run'});assert.equal(run.status,'SUCCESS');assert.equal(run.summary.gamesCaptured,1);assert.equal(run.summary.teamRecordsCaptured,1);assert.equal(run.summary.apiRequests,2);assert.equal(run.summary.actualPaidCredits,0);assert.equal(run.featureScorecard.find(row=>row.category==='TEAM_VOLUME')!.status,'PASS');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('feature correction links to prior evidence without rewriting it',()=>{const original=feature(),corrected=feature({normalizedValue:65,numerator:65,rawEvidenceReference:hash('correction'),correctionOf:original.recordId});assert.equal(corrected.correctionOf,original.recordId);assert.notEqual(corrected.recordId,original.recordId);assert.equal(original.normalizedValue,64);});
test('manual-only policy, protected cutoff and future data gates remain frozen',()=>{assert.equal(NFL_FORWARD_POLICY.protectedCutoff,'2026-09-08T02:19:07.588Z');assert.equal(NFL_NEXT_MODEL_DATA_GATES.gameModels.minimumSettledGameForecasts,200);assert.equal(NFL_NEXT_MODEL_DATA_GATES.playerOpportunity.positionsRequired.includes('TE'),true);});
test('forward sample labels do not call 200 observations proof',()=>{assert.equal(nflForwardSampleLabel(49),'EARLY COLLECTION');assert.equal(nflForwardSampleLabel(50),'PRELIMINARY');assert.equal(nflForwardSampleLabel(199),'PRELIMINARY');assert.equal(nflForwardSampleLabel(200),'RESEARCH-EVALUABLE');});
