import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {buildNflOperationalStatus,centralScheduledInstant,nextNflCentralRun,nflCaptureEventId,NflCollectorAdapter,NflForwardOperationalCollector} from '../services/nflForwardOperations';
import {LiveNflForwardCollectorAdapter} from '../services/nflForwardCollectorRuntime';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';

test('7 AM and 2 PM Central scheduling respects summer CDT',()=>{assert.equal(centralScheduledInstant('2026-09-07',7),'2026-09-07T12:00:00.000Z');assert.equal(centralScheduledInstant('2026-09-07',14),'2026-09-07T19:00:00.000Z');});
test('7 AM and 2 PM Central scheduling respects winter CST',()=>{assert.equal(centralScheduledInstant('2026-12-07',7),'2026-12-07T13:00:00.000Z');assert.equal(centralScheduledInstant('2026-12-07',14),'2026-12-07T20:00:00.000Z');});
test('DST transition changes UTC offset without changing Central wall time',()=>{assert.equal(centralScheduledInstant('2026-10-31',7),'2026-10-31T12:00:00.000Z');assert.equal(centralScheduledInstant('2026-11-02',7),'2026-11-02T13:00:00.000Z');});
test('next run selects same-day afternoon after morning',()=>assert.deepEqual(nextNflCentralRun(Date.parse('2026-09-07T13:00:00.000Z')),{trigger:'SCHEDULED_1400_CT',at:'2026-09-07T19:00:00.000Z'}));
test('manual collection requires bounded idempotency key',()=>assert.throws(()=>nflCaptureEventId('MANUAL',Date.now()),/idempotency/));
test('same manual key produces deterministic capture event ID',()=>assert.equal(nflCaptureEventId('MANUAL',1,'same'),nflCaptureEventId('MANUAL',2,'same')));
test('market request planning is deterministically capped at 20 requests and 200 credits',()=>{const live=new LiveNflForwardCollectorAdapter(),games=Array.from({length:30},(_,i)=>({gameId:`espn:${i}`,kickoff:new Date(Date.parse('2026-09-10T00:00:00.000Z')+i*60000).toISOString(),status:'SCHEDULED' as const,missingIdentity:0,payload:{provider:{id:`odds-${i}`}}})),row=live.plan(games,'2026-09-09T00:00:00.000Z').find(item=>item.provider==='The Odds API')!;assert.equal(row.maximumRequests,20);assert.equal(row.estimatedCredits,200);});
test('health is not configured without durable scheduler and stale before a scheduled run exists',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-health-'));try{assert.equal(buildNflOperationalStatus(root,Date.parse('2026-09-09T00:00:00.000Z'),{scheduler:false,durableStorage:false}).health,'NOT_CONFIGURED');assert.equal(buildNflOperationalStatus(root,Date.parse('2026-09-09T00:00:00.000Z'),{scheduler:true,durableStorage:true}).health,'STALE');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('manual-only mode is healthy without inventing missed scheduled runs',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-manual-health-'));try{const status=buildNflOperationalStatus(root,Date.parse('2026-09-09T00:00:00.000Z'),{scheduler:false,durableStorage:true,collectionMode:'MANUAL_ONLY'});assert.equal(status.health,'HEALTHY');assert.equal(status.collectionMode,'MANUAL_ONLY');assert.equal(status.scheduledCollection,'DISABLED_BY_CONFIGURATION');assert.equal(status.manualCollection,'AVAILABLE');assert.equal(status.nextExpectedRun,null);assert.deepEqual(status.missedScheduledRuns,[]);assert.equal(status.last7AmRun,null);assert.equal(status.last2PmRun,null);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('manual-only workflow preserves dispatch, collector, archive verification, and dormant Central schedule',()=>{const file=path.resolve(process.cwd(),'..','.github','workflows','nfl-forward-collector.yml'),yaml=fs.readFileSync(file,'utf8'),active=yaml.split(/\r?\n/).filter(line=>!/^\s*#/.test(line)).join('\n');assert.match(active,/workflow_dispatch:/);assert.doesNotMatch(active,/^\s+schedule:/m);assert.doesNotMatch(active,/^\s+- cron:/m);assert.match(active,/NFL_FORWARD_COLLECTION_MODE: 'manual_only'/);assert.match(active,/NFL_FORWARD_SCHEDULER_CONFIGURED: 'false'/);assert.match(active,/echo "trigger=MANUAL"/);assert.match(active,/npm run research:nfl-forward-collect/);assert.match(active,/npm run research:nfl-forward-verify/);assert.match(active,/git add research\/nfl-forward-archive/);assert.match(yaml,/#\s+schedule:/);assert.match(yaml,/#\s+- cron: '0 7 \* \* \*'/);assert.match(yaml,/#\s+- cron: '0 14 \* \* \*'/);assert.match(yaml,/#\s+timezone: 'America\/Chicago'/);});
test('manual-only change preserves exact protected forward cutoff',()=>assert.equal(NFL_FORWARD_POLICY.protectedCutoff,'2026-09-08T02:19:07.588Z'));
test('manual run preserves request, credit, cache, retry, failure, and deferred accounting',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-accounting-')),live=adapter();live.prepare=async()=>({state:null,apiUsage:[{provider:'The Odds API',requests:2,estimatedCredits:20,actualCredits:20,cacheHits:3,retries:1,failures:1,deferred:['later props']}],failures:['one bounded provider failure'],deferred:['later props']});try{const result=await new NflForwardOperationalCollector(root,live,()=>Date.parse('2026-09-09T12:00:00.000Z')).run({trigger:'MANUAL',dryRun:false,idempotencyKey:'accounting'});assert.equal(result.trigger,'MANUAL');assert.deepEqual(result.apiUsage[0],{provider:'The Odds API',requests:2,estimatedCredits:20,actualCredits:20,cacheHits:3,retries:1,failures:1,deferred:['later props']});assert.deepEqual(result.deferred,['later props']);assert.deepEqual(result.providerFailures,['one bounded provider failure']);assert.equal(result.eligibleGames,1);assert.equal(result.observations.length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});

function adapter(state:'SCHEDULED'|'CANCELED'|'POSTPONED'|'IN_PROGRESS'='SCHEDULED'):NflCollectorAdapter{return{discover:async()=>({games:[{gameId:'espn:1',kickoff:'2026-09-10T00:00:00.000Z',status:state,missingIdentity:0,payload:null}],requests:1,failures:[]}),plan:()=>[{provider:'Odds',category:'CORE',maximumRequests:1,estimatedCredits:10,priority:1,scope:'all'}],prepare:async()=>({state:null,apiUsage:[],failures:[],deferred:[]}),capture:async()=>{throw Error('capture fixture intentionally unavailable');}};}
test('dry run discovers and plans without writing archive',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-ops-'));try{const collector=new NflForwardOperationalCollector(root,adapter(),()=>Date.parse('2026-09-09T12:00:00.000Z')),result=await collector.run({trigger:'MANUAL',dryRun:true,idempotencyKey:'dry'});assert.equal(result.status,'DRY_RUN');assert.equal(result.observations[0].status,'WOULD_CAPTURE');assert.equal(fs.existsSync(path.join(root,'nfl_forward_research')),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('canceled game is considered but not captured',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-ops-'));try{const result=await new NflForwardOperationalCollector(root,adapter('CANCELED'),()=>Date.parse('2026-09-09T12:00:00.000Z')).run({trigger:'MANUAL',dryRun:false,idempotencyKey:'cancel'});assert.equal(result.eligibleGames,0);assert.equal(result.observations[0].status,'SKIPPED_STATUS');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('postponed game is considered but not captured',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-ops-'));try{const result=await new NflForwardOperationalCollector(root,adapter('POSTPONED'),()=>Date.parse('2026-09-09T12:00:00.000Z')).run({trigger:'MANUAL',dryRun:false,idempotencyKey:'postponed'});assert.equal(result.observations[0].status,'SKIPPED_STATUS');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('in-progress game is considered but not captured',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-ops-'));try{const result=await new NflForwardOperationalCollector(root,adapter('IN_PROGRESS'),()=>Date.parse('2026-09-09T12:00:00.000Z')).run({trigger:'MANUAL',dryRun:false,idempotencyKey:'in'});assert.equal(result.observations[0].status,'SKIPPED_STATUS');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('game with elapsed kickoff is rejected before adapter capture',async()=>{const old=adapter(),base=old.discover;old.discover=async at=>{const result=await base(at);result.games[0].kickoff='2026-09-09T11:59:59.000Z';return result;};const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-ops-'));try{const result=await new NflForwardOperationalCollector(root,old,()=>Date.parse('2026-09-09T12:00:00.000Z')).run({trigger:'MANUAL',dryRun:false,idempotencyKey:'started'});assert.equal(result.observations[0].status,'SKIPPED_STARTED');}finally{fs.rmSync(root,{recursive:true,force:true});}});
