import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import {buildNflOpportunityProjection,classifyNflOpportunityRole,NFL_OPPORTUNITY_MODEL_VERSION,NflOpportunityHistoryRow,NflOpportunityInput,opportunityAvailability,opportunityMetricForMarket} from '../services/nflOpportunityEngine';
import {DEFAULT_OPPORTUNITY_EVALUATION_POLICY,evaluateOpportunityCandidates,OpportunityTargetRow} from '../services/nflOpportunityEvaluation';
import {CanonicalNflGame,CanonicalNflPlayer,NewNflForwardSnapshot,NflForwardArchive,NFL_PLAYER_CATEGORIES,NFL_TEAM_CATEGORIES,makeDiagnostic,validateNflForwardSnapshot} from '../services/nflForwardResearch';

const forecast='2026-11-01T12:00:00.000Z',teamId='espn-team:1',playerId='espn-player:10';
const game:CanonicalNflGame={canonicalGameId:'espn:100',providerGameIds:{ESPN:'100'},season:2026,seasonType:'REG',week:9,away:{canonicalTeamId:'espn-team:2',name:'Away',abbreviation:'AWY'},home:{canonicalTeamId:teamId,name:'Home',abbreviation:'HME'},scheduledKickoff:'2026-11-02T00:00:00.000Z',venue:{id:'1',name:'Field',indoor:false},neutralSite:false,international:false,status:'SCHEDULED'};
function player(position='RB',change:Partial<CanonicalNflPlayer>={}):CanonicalNflPlayer{return{canonicalPlayerId:playerId,providerPlayerIds:{ESPN:'10'},name:'Test Player',teamId,position,season:2026,effectiveAt:'2026-08-01T00:00:00.000Z',rookie:'NO',newTeam:'NO',teamChange:'UNCHANGED',positionChange:'UNCHANGED',...change};}
function history(metric:'PASS_ATTEMPTS'|'RUSH_ATTEMPTS'|'TARGETS'='RUSH_ATTEMPTS',count=8,season=2026):NflOpportunityHistoryRow[]{return Array.from({length:count},(_,i)=>({eventId:`event-${metric}-${i}`,date:new Date(Date.parse('2026-09-01T00:00:00Z')+i*7*86400_000).toISOString(),season,playerId,teamId,metric,opportunity:10+i,teamOpportunity:20+i,sourceRetrievedAt:forecast,evidenceClass:'RECONSTRUCTED_WITHOUT_FUTURE_INFO'}));}
function input(position='RB',rows=history(),change:Partial<NflOpportunityInput>={}):NflOpportunityInput{return{game,player:player(position),forecastAt:forecast,phase2Availability:'ACTIVE_VERIFIED',rosterStatus:'Active',injuryStatuses:[],depth:[{playerId,position,listedOrder:1,formation:'Offense'}],depthRetrievedAt:forecast,history:rows,snapShare:rows.slice(-5).map((row,i)=>({date:row.date,season:row.season,offenseSnaps:45+i,offensePct:.6+i*.03})),snapRetrievedAt:forecast,teammateDependency:'REDISTRIBUTION_UNKNOWN',flags:[],...change};}

test('player identity and position handling produce one canonical research-only row',()=>{const result=buildNflOpportunityProjection(input());assert.equal(result.canonicalPlayerId,playerId);assert.equal(result.position,'RB');assert.equal(result.researchOnly,true);assert.equal(result.productionEnabled,false);assert.equal(result.opportunityModelVersion,NFL_OPPORTUNITY_MODEL_VERSION);});
test('trade and new-team history cannot contaminate the current team',()=>{const changed=history().map(row=>({...row,teamId:'espn-team:old'}));const result=buildNflOpportunityProjection(input('RB',changed,{player:player('RB',{newTeam:'YES',teamChange:'CHANGED'})}));assert.equal(result.status,'OPPORTUNITY_MODEL_UNAVAILABLE');assert.match(result.failureStates.join(' '),/cross-team|traded/i);});
test('rookie with no trustworthy history remains data insufficient without fake precision',()=>{const result=buildNflOpportunityProjection(input('RB',[],{player:player('RB',{rookie:'YES'}),flags:['ROOKIE']}));assert.equal(result.status,'OPPORTUNITY_DATA_INSUFFICIENT');assert.equal(result.uncertainty,'MODEL_UNAVAILABLE');assert.equal(result.expectedCarries,null);});
test('availability preserves verified, pending, questionable, doubtful and unknown states',()=>{assert.equal(opportunityAvailability({phase2Availability:'ACTIVE_VERIFIED',rosterStatus:'Active',injuryStatuses:[]}),'ACTIVE_VERIFIED');assert.equal(opportunityAvailability({phase2Availability:'STATUS_PENDING',rosterStatus:'Active',injuryStatuses:[]}),'STATUS_PENDING');assert.equal(opportunityAvailability({phase2Availability:'STATUS_PENDING',rosterStatus:'Active',injuryStatuses:['Questionable']}),'QUESTIONABLE');assert.equal(opportunityAvailability({phase2Availability:'STATUS_UNKNOWN',rosterStatus:'Active',injuryStatuses:['Doubtful']}),'DOUBTFUL');assert.equal(opportunityAvailability({phase2Availability:'STATUS_UNKNOWN',rosterStatus:'Active',injuryStatuses:[]}),'STATUS_UNKNOWN');});
test('inactive player gets only an explicit zero-opportunity diagnostic',()=>{const result=buildNflOpportunityProjection(input('RB',history(),{phase2Availability:'INACTIVE_VERIFIED'}));assert.equal(result.status,'INACTIVE_VERIFIED');assert.equal(result.expectedCarries,0);assert.equal(result.expectedTargets,0);});
test('unknown availability never becomes healthy or receives a normal projection',()=>{const result=buildNflOpportunityProjection(input('RB',history(),{phase2Availability:'STATUS_UNKNOWN'}));assert.equal(result.status,'OPPORTUNITY_MODEL_UNAVAILABLE');assert.equal(result.availabilityState,'STATUS_UNKNOWN');assert.equal(result.expectedCarries,null);});
test('QB depth listing is starter-unverified and QB2 remains separate',()=>{assert.equal(classifyNflOpportunityRole(player('QB'),input('QB').depth,history('PASS_ATTEMPTS'),[]),'STARTER_UNVERIFIED');assert.equal(classifyNflOpportunityRole(player('QB'),[{playerId,position:'QB',listedOrder:2,formation:'Offense'}],history('PASS_ATTEMPTS'),[]),'QB2');});
test('RB committee classification uses observed carry-share volatility rather than an assumed RB1 share',()=>{const rows=history().map((row,i)=>({...row,opportunity:i%2?4:18,teamOpportunity:24}));assert.equal(classifyNflOpportunityRole(player('RB'),input().depth,rows,[]),'COMMITTEE');});
test('WR slot and depth roles are explicit and a role change stays visible',()=>{assert.equal(classifyNflOpportunityRole(player('WR'),[{playerId,position:'WR',listedOrder:2,formation:'Slot'}],history('TARGETS'),[]),'SLOT');const result=buildNflOpportunityProjection(input('WR',history('TARGETS'),{player:player('WR'),depth:[{playerId,position:'WR',listedOrder:2,formation:'Slot'}],flags:['ROLE_CHANGE']}));assert.equal(result.roleState,'SLOT');assert.ok(result.flags.includes('ROLE_CHANGE'));});
test('TE high snaps and low target share can be labeled blocking-heavy without equating snaps to routes',()=>{const rows=history('TARGETS').map(row=>({...row,opportunity:1,teamOpportunity:30})),snaps=rows.map(row=>({date:row.date,season:row.season,offenseSnaps:55,offensePct:.8}));const result=buildNflOpportunityProjection(input('TE',rows,{player:player('TE'),snapShare:snaps}));assert.equal(result.roleState,'BLOCKING_HEAVY');assert.equal(result.expectedRoutes,null);assert.equal(result.routeParticipation,null);});
test('snap-share is a separate raw diagnostic and never substitutes for route participation',()=>{const result=buildNflOpportunityProjection(input('WR',history('TARGETS'),{player:player('WR')}));assert.ok(result.snapShare!>0);assert.equal(result.expectedRoutes,null);assert.equal(result.routeParticipation,null);assert.ok(result.failureStates.includes('ROUTE_DATA_UNAVAILABLE'));});
test('target-share calculation reconciles player targets with team targets',()=>{const result=buildNflOpportunityProjection(input('WR',history('TARGETS'),{player:player('WR')}));assert.ok(result.expectedTargets!>0);assert.ok(result.targetShare!>0&&result.targetShare!<1);assert.equal(result.carryShare,null);});
test('carry-share calculation reconciles carries with team rushing attempts',()=>{const result=buildNflOpportunityProjection(input());assert.ok(result.expectedCarries!>0);assert.ok(result.carryShare!>0&&result.carryShare!<1);assert.equal(result.targetShare,null);});
test('QB pass attempts are projected separately while designed rushes and scrambles stay unavailable',()=>{const result=buildNflOpportunityProjection(input('QB',history('PASS_ATTEMPTS'),{player:player('QB')}));assert.ok(result.expectedPassAttempts!>0);assert.equal(result.expectedCompletionsOpportunities,result.expectedPassAttempts);assert.equal(result.expectedDesignedRushes,null);assert.equal(result.expectedScrambleOpportunities,null);});
test('core market mapping covers attempts, completions, carries and targets only',()=>{assert.equal(opportunityMetricForMarket('player_pass_completions'),'PASS_ATTEMPTS');assert.equal(opportunityMetricForMarket('player_rush_attempts'),'RUSH_ATTEMPTS');assert.equal(opportunityMetricForMarket('player_receptions'),'TARGETS');assert.equal(opportunityMetricForMarket('player_anytime_td'),null);});
test('teammate dependency is disclosed without arbitrary redistribution',()=>{const result=buildNflOpportunityProjection(input('WR',history('TARGETS'),{player:player('WR'),teammateDependency:'TEAMMATE_ROLE_CHANGE_DETECTED'}));assert.equal(result.teammateDependency,'TEAMMATE_ROLE_CHANGE_DETECTED');assert.ok(!result.method.includes('%'));});
test('early-season prior reliance is explicit and declines with current games',()=>{const prior=history('RUSH_ATTEMPTS',8,2025).map((row,i)=>({...row,date:new Date(Date.parse('2025-09-01')+i*7*86400_000).toISOString()})),one={...history('RUSH_ATTEMPTS',1)[0],eventId:'current-one'},a=buildNflOpportunityProjection(input('RB',[...prior,one])),six=buildNflOpportunityProjection(input('RB',[...prior,...history('RUSH_ATTEMPTS',6)]));assert.ok(a.priorSeasonWeight!>six.priorSeasonWeight!);assert.ok(a.flags.includes('LIMITED_SAMPLE'));});
test('future feature timestamps fail closed as leakage',()=>{const rows=history();rows[0]={...rows[0],sourceRetrievedAt:'2026-11-01T12:00:01.000Z'};assert.equal(buildNflOpportunityProjection(input('RB',rows)).status,'LEAKAGE_VIOLATION');});
test('market fields are programmatically rejected from independent opportunity input',()=>{const contaminated:any=input();contaminated.history[0].propLine=12.5;const result=buildNflOpportunityProjection(contaminated);assert.equal(result.status,'MARKET_CONTAMINATION');assert.equal(result.marketInputsUsed,false);});
test('missing role or evidence returns explicit MODEL_UNAVAILABLE/data-insufficient state',()=>{const role=buildNflOpportunityProjection(input('WR',history('TARGETS'),{player:player('WR'),depth:[]}));assert.equal(role.status,'OPPORTUNITY_MODEL_UNAVAILABLE');assert.ok(role.failureStates.includes('ROLE_UNKNOWN'));const missing=buildNflOpportunityProjection(input('RB',history('RUSH_ATTEMPTS',3)));assert.equal(missing.status,'OPPORTUNITY_DATA_INSUFFICIENT');});

function targets():OpportunityTargetRow[]{const positions:Array<'QB'|'RB'|'WR'>=['QB','RB','WR'];return positions.flatMap((position,p)=>Array.from({length:30},(_,i)=>({playerId:`p${p}`,playerName:`Player ${p}`,gameId:`g${p}-${i}`,date:new Date(Date.parse('2024-09-01')+i*18*86400_000).toISOString(),season:i<12?2024:2025,teamId:`t${p}`,position,metric:position==='QB'?'PASS_ATTEMPTS':position==='RB'?'RUSH_ATTEMPTS':'TARGETS',actual:position==='QB'?30+i%5:position==='RB'?12+i%4:7+i%3,teamOpportunity:position==='QB'?34+i%5:position==='RB'?25+i%4:32+i%3})) as OpportunityTargetRow[]);}
test('chronological evaluation never trains on target or later games',()=>{const report=evaluateOpportunityCandidates(targets());assert.ok(report.tests.length>0);assert.ok(report.tests.every(row=>Date.parse(row.trainingThrough)<Date.parse(row.date)));});
test('evaluation reports MAE RMSE bias coverage N and blocks missing TE data quality',()=>{const report=evaluateOpportunityCandidates(targets());const metric=report.candidates.LAST_3_AVERAGE.holdout;assert.ok(metric.n>0);assert.ok(metric.mae!==null&&metric.rmse!==null&&metric.bias!==null&&metric.coverage!==null);assert.deepEqual(report.missingPositions,['TE']);assert.equal(report.decision,'PLAYER OPPORTUNITY ENGINE BLOCKED BY DATA QUALITY');});
test('duplicate player-game target is rejected and outputs are deterministic',()=>{const rows=targets(),a=evaluateOpportunityCandidates(rows),b=evaluateOpportunityCandidates([...rows].reverse());assert.deepEqual(a,b);assert.throws(()=>evaluateOpportunityCandidates([...rows,rows[0]]),/Duplicate/);});
test('research gates are declared independently of betting profitability',()=>{assert.equal(DEFAULT_OPPORTUNITY_EVALUATION_POLICY.minimumEvaluationN,200);assert.equal(DEFAULT_OPPORTUNITY_EVALUATION_POLICY.requiredPositions.length,4);assert.ok(!JSON.stringify(DEFAULT_OPPORTUNITY_EVALUATION_POLICY).match(/roi|odds|profit|edge/i));});

function snapshotWithOpportunity():NewNflForwardSnapshot{const p=player('RB'),projection=buildNflOpportunityProjection(input());const diagnostics=[...NFL_TEAM_CATEGORIES.flatMap(category=>[game.home,game.away].map(team=>makeDiagnostic('TEAM',category,team.canonicalTeamId,forecast,0,1))),...NFL_PLAYER_CATEGORIES.map(category=>makeDiagnostic('PLAYER',category,p.canonicalPlayerId,forecast,0,1))],hash='a'.repeat(64);return{schemaVersion:'nfl-forward-research-v1',evidenceClass:'LIVE_FORWARD',capturedAt:forecast,forecastAt:forecast,trigger:'MANUAL',captureEventId:'manual-opportunity-test',scheduledFor:null,minutesToKickoff:720,hoursToKickoff:12,game,players:[p],footballEvidence:[],diagnostics,inactiveEvidence:{state:'SEASON_PENDING',source:{provider:'NFL.com',url:'https://nfl.test',providerRecordId:null,retrievedAt:forecast,effectiveAt:null,rawPayloadHash:hash},players:[{canonicalPlayerId:p.canonicalPlayerId,state:'STATUS_PENDING',reason:'pending'}]},gameMarkets:[],propMarkets:[],propUniverse:[],opportunityProjections:[projection],model:{gameProjection:null},apiUsage:[],failures:[]};}
test('shadow opportunity component is immutable, hash-verified, and deterministically exported',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'nfl-opportunity-'));try{const archive=new NflForwardArchive(root),row=snapshotWithOpportunity(),saved=archive.capture(row);assert.equal(saved.created,true);assert.equal(archive.verify().status,'PASS');assert.equal(archive.load().snapshots[0].opportunityProjections?.length,1);assert.equal(archive.export(forecast).datasetHash,archive.export('2026-11-01T13:00:00.000Z').datasetHash);assert.equal(archive.capture(row).created,false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('forward archive rejects future opportunity features and preserves manual-only trigger',()=>{const row=snapshotWithOpportunity();row.opportunityProjections![0].featureTimestamp=forecast;assert.throws(()=>validateNflForwardSnapshot(row),/future shadow opportunity/);assert.equal(row.trigger,'MANUAL');});
