import test from 'node:test';
import assert from 'node:assert/strict';
import * as path from 'path';
import {buildNflPredictiveBoardFromInputs,buildParlays,buildSgps,crossesNflKeyNumber,crossMarketConsistency,DecisionOpportunity,displayedOpportunity,gradeOpportunity,gradeTier,independentGameForecast,PredictiveGameInput,predictedGameScript,reconcilePredictedScore,timestampSafeMovement} from '../services/nflPredictiveBoard';

const projectRoot=path.resolve(__dirname,'../..'),now=Date.parse('2026-09-09T04:00:00Z'),at='2026-09-09T03:58:00Z';
const q=(gameId:string,market:string,side:string,line:number|null,price=-110,book='Book A',participant:string|null=null)=>({kind:participant?'PROP' as const:'GAME' as const,canonicalGameId:gameId,canonicalPlayerId:participant?'p1':null,market,participant,side,line,price,sportsbook:book,providerEventId:gameId,quoteTimestamp:at,captureTimestamp:at,rawPayloadHash:'a'.repeat(64),label:'CONTEMPORANEOUS_QUOTE' as const});
function input(id='g1'):PredictiveGameInput{return{id,homeName:'Seattle Seahawks',awayName:'New England Patriots',homeCode:'SEA',awayCode:'NE',kickoff:'2026-09-10T00:20:00Z',seasonType:'REG',week:1,neutral:false,capturedAt:at,dataQuality:'PASS',failures:[],snapshotCount:1,source:'FORWARD_ARCHIVE',quotes:[
  q(id,'spreads','Seattle Seahawks',-3,-110,'Book A'),q(id,'spreads','New England Patriots',3,-110,'Book A'),q(id,'spreads','Seattle Seahawks',-3.5,-105,'Book B'),q(id,'spreads','New England Patriots',3.5,-115,'Book B'),q(id,'spreads','Seattle Seahawks',-3,-108,'Book C'),q(id,'spreads','New England Patriots',3,-112,'Book C'),
  q(id,'h2h','Seattle Seahawks',null,-180,'Book A'),q(id,'h2h','New England Patriots',null,160,'Book A'),q(id,'h2h','Seattle Seahawks',null,-175,'Book B'),q(id,'h2h','New England Patriots',null,155,'Book B'),
  q(id,'totals','Over',44.5,-108,'Book A'),q(id,'totals','Under',44.5,-112,'Book A'),q(id,'totals','Over',45,-105,'Book B'),q(id,'totals','Under',45,-115,'Book B'),
  q(id,'team_totals','Over',24.5,-110,'Book A','Seattle Seahawks'),q(id,'team_totals','Under',24.5,-110,'Book A','Seattle Seahawks'),
  q(id,'player_pass_yds','Over',235.5,-110,'Book A','Drake Maye'),q(id,'player_pass_yds','Under',235.5,-110,'Book A','Drake Maye'),q(id,'player_pass_yds','Over',237.5,-105,'Book B','Drake Maye'),q(id,'player_pass_yds','Under',237.5,-115,'Book B','Drake Maye'),
],propProjections:[{playerId:'p1',player:'Drake Maye',market:'player_pass_yds',projection:244,version:'existing-prop-v1',availability:'ACTIVE_VERIFIED',role:'PARTIAL'}]};}
const gradeBase={market:'SPREAD' as const,edgeMagnitude:4,edgeScale:6,reliability:'FAILED' as const,dataQuality:'PASS' as const,availability:'VERIFIED_ACTIVE' as const,roleCertainty:'VERIFIED' as const,stabilitySamples:3,bookCount:8,dispersion:.5,price:-110,matchupSupport:'SUPPORTS' as const,currentSeasonSamples:4,movement:'SUPPORTS' as const,dependencySafe:true,extremeDisagreement:false};
function leg(id:string,gameId:string,grade:number,thesis:string[],type:'SPREAD'|'TOTAL'|'PLAYER_PROP'='SPREAD'):DecisionOpportunity{return{id,gameId,type,label:id,direction:'Over',line:1,projection:2,difference:1,grade,tier:gradeTier(grade),isProbability:false,price:-110,sportsbook:'Book',consensus:1,range:[1,1],dataQuality:'PASS',availability:'VERIFIED_ACTIVE',role:'VERIFIED',marketFresh:true,recommendable:true,why:[],risks:[],components:[],caps:[],modelFamily:type,thesis};}

test('score reconciliation makes displayed total and margin exactly match displayed team scores',()=>{const score=reconcilePredictedScore(7.24,47.36);assert.equal(score.homeScore+score.awayScore,score.total);assert.equal(score.homeScore-score.awayScore,score.homeMargin);assert.match(score.method,/Algebraic midpoint/);});
test('score reconciliation rejects impossible or invalid component forecasts',()=>{assert.throws(()=>reconcilePredictedScore(60,40),/Invalid/);assert.throws(()=>reconcilePredictedScore(3,NaN),/Invalid/);});
test('grade tiers and 60 display threshold match the declared board policy',()=>{assert.equal(gradeTier(90),'ELITE');assert.equal(gradeTier(85),'STRONG');assert.equal(gradeTier(78),'PLAYABLE');assert.equal(gradeTier(70),'LEAN');assert.equal(gradeTier(60),'WEAK / INFORMATIONAL');assert.equal(gradeTier(59),'BELOW DISPLAY THRESHOLD');assert.equal(displayedOpportunity(60),true);assert.equal(displayedOpportunity(59),false);});
test('predictability grade is explicitly not a probability',()=>{const result=gradeOpportunity(gradeBase);assert.equal(result.isProbability,false);assert.equal('probability' in result,false);});
test('known failed historical reliability lowers an otherwise identical grade',()=>{assert.ok(gradeOpportunity({...gradeBase,reliability:'PASSED'}).grade>gradeOpportunity(gradeBase).grade);});
test('failed data quality lowers and caps the grade below recommendation display',()=>{const result=gradeOpportunity({...gradeBase,dataQuality:'FAIL'});assert.ok(result.grade<60);assert.match(result.caps.join(' '),/blocks primary-board/);});
test('pending availability and unknown role reduce player evidence strength',()=>{const verified=gradeOpportunity({...gradeBase,market:'PLAYER_PROP',reliability:'BLOCKED'}),pending=gradeOpportunity({...gradeBase,market:'PLAYER_PROP',reliability:'BLOCKED',availability:'PENDING_OR_QUESTIONABLE',roleCertainty:'UNKNOWN'});assert.ok(pending.grade<verified.grade);});
test('verified inactive caps normal player opportunity below the board',()=>{const result=gradeOpportunity({...gradeBase,market:'PLAYER_PROP',reliability:'BLOCKED',availability:'INACTIVE'});assert.ok(result.grade<60);assert.match(result.caps.join(' '),/inactive/);});
test('large model disagreement alone cannot earn elite with a failed model',()=>{const result=gradeOpportunity({...gradeBase,edgeMagnitude:50,extremeDisagreement:true});assert.ok(result.grade<=69);assert.notEqual(result.tier,'ELITE');});
test('moneyline price is graded independently from winner strength',()=>{const fair=gradeOpportunity({...gradeBase,market:'MONEYLINE',price:-110}),expensive=gradeOpportunity({...gradeBase,market:'MONEYLINE',price:-600});assert.ok(fair.grade>expensive.grade);});
test('NFL key-number handler detects crossings of 3 and 7 but not ordinary movement',()=>{assert.deepEqual(crossesNflKeyNumber(2.5,3.5),[3]);assert.deepEqual(crossesNflKeyNumber(6.5,7.5),[7]);assert.deepEqual(crossesNflKeyNumber(4.5,5.5),[]);});
test('timestamp-safe movement distinguishes support, opposition, neutral and unavailable',()=>{const first=input(),later={...input(),capturedAt:'2026-09-09T03:59:00Z',quotes:input().quotes.map(row=>row.market==='totals'&&row.line!==null?{...row,line:row.line+1,quoteTimestamp:'2026-09-09T03:58:30Z',captureTimestamp:'2026-09-09T03:59:00Z'}:row)};assert.equal(timestampSafeMovement([first,later],'totals','Over'),'SUPPORTS');assert.equal(timestampSafeMovement([first,later],'totals','Under'),'OPPOSES');assert.equal(timestampSafeMovement([first,first],'totals','Over'),'NEUTRAL');assert.equal(timestampSafeMovement([first],'totals','Over'),'UNAVAILABLE');});
test('locked independent models produce a score without receiving market data',()=>{const forecast=independentGameForecast({...input(),quotes:[],propProjections:[]},projectRoot);assert.equal(forecast.status,'PROJECTED');assert.equal(forecast.homeScore!+forecast.awayScore!,forecast.total);assert.equal(forecast.homeScore!-forecast.awayScore!,forecast.homeMargin);assert.match(forecast.version,/FAILED RESEARCH GATES/);});
test('unresolved team identity remains a true forecast-unavailable state',()=>{const forecast=independentGameForecast({...input(),homeName:'Unknown Team',homeCode:null},projectRoot);assert.equal(forecast.status,'FORECAST_UNAVAILABLE');assert.match(forecast.reason!,/IDENTITY_UNRESOLVED/);});
test('nonregular derivative cannot borrow the full-game regular-season model',()=>{const forecast=independentGameForecast({...input(),seasonType:'PRE'},projectRoot);assert.equal(forecast.status,'FORECAST_UNAVAILABLE');});
test('game script follows the reconciled score rather than market price',()=>{const forecast=independentGameForecast(input(),projectRoot),script=predictedGameScript('Seattle Seahawks','New England Patriots',forecast);assert.match(script,/environment/);assert.match(script,/projected/);});
test('board grades spread moneyline total team total and supported prop independently',()=>{const report=buildNflPredictiveBoardFromInputs([input()],projectRoot,now),game=report.games[0];assert.equal(game.forecast.status,'PROJECTED');assert.ok(game.spread);assert.ok(game.moneyline);assert.ok(game.total);assert.equal(game.teamTotals.length,1);assert.equal(game.playerProps.length,1);assert.equal(new Set([game.spread!.grade,game.moneyline!.grade,game.total!.grade,game.teamTotals[0].grade,game.playerProps[0].grade]).size>1,true);});
test('forecast remains visible when every betting grade is below 60',()=>{const weak={...input(),dataQuality:'FAIL' as const},report=buildNflPredictiveBoardFromInputs([weak],projectRoot,now);assert.equal(report.games[0].forecast.status,'PROJECTED');assert.equal(report.topOverall.length,0);assert.ok(report.below60>0);});
test('projection replaces unhelpful monitor state without promoting a below-60 wager',()=>{const report=buildNflPredictiveBoardFromInputs([{...input(),dataQuality:'FAIL'}],projectRoot,now),encoded=JSON.stringify(report);assert.equal(report.games[0].forecast.status,'PROJECTED');assert.doesNotMatch(encoded,/MONITOR/);assert.equal(report.topOverall.length,0);assert.ok(report.games[0].failures.includes('DATA_INVALID'));});
test('primary ranked board never contains below-60 opportunities',()=>{const report=buildNflPredictiveBoardFromInputs([input()],projectRoot,now);assert.ok(report.topOverall.every(row=>row.grade>=60&&row.recommendable));});
test('team total direction comes from the displayed team score',()=>{const game=buildNflPredictiveBoardFromInputs([input()],projectRoot,now).games[0],row=game.teamTotals[0];assert.equal(row.projection,game.forecast.homeScore);assert.equal(row.direction,row.projection!>row.consensus!?'Over':'Under');});
test('prop prediction remains visible while Phase 3C limitation reduces its grade',()=>{const row=buildNflPredictiveBoardFromInputs([input()],projectRoot,now).games[0].playerProps[0];assert.equal(row.projection,244);assert.match(row.modelFamily,/PHASE3C_BLOCKED/);assert.match(row.risks.join(' '),/role/);});
test('first-half and first-quarter markets remain explicitly unavailable',()=>{const rows=buildNflPredictiveBoardFromInputs([input()],projectRoot,now).games[0].derivatives;assert.equal(rows.length,6);assert.ok(rows.every(row=>row.status==='FORECAST_UNAVAILABLE'&&/not divided/.test(row.reason)));});
test('cross-market check catches a displayed score contradiction',()=>{const forecast=independentGameForecast(input(),projectRoot),bad=leg('bad','g1',80,[],'TOTAL');bad.projection=forecast.total!+10;const result=crossMarketConsistency({forecast,opportunities:[bad]});assert.equal(result.safe,false);assert.match(result.contradictions[0],/differs/);});
test('SGP requires individually supported grade-70 legs',()=>{assert.equal(buildSgps('g1',[leg('a','g1',69,[]),leg('b','g1',90,[])],true).length,0);});
test('SGP rejects directly contradictory volume theses',()=>{const a=leg('Player over','g1',90,['PLAYER_VOLUME_UP'],'PLAYER_PROP'),b=leg('Player under','g1',90,['PLAYER_VOLUME_DOWN'],'PLAYER_PROP');assert.equal(buildSgps('g1',[a,b],true).length,0);});
test('SGP receives a separate dependency-aware grade rather than leg average',()=>{const a=leg('game over','g1',82,['HIGH_SCORING'],'TOTAL'),b=leg('receiver over','g1',88,['PLAYER_VOLUME_UP'],'PLAYER_PROP'),sgp=buildSgps('g1',[a,b],true)[0];assert.ok(sgp);assert.notEqual(sgp.grade,(a.grade+b.grade)/2);assert.match(sgp.why.join(' '),/correlation/);});
test('cross-game parlay excludes same-game legs and grades qualifying independent legs separately',()=>{assert.equal(buildParlays([leg('a','g1',90,[]),leg('b','g1',90,[])]).length,0);const parlay=buildParlays([leg('a','g1',90,[]),leg('b','g2',88,[])])[0];assert.ok(parlay);assert.notEqual(parlay.grade,89);assert.match(parlay.risks[0],/not a win probability/);});
test('started games preserve forecasts but cannot create board recommendations',()=>{const report=buildNflPredictiveBoardFromInputs([{...input(),kickoff:'2026-09-09T03:00:00Z'}],projectRoot,now),game=report.games[0];assert.equal(game.forecast.status,'PROJECTED');assert.ok(game.failures.includes('STARTED_GAME'));assert.equal(report.topOverall.length,0);});
test('missing market remains a true failure rather than a fabricated bet',()=>{const report=buildNflPredictiveBoardFromInputs([{...input(),quotes:[]}],projectRoot,now),game=report.games[0];assert.ok(game.failures.includes('MARKET_UNAVAILABLE'));assert.equal(game.spread,null);assert.equal(game.total,null);});
test('board preserves manual-only collection, cutoff, and zero new paid decision calls',()=>{const report=buildNflPredictiveBoardFromInputs([input()],projectRoot,now);assert.deepEqual(report.collection,{mode:'MANUAL_ONLY',scheduled:'DISABLED_BY_CONFIGURATION',protectedCutoff:'2026-09-08T02:19:07.588Z',newPaidProviderCalls:0,newPaidCredits:0});});
test('grade distribution is explicit and no grade exceeds 100',()=>{const report=buildNflPredictiveBoardFromInputs([input()],projectRoot,now),rows=report.games.flatMap(game=>[game.spread,game.moneyline,game.total,...game.teamTotals,...game.playerProps].filter(Boolean) as DecisionOpportunity[]);assert.ok(rows.every(row=>row.grade>=0&&row.grade<=100));assert.equal(Object.keys(report.gradeDistribution).length,5);});
test('100 requires complete alignment and is not produced by ordinary failed research',()=>{assert.ok(gradeOpportunity(gradeBase).grade<100);const perfect=gradeOpportunity({...gradeBase,edgeMagnitude:6,reliability:'PASSED',stabilitySamples:3,price:120,currentSeasonSamples:8});assert.equal(perfect.grade,100);assert.equal(perfect.isProbability,false);});
