import test from 'node:test';
import assert from 'node:assert/strict';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';
import {NFL_GAME_LINE_RESEARCH_VERSION} from '../services/nflGameLineResearch';
import {NflSpreadFeatureRow,NflSpreadGame,assertIndependentFeatures,atsDiagnostic,buildNflSpreadFeatureRows,disagreementAnalysis,evaluateRidge,fitIncrementalMarket,fitSpreadRidge,metrics,parseNflSpreadSourceCsv,predictSpread,selectEnsembleWeight,stableHash} from '../services/nflSpreadPhase3A';

const fullHeader='game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium';
const values=Object.fromEntries(fullHeader.split(',').map(key=>[key,'']));Object.assign(values,{game_id:'2025_01_DAL_PHI',season:'2025',game_type:'REG',week:'1',gameday:'2025-09-04',weekday:'Thursday',gametime:'20:20',away_team:'DAL',away_score:'20',home_team:'PHI',home_score:'24',location:'Home',result:'4',total:'44',overtime:'0',away_rest:'7',home_rest:'7',away_moneyline:'330',home_moneyline:'-425',spread_line:'8.5',away_spread_odds:'-105',home_spread_odds:'-115',total_line:'47.5',under_odds:'-110',over_odds:'-110',div_game:'1',roof:'outdoors',surface:'grass',temp:'75',wind:'11',away_qb_id:'qb-a',home_qb_id:'qb-h',away_qb_name:'Dak',home_qb_name:'Jalen',away_coach:'Away Coach',home_coach:'Home Coach',referee:'Ref',stadium_id:'PHI00',stadium:'Stadium'});const csvRow=fullHeader.split(',').map(key=>values[key]).join(',');

test('Phase 3A source parser preserves target sign, exact prices, rest, QB fields and game flags',()=>{const audit=parseNflSpreadSourceCsv(`${fullHeader}\n${csvRow}\n`),game=audit.games[0];assert.equal(game.homeScore-game.awayScore,4);assert.equal(game.spreadLine,8.5);assert.equal(game.homeSpreadOdds,-115);assert.equal(game.awaySpreadOdds,-105);assert.equal(game.homeRest,7);assert.equal(game.divisional,true);assert.equal(game.homeQbId,'qb-h');});
test('historical dataset audit keeps postseason separate and counts unfinished games explicitly',()=>{const post=csvRow.replace('2025_01_DAL_PHI,2025,REG,1','2025_WC_DAL_PHI,2025,WC,19'),future=csvRow.replace('2025_01_DAL_PHI,2025,REG,1,2025-09-04','2026_01_DAL_PHI,2026,REG,1,2026-09-04').replace(',DAL,20,PHI,24,Home,4,',',DAL,,PHI,,Home,,');const audit=parseNflSpreadSourceCsv(`${fullHeader}\n${post}\n${future}\n`);assert.equal(audit.games[0].gameType,'WC');assert.equal(audit.excluded.NOT_FINAL,1);});
test('unsafe market feature names are rejected programmatically',()=>{assert.throws(()=>assertIndependentFeatures(['TEAM_STRENGTH_DIFF','spread_line']),/Market contamination/);assert.doesNotThrow(()=>assertIndependentFeatures(['TEAM_STRENGTH_DIFF','HOME_FIELD']));});

function schedule(season:number,marginShift=0){const games:NflSpreadGame[]=[];for(let week=1;week<=17;week++){const day=new Date(Date.UTC(season,8,1+(week-1)*7)).toISOString().slice(0,10);for(let game=0;game<8;game++){const home=`T${game}`,away=`T${8+(game+week)%8}`,homeScore=24+((game+week)%7)+marginShift,awayScore=20+((game*2+week)%6);games.push({id:`${season}_${week}_${away}_${home}`,season,gameType:'REG',week,date:`${day}T12:00:00.000Z`,weekday:'Sunday',awayId:away,homeId:home,awayScore,homeScore,neutral:false,overtime:false,awayRest:7,homeRest:7,spreadLine:3,awaySpreadOdds:-105,homeSpreadOdds:-115,divisional:game%2===0,roof:'outdoors',temperature:70,wind:5,awayQbId:`${away}-qb`,homeQbId:`${home}-qb`,awayCoach:'A',homeCoach:'H',stadiumId:`${home}-stadium`});}}return games;}
const featurePolicy={teamRatingRidge:20,teamRatingHalfLifeDays:365,priorSeasonShrinkGames:8,currentSeasonBlendGames:4,rollingGames:4,minimumPriorGamesPerTeam:8};
test('feature construction uses earlier dates only and does not consume another same-day final',()=>{const prior=schedule(2019),current=schedule(2020),base=buildNflSpreadFeatureRows([...prior,...current],2020,2020,featurePolicy),changed=current.map((game,index)=>index===0?{...game,homeScore:99}:game),again=buildNflSpreadFeatureRows([...prior,...changed],2020,2020,featurePolicy);assert.equal(base.rows.length,current.length);assert.equal(base.rows[0].latestInputDate<base.rows[0].date,true);assert.deepEqual(base.rows[1].features,again.rows[1].features);});
test('missing prior team history is explicit rather than fabricated',()=>{const result=buildNflSpreadFeatureRows(schedule(2020),2020,2020,featurePolicy);assert.equal(result.rows.length,0);assert.equal(result.excluded.INSUFFICIENT_PRIOR_TEAM_HISTORY,136);});

const features=(strength:number,home=1)=>({TEAM_STRENGTH_DIFF:strength,HOME_FIELD:home,PRIOR_STRENGTH_DIFF:strength,CURRENT_SCORING_MARGIN_DIFF:strength,BLENDED_OFFENSE_DIFF:strength/2,BLENDED_DEFENSE_DIFF:strength/3,ROLLING_MARGIN_DIFF:strength,REST_DIFF:0,HOME_SHORT_WEEK:0,AWAY_SHORT_WEEK:0,DIVISIONAL_GAME:0,NEUTRAL_SITE:home?0:1,AWAY_ROAD_STREAK:0});
function rows(n=80):NflSpreadFeatureRow[]{return Array.from({length:n},(_,i)=>{const strength=i%11-5,market=1.8*strength+2;return{id:`g${i}`,season:i<60?2024:2025,week:i%18+1,date:`2025-01-${String(i%28+1).padStart(2,'0')}T12:00:00.000Z`,gameType:'REG',homeId:'H',awayId:'A',actualMargin:2.2*strength+2.5,marketMargin:market,homeSpreadOdds:-110,awaySpreadOdds:-110,neutral:false,overtime:false,divisional:false,homeRest:7,awayRest:7,features:features(strength),latestInputDate:'2024-12-01T12:00:00.000Z',currentHomeGames:4,currentAwayGames:4,priorHomeGames:17,priorAwayGames:17};});}
test('regularized Model B is deterministic and reports MAE RMSE bias N',()=>{const data=rows(),a=fitSpreadRidge(data,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),b=fitSpreadRidge(data,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10);assert.deepEqual(a,b);const result=evaluateRidge(a,data);assert.equal(result.n,80);assert.ok(result.mae!==null&&result.rmse!==null&&result.bias!==null);});
test('changing locked holdout outcomes cannot change a training-only model',()=>{const data=rows(),train=data.slice(0,60),holdout=data.slice(60),model=fitSpreadRidge(train,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),changed=holdout.map(row=>({...row,actualMargin:row.actualMargin+100}));assert.equal(model.trainingHash,fitSpreadRidge(train,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10).trainingHash);assert.notDeepEqual(evaluateRidge(model,holdout),evaluateRidge(model,changed));});
test('incremental market regression reports separate market and Model B coefficients',()=>{const data=rows(),model=fitSpreadRidge(data,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),incremental=fitIncrementalMarket(data,model);assert.equal(incremental.trainingN,80);assert.equal(Number.isFinite(incremental.marketCoefficient),true);assert.equal(Number.isFinite(incremental.modelCoefficient),true);});
test('ensemble weight is trained from validation only',()=>{const validation=rows(60),model=fitSpreadRidge(validation,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),before=selectEnsembleWeight(validation,model),unseen=rows(20).map(row=>({...row,actualMargin:row.actualMargin+999}));assert.deepEqual(before,selectEnsembleWeight(validation,model));assert.ok(unseen.length>0);});
test('ablation refits on the same rows and visibly changes the feature set',()=>{const data=rows(),full=fitSpreadRidge(data,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),ablated=fitSpreadRidge(data,['HOME_FIELD'],10);assert.notDeepEqual(full.features,ablated.features);assert.notEqual(stableHash(full),stableHash(ablated));});
test('disagreement research uses margin errors and fixed descriptive buckets',()=>{const data=rows(),model=fitSpreadRidge(data,['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),result=disagreementAnalysis(data,model);assert.equal(result.buckets.length,6);assert.equal(result.n,80);assert.equal(typeof result.regressionSlope,'number');});
test('ATS diagnostic uses exact side price and keeps pushes separate',()=>{const data=rows(3),model=fitSpreadRidge(rows(),['TEAM_STRENGTH_DIFF','HOME_FIELD'],10),result=atsDiagnostic(data,model);assert.equal(result.priced,3);assert.equal(result.wins+result.losses+result.pushes,3);assert.match(result.label,/NOT AN ACTIONABLE BACKTEST/);});
test('metric function rejects different samples and preserves final-home-margin sign',()=>{assert.throws(()=>metrics([1],[1,2]),/differ/);assert.deepEqual(metrics([4],[-1]),{n:1,mae:5,rmse:5,bias:5});});
test('Model A version and protected forward cutoff remain frozen',()=>{assert.equal(NFL_GAME_LINE_RESEARCH_VERSION,'nfl-game-line-ridge-research-v2-audit-metrics');assert.equal(NFL_FORWARD_POLICY.protectedCutoff,'2026-09-08T02:19:07.588Z');});
test('Phase 3A cannot re-enable scheduling or touch prop-market policy',()=>{assert.deepEqual(NFL_FORWARD_POLICY.corePropMarkets,['player_pass_yds','player_pass_attempts','player_pass_completions','player_rush_yds','player_rush_attempts','player_reception_yds','player_receptions']);assert.equal(process.env.NFL_FORWARD_COLLECTION_MODE==='scheduled',false);});
test('2026 shadow archive remains manual-only and no Phase 3A candidate is a production formula',()=>{const model=fitSpreadRidge(rows(),['TEAM_STRENGTH_DIFF','HOME_FIELD'],10);assert.equal(model.version,'nfl-spread-phase3a-v1');assert.equal('recommendation' in model,false);assert.equal('probability' in model,false);assert.equal('stake' in model,false);});
