import test from 'node:test';
import assert from 'node:assert/strict';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';
import {NFL_GAME_LINE_RESEARCH_VERSION} from '../services/nflGameLineResearch';
import {NflTotalFeatureRow,NflTotalGame,assertIndependentTotalFeatures,assertWeatherPointInTime,buildNflTotalFeatureRows,evaluateTotal,fitIncrementalTotalMarket,fitTotalRidge,parseNflTotalSourceCsv,predictTotal,selectTotalEnsembleWeight,totalDisagreement,totalOuDiagnostic} from '../services/nflTotalPhase3B';

const header='game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium',values=Object.fromEntries(header.split(',').map(key=>[key,'']));Object.assign(values,{game_id:'2025_01_DAL_PHI',season:'2025',game_type:'REG',week:'1',gameday:'2025-09-04',weekday:'Thursday',gametime:'20:20',away_team:'DAL',away_score:'20',home_team:'PHI',home_score:'24',location:'Home',result:'4',total:'44',overtime:'0',away_rest:'7',home_rest:'7',spread_line:'8.5',away_spread_odds:'-105',home_spread_odds:'-115',total_line:'47.5',under_odds:'-108',over_odds:'-112',div_game:'1',roof:'outdoors',temp:'75',wind:'11'});const gameRow=header.split(',').map(key=>values[key]).join(',');
test('totals source preserves final total, external line, exact prices and primetime',()=>{const game=parseNflTotalSourceCsv(`${header}\n${gameRow}\n`).games[0];assert.equal(game.homeScore+game.awayScore,44);assert.equal(game.totalLine,47.5);assert.equal(game.underOdds,-108);assert.equal(game.overOdds,-112);assert.equal(game.primetime,true);});
test('missing market total remains null rather than invented',()=>{const row=gameRow.replace(',47.5,-108,-112,',',,,-112,'),game=parseNflTotalSourceCsv(`${header}\n${row}\n`).games[0];assert.equal(game.totalLine,null);assert.equal(game.underOdds,null);});
test('market and game-script feature names are rejected',()=>{assert.throws(()=>assertIndependentTotalFeatures(['BLENDED_OFFENSE_SUM','market_total']),/Market contamination/);assert.throws(()=>assertIndependentTotalFeatures(['sportsbook_spread']),/Market contamination/);assert.doesNotThrow(()=>assertIndependentTotalFeatures(['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM']));});
test('weather after forecast is unsafe and cannot enter the model',()=>{assert.throws(()=>assertWeatherPointInTime('2025-09-01T18:01:00Z','2025-09-01T18:00:00Z'),/Unsafe/);assert.equal(assertWeatherPointInTime('2025-09-01T17:59:00Z','2025-09-01T18:00:00Z'),true);});

function schedule(season:number,shift=0){const games:NflTotalGame[]=[];for(let week=1;week<=17;week++){const day=new Date(Date.UTC(season,8,1+(week-1)*7)).toISOString().slice(0,10);for(let index=0;index<8;index++){const home=`T${index}`,away=`T${8+(index+week)%8}`,homeScore=24+(index+week)%7+shift,awayScore=20+(index*2+week)%6;games.push({id:`${season}_${week}_${away}_${home}`,season,gameType:'REG',week,date:`${day}T12:00:00.000Z`,weekday:'Sunday',awayId:away,homeId:home,awayScore,homeScore,neutral:false,overtime:week%9===0,awayRest:7,homeRest:7,spreadLine:3,awaySpreadOdds:-110,homeSpreadOdds:-110,divisional:index%2===0,roof:'outdoors',temperature:70,wind:5,awayQbId:null,homeQbId:null,awayCoach:null,homeCoach:null,stadiumId:`${home}-stadium`,totalLine:45,underOdds:-105,overOdds:-115,primetime:false});}}return games;}
const policy={opponentRidge:20,opponentHalfLifeDays:365,currentSeasonBlendGames:4,rollingGames:4,minimumPriorGamesPerTeam:8};
test('totals features exclude all same-day outcomes and remain chronological',()=>{const prior=schedule(2019),current=schedule(2020),first=buildNflTotalFeatureRows([...prior,...current],2020,2020,policy),changed=current.map((game,index)=>index===0?{...game,homeScore:100}:game),second=buildNflTotalFeatureRows([...prior,...changed],2020,2020,policy);assert.equal(first.rows.length,136);assert.ok(first.rows[0].latestInputDate<first.rows[0].date);assert.deepEqual(first.rows[1].features,second.rows[1].features);});
test('missing prior totals history becomes unavailable',()=>{const result=buildNflTotalFeatureRows(schedule(2020),2020,2020,policy);assert.equal(result.rows.length,0);assert.equal(result.excluded.INSUFFICIENT_PRIOR_TEAM_HISTORY,136);});
const features=(level:number)=>({BLENDED_OFFENSE_SUM:44+level,BLENDED_DEFENSE_SUM:43+level/2,OPPONENT_ADJUSTED_TOTAL:45+level,RECENT_COMBINED_TOTAL:44+level/3,REST_SUM:0,HOME_SHORT_WEEK:0,AWAY_SHORT_WEEK:0,DIVISIONAL_GAME:0,NEUTRAL_SITE:0,PREVIOUS_OVERTIME_COUNT:0});
function rows(n=80):NflTotalFeatureRow[]{return Array.from({length:n},(_,i)=>{const level=i%11-5;return{id:`t${i}`,season:i<60?2024:2025,week:i%18+1,date:`2025-01-${String(i%28+1).padStart(2,'0')}T12:00:00.000Z`,homeId:'H',awayId:'A',actualTotal:46+1.7*level,marketTotal:45+1.5*level,underOdds:-105,overOdds:-115,neutral:false,overtime:false,divisional:false,roof:'outdoors',primetime:false,features:features(level),priorCombinedTotal:44+level,simpleOffenseDefenseTotal:45+level,latestInputDate:'2024-12-01T12:00:00.000Z',currentHomeGames:4,currentAwayGames:4};});}
test('Total Model B is deterministic and reports margin-error metrics',()=>{const data=rows(),a=fitTotalRidge(data,['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10),b=fitTotalRidge(data,['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10);assert.deepEqual(a,b);const result=evaluateTotal(a,data);assert.equal(result.n,80);assert.ok(result.mae!==null&&result.rmse!==null&&result.bias!==null);});
test('locked holdout changes cannot alter training model or ensemble selection',()=>{const train=rows(60),holdout=rows(20),model=fitTotalRidge(train,['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10),weight=selectTotalEnsembleWeight(train,model),changed=holdout.map(row=>({...row,actualTotal:row.actualTotal+100}));assert.equal(model.trainingHash,fitTotalRidge(train,['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10).trainingHash);assert.deepEqual(weight,selectTotalEnsembleWeight(train,model));assert.notDeepEqual(evaluateTotal(model,holdout),evaluateTotal(model,changed));});
test('incremental market regression keeps market and model coefficients separate',()=>{const data=rows(),model=fitTotalRidge(data,['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10),result=fitIncrementalTotalMarket(data,model);assert.equal(result.trainingN,80);assert.equal(Number.isFinite(result.marketCoefficient),true);assert.equal(Number.isFinite(result.modelCoefficient),true);});
test('pace ablation cannot be claimed when no pace feature exists',()=>{const model=fitTotalRidge(rows(),['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10);assert.equal(model.features.includes('RECENT_COMBINED_TOTAL'),false);assert.equal(model.features.some(feature=>String(feature).includes('PACE')),false);});
test('total disagreement has fixed diagnostic buckets and error slope',()=>{const data=rows(),model=fitTotalRidge(data,['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10),result=totalDisagreement(data,model);assert.equal(result.buckets.length,6);assert.equal(result.n,80);assert.equal(typeof result.regressionSlope,'number');});
test('over/under diagnostic uses exact stored price and separates pushes',()=>{const data=rows(4),model=fitTotalRidge(rows(),['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10),result=totalOuDiagnostic(data,model);assert.equal(result.priced,4);assert.equal(result.wins+result.losses+result.pushes,4);assert.match(result.label,/NOT AN ACTIONABLE BACKTEST/);});
test('Total Model A and the protected forward cutoff remain frozen',()=>{assert.equal(NFL_GAME_LINE_RESEARCH_VERSION,'nfl-game-line-ridge-research-v2-audit-metrics');assert.equal(NFL_FORWARD_POLICY.protectedCutoff,'2026-09-08T02:19:07.588Z');});
test('Phase 3B remains manual-only and cannot emit recommendation/probability/stake fields',()=>{const model=fitTotalRidge(rows(),['BLENDED_OFFENSE_SUM','BLENDED_DEFENSE_SUM'],10);assert.equal(process.env.NFL_FORWARD_COLLECTION_MODE==='scheduled',false);assert.equal('recommendation' in model,false);assert.equal('probability' in model,false);assert.equal('stake' in model,false);assert.equal(predictTotal(model,rows(1)[0])>0,true);});
