import * as fs from 'fs';
import * as path from 'path';
import {createHash,randomUUID} from 'crypto';
import {stableStringify} from './collegeEdgeResearch';

export const COLLEGE_FORWARD_RESEARCH_VERSION='college-forward-research-v1';
export const COLLEGE_FORWARD_FINAL_VERSION='college-forward-final-v1';
export const COLLEGE_FORWARD_CORRECTION_VERSION='college-forward-correction-v1';
export const COLLEGE_FORWARD_LOCKED_AT='2026-09-07T12:45:00.000Z';
export type SnapshotWindow='T24H'|'T6H'|'T1H'|'LATEST_PREKICK'|'ACTUAL_PREKICK';
export type ForwardCaptureTrigger='SCHEDULED_0700_CT'|'SCHEDULED_1400_CT'|'MANUAL';
export type ConceptualCaptureState='CAPTURED'|'NOT_SCHEDULED_FOR_CAPTURE'|'MISSED_CAPTURE_WINDOW';
export type ForwardStage='PASS'|'PARTIAL'|'FAIL'|'UNKNOWN';
export type ForwardFailureClass='SOURCE_DOWN'|'NO_RECORD'|'ENTITY_MISMATCH'|'RATE_LIMIT'|'AUTH_FAILURE'|'INVALID_RESPONSE'|'STALE_DATA'|'UNKNOWN';
export type FootballCategory='TEAM_EFFICIENCY'|'OPPONENT_HISTORY'|'QB'|'ROSTER'|'TRANSFERS'|'TALENT'|'COACHING'|'INJURIES'|'FBS_FCS'|'WEATHER';
export const REQUIRED_FORWARD_CATEGORIES:FootballCategory[]=['TEAM_EFFICIENCY','OPPONENT_HISTORY','QB','ROSTER','TRANSFERS','TALENT','COACHING','INJURIES','FBS_FCS','WEATHER'];
export type QbEvidenceStatus='CONFIRMED'|'EXPECTED'|'COMPETITION'|'QUESTIONABLE'|'OUT'|'UNKNOWN';

export interface ForwardTeamIdentity {canonicalId:string;name:string;subdivision:'FBS'|'FCS'|'UNKNOWN';conference:string|null;}
export interface ForwardEventIdentity {canonicalEventId:string;providerEventIds:Record<string,string>;season:2026;week:number|null;kickoff:string;home:ForwardTeamIdentity;away:ForwardTeamIdentity;neutralSite:boolean;conferenceGame:boolean|null;venue:{id:string|null;name:string|null;indoor:boolean|null};}
export interface ForwardSource {provider:string;providerRecordId:string|null;url:string;retrievedAt:string;publishedAt:string|null;rawPayloadHash:string;}
export interface ForwardFeatureEvidence {category:FootballCategory;teamId:string|null;field:string;value:unknown;definition:string;units:string|null;sampleSize:number|null;season:number;gamesIncluded:string[];effectiveAt:string;forecastAt:string;validity:'VALID'|'INVALID'|'UNKNOWN';freshness:'FRESH'|'STALE'|'UNKNOWN';source:ForwardSource;}
export interface ForwardDiagnostic {category:FootballCategory;teamId:string|null;forecastAt:string;stages:{SOURCE_RETRIEVAL:ForwardStage;NORMALIZATION:ForwardStage;ENTITY_MATCH:ForwardStage;ATTACHMENT:ForwardStage;FIELD_VALIDITY:ForwardStage;FORECAST_TIME_FRESHNESS:ForwardStage};availableFields:number;expectedFields:number;notes:string[];}
export interface ForwardFailure {id?:string;provider:string;requestCategory:string;canonicalEventId:string|null;teamId:string|null;failedAt:string;errorClass:ForwardFailureClass;attempts:number;retryState:'NOT_RETRIED'|'RETRY_EXHAUSTED'|'RETRY_SUCCEEDED'|'NOT_APPLICABLE';finalAvailability:'AVAILABLE'|'UNAVAILABLE'|'PARTIAL';message:string;}
export interface ModelAForwardForecast {status:'PROJECTED'|'MODEL_UNAVAILABLE';forecastAt:string;modelVersion:string;dataVersion:string;homeScore:number|null;awayScore:number|null;homeMargin:number|null;historyHash:string|null;}
export interface ShadowForwardForecast {shadowOnly:true;status:'PROJECTED'|'MODEL_UNAVAILABLE';forecastAt:string;modelVersion:string;candidateId:string;homeScore:number|null;awayScore:number|null;homeMargin:number|null;inputEvidenceHash:string;}
export interface ForwardMarketEvidence {namespace:'EXTERNAL_MARKET_BENCHMARK';sportsbook:string;market:'spreads';homeSpread:number;homePrice:number;awaySpread:number;awayPrice:number;quoteTimestamp:string;retrievedAt:string;providerEventId:string;rawPayloadHash:string;acquisition:'CACHE'|'NETWORK';requestAttempts:0|1;}
export interface ForwardOperationalMetadata {trigger:ForwardCaptureTrigger;captureEventId:string;captureTimestamp:string;scheduledFor:string|null;originalScheduledKickoff:string;latestVerifiedKickoff:string;minutesToKickoff:number;hoursToKickoff:number;scheduleStatus:'SCHEDULED'|'POSTPONED'|'CANCELED';scheduleSource:{provider:string;retrievedAt:string;rawPayloadHash:string};conceptualWindows:Record<'T24H'|'T6H'|'T1H'|'LATEST_PREKICK',ConceptualCaptureState>;}
export interface NewForwardResearchSnapshot {schemaVersion:typeof COLLEGE_FORWARD_RESEARCH_VERSION;partition:'FORWARD_VALIDATION_2026';window:SnapshotWindow;capturedAt:string;forecastAt:string;identity:ForwardEventIdentity;applicationRelease:string;featureSchemaVersion:string;modelA:ModelAForwardForecast;shadowModels:ShadowForwardForecast[];footballEvidence:ForwardFeatureEvidence[];diagnostics:ForwardDiagnostic[];failures:ForwardFailure[];market:ForwardMarketEvidence|null;operational?:ForwardOperationalMetadata;}
export interface ForwardResearchSnapshot extends NewForwardResearchSnapshot {snapshotId:string;}
export interface NewForwardFinal {schemaVersion:typeof COLLEGE_FORWARD_FINAL_VERSION;canonicalEventId:string;recordedAt:string;sourceTimestamp:string;provider:string;providerEventId:string;status:'STATUS_FINAL'|'STATUS_FINAL_OVERTIME';homeScore:number;awayScore:number;actualHomeMargin:number;rawPayloadHash:string;}
export interface ForwardFinal extends NewForwardFinal {finalId:string;}
export interface NewForwardCorrection {schemaVersion:typeof COLLEGE_FORWARD_CORRECTION_VERSION;targetType:'SNAPSHOT'|'FINAL';targetId:string;recordedAt:string;reason:string;evidence:unknown;source:ForwardSource;}
export interface ForwardCorrection extends NewForwardCorrection {correctionId:string;}
interface ArchiveIndex {schema:1;version:typeof COLLEGE_FORWARD_RESEARCH_VERSION;snapshots:Array<{id:string;eventId:string;forecastAt:string;window:SnapshotWindow}>;finals:Array<{id:string;eventId:string;recordedAt:string}>;corrections:Array<{id:string;targetId:string;recordedAt:string}>;failures:Array<{id:string;failedAt:string}>;}

const safe=(value:string,label:string)=>{if(!/^[A-Za-z0-9._-]{1,160}$/.test(value))throw Error(`Invalid ${label}.`);return value;};
const stamp=(value:string,label:string)=>{const n=Date.parse(value);if(!Number.isFinite(n))throw Error(`Invalid ${label} timestamp.`);return n;};
const hash=(value:unknown)=>createHash('sha256').update(stableStringify(value)).digest('hex');
const forbiddenMarket=/(sportsbook|moneyline|spread|total|odds|consensus|closing.?line|market.?implied)/i;
function validHash(value:string){return /^[a-f0-9]{64}$/.test(value);}
function finiteOrNull(value:number|null){return value===null||Number.isFinite(value);}
function indexFile(root:string){return path.join(root,'college_forward_research','v1','index.json');}
function authority(root:string){return path.dirname(indexFile(root));}
function emptyIndex():ArchiveIndex{return{schema:1,version:COLLEGE_FORWARD_RESEARCH_VERSION,snapshots:[],finals:[],corrections:[],failures:[]};}
function loadIndex(root:string):ArchiveIndex{const file=indexFile(root);if(!fs.existsSync(file))return emptyIndex();const data=JSON.parse(fs.readFileSync(file,'utf8'));if(data?.schema!==1||data?.version!==COLLEGE_FORWARD_RESEARCH_VERSION||!Array.isArray(data.snapshots)||!Array.isArray(data.finals)||!Array.isArray(data.corrections)||!Array.isArray(data.failures))throw Error('Invalid forward research index.');return data;}
function saveIndex(root:string,index:ArchiveIndex){const dir=authority(root);fs.mkdirSync(dir,{recursive:true});const tmp=path.join(dir,randomUUID()+'.tmp');fs.writeFileSync(tmp,JSON.stringify(index,null,2),{flag:'wx'});fs.renameSync(tmp,indexFile(root));}
function contentFile(root:string,type:'snapshots'|'finals'|'corrections'|'failures'|'raw',id:string){return path.join(authority(root),type,safe(id,`${type} ID`)+'.json');}
function writeImmutable(file:string,value:unknown){const body=JSON.stringify(value,null,2);fs.mkdirSync(path.dirname(file),{recursive:true});try{fs.writeFileSync(file,body,{flag:'wx'});return true;}catch(error:any){if(error.code==='EEXIST'&&fs.readFileSync(file,'utf8')===body)return false;throw Error(`Immutable archive collision at ${file}.`);}}
function readChecked<T>(file:string,id:string,idField:string):T{const value=JSON.parse(fs.readFileSync(file,'utf8'));const body={...value};delete body[idField];if(value[idField]!==id||hash(body)!==id)throw Error(`Forward archive integrity failure at ${file}.`);return value as T;}

export interface SnapshotWindowPolicy {name:SnapshotWindow;minimumMinutesBeforeKickoff:number;maximumMinutesBeforeKickoff:number;marketNetworkAllowed:boolean;}
export function selectForwardSnapshotWindow(now:number,kickoff:number,policies:SnapshotWindowPolicy[]):SnapshotWindow|null{if(!Number.isFinite(now)||!Number.isFinite(kickoff)||now>=kickoff)return null;const minutes=(kickoff-now)/60_000;
  return policies.filter(p=>minutes>=p.minimumMinutesBeforeKickoff&&minutes<=p.maximumMinutesBeforeKickoff).sort((a,b)=>a.maximumMinutesBeforeKickoff-b.maximumMinutesBeforeKickoff)[0]?.name??null;}
export function marketNetworkAllowed(window:SnapshotWindow,policies:SnapshotWindowPolicy[]){return policies.find(p=>p.name===window)?.marketNetworkAllowed===true;}

export function validateForwardSnapshot(input:NewForwardResearchSnapshot){if(input.schemaVersion!==COLLEGE_FORWARD_RESEARCH_VERSION||input.partition!=='FORWARD_VALIDATION_2026')throw Error('Invalid forward snapshot schema/partition.');
  const forecast=stamp(input.forecastAt,'forecast'),captured=stamp(input.capturedAt,'capture'),kickoff=stamp(input.identity.kickoff,'kickoff');if(forecast<Date.parse(COLLEGE_FORWARD_LOCKED_AT))throw Error('Snapshot predates the protected 2026 forward lock.');if(forecast>captured||captured>=kickoff)throw Error('Pregame cutoff violation.');
  if(input.window==='ACTUAL_PREKICK'&&!input.operational)throw Error('Operational capture metadata is required for an actual pre-kickoff snapshot.');
  if(input.operational){const operation=input.operational,latest=stamp(operation.latestVerifiedKickoff,'latest kickoff'),actualMinutes=(latest-captured)/60_000;
    safe(operation.captureEventId,'capture event ID');stamp(operation.originalScheduledKickoff,'original kickoff');if(operation.captureTimestamp!==input.capturedAt||Math.abs(operation.minutesToKickoff-actualMinutes)>1e-6||Math.abs(operation.hoursToKickoff-actualMinutes/60)>1e-6||operation.minutesToKickoff<=0||stamp(operation.scheduleSource.retrievedAt,'schedule retrieval')>forecast||!validHash(operation.scheduleSource.rawPayloadHash))throw Error('Invalid operational capture semantics.');
    if(operation.latestVerifiedKickoff!==input.identity.kickoff||operation.scheduleStatus!=='SCHEDULED'||!['SCHEDULED_0700_CT','SCHEDULED_1400_CT','MANUAL'].includes(operation.trigger))throw Error('Invalid operational trigger or schedule state.');
    for(const value of Object.values(operation.conceptualWindows))if(!['CAPTURED','NOT_SCHEDULED_FOR_CAPTURE','MISSED_CAPTURE_WINDOW'].includes(value))throw Error('Invalid conceptual capture state.');}
  safe(input.identity.canonicalEventId,'canonical event ID');safe(input.identity.home.canonicalId,'home canonical ID');safe(input.identity.away.canonicalId,'away canonical ID');if(input.identity.home.canonicalId===input.identity.away.canonicalId)throw Error('Duplicate team identity.');
  if(input.identity.season!==2026||typeof input.identity.neutralSite!=='boolean'||!input.applicationRelease||!input.featureSchemaVersion)throw Error('Invalid event/release identity.');
  for(const [provider,id]of Object.entries(input.identity.providerEventIds)){if(!provider||!id)safe('',`provider event ID`);safe(id,'provider event ID');}
  const diagnostics=new Map(input.diagnostics.map(d=>[`${d.category}:${d.teamId??'GAME'}`,d]));for(const category of REQUIRED_FORWARD_CATEGORIES)for(const teamId of [input.identity.home.canonicalId,input.identity.away.canonicalId])if(!diagnostics.has(`${category}:${teamId}`))throw Error(`Missing six-stage diagnostic for ${category}/${teamId}.`);
  for(const diagnostic of input.diagnostics){if(diagnostic.forecastAt!==input.forecastAt||diagnostic.availableFields<0||diagnostic.expectedFields<0||diagnostic.availableFields>diagnostic.expectedFields)throw Error('Invalid/timestamp-mismatched diagnostic.');for(const state of Object.values(diagnostic.stages))if(!['PASS','PARTIAL','FAIL','UNKNOWN'].includes(state))throw Error('Invalid diagnostic stage.');}
  const evidenceKeys=new Set<string>();for(const row of input.footballEvidence){const key=`${row.category}:${row.teamId}:${row.field}:${row.source.provider}:${row.source.providerRecordId}`;if(evidenceKeys.has(key))throw Error(`Duplicate feature evidence: ${key}`);evidenceKeys.add(key);
    if(row.value===undefined||row.forecastAt!==input.forecastAt||stamp(row.effectiveAt,'feature effective')>forecast||stamp(row.source.retrievedAt,'feature retrieval')>forecast||row.source.publishedAt!==null&&stamp(row.source.publishedAt,'feature publication')>forecast)throw Error('Post-forecast feature leakage.');
    if(row.teamId!==null&&![input.identity.home.canonicalId,input.identity.away.canonicalId].includes(row.teamId)||row.season!==2026||!validHash(row.source.rawPayloadHash))throw Error('Invalid feature identity/provenance.');
    if(row.category==='QB'&&row.field==='qb.status'&&!['CONFIRMED','EXPECTED','COMPETITION','QUESTIONABLE','OUT','UNKNOWN'].includes(String(row.value)))throw Error('Invalid QB status.');
    if(forbiddenMarket.test(row.field)||forbiddenMarket.test(row.definition)||forbiddenMarket.test(row.source.provider))throw Error('Market evidence contaminated football features.');}
  for(const failure of input.failures){if(stamp(failure.failedAt,'failure')>forecast||failure.canonicalEventId!==null&&failure.canonicalEventId!==input.identity.canonicalEventId||failure.attempts<0)throw Error('Invalid source failure.');}
  const modelTimes=[input.modelA,...input.shadowModels];for(const model of modelTimes){if(stamp(model.forecastAt,'model forecast')>forecast)throw Error('Post-forecast model output.');}
  if(!input.shadowModels.every(model=>model.shadowOnly===true))throw Error('Research candidate is not isolated in shadow mode.');
  if(!finiteOrNull(input.modelA.homeScore)||!finiteOrNull(input.modelA.awayScore)||!finiteOrNull(input.modelA.homeMargin)||input.modelA.status==='PROJECTED'&&(input.modelA.homeScore===null||input.modelA.awayScore===null||input.modelA.homeMargin===null||Math.abs(input.modelA.homeScore-input.modelA.awayScore-input.modelA.homeMargin)>1e-6))throw Error('Invalid Model A forecast.');
  for(const model of input.shadowModels)if(model.status==='PROJECTED'&&(model.homeScore===null||model.awayScore===null||model.homeMargin===null||Math.abs(model.homeScore-model.awayScore-model.homeMargin)>1e-6))throw Error('Invalid shadow forecast.');
  if(input.market){const market=input.market;if(market.namespace!=='EXTERNAL_MARKET_BENCHMARK'||market.market!=='spreads'||stamp(market.quoteTimestamp,'market quote')>forecast||stamp(market.retrievedAt,'market retrieval')>forecast||!validHash(market.rawPayloadHash)||![market.homeSpread,market.homePrice,market.awaySpread,market.awayPrice].every(Number.isFinite)||Math.abs(market.homeSpread+market.awaySpread)>1e-9||market.acquisition==='NETWORK'&&!['T1H','LATEST_PREKICK','ACTUAL_PREKICK'].includes(input.window)||market.acquisition==='NETWORK'&&market.requestAttempts!==1||market.acquisition==='CACHE'&&market.requestAttempts!==0)throw Error('Invalid external market evidence.');}
  return{contentHash:hash(input),evidenceCount:input.footballEvidence.length,diagnosticCount:input.diagnostics.length};}

export class CollegeForwardResearchArchive {
  constructor(private readonly root:string){}
  archiveRaw(provider:string,url:string,retrievedAt:string,payload:unknown){if(!provider||!/^https:\/\//.test(url))throw Error('Invalid raw provider source.');stamp(retrievedAt,'raw retrieval');const body={schema:1,provider,url,retrievedAt,payload},id=hash(body),created=writeImmutable(contentFile(this.root,'raw',id),{id,...body});return{id,created};}
  capture(input:NewForwardResearchSnapshot){const audit=validateForwardSnapshot(input),snapshotId=audit.contentHash,snapshot:ForwardResearchSnapshot={snapshotId,...structuredClone(input)},index=loadIndex(this.root);
    const duplicate=index.snapshots.find(row=>row.eventId===input.identity.canonicalEventId&&row.window===input.window&&row.forecastAt===input.forecastAt&&row.id!==snapshotId);if(duplicate)throw Error('Conflicting duplicate capture for canonical event/window/forecast.');
    const created=writeImmutable(contentFile(this.root,'snapshots',snapshotId),snapshot);if(!index.snapshots.some(row=>row.id===snapshotId)){index.snapshots.push({id:snapshotId,eventId:input.identity.canonicalEventId,forecastAt:input.forecastAt,window:input.window});index.snapshots.sort((a,b)=>a.forecastAt.localeCompare(b.forecastAt)||a.id.localeCompare(b.id));saveIndex(this.root,index);}for(const failure of input.failures)this.logFailure(failure);return{snapshotId,created,failuresLogged:input.failures.length,...audit};}
  archiveFinal(input:NewForwardFinal){if(input.schemaVersion!==COLLEGE_FORWARD_FINAL_VERSION||!['STATUS_FINAL','STATUS_FINAL_OVERTIME'].includes(input.status)||![input.homeScore,input.awayScore,input.actualHomeMargin].every(Number.isFinite)||input.homeScore-input.awayScore!==input.actualHomeMargin||!validHash(input.rawPayloadHash))throw Error('Invalid verified final.');
    const index=loadIndex(this.root),snapshots=index.snapshots.filter(row=>row.eventId===input.canonicalEventId);if(!snapshots.length)throw Error('Final has no archived pregame snapshot.');const kickoff=Math.min(...snapshots.map(row=>Date.parse(readChecked<ForwardResearchSnapshot>(contentFile(this.root,'snapshots',row.id),row.id,'snapshotId').identity.kickoff)));
    if(stamp(input.sourceTimestamp,'final source')>stamp(input.recordedAt,'final record')||stamp(input.sourceTimestamp,'final source')<kickoff)throw Error('Final source timestamp is invalid.');const finalId=hash(input),prior=index.finals.find(row=>row.eventId===input.canonicalEventId);if(prior&&prior.id!==finalId)throw Error('Verified final already exists; append a correction instead of replacing it.');
    const value:ForwardFinal={finalId,...structuredClone(input)},created=writeImmutable(contentFile(this.root,'finals',finalId),value);if(!prior){index.finals.push({id:finalId,eventId:input.canonicalEventId,recordedAt:input.recordedAt});index.finals.sort((a,b)=>a.recordedAt.localeCompare(b.recordedAt)||a.id.localeCompare(b.id));saveIndex(this.root,index);}return{finalId,created};}
  appendCorrection(input:NewForwardCorrection){if(input.schemaVersion!==COLLEGE_FORWARD_CORRECTION_VERSION||!input.reason||stamp(input.source.retrievedAt,'correction source')>stamp(input.recordedAt,'correction')||!validHash(input.source.rawPayloadHash))throw Error('Invalid correction evidence.');const index=loadIndex(this.root),exists=input.targetType==='SNAPSHOT'?index.snapshots.some(row=>row.id===input.targetId):index.finals.some(row=>row.id===input.targetId);if(!exists)throw Error('Correction target does not exist.');
    const correctionId=hash(input),value:ForwardCorrection={correctionId,...structuredClone(input)},created=writeImmutable(contentFile(this.root,'corrections',correctionId),value);if(!index.corrections.some(row=>row.id===correctionId)){index.corrections.push({id:correctionId,targetId:input.targetId,recordedAt:input.recordedAt});index.corrections.sort((a,b)=>a.recordedAt.localeCompare(b.recordedAt)||a.id.localeCompare(b.id));saveIndex(this.root,index);}return{correctionId,created};}
  logFailure(input:ForwardFailure){const body={...input};delete body.id;if(!input.provider||!input.requestCategory||!Number.isFinite(stamp(input.failedAt,'failure'))||input.attempts<0)throw Error('Invalid source failure log.');const id=hash(body),value={id,...structuredClone(body)},created=writeImmutable(contentFile(this.root,'failures',id),value),index=loadIndex(this.root);if(!index.failures.some(row=>row.id===id)){index.failures.push({id,failedAt:input.failedAt});index.failures.sort((a,b)=>a.failedAt.localeCompare(b.failedAt)||a.id.localeCompare(b.id));saveIndex(this.root,index);}return{id,created};}
  load(){const index=loadIndex(this.root),snapshots=index.snapshots.map(row=>readChecked<ForwardResearchSnapshot>(contentFile(this.root,'snapshots',row.id),row.id,'snapshotId')),finals=index.finals.map(row=>readChecked<ForwardFinal>(contentFile(this.root,'finals',row.id),row.id,'finalId')),corrections=index.corrections.map(row=>readChecked<ForwardCorrection>(contentFile(this.root,'corrections',row.id),row.id,'correctionId')),
    failures=index.failures.map(row=>readChecked<ForwardFailure&{id:string}>(contentFile(this.root,'failures',row.id),row.id,'id'));return{snapshots,finals,corrections,failures};}
}

export interface ExpectedForwardGame {canonicalEventId:string;kickoff:string;season:2026;week:number|null;homeSubdivision:'FBS'|'FCS'|'UNKNOWN';awaySubdivision:'FBS'|'FCS'|'UNKNOWN';neutralSite:boolean;conferenceGame:boolean|null;}
function pct(n:number,d:number){return d?Number((100*n/d).toFixed(1)):null;}
export function buildForwardCoverageDashboard(data:ReturnType<CollegeForwardResearchArchive['load']>,expected:ExpectedForwardGame[],milestones=[50,100,250,500,1000],largeMismatch=21){const latest=new Map<string,ForwardResearchSnapshot>();for(const row of data.snapshots){const old=latest.get(row.identity.canonicalEventId);if(!old||Date.parse(row.forecastAt)>Date.parse(old.forecastAt))latest.set(row.identity.canonicalEventId,row);}const rows=[...latest.values()],capturedIds=new Set(rows.map(r=>r.identity.canonicalEventId)),coverage=(category:FootballCategory,applicable=rows)=>{const covered=applicable.filter(row=>[row.identity.home.canonicalId,row.identity.away.canonicalId].every(teamId=>row.footballEvidence.some(e=>e.category===category&&e.teamId===teamId&&e.validity==='VALID'&&e.freshness==='FRESH'))).length;return{covered,total:applicable.length,percent:pct(covered,applicable.length)};},fcsRows=rows.filter(r=>r.identity.home.subdivision!==r.identity.away.subdivision&&[r.identity.home.subdivision,r.identity.away.subdivision].includes('FCS')),
    verifiedQb=rows.filter(row=>[row.identity.home.canonicalId,row.identity.away.canonicalId].every(teamId=>row.footballEvidence.some(e=>e.category==='QB'&&e.teamId===teamId&&e.field==='qb.status'&&e.value==='CONFIRMED'))),required=['QB','ROSTER','TEAM_EFFICIENCY','INJURIES','TALENT','FBS_FCS','WEATHER'] as FootballCategory[],high=rows.filter(row=>required.every(category=>[row.identity.home.canonicalId,row.identity.away.canonicalId].every(teamId=>row.footballEvidence.some(e=>e.category===category&&e.teamId===teamId&&e.validity==='VALID'&&e.freshness==='FRESH'))));
  const regime={weeks0To2:rows.filter(r=>(r.identity.week??99)<=2).length,weeks3To5:rows.filter(r=>(r.identity.week??99)>=3&&(r.identity.week??99)<=5).length,week6Plus:rows.filter(r=>(r.identity.week??-1)>=6).length,
    fbsFbs:rows.filter(r=>r.identity.home.subdivision==='FBS'&&r.identity.away.subdivision==='FBS').length,fbsFcs:fcsRows.length,conference:rows.filter(r=>r.identity.conferenceGame===true).length,nonconference:rows.filter(r=>r.identity.conferenceGame===false).length,neutral:rows.filter(r=>r.identity.neutralSite).length,
    largeIndependentMismatch:rows.filter(r=>r.modelA.homeMargin!==null&&Math.abs(r.modelA.homeMargin)>=largeMismatch).length,verifiedQb:verifiedQb.length,unverifiedQb:rows.length-verifiedQb.length,highContext:high.length,lowContext:rows.length-high.length};
  const slates=[...new Set(expected.map(row=>row.kickoff.slice(0,10)))].sort(),bySlate=Object.fromEntries(slates.map(date=>{const slate=expected.filter(row=>row.kickoff.startsWith(date)),captured=slate.filter(row=>capturedIds.has(row.canonicalEventId)).length;return[date,{expected:slate.length,captured,missed:slate.length-captured,percent:pct(captured,slate.length)}];}));
  return{schemaVersion:'college-forward-coverage-v1',season:2026,bySeason:{'2026':{expected:expected.length,captured:rows.length,missed:expected.filter(e=>!capturedIds.has(e.canonicalEventId)).length,percent:pct(rows.length,expected.length)}},bySlate,expectedGames:expected.length,gamesCaptured:rows.length,gamesMissed:expected.filter(e=>!capturedIds.has(e.canonicalEventId)).length,capturePercent:pct(rows.length,expected.length),pregameSnapshots:data.snapshots.length,verifiedFinals:new Set(data.finals.map(r=>r.canonicalEventId)).size,
    coverage:{qb:coverage('QB'),roster:coverage('ROSTER'),efficiency:coverage('TEAM_EFFICIENCY'),injury:coverage('INJURIES'),talent:coverage('TALENT'),fcs:coverage('FBS_FCS',fcsRows),weather:coverage('WEATHER'),market:{covered:rows.filter(r=>r.market!==null).length,total:rows.length,percent:pct(rows.filter(r=>r.market!==null).length,rows.length)}},regime,
    milestones:milestones.map(target=>({target,reached:rows.length>=target,remaining:Math.max(0,target-rows.length)})),failures:data.failures.length,corrections:data.corrections.length};}

export function exportForwardResearchDataset(root:string,outputRoot:string,createdAt:string){stamp(createdAt,'export creation');const archive=new CollegeForwardResearchArchive(root),data=archive.load(),records=[...data.snapshots.map(value=>({kind:'PREGAME_SNAPSHOT',value})),...data.finals.map(value=>({kind:'FINAL',value})),...data.corrections.map(value=>({kind:'CORRECTION',value})),...data.failures.map(value=>({kind:'SOURCE_FAILURE',value}))].sort((a,b)=>stableStringify(a).localeCompare(stableStringify(b))),datasetHash=hash(records),runId=`${COLLEGE_FORWARD_RESEARCH_VERSION}-${datasetHash.slice(0,12)}-${createdAt.replace(/[:.]/g,'-')}`,directory=path.join(outputRoot,runId),ndjson=records.map(stableStringify).join('\n')+(records.length?'\n':''),manifest={schemaVersion:'college-forward-export-manifest-v1',archiveSchemaVersion:COLLEGE_FORWARD_RESEARCH_VERSION,createdAt,datasetHash,counts:{snapshots:data.snapshots.length,finals:data.finals.length,corrections:data.corrections.length,failures:data.failures.length},authoritativeArchive:path.resolve(root)};
  const files={'dataset.ndjson':ndjson,'manifest.json':JSON.stringify(manifest,null,2)};fs.mkdirSync(outputRoot,{recursive:true});if(fs.existsSync(directory)){for(const [name,body]of Object.entries(files))if(!fs.existsSync(path.join(directory,name))||fs.readFileSync(path.join(directory,name),'utf8')!==body)throw Error('Immutable forward export collision.');return{directory,datasetHash,created:false,manifest};}fs.mkdirSync(directory);for(const [name,body]of Object.entries(files))fs.writeFileSync(path.join(directory,name),body,{flag:'wx'});return{directory,datasetHash,created:true,manifest};}
