import {createHash} from 'crypto';
import {canonicalCollegeName} from './collegeEntities';
import {CollegeContextRecord,resolveCollegeTeamContext} from './collegeContextEvidence';
import {FootballCategory,ForwardDiagnostic,ForwardFailure,ForwardFeatureEvidence,ForwardStage,ForwardTeamIdentity,REQUIRED_FORWARD_CATEGORIES} from './collegeForwardResearch';
import {stableStringify} from './collegeEdgeResearch';

const CFBD='https://api.collegefootballdata.com';
const sha=(value:unknown)=>createHash('sha256').update(stableStringify(value)).digest('hex');
const iso=(n:number)=>new Date(n).toISOString();
export interface SourceFetchResponse {ok:boolean;status:number;json:()=>Promise<unknown>;}
export interface SourceResult {ok:boolean;payload:unknown|null;retrievedAt:string;cached:boolean;attempts:number;failureClass?:ForwardFailure['errorClass'];message?:string;}
function failureClass(status:number,message:string):ForwardFailure['errorClass']{if(status===401||status===403)return'AUTH_FAILURE';if(status===429)return'RATE_LIMIT';if(status>=500||/network|timeout|fetch failed/i.test(message))return'SOURCE_DOWN';if(status===404)return'NO_RECORD';return status>=400?'INVALID_RESPONSE':'UNKNOWN';}
export class BoundedForwardSourceCache {
  private cache=new Map<string,{at:number;payload:unknown}>();private pending=new Map<string,Promise<SourceResult>>();private used=0;
  constructor(private fetcher:(url:string,init?:any)=>Promise<SourceFetchResponse>,private now=()=>Date.now(),private wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms)),private maximumRequests=4){}
  get requestsUsed(){return this.used;}
  prime(key:string,payload:unknown,retrievedAt:string){const at=Date.parse(retrievedAt);if(!Number.isFinite(at)||at>this.now())throw Error('Invalid forward source cache seed.');const prior=this.cache.get(key);if(!prior||prior.at<at)this.cache.set(key,{at,payload:structuredClone(payload)});}
  resetRunBudget(){this.used=0;}
  async request(key:string,url:string,ttlMs:number,init?:any):Promise<SourceResult>{const hit=this.cache.get(key);if(hit&&this.now()-hit.at<=ttlMs)return{ok:true,payload:structuredClone(hit.payload),retrievedAt:iso(hit.at),cached:true,attempts:0};if(this.pending.has(key))return this.pending.get(key)!;
    if(this.used>=this.maximumRequests)return{ok:false,payload:null,retrievedAt:iso(this.now()),cached:false,attempts:0,failureClass:'RATE_LIMIT',message:'Per-run research request budget exhausted.'};
    const promise=this.fetch(key,url,init).finally(()=>this.pending.delete(key));this.pending.set(key,promise);return promise;}
  private async fetch(key:string,url:string,init?:any):Promise<SourceResult>{let lastStatus=0,last='UNKNOWN',attempts=0;for(let attempt=1;attempt<=2;attempt++){if(this.used>=this.maximumRequests)return{ok:false,payload:null,retrievedAt:iso(this.now()),cached:false,attempts:attempt-1,failureClass:'RATE_LIMIT',message:'Per-run research request budget exhausted.'};this.used++;attempts=attempt;
      try{const response=await this.fetcher(url,init);lastStatus=response.status;if(response.ok){const payload=await response.json();this.cache.set(key,{at:this.now(),payload:structuredClone(payload)});return{ok:true,payload,retrievedAt:iso(this.now()),cached:false,attempts:attempt};}last=`HTTP ${response.status}`;if([401,403,404,429].includes(response.status))break;}
      catch(error){last=String(error instanceof Error?error.message:error);}if(attempt===1)await this.wait(250);}
    return{ok:false,payload:null,retrievedAt:iso(this.now()),cached:false,attempts,failureClass:failureClass(lastStatus,last),message:last};}
}

export interface ForwardTeamSeed extends ForwardTeamIdentity {aliases:string[];eventId:string;}
export interface ForwardSourceCollection {evidence:ForwardFeatureEvidence[];diagnostics:ForwardDiagnostic[];failures:ForwardFailure[];raw:Array<{provider:string;url:string;retrievedAt:string;payload:unknown}>;}
function matchTeam(value:unknown,team:ForwardTeamSeed){const name=canonicalCollegeName(String(value??''));return name.length>0&&[team.name,...team.aliases].some(alias=>canonicalCollegeName(alias)===name);}
function stages(source:ForwardStage,normalized:ForwardStage,match:ForwardStage,attached:ForwardStage,valid:ForwardStage,fresh:ForwardStage){return{SOURCE_RETRIEVAL:source,NORMALIZATION:normalized,ENTITY_MATCH:match,ATTACHMENT:attached,FIELD_VALIDITY:valid,FORECAST_TIME_FRESHNESS:fresh};}
function diagnostic(category:FootballCategory,teamId:string,forecastAt:string,stage:ReturnType<typeof stages>,availableFields:number,expectedFields:number,notes:string[]=[]):ForwardDiagnostic{return{category,teamId,forecastAt,stages:stage,availableFields,expectedFields,notes};}
function fail(result:SourceResult,provider:string,requestCategory:string,eventId:string|null,teamId:string|null):ForwardFailure{return{provider,requestCategory,canonicalEventId:eventId,teamId,failedAt:result.retrievedAt,errorClass:result.failureClass??'UNKNOWN',attempts:result.attempts,retryState:result.attempts>1?'RETRY_EXHAUSTED':'NOT_RETRIED',finalAvailability:'UNAVAILABLE',message:String(result.message??result.failureClass??'UNKNOWN').slice(0,500)};}
function feature(args:Omit<ForwardFeatureEvidence,'forecastAt'|'validity'|'freshness'>,forecastAt:string):ForwardFeatureEvidence{return{...args,forecastAt,validity:'VALID',freshness:'FRESH'};}

/** Forward-only CFBD collector. It archives retrieved snapshots; it never treats
 * retrospective historical ratings as what was known on an earlier date. */
export class CfbdForwardResearchSource {
  constructor(private cache:BoundedForwardSourceCache,private apiKey:string|undefined,private now=()=>Date.now()){}
  async collect(teams:ForwardTeamSeed[],season:2026,forecastAt:string):Promise<ForwardSourceCollection>{const evidence:ForwardFeatureEvidence[]=[],diagnostics:ForwardDiagnostic[]=[],failures:ForwardFailure[]=[],raw:ForwardSourceCollection['raw']=[],forecast=Date.parse(forecastAt);if(!Number.isFinite(forecast))throw Error('Invalid forward forecast timestamp.');
    if(!this.apiKey){for(const team of teams)for(const category of ['TEAM_EFFICIENCY','OPPONENT_HISTORY'] as FootballCategory[]){diagnostics.push(diagnostic(category,team.canonicalId,forecastAt,stages('FAIL','UNKNOWN','UNKNOWN','FAIL','UNKNOWN','UNKNOWN'),0,1,['CFBD_API_KEY is not configured.']));failures.push({provider:'CollegeFootballData',requestCategory:category,canonicalEventId:team.eventId,teamId:team.canonicalId,failedAt:iso(this.now()),errorClass:'AUTH_FAILURE',attempts:0,retryState:'NOT_APPLICABLE',finalAvailability:'UNAVAILABLE',message:'CFBD_API_KEY is not configured.'});}return{evidence,diagnostics,failures,raw};}
    this.cache.resetRunBudget();const urls={core:`${CFBD}/ratings/core?year=${season}`,fbsGames:`${CFBD}/games?year=${season}&seasonType=regular&classification=fbs`,fcsGames:`${CFBD}/games?year=${season}&seasonType=regular&classification=fcs`,fcsSrs:`${CFBD}/ratings/srs/expanded?year=${season-1}&classification=fcs`},headers={Authorization:`Bearer ${this.apiKey}`};
    const entries=await Promise.all([['core',urls.core,6*3600_000],['fbsGames',urls.fbsGames,6*3600_000],['fcsGames',urls.fcsGames,6*3600_000],['fcsSrs',urls.fcsSrs,24*3600_000]].map(async([key,url,ttl])=>[key,await this.cache.request(String(key),String(url),Number(ttl),{headers})] as const)),by=Object.fromEntries(entries) as Record<string,SourceResult>;
    for(const [key,result]of Object.entries(by))if(result.ok)raw.push({provider:'CollegeFootballData',url:urls[key as keyof typeof urls],retrievedAt:result.retrievedAt,payload:result.payload});
    const core=Array.isArray(by.core.payload)?by.core.payload:[],games=[...(Array.isArray(by.fbsGames.payload)?by.fbsGames.payload:[]),...(Array.isArray(by.fcsGames.payload)?by.fcsGames.payload:[])],srs=Array.isArray(by.fcsSrs.payload)?by.fcsSrs.payload:[];
    for(const team of teams){const coreRows=core.filter((row:any)=>matchTeam(row.team,team)),gameRows=games.filter((row:any)=>(matchTeam(row.homeTeam,team)||matchTeam(row.awayTeam,team))&&row.completed===true&&Date.parse(row.startDate)<forecast).sort((a:any,b:any)=>Date.parse(a.startDate)-Date.parse(b.startDate));
      if(by.core.ok&&coreRows.length===1){const row:any=coreRows[0],payloadHash=sha(by.core.payload);evidence.push(feature({category:'TEAM_EFFICIENCY',teamId:team.canonicalId,field:'efficiency.core',value:{overall:row.overall,offense:row.offense,defense:row.defense,throughSeasonType:row.throughSeasonType,throughWeek:row.throughWeek,modelVersion:row.modelVersion},definition:'CFBD CORE opponent-relative efficiency; higher offense/overall and lower defense are better.',units:'points above average per 100 qualifying plays',sampleSize:Number(row.offensePlays)+Number(row.defensePlays),season,gamesIncluded:[],effectiveAt:by.core.retrievedAt,source:{provider:'CollegeFootballData',providerRecordId:String(row.team),url:urls.core,retrievedAt:by.core.retrievedAt,publishedAt:null,rawPayloadHash:payloadHash}},forecastAt));diagnostics.push(diagnostic('TEAM_EFFICIENCY',team.canonicalId,forecastAt,stages('PASS','PASS','PASS','PASS','PASS','PASS'),1,1));}
      else{const result=by.core.ok?{...by.core,ok:false,failureClass:(coreRows.length?'ENTITY_MISMATCH':'NO_RECORD') as ForwardFailure['errorClass'],message:coreRows.length?'Multiple provider team rows matched.':'No CORE row attached to team.'}:by.core;diagnostics.push(diagnostic('TEAM_EFFICIENCY',team.canonicalId,forecastAt,stages(by.core.ok?'PASS':'FAIL',by.core.ok?'PASS':'UNKNOWN',coreRows.length>1?'FAIL':coreRows.length?'PASS':'UNKNOWN','FAIL','UNKNOWN','UNKNOWN'),0,1,[String(result.message)]));failures.push(fail(result,'CollegeFootballData','TEAM_EFFICIENCY',team.eventId,team.canonicalId));}
      const gamesSource=team.subdivision==='FCS'?by.fcsGames:by.fbsGames,url=team.subdivision==='FCS'?urls.fcsGames:urls.fbsGames;if(gamesSource.ok){const value=gameRows.map((row:any)=>({providerGameId:String(row.id),playedAt:row.startDate,opponent:matchTeam(row.homeTeam,team)?row.awayTeam:row.homeTeam,opponentProviderId:String(matchTeam(row.homeTeam,team)?row.awayId:row.homeId),teamPoints:matchTeam(row.homeTeam,team)?row.homePoints:row.awayPoints,opponentPoints:matchTeam(row.homeTeam,team)?row.awayPoints:row.homePoints,homeAway:matchTeam(row.homeTeam,team)?'HOME':'AWAY',neutralSite:row.neutralSite,conferenceGame:row.conferenceGame,classification:matchTeam(row.homeTeam,team)?row.homeClassification:row.awayClassification}));evidence.push(feature({category:'OPPONENT_HISTORY',teamId:team.canonicalId,field:'opponent.completedGames',value,definition:'Provider games explicitly completed before forecast; raw game identities and scores retained.',units:null,sampleSize:value.length,season,gamesIncluded:value.map(v=>v.providerGameId),effectiveAt:gamesSource.retrievedAt,source:{provider:'CollegeFootballData',providerRecordId:team.name,url,retrievedAt:gamesSource.retrievedAt,publishedAt:null,rawPayloadHash:sha(gamesSource.payload)}},forecastAt));diagnostics.push(diagnostic('OPPONENT_HISTORY',team.canonicalId,forecastAt,stages('PASS','PASS',gameRows.length?'PASS':'UNKNOWN','PASS','PASS','PASS'),1,1,gameRows.length?[]:['Valid empty completed-game history preserved.']));}
      else{diagnostics.push(diagnostic('OPPONENT_HISTORY',team.canonicalId,forecastAt,stages('FAIL','UNKNOWN','UNKNOWN','FAIL','UNKNOWN','UNKNOWN'),0,1,[String(gamesSource.message)]));failures.push(fail(gamesSource,'CollegeFootballData','OPPONENT_HISTORY',team.eventId,team.canonicalId));}
      const classificationPayload={subdivision:team.subdivision,conference:team.conference},srsRows=team.subdivision==='FCS'?srs.filter((row:any)=>matchTeam(row.team,team)):[];if(srsRows.length===1)Object.assign(classificationPayload,{priorSeasonSrs:(srsRows[0] as any).rating,priorSeasonSrsRank:(srsRows[0] as any).ranking});
      evidence.push(feature({category:'FBS_FCS',teamId:team.canonicalId,field:'classification.forwardEvidence',value:classificationPayload,definition:'Schedule subdivision/conference plus prior FCS SRS only when one exact provider team match exists.',units:null,sampleSize:null,season,gamesIncluded:[],effectiveAt:forecastAt,source:{provider:'Verified schedule identity',providerRecordId:team.canonicalId,url:'https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard',retrievedAt:forecastAt,publishedAt:null,rawPayloadHash:sha(classificationPayload)}},forecastAt));diagnostics.push(diagnostic('FBS_FCS',team.canonicalId,forecastAt,stages('PASS','PASS','PASS','PASS','PASS','PASS'),1,1,team.subdivision==='FCS'&&!srsRows.length?['FCS classification retained; prior SRS unavailable or unmatched.']:[]));}
    return{evidence,diagnostics,failures,raw};}
}

const DOMAIN_CATEGORY:Record<string,FootballCategory|undefined>={qb:'QB',roster:'ROSTER',returning_production:'ROSTER',transfers:'TRANSFERS',coaching:'COACHING',talent:'TALENT',fcs:'FBS_FCS',injuries:'INJURIES',weather:'WEATHER',current_season:'OPPONENT_HISTORY'};
const PIPE_CATEGORY:Record<string,FootballCategory>={roster:'ROSTER',qb:'QB',returningProduction:'ROSTER',transfers:'TRANSFERS',coaching:'COACHING',talentDepth:'TALENT',injuries:'INJURIES',weather:'WEATHER',currentSeason:'OPPONENT_HISTORY'};
export function forwardEvidenceFromContext(records:CollegeContextRecord[],teams:ForwardTeamSeed[],forecastAt:string){const at=Date.parse(forecastAt),evidence:ForwardFeatureEvidence[]=[],diagnostics:ForwardDiagnostic[]=[];for(const team of teams){const applicable=records.filter(row=>row.teamId===team.canonicalId&&row.season===2026&&(row.eventId===null||row.eventId===team.eventId)&&Date.parse(row.source.retrievedAt)<=at&&Date.parse(row.source.publishedAt)<=at&&Date.parse(row.effectiveFrom)<=at&&(row.effectiveTo===null||Date.parse(row.effectiveTo)>at));
    const selected=new Map<string,CollegeContextRecord>();for(const row of applicable.sort((a,b)=>Date.parse(b.source.retrievedAt)-Date.parse(a.source.retrievedAt)||b.id.localeCompare(a.id))){const category=DOMAIN_CATEGORY[row.domain];if(!category||row.field.endsWith('.diagnostic')||row.field.endsWith('.ingestionStatus')||row.field.endsWith('.sourceStatus')||row.field.endsWith('.providerChecked'))continue;const key=`${category}:${row.field}:${row.source.name}:${row.playerId??''}`;if(!selected.has(key))selected.set(key,row);}
    for(const row of selected.values()){const category=DOMAIN_CATEGORY[row.domain]!;evidence.push({category,teamId:team.canonicalId,field:row.field,value:structuredClone(row.value),definition:`Raw normalized ${row.domain} fact; no point adjustment.`,units:null,sampleSize:null,season:2026,gamesIncluded:[],effectiveAt:row.effectiveFrom,forecastAt,validity:'VALID',freshness:'FRESH',source:{provider:row.source.name,providerRecordId:row.playerId,url:row.source.url,retrievedAt:row.source.retrievedAt,publishedAt:row.source.publishedAt,rawPayloadHash:row.rawPayloadHash}});}
    const resolved=resolveCollegeTeamContext(records,{teamId:team.canonicalId,teamName:team.name,season:2026,eventId:team.eventId,asOf:at,currentGames:0});for(const [key,pipeline]of Object.entries(resolved.pipelineDiagnostics)){const category=PIPE_CATEGORY[key];diagnostics.push({category,teamId:team.canonicalId,forecastAt,stages:{SOURCE_RETRIEVAL:pipeline.stages.SOURCE_SUCCESS,NORMALIZATION:pipeline.stages.NORMALIZATION_SUCCESS,ENTITY_MATCH:pipeline.stages.ENTITY_MATCH_SUCCESS,ATTACHMENT:pipeline.stages.CONTEXT_ATTACHED,FIELD_VALIDITY:pipeline.stages.FIELD_VALID,FORECAST_TIME_FRESHNESS:pipeline.stages.FRESH_AT_FORECAST_TIME},availableFields:pipeline.validFields,expectedFields:pipeline.requiredFields,notes:[pipeline.sourceResult]});}}
  return{evidence,diagnostics};}

export function completeForwardDiagnostics(existing:ForwardDiagnostic[],teams:ForwardTeamSeed[],forecastAt:string){const map=new Map(existing.map(row=>[`${row.category}:${row.teamId}`,row]));for(const team of teams)for(const category of REQUIRED_FORWARD_CATEGORIES){const key=`${category}:${team.canonicalId}`;if(!map.has(key))map.set(key,diagnostic(category,team.canonicalId,forecastAt,stages('UNKNOWN','UNKNOWN','UNKNOWN','UNKNOWN','UNKNOWN','UNKNOWN'),0,1,['No source attempt recorded for this category.']));}return[...map.values()].sort((a,b)=>a.category.localeCompare(b.category)||String(a.teamId).localeCompare(String(b.teamId)));}
