import {createHash} from 'crypto';
import {stableStringify} from './collegeEdgeResearch';
import {centralScheduledInstant,ForwardOperationalRun,ForwardOperationsStore,ForwardRunObservation} from './collegeForwardOperations';
import {CollegeForwardResearchArchive,FootballCategory,ForwardDiagnostic,ForwardResearchSnapshot} from './collegeForwardResearch';

export const COLLEGE_FORWARD_MONITORING_VERSION='college-forward-monitoring-v1';
export type ForwardDatasetStatus='COLLECTING'|'DATA_QUALITY_WARNING'|'READY_FOR_PRELIMINARY_AUDIT'|'READY_FOR_MODEL_RESEARCH'|'BLOCKED';
export type CoverageState='PASS'|'PARTIAL'|'FAIL'|'UNKNOWN';
export type ForwardAlert='COLLECTOR_STALE'|'MORNING_RUN_MISSED'|'AFTERNOON_RUN_MISSED'|'PROVIDER_FAILURE_SPIKE'|'ENTITY_MATCH_FAILURE'|'CRITICAL_FEATURE_COVERAGE_LOW'|'LEAKAGE_VIOLATION'|'ARCHIVE_WRITE_FAILURE'|'MARKET_CONTAMINATION'|'UNEXPECTED_DUPLICATE'|'DATASET_HASH_FAILURE';
export type ScheduledCaptureState='COMPLETED'|'AWAITING_FIRST_SCHEDULED_EXECUTION'|'NO_ELIGIBLE_GAMES'|'NOT_REQUIRED'|'MISSED_CAPTURE'|'PROVIDER_FAILURE'|'ARCHIVE_FAILURE'|'WORKFLOW_FAILURE';

export interface ForwardMonitoringPolicy {
  activatedAt:string;scheduleGraceMinutes:number;preliminaryReportingN:number;milestones:number[];
  fbsFbs:{finalized:number;modelAIntegrityPercent:number;teamEfficiencyPercent:number;qbPercent:number;rosterPercent:number;talentPercent:number;transferPercent:number;entityMatchPercent:number;providerSuccessPercent:number;development:number;validation:number;holdout:number};
  fbsFcs:{finalized:number;fcsQualityPercent:number;qbPercent:number;rosterPercent:number;talentPercent:number;entityMatchPercent:number};
}
export const DEFAULT_FORWARD_MONITORING_POLICY:ForwardMonitoringPolicy={activatedAt:'2026-09-07T13:33:48.000Z',scheduleGraceMinutes:60,preliminaryReportingN:25,milestones:[25,50,100,250,500,1000],fbsFbs:{finalized:250,modelAIntegrityPercent:90,teamEfficiencyPercent:90,qbPercent:85,rosterPercent:80,talentPercent:80,transferPercent:70,entityMatchPercent:99,providerSuccessPercent:95,development:100,validation:75,holdout:75},fbsFcs:{finalized:75,fcsQualityPercent:80,qbPercent:70,rosterPercent:70,talentPercent:70,entityMatchPercent:99}};

export const COVERAGE_CATEGORIES=['MODEL_A','MARKET_QUOTE','TEAM_IDENTITY','SCHEDULE','CURRENT_SEASON_RESULTS','TEAM_EFFICIENCY','OFFENSIVE_EFFICIENCY','DEFENSIVE_EFFICIENCY','RUSH_INFORMATION','PASS_INFORMATION','QB_EVIDENCE','QB_AVAILABILITY','ROSTER_EVIDENCE','RETURNING_PRODUCTION','TRANSFER_EVIDENCE','TALENT_EVIDENCE','COACHING_EVIDENCE','INJURY_EVIDENCE','WEATHER','VENUE','NEUTRAL_SITE_STATUS','FBS_FCS_CLASSIFICATION'] as const;
export type MonitoringCoverageCategory=typeof COVERAGE_CATEGORIES[number];
const criticalCategories=['TEAM_EFFICIENCY','QB_EVIDENCE','ROSTER_EVIDENCE','TALENT_EVIDENCE','TRANSFER_EVIDENCE','COACHING_EVIDENCE','INJURY_EVIDENCE'] as const;
const forbiddenMarket=/(sportsbook|moneyline|spread|total|odds|consensus|closing.?line|line.?movement|implied.?probability|market.?derived|market.?power)/i;
const sha=(value:unknown)=>createHash('sha256').update(stableStringify(value)).digest('hex');
const pct=(n:number,d:number)=>d?Number((n*100/d).toFixed(1)):null;
const average=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
const median=(values:number[])=>values.length?(values[Math.floor((values.length-1)/2)]+values[Math.ceil((values.length-1)/2)])/2:null;
const gameRegime=(home?:string,away?:string)=>home==='FBS'&&away==='FBS'?'FBS_FBS':home!==away&&[home,away].includes('FCS')?'FBS_FCS':'UNKNOWN';

function evidenceState(snapshot:ForwardResearchSnapshot,category:FootballCategory,field?:RegExp):CoverageState{
  const ids=[snapshot.identity.home.canonicalId,snapshot.identity.away.canonicalId],counts=ids.map(teamId=>snapshot.footballEvidence.filter(row=>row.teamId===teamId&&row.category===category&&(!field||field.test(row.field))&&row.validity==='VALID'&&row.freshness==='FRESH').length),covered=counts.filter(Boolean).length;
  if(covered===2)return'PASS';if(covered===1)return'PARTIAL';const diagnostics=snapshot.diagnostics.filter(row=>row.category===category&&ids.includes(String(row.teamId)));if(diagnostics.some(row=>Object.values(row.stages).includes('FAIL')))return'FAIL';if(diagnostics.some(row=>Object.values(row.stages).includes('PARTIAL')))return'PARTIAL';return'UNKNOWN';
}
function combine(...values:CoverageState[]):CoverageState {if(values.includes('PASS'))return'PASS';if(values.includes('PARTIAL'))return'PARTIAL';if(values.every(value=>value==='FAIL'))return'FAIL';return'UNKNOWN';}
export function snapshotCoverage(snapshot:ForwardResearchSnapshot):Record<MonitoringCoverageCategory,CoverageState>{
  const ids=[snapshot.identity.home.canonicalId,snapshot.identity.away.canonicalId];return{
    MODEL_A:snapshot.modelA.status==='PROJECTED'?'PASS':'FAIL',MARKET_QUOTE:snapshot.market?'PASS':'UNKNOWN',TEAM_IDENTITY:ids.every(Boolean)&&new Set(ids).size===2?'PASS':'FAIL',SCHEDULE:Date.parse(snapshot.capturedAt)<Date.parse(snapshot.identity.kickoff)&&snapshot.operational?.scheduleStatus==='SCHEDULED'?'PASS':'FAIL',
    CURRENT_SEASON_RESULTS:evidenceState(snapshot,'OPPONENT_HISTORY',/^current\./i),TEAM_EFFICIENCY:evidenceState(snapshot,'TEAM_EFFICIENCY'),OFFENSIVE_EFFICIENCY:evidenceState(snapshot,'TEAM_EFFICIENCY',/(offense|offensive)/i),DEFENSIVE_EFFICIENCY:evidenceState(snapshot,'TEAM_EFFICIENCY',/(defense|defensive)/i),RUSH_INFORMATION:combine(evidenceState(snapshot,'TEAM_EFFICIENCY',/rush/i),evidenceState(snapshot,'OPPONENT_HISTORY',/rush/i)),PASS_INFORMATION:combine(evidenceState(snapshot,'TEAM_EFFICIENCY',/pass/i),evidenceState(snapshot,'OPPONENT_HISTORY',/pass/i)),QB_EVIDENCE:evidenceState(snapshot,'QB'),QB_AVAILABILITY:evidenceState(snapshot,'QB',/qb\.status/i),ROSTER_EVIDENCE:evidenceState(snapshot,'ROSTER'),RETURNING_PRODUCTION:evidenceState(snapshot,'ROSTER',/returning|returningProduction/i),TRANSFER_EVIDENCE:evidenceState(snapshot,'TRANSFERS'),TALENT_EVIDENCE:evidenceState(snapshot,'TALENT'),COACHING_EVIDENCE:evidenceState(snapshot,'COACHING'),INJURY_EVIDENCE:evidenceState(snapshot,'INJURIES'),WEATHER:evidenceState(snapshot,'WEATHER'),VENUE:snapshot.identity.venue.id||snapshot.identity.venue.name?'PASS':'UNKNOWN',NEUTRAL_SITE_STATUS:typeof snapshot.identity.neutralSite==='boolean'?'PASS':'FAIL',FBS_FCS_CLASSIFICATION:[snapshot.identity.home.subdivision,snapshot.identity.away.subdivision].every(value=>['FBS','FCS'].includes(value))?'PASS':'FAIL'};
}
function latestByGame(snapshots:ForwardResearchSnapshot[]){const map=new Map<string,ForwardResearchSnapshot>();for(const row of snapshots){const old=map.get(row.identity.canonicalEventId);if(!old||row.forecastAt>old.forecastAt)map.set(row.identity.canonicalEventId,row);}return[...map.values()].sort((a,b)=>a.identity.kickoff.localeCompare(b.identity.kickoff)||a.identity.canonicalEventId.localeCompare(b.identity.canonicalEventId));}
function aggregateCoverage(rows:ForwardResearchSnapshot[]){const perGame=rows.map(snapshot=>({eventId:snapshot.identity.canonicalEventId,snapshotId:snapshot.snapshotId,coverage:snapshotCoverage(snapshot)})),aggregate=Object.fromEntries(COVERAGE_CATEGORIES.map(category=>{const states=perGame.map(row=>row.coverage[category]),counts={PASS:states.filter(v=>v==='PASS').length,PARTIAL:states.filter(v=>v==='PARTIAL').length,FAIL:states.filter(v=>v==='FAIL').length,UNKNOWN:states.filter(v=>v==='UNKNOWN').length},available=counts.PASS+counts.PARTIAL;return[category,{...counts,available,missing:rows.length-available,coveragePercent:pct(available,rows.length)}];}));return{perGame,aggregate};}
export function aggregateSixStages(diagnostics:ForwardDiagnostic[]){return Object.fromEntries(['SOURCE_RETRIEVAL','NORMALIZATION','ENTITY_MATCH','ATTACHMENT','FIELD_VALIDITY','FORECAST_TIME_FRESHNESS'].map(stage=>{const values=diagnostics.map(row=>row.stages[stage as keyof ForwardDiagnostic['stages']]);return[stage,{PASS:values.filter(v=>v==='PASS').length,PARTIAL:values.filter(v=>v==='PARTIAL').length,FAIL:values.filter(v=>v==='FAIL').length,UNKNOWN:values.filter(v=>v==='UNKNOWN').length}];}));}

function distribution(values:number[]){const sorted=[...values].sort((a,b)=>a-b);return{n:sorted.length,meanMinutes:average(sorted),medianMinutes:median(sorted),minimumMinutes:sorted[0]??null,maximumMinutes:sorted.at(-1)??null,ranges:{over24h:sorted.filter(v=>v>1440).length,h12To24:sorted.filter(v=>v>720&&v<=1440).length,h6To12:sorted.filter(v=>v>360&&v<=720).length,h3To6:sorted.filter(v=>v>180&&v<=360).length,h1To3:sorted.filter(v=>v>=60&&v<=180).length,under1h:sorted.filter(v=>v<60).length}};}
export function snapshotTiming(snapshots:ForwardResearchSnapshot[]){const values=(trigger:string)=>snapshots.filter(row=>row.operational?.trigger===trigger).map(row=>row.operational!.minutesToKickoff);return{morning:distribution(values('SCHEDULED_0700_CT')),afternoon:distribution(values('SCHEDULED_1400_CT')),manual:distribution(values('MANUAL'))};}
function timingCoverage(snapshots:ForwardResearchSnapshot[]){return Object.fromEntries([['morning','SCHEDULED_0700_CT'],['afternoon','SCHEDULED_1400_CT'],['manual','MANUAL']].map(([name,trigger])=>{const aggregate=aggregateCoverage(snapshots.filter(row=>row.operational?.trigger===trigger)).aggregate;return[name,Object.fromEntries(COVERAGE_CATEGORIES.map(category=>[category,(aggregate as any)[category].coveragePercent]))];}));}
export function auditMarketContamination(snapshots:ForwardResearchSnapshot[]){const violations=snapshots.flatMap(snapshot=>snapshot.footballEvidence.filter(row=>forbiddenMarket.test(row.field)||forbiddenMarket.test(row.definition)||forbiddenMarket.test(row.source.provider)).map(row=>({snapshotId:snapshot.snapshotId,eventId:snapshot.identity.canonicalEventId,field:row.field,provider:row.source.provider})));return{status:violations.length?'MARKET_CONTAMINATION':'PASS',violations};}
export function auditFutureLeakage(snapshots:ForwardResearchSnapshot[]){const violations:any[]=[];for(const snapshot of snapshots){const at=Date.parse(snapshot.forecastAt);if(!(at<Date.parse(snapshot.identity.kickoff)))violations.push({snapshotId:snapshot.snapshotId,type:'SNAPSHOT_NOT_PREGAME'});for(const row of snapshot.footballEvidence){if(Date.parse(row.source.retrievedAt)>at)violations.push({snapshotId:snapshot.snapshotId,field:row.field,type:'RETRIEVED_AFTER_SNAPSHOT'});if(row.source.publishedAt&&Date.parse(row.source.publishedAt)>at)violations.push({snapshotId:snapshot.snapshotId,field:row.field,type:'PUBLISHED_AFTER_SNAPSHOT'});if(Date.parse(row.effectiveAt)>at)violations.push({snapshotId:snapshot.snapshotId,field:row.field,type:'EFFECTIVE_AFTER_SNAPSHOT'});}if(snapshot.market&&(Date.parse(snapshot.market.retrievedAt)>at||Date.parse(snapshot.market.quoteTimestamp)>at))violations.push({snapshotId:snapshot.snapshotId,type:'MARKET_AFTER_SNAPSHOT'});}return{status:violations.length?'LEAKAGE_VIOLATION':'PASS',violations};}

function providerReport(snapshots:ForwardResearchSnapshot[],runs:ForwardOperationalRun[]){const names=new Set<string>();for(const snapshot of snapshots){for(const row of snapshot.footballEvidence)names.add(row.source.provider);for(const row of snapshot.failures)names.add(row.provider);if(snapshot.market)names.add('The Odds API');}for(const run of runs)for(const row of run.requestPlan)names.add(row.provider);const api=runs.reduce((n,row)=>n+row.metrics.apiRequests,0),cfbd=runs.reduce((n,row)=>n+row.metrics.cfbdRequests,0),market=runs.reduce((n,row)=>n+row.metrics.marketRequests,0),cache=runs.reduce((n,row)=>n+row.metrics.cacheHits,0);return[...names].sort().map(provider=>{const lower=provider.toLowerCase(),requests=lower.includes('collegefootball')?cfbd:lower.includes('odds')?market:lower.includes('espn')?Math.max(0,api-cfbd-market):0,evidence=snapshots.flatMap(row=>row.footballEvidence).filter(row=>row.source.provider===provider),failures=snapshots.flatMap(row=>row.failures).filter(row=>row.provider===provider),runFailures=runs.flatMap(row=>row.providerFailures).filter(row=>row.provider===provider),successes=new Set(evidence.map(row=>row.source.rawPayloadHash)).size;return{provider,requests,successes,usableFeatureAttachments:evidence.length,partialResponses:failures.filter(row=>row.finalAvailability==='PARTIAL').length+runFailures.filter(row=>/partial/i.test(row.type)).length,failures:failures.length+runFailures.length,rateLimits:failures.filter(row=>row.errorClass==='RATE_LIMIT').length,timeouts:[...failures.map(row=>row.message),...runFailures.map(row=>row.message)].filter(message=>/timeout/i.test(message)).length,entityMismatches:failures.filter(row=>row.errorClass==='ENTITY_MISMATCH').length,staleResponses:failures.filter(row=>row.errorClass==='STALE_DATA').length,cacheHits:lower.includes('collegefootball')?cache:0,operationalSuccessPercent:pct(successes,requests)};});}
function entityReport(rows:ForwardResearchSnapshot[]){let total=0,matched=0,ambiguous=0,failed=0,aliases=0;for(const row of rows){aliases+=Math.max(0,Object.keys(row.identity.providerEventIds).length-1);for(const id of [row.identity.home.canonicalId,row.identity.away.canonicalId]){total++;const states=row.diagnostics.filter(d=>d.teamId===id).map(d=>d.stages.ENTITY_MATCH);if(states.includes('FAIL'))failed++;else if(states.includes('PARTIAL'))ambiguous++;else if(id)matched++;}}return{gamesSuccessfullyCanonicalized:rows.filter(row=>Boolean(row.identity.canonicalEventId)).length,totalGames:rows.length,teamsSuccessfullyMatched:matched,totalTeams:total,providerAliasesUsed:aliases,ambiguousMatches:ambiguous,failedMatches:failed,manualOverrides:0,matchPercent:pct(matched,total)};}
function observationRegime(row:ForwardRunObservation,snapshot?:ForwardResearchSnapshot){return gameRegime(row.homeSubdivision??snapshot?.identity.home.subdivision,row.awaySubdivision??snapshot?.identity.away.subdivision);}
function universeReport(runs:ForwardOperationalRun[],snapshots:ForwardResearchSnapshot[]){const bySnapshot=new Map(snapshots.map(row=>[row.snapshotId,row])),map=new Map<string,{eventId:string;regime:string;captured:boolean;failed:boolean}>();for(const run of runs)for(const row of run.observations){if(!['CAPTURED','DEDUPLICATED','WOULD_CAPTURE','DEFERRED','FAILED','SKIPPED_POSTPONED','SKIPPED_CANCELED'].includes(row.status))continue;const old=map.get(row.eventId),snapshot=row.snapshotId?bySnapshot.get(row.snapshotId):undefined;map.set(row.eventId,{eventId:row.eventId,regime:observationRegime(row,snapshot),captured:old?.captured===true||['CAPTURED','DEDUPLICATED'].includes(row.status),failed:old?.failed===true||row.status==='FAILED'});}const values=[...map.values()],group=(name:string)=>({eligible:values.filter(row=>row.regime===name).length,captured:values.filter(row=>row.regime===name&&row.captured).length});return{eligibleGames:values.length,capturedGames:values.filter(row=>row.captured).length,missingGames:values.filter(row=>!row.captured).length,captureRatePercent:pct(values.filter(row=>row.captured).length,values.length),byRegime:{FBS_FBS:group('FBS_FBS'),FBS_FCS:group('FBS_FCS')},missingEventIds:values.filter(row=>!row.captured).map(row=>row.eventId)};}

export function classifyScheduledRun(trigger:'SCHEDULED_0700_CT'|'SCHEDULED_1400_CT',date:string,now:number,runs:ForwardOperationalRun[],policy=DEFAULT_FORWARD_MONITORING_POLICY):ScheduledCaptureState{const scheduled=Date.parse(centralScheduledInstant(date,trigger==='SCHEDULED_0700_CT'?7:14));if(scheduled<Date.parse(policy.activatedAt)||now<scheduled+policy.scheduleGraceMinutes*60_000)return'NOT_REQUIRED';const id=`${date}-${trigger==='SCHEDULED_0700_CT'?'0700':'1400'}-ct`,run=runs.find(row=>row.captureEventId===id);if(!run)return runs.some(row=>row.trigger===trigger)?'WORKFLOW_FAILURE':'AWAITING_FIRST_SCHEDULED_EXECUTION';if(run.status==='FAILED')return'WORKFLOW_FAILURE';if(run.observations.some(row=>row.status==='FAILED'&&/archive/i.test(row.message)))return'ARCHIVE_FAILURE';if(run.providerFailures.length||run.observations.some(row=>row.status==='FAILED'))return'PROVIDER_FAILURE';const eligible=run.observations.filter(row=>['CAPTURED','DEDUPLICATED','DEFERRED','FAILED'].includes(row.status));if(!eligible.length)return'NO_ELIGIBLE_GAMES';return eligible.some(row=>['CAPTURED','DEDUPLICATED'].includes(row.status))?'COMPLETED':'MISSED_CAPTURE';}
function runEvidence(runs:ForwardOperationalRun[],hashes:Record<string,string|null>){return(['SCHEDULED_0700_CT','SCHEDULED_1400_CT'] as const).map(trigger=>{const run=runs.filter(row=>row.trigger===trigger).sort((a,b)=>a.startedAt.localeCompare(b.startedAt))[0];if(!run)return{trigger,status:'AWAITING_FIRST_SCHEDULED_EXECUTION',scheduledTime:null,actualStartTime:null,actualCompletionTime:null,eligibleGamesDiscovered:null,snapshotsCreated:null,snapshotsDeduplicated:null,gamesSkippedAfterKickoff:null,providerRequests:null,cacheHits:null,failures:null,archiveCommitHash:null};return{trigger,status:run.status,scheduledTime:run.scheduledFor,actualStartTime:run.startedAt,actualCompletionTime:run.completedAt,eligibleGamesDiscovered:run.observations.filter(row=>['CAPTURED','DEDUPLICATED','DEFERRED','FAILED'].includes(row.status)).length,snapshotsCreated:run.observations.filter(row=>row.status==='CAPTURED').length,snapshotsDeduplicated:run.observations.filter(row=>row.status==='DEDUPLICATED').length,gamesSkippedAfterKickoff:run.observations.filter(row=>row.status==='SKIPPED_STARTED').length,providerRequests:run.metrics.apiRequests,cacheHits:run.metrics.cacheHits,failures:run.providerFailures.length+run.discoveryFailures.length+run.observations.filter(row=>row.status==='FAILED').length,archiveCommitHash:hashes[run.runId]??null};});}
function counts(snapshots:ForwardResearchSnapshot[],finalIds:Set<string>,runs:ForwardOperationalRun[]){const games=latestByGame(snapshots),ids=new Set(games.map(row=>row.identity.canonicalEventId)),trigger=(name:string)=>new Set(snapshots.filter(row=>row.operational?.trigger===name).map(row=>row.identity.canonicalEventId)).size;return{eligibleGames:universeReport(runs,snapshots).eligibleGames,gamesWithAtLeastOneValidPregameSnapshot:ids.size,gamesWithMorningSnapshot:trigger('SCHEDULED_0700_CT'),gamesWithAfternoonSnapshot:trigger('SCHEDULED_1400_CT'),gamesWithManualSnapshot:trigger('MANUAL'),gamesWithMultipleValidSnapshots:[...ids].filter(id=>snapshots.filter(row=>row.identity.canonicalEventId===id).length>1).length,gamesFinalized:[...ids].filter(id=>finalIds.has(id)).length,gamesPending:[...ids].filter(id=>!finalIds.has(id)).length,gamesCanceledPostponed:new Set(runs.flatMap(run=>run.observations.filter(row=>['SKIPPED_CANCELED','SKIPPED_POSTPONED'].includes(row.status)).map(row=>row.eventId))).size,gamesWithCaptureFailure:new Set(runs.flatMap(run=>run.observations.filter(row=>row.status==='FAILED').map(row=>row.eventId))).size,regime:{fbsFbs:games.filter(row=>gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FBS').length,fbsFcs:games.filter(row=>gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FCS').length},seasonStage:{weeks0To2:games.filter(row=>(row.identity.week??99)<=2).length,weeks3To5:games.filter(row=>(row.identity.week??99)>=3&&(row.identity.week??99)<=5).length,week6Plus:games.filter(row=>(row.identity.week??-1)>=6).length}};}
function performance(snapshots:ForwardResearchSnapshot[],finals:any[],minimum:number,market=false){const finalMap=new Map(finals.map(row=>[row.canonicalEventId,row])),rows=latestByGame(snapshots).filter(row=>finalMap.has(row.identity.canonicalEventId)&&(market?row.market!==null:row.modelA.status==='PROJECTED')),errors=rows.map(row=>(market?-row.market!.homeSpread:row.modelA.homeMargin!)-finalMap.get(row.identity.canonicalEventId).actualHomeMargin);if(errors.length<minimum)return{status:'SUPPRESSED_MINIMUM_N',n:errors.length,minimumN:minimum,mae:null,rmse:null,bias:null};return{status:'DESCRIPTIVE_ONLY',n:errors.length,minimumN:minimum,mae:average(errors.map(Math.abs)),rmse:Math.sqrt(errors.reduce((n,v)=>n+v*v,0)/errors.length),bias:average(errors)};}
function partition(rows:ForwardResearchSnapshot[],finalIds:Set<string>){const finalized=latestByGame(rows).filter(row=>finalIds.has(row.identity.canonicalEventId)&&gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FBS'),name=(week:number|null)=>week!==null&&week<=5?'DEVELOPMENT':week!==null&&week<=9?'VALIDATION':week!==null?'LOCKED_HOLDOUT':'UNASSIGNED';return Object.fromEntries(['DEVELOPMENT','VALIDATION','LOCKED_HOLDOUT','UNASSIGNED'].map(value=>[value,finalized.filter(row=>name(row.identity.week)===value).length]));}
function fcsQualityAvailable(row:ForwardResearchSnapshot){const fcsId=row.identity.home.subdivision==='FCS'?row.identity.home.canonicalId:row.identity.away.subdivision==='FCS'?row.identity.away.canonicalId:null;if(!fcsId)return false;return row.footballEvidence.some(evidence=>evidence.teamId===fcsId&&evidence.category==='FBS_FCS'&&evidence.validity==='VALID'&&evidence.freshness==='FRESH'&&(/srs|quality|rating/i.test(evidence.field)||typeof evidence.value==='object'&&evidence.value!==null&&Object.keys(evidence.value as object).some(key=>/srs|quality|rating/i.test(key))));}
function readiness(rows:ForwardResearchSnapshot[],finalIds:Set<string>,entity:any,providers:any,leakage:any,contamination:any,hashValid:boolean,policy:ForwardMonitoringPolicy){const games=latestByGame(rows),fbsFbs=games.filter(row=>gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FBS'),fbsFcs=games.filter(row=>gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FCS'),available=(category:MonitoringCoverageCategory,subset:ForwardResearchSnapshot[])=>pct(subset.filter(row=>['PASS','PARTIAL'].includes(snapshotCoverage(row)[category])).length,subset.length)??0,parts=partition(rows,finalIds),providerRequests=providers.reduce((n:number,row:any)=>n+row.requests,0),providerSuccesses=providers.reduce((n:number,row:any)=>n+row.successes,0),fbsFbsFinal=[...finalIds].filter(id=>fbsFbs.some(row=>row.identity.canonicalEventId===id)).length,fbsFcsFinal=[...finalIds].filter(id=>fbsFcs.some(row=>row.identity.canonicalEventId===id)).length;
  const a={finalized:fbsFbsFinal>=policy.fbsFbs.finalized,modelAIntegrity:available('MODEL_A',fbsFbs)>=policy.fbsFbs.modelAIntegrityPercent,teamEfficiency:available('TEAM_EFFICIENCY',fbsFbs)>=policy.fbsFbs.teamEfficiencyPercent,qb:available('QB_EVIDENCE',fbsFbs)>=policy.fbsFbs.qbPercent,roster:available('ROSTER_EVIDENCE',fbsFbs)>=policy.fbsFbs.rosterPercent,talent:available('TALENT_EVIDENCE',fbsFbs)>=policy.fbsFbs.talentPercent,transfers:available('TRANSFER_EVIDENCE',fbsFbs)>=policy.fbsFbs.transferPercent,entityMatch:(entity.matchPercent??0)>=policy.fbsFbs.entityMatchPercent,providerSuccess:(pct(providerSuccesses,providerRequests)??0)>=policy.fbsFbs.providerSuccessPercent,zeroLeakage:!leakage.violations.length,zeroContamination:!contamination.violations.length,datasetHashValid:hashValid,development:parts.DEVELOPMENT>=policy.fbsFbs.development,validation:parts.VALIDATION>=policy.fbsFbs.validation,holdout:parts.LOCKED_HOLDOUT>=policy.fbsFbs.holdout},b={finalized:fbsFcsFinal>=policy.fbsFcs.finalized,fcsQuality:(pct(fbsFcs.filter(fcsQualityAvailable).length,fbsFcs.length)??0)>=policy.fbsFcs.fcsQualityPercent,qb:available('QB_EVIDENCE',fbsFcs)>=policy.fbsFcs.qbPercent,roster:available('ROSTER_EVIDENCE',fbsFcs)>=policy.fbsFcs.rosterPercent,talent:available('TALENT_EVIDENCE',fbsFcs)>=policy.fbsFcs.talentPercent,entityMatch:(entity.matchPercent??0)>=policy.fbsFcs.entityMatchPercent,zeroLeakage:!leakage.violations.length,zeroContamination:!contamination.violations.length,datasetHashValid:hashValid};return{fbsFbs:{ready:Object.values(a).every(Boolean),checks:a},fbsFcs:{ready:Object.values(b).every(Boolean),checks:b},partitions:parts,policy:'Weeks 0–5 DEVELOPMENT; Weeks 6–9 VALIDATION; Week 10+ LOCKED_HOLDOUT. Fixed chronologically before outcomes; FBS/FBS and FBS/FCS stay separate; postseason excluded until separately declared.'};}

export function buildForwardMonitoringReport(root:string,generatedAt:string,options:{policy?:ForwardMonitoringPolicy;commitHashes?:Record<string,string|null>;schedulerConfigured?:boolean;secretsVerified?:boolean|null}={}){const policy=options.policy??DEFAULT_FORWARD_MONITORING_POLICY,archive=new CollegeForwardResearchArchive(root).load(),runs=new ForwardOperationsStore(root).runs(),rows=latestByGame(archive.snapshots),finalIds=new Set(archive.finals.map(row=>row.canonicalEventId)),coverage=aggregateCoverage(rows),contamination=auditMarketContamination(archive.snapshots),leakage=auditFutureLeakage(archive.snapshots),entities=entityReport(rows),providers=providerReport(archive.snapshots,runs),universe=universeReport(runs,archive.snapshots),records=[...archive.snapshots.map(value=>({kind:'SNAPSHOT',value})),...archive.finals.map(value=>({kind:'FINAL',value})),...archive.corrections.map(value=>({kind:'CORRECTION',value})),...archive.failures.map(value=>({kind:'FAILURE',value})),...runs.map(value=>({kind:'RUN',value}))].sort((a,b)=>stableStringify(a).localeCompare(stableStringify(b))),datasetHash=sha(records),hashValid=/^[a-f0-9]{64}$/.test(datasetHash),gate=readiness(rows,finalIds,entities,providers,leakage,contamination,hashValid,policy),scheduled=runEvidence(runs,options.commitHashes??{}),now=Date.parse(generatedAt),today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now)),morning=classifyScheduledRun('SCHEDULED_0700_CT',today,now,runs,policy),afternoon=classifyScheduledRun('SCHEDULED_1400_CT',today,now,runs,policy),alerts:ForwardAlert[]=[];
  if([morning,afternoon].includes('WORKFLOW_FAILURE'))alerts.push('COLLECTOR_STALE');if(morning==='WORKFLOW_FAILURE')alerts.push('MORNING_RUN_MISSED');if(afternoon==='WORKFLOW_FAILURE')alerts.push('AFTERNOON_RUN_MISSED');if(providers.some(row=>row.failures>=3))alerts.push('PROVIDER_FAILURE_SPIKE');if(entities.failedMatches||entities.ambiguousMatches)alerts.push('ENTITY_MATCH_FAILURE');if(rows.length&&criticalCategories.some(category=>(coverage.aggregate as any)[category].coveragePercent<85))alerts.push('CRITICAL_FEATURE_COVERAGE_LOW');if(leakage.violations.length)alerts.push('LEAKAGE_VIOLATION');if(contamination.violations.length)alerts.push('MARKET_CONTAMINATION');if(!hashValid)alerts.push('DATASET_HASH_FAILURE');if(new Set(archive.snapshots.map(row=>row.snapshotId)).size!==archive.snapshots.length)alerts.push('UNEXPECTED_DUPLICATE');const severe=alerts.some(value=>['LEAKAGE_VIOLATION','MARKET_CONTAMINATION','DATASET_HASH_FAILURE','ARCHIVE_WRITE_FAILURE'].includes(value)),finalized=finalIds.size,datasetStatus:ForwardDatasetStatus=severe?'BLOCKED':gate.fbsFbs.ready?'READY_FOR_MODEL_RESEARCH':finalized>=100&&!alerts.length?'READY_FOR_PRELIMINARY_AUDIT':finalized<25?'COLLECTING':'DATA_QUALITY_WARNING',bad=[morning,afternoon].some(value=>['WORKFLOW_FAILURE','PROVIDER_FAILURE','ARCHIVE_FAILURE','MISSED_CAPTURE'].includes(value));
  const providerAccessVerified=runs.some(row=>row.trigger!=='MANUAL'&&row.status==='SUCCESS'&&row.metrics.cfbdRequests>0&&row.metrics.marketRequests>0),secretsVerified=options.secretsVerified??(providerAccessVerified?true:null),bothWindowsObserved=scheduled.every(row=>row.status==='SUCCESS'||row.status==='DEGRADED'),phase7Operational=(options.schedulerConfigured??true)&&secretsVerified===true&&providerAccessVerified&&bothWindowsObserved;
  return{schemaVersion:COLLEGE_FORWARD_MONITORING_VERSION,generatedAt,datasetStatus,datasetHash,datasetHashValid:hashValid,phase7:{workflowConfigured:options.schedulerConfigured??true,operationallyVerified:phase7Operational,schedule:{morning:'07:00 America/Chicago',afternoon:'14:00 America/Chicago',runsPerDay:2,dstIanaZone:true},requiredSecretsVerified:secretsVerified,providerAccessVerified,durableAuthority:'research/forward-archive on default Git branch',manualAndScheduledShareAuthority:true,normalArchiveCommitsSkipRender:true},scheduledRunEvidence:scheduled,missedScheduledCaptures:{morning,afternoon},counts:counts(archive.snapshots,finalIds,runs),eligibleUniverse:universe,coverage,criticalFeatureCoverage:Object.fromEntries(criticalCategories.map(category=>[category,(coverage.aggregate as any)[category]])),fcsQualityCoverage:{available:rows.filter(row=>gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FCS'&&fcsQualityAvailable(row)).length,total:rows.filter(row=>gameRegime(row.identity.home.subdivision,row.identity.away.subdivision)==='FBS_FCS').length},sixStageDiagnostics:aggregateSixStages(archive.snapshots.flatMap(row=>row.diagnostics)),providerReliability:providers,entityMatchQuality:entities,snapshotTiming:snapshotTiming(archive.snapshots),completenessByTiming:timingCoverage(archive.snapshots),marketFootballSeparation:contamination,futureLeakageAudit:leakage,correctionAudit:{appendOnly:true,count:archive.corrections.length,records:archive.corrections.map(row=>({correctionId:row.correctionId,targetType:row.targetType,targetId:row.targetId,reason:row.reason,timestamp:row.recordedAt,previousHash:row.targetId,newHash:row.correctionId}))},modelAForward:performance(archive.snapshots,archive.finals,policy.preliminaryReportingN),marketForward:performance(archive.snapshots,archive.finals,policy.preliminaryReportingN,true),holdoutPolicy:gate.policy,modelBV2Readiness:gate,milestones:policy.milestones.map(target=>({target,reached:finalized>=target,remaining:Math.max(0,target-finalized)})),nextResearchMilestone:policy.milestones.find(target=>finalized<target)??null,alerts:[...new Set(alerts)].sort(),productionImpact:{recommendations:false,modelACoefficients:false,spreadQualification:false,totalsQualification:false,calibration:false,kelly:false,staking:false,parlays:false,paperSelectionRules:false},finalDecision:gate.fbsFbs.ready?'MODEL B V2 RESEARCH GATE REACHED':!phase7Operational||severe||bad?'FORWARD COLLECTION DEGRADED — FIX DATA PIPELINE':'FORWARD COLLECTION HEALTHY — CONTINUE ACCUMULATING DATA'};
}
