import {createHash} from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import {getCollegeSlateOdds,getUpcomingEvents,UpcomingEvent} from '../api/oddsApiClient';
import {NCAAF} from '../config/productionFocus';
import {RawEvent} from '../types/odds';
import {collegeDate} from './collegeDayScan';
import {collegeDivision} from './collegeContext';
import {CollegeContextIngestion} from './collegeContextIngestion';
import {COLLEGE_CONTEXT_EVIDENCE_VERSION,loadCollegeContextRecords} from './collegeContextEvidence';
import {collegeTeamMatches} from './collegeEntities';
import {stableStringify} from './collegeEdgeResearch';
import {
  COLLEGE_FORWARD_RESEARCH_VERSION,CollegeForwardResearchArchive,ForwardFailure,
  ForwardMarketEvidence,ModelAForwardForecast,NewForwardResearchSnapshot,
} from './collegeForwardResearch';
import {BoundedForwardSourceCache,CfbdForwardResearchSource,completeForwardDiagnostics,forwardEvidenceFromContext,ForwardTeamSeed} from './collegeForwardSources';
import {ForwardCollectorAdapter,ForwardDiscoveredGame,ForwardPreparedRun,ForwardRequestPlan} from './collegeForwardOperations';
import {flattenNflQuotes} from './nflMarketBoard';
import {fetchNflJson,nflSeason} from './nflResearch';
import {fitCollegeScores,mergeCollegeResults,parseCollegeResults} from './collegeScoreModel';
import {loadCollegeModelBundle} from './collegePredictions';
import {ESPN_COLLEGE} from './collegeResearch';
import {PAPER_APPLICATION_RELEASE} from './footballSettlement';

const sha=(value:unknown)=>createHash('sha256').update(stableStringify(value)).digest('hex');
const toDay=(ms:number)=>new Date(ms).toISOString().slice(0,10).replace(/-/g,'');
const fetchResponse=async(url:string,init?:any)=>{const response=await fetch(url,init);return{ok:response.ok,status:response.status,json:()=>response.json()};};
interface RuntimeGamePayload {event:any;home:any;away:any;competition:any;provider:UpcomingEvent|null;}
interface RuntimeState {contextRecords:any[];cfbd:Awaited<ReturnType<CfbdForwardResearchSource['collect']>>;rawOdds:RawEvent[];marketRetrievedAt:string|null;marketFailure:string|null;modelForecasts:Map<string,ModelAForwardForecast>;modelFailure:string|null;}

function explicitStatus(event:any){const type=event?.status?.type,name=String(type?.name??'').toUpperCase(),state=String(type?.state??'').toLowerCase();if(type?.completed===true&&state==='post'&&['STATUS_FINAL','STATUS_FINAL_OVERTIME'].includes(name))return'FINAL' as const;if(['STATUS_CANCELED','STATUS_CANCELLED'].includes(name))return'CANCELED' as const;if(name==='STATUS_POSTPONED')return'POSTPONED' as const;if(state==='in'||['STATUS_IN_PROGRESS','STATUS_HALFTIME','STATUS_DELAYED'].includes(name))return'IN_PROGRESS' as const;if(state==='pre'&&name==='STATUS_SCHEDULED')return'SCHEDULED' as const;return'UNKNOWN' as const;}
function teamFrom(competition:any,side:'home'|'away'){return (competition?.competitors??[]).find((row:any)=>row.homeAway===side);}
function safeConference(team:any){return String(team?.conferenceId??'')||null;}
function matchProvider(home:any,away:any,kickoff:string,provider:UpcomingEvent[]){const matches=provider.filter(row=>collegeTeamMatches(row.homeTeam,home.team)&&collegeTeamMatches(row.awayTeam,away.team)&&Math.abs(Date.parse(row.commenceTime)-Date.parse(kickoff))<=15*60_000);return matches.length===1?matches[0]:null;}

export class LiveCollegeForwardCollectorAdapter implements ForwardCollectorAdapter {
  private archive:CollegeForwardResearchArchive;
  constructor(private root:string,private now=()=>Date.now(),private get=fetchNflJson,private horizonHours=36){this.archive=new CollegeForwardResearchArchive(root);}
  async discover(at:string){const now=Date.parse(at),end=now+this.horizonHours*3600_000,startDay=toDay(now-86400_000),endDay=toDay(end+86400_000),failures:string[]=[],payloads:any[]=[];let provider:UpcomingEvent[]=[];
    try{provider=await getUpcomingEvents(NCAAF);}catch(error){failures.push(`Odds-provider free event discovery failed: ${String(error instanceof Error?error.message:error)}`);}
    for(const group of [80,81]){const url=`${ESPN_COLLEGE}/scoreboard?dates=${startDay}-${endDay}&groups=${group}&limit=1000`;try{payloads.push({group,url,data:await this.get(url)});}catch(error){failures.push(`ESPN group ${group} discovery failed: ${String(error instanceof Error?error.message:error)}`);}}
    const seen=new Map<string,ForwardDiscoveredGame>();for(const source of payloads)for(const event of source.data?.events??[]){const competition=event?.competitions?.[0],home=teamFrom(competition,'home'),away=teamFrom(competition,'away'),kickoff=String(event?.date??''),kickoffMs=Date.parse(kickoff);if(!/^\d+$/.test(String(event?.id??''))||!home?.team?.id||!away?.team?.id||!Number.isFinite(kickoffMs)||kickoffMs<now-86400_000||kickoffMs>end)continue;const homeDivision=collegeDivision(2026,String(home.team.conferenceId??'')),awayDivision=collegeDivision(2026,String(away.team.conferenceId??''));if(!['FBS','FCS'].includes(homeDivision)||!['FBS','FCS'].includes(awayDivision)||homeDivision==='FCS'&&awayDivision==='FCS')continue;const providerEvent=matchProvider(home,away,kickoff,provider),rawHash=sha(source.data),status=explicitStatus(event),game:ForwardDiscoveredGame={canonicalEventId:String(event.id),originalScheduledKickoff:kickoff,latestVerifiedKickoff:status==='POSTPONED'?null:kickoff,status,homeSubdivision:homeDivision,awaySubdivision:awayDivision,missingCriticalEvidence:10,scheduleSource:{provider:'ESPN',retrievedAt:at,rawPayloadHash:rawHash},payload:{event,home,away,competition,provider:providerEvent} satisfies RuntimeGamePayload};const prior=seen.get(game.canonicalEventId);if(!prior||source.group===80)seen.set(game.canonicalEventId,game);}
    return{games:[...seen.values()].sort((a,b)=>Date.parse(a.latestVerifiedKickoff??'9999')-Date.parse(b.latestVerifiedKickoff??'9999')||a.canonicalEventId.localeCompare(b.canonicalEventId)),requests:payloads.length+1,cacheHits:0,failures};}
  plan(games:ForwardDiscoveredGame[],at:string):ForwardRequestPlan[]{if(!games.length)return[];return[
    {provider:'ESPN',category:'GAME_CONTEXT',scope:`${games.length} events; stale/missing summaries only`,cache:'UNKNOWN',maximumRequests:games.length,priority:1},
    {provider:'ESPN',category:'ROSTER',scope:'unique stale/missing teams only',cache:'UNKNOWN',maximumRequests:games.length*2,priority:2},
    {provider:'CollegeFootballData',category:'SHARED_FORWARD_FACTS',scope:'whole-season shared payloads',cache:'UNKNOWN',maximumRequests:4,priority:3},
    {provider:'The Odds API',category:'EXTERNAL_MARKET_BENCHMARK',scope:'one bulk college spread/total request',cache:'UNKNOWN',maximumRequests:1,priority:4},
    {provider:'ESPN',category:'MODEL_A_CURRENT_RESULTS',scope:`season-to-date as of ${at}`,cache:'UNKNOWN',maximumRequests:2,priority:5},
  ];}
  async prepare(games:ForwardDiscoveredGame[],at:string):Promise<ForwardPreparedRun>{if(!games.length)return{state:{contextRecords:[],cfbd:{evidence:[],diagnostics:[],failures:[],raw:[]},rawOdds:[],marketRetrievedAt:null,marketFailure:null,modelForecasts:new Map(),modelFailure:null} satisfies RuntimeState,metrics:{apiRequests:0,cacheHits:0,cfbdRequests:0,marketRequests:0},deferred:[],failures:[]};
    const teams=this.teams(games),seeds=games.flatMap(game=>{const payload=game.payload as RuntimeGamePayload,venue={id:payload.competition.venue?.id?String(payload.competition.venue.id):null,name:payload.competition.venue?.fullName??null,indoor:typeof payload.competition.venue?.indoor==='boolean'?payload.competition.venue.indoor:null};return[
      {teamId:String(payload.home.team.id),teamName:String(payload.home.team.displayName??payload.home.team.name),aliases:[payload.home.team.shortDisplayName,payload.home.team.location,payload.home.team.abbreviation].filter(Boolean),eventId:game.canonicalEventId,commenceTime:game.latestVerifiedKickoff!,division:game.homeSubdivision,venue},
      {teamId:String(payload.away.team.id),teamName:String(payload.away.team.displayName??payload.away.team.name),aliases:[payload.away.team.shortDisplayName,payload.away.team.location,payload.away.team.abbreviation].filter(Boolean),eventId:game.canonicalEventId,commenceTime:game.latestVerifiedKickoff!,division:game.awaySubdivision,venue},
    ];}),failures:ForwardPreparedRun['failures']=[];
    let contextRecords:any[]=[];try{const context=new CollegeContextIngestion(this.root,this.get,this.now,'');const refreshed=await context.refresh(seeds);contextRecords=refreshed.records.filter(row=>row.source?.name!=='CollegeFootballData');for(const warning of refreshed.warnings.filter(row=>!row.includes('CollegeFootballData key is not configured')))failures.push({provider:'ESPN_CONTEXT',type:'PARTIAL_CONTEXT',retryable:true,nextEligibleAttempt:new Date(this.now()+15*60_000).toISOString(),message:warning});}catch(error){try{contextRecords=loadCollegeContextRecords(this.root).filter(row=>row.source?.name!=='CollegeFootballData');}catch{}failures.push({provider:'ESPN_CONTEXT',type:'CONTEXT_REFRESH_FAILED',retryable:true,nextEligibleAttempt:new Date(this.now()+15*60_000).toISOString(),message:String(error instanceof Error?error.message:error)});}
    const cache=new BoundedForwardSourceCache(fetchResponse,this.now,undefined,4);this.primeCfbdCache(cache);const cfbdSource=new CfbdForwardResearchSource(cache,process.env.CFBD_API_KEY,this.now),cfbd=await cfbdSource.collect(teams,2026,new Date(this.now()).toISOString());for(const raw of cfbd.raw)this.archive.archiveRaw(raw.provider,raw.url,raw.retrievedAt,raw.payload);
    let rawOdds:RawEvent[]=[],marketRetrievedAt:string|null=null,marketFailure:string|null=null,marketRequests=0;try{const result=await getCollegeSlateOdds();rawOdds=result.events;marketRetrievedAt=new Date(this.now()).toISOString();marketRequests=1;this.archive.archiveRaw('The Odds API','https://api.the-odds-api.com/v4/sports/americanfootball_ncaaf/odds',marketRetrievedAt,rawOdds);}catch(error){marketFailure=String(error instanceof Error?error.message:error);failures.push({provider:'The Odds API',type:'MARKET_UNAVAILABLE',retryable:true,nextEligibleAttempt:new Date(this.now()+15*60_000).toISOString(),message:marketFailure});}
    const model=await this.modelA(games);if(model.failure)failures.push({provider:'MODEL_A_INPUTS',type:'MODEL_UNAVAILABLE',retryable:true,nextEligibleAttempt:new Date(this.now()+60*60_000).toISOString(),message:model.failure});const state:RuntimeState={contextRecords,cfbd,rawOdds,marketRetrievedAt,marketFailure,modelForecasts:model.forecasts,modelFailure:model.failure};return{state,metrics:{apiRequests:cache.requestsUsed+marketRequests+model.requests,cacheHits:Math.max(0,4-cache.requestsUsed),cfbdRequests:cache.requestsUsed,marketRequests},deferred:[],failures};}
  async capture(game:ForwardDiscoveredGame,prepared:ForwardPreparedRun):Promise<NewForwardResearchSnapshot>{const state=prepared.state as RuntimeState,capturedAt=new Date(this.now()).toISOString(),payload=game.payload as RuntimeGamePayload,teams=this.teams([game]),context=forwardEvidenceFromContext(state.contextRecords,teams,capturedAt),ids=new Set(teams.map(team=>team.canonicalId)),footballEvidence=[...context.evidence,...state.cfbd.evidence.filter(row=>row.teamId===null||ids.has(row.teamId)).map(row=>({...row,forecastAt:capturedAt}))],diagnostics=completeForwardDiagnostics([...context.diagnostics,...state.cfbd.diagnostics.filter(row=>row.teamId===null||ids.has(row.teamId)).map(row=>({...row,forecastAt:capturedAt}))],teams,capturedAt),failures=state.cfbd.failures.filter(row=>row.canonicalEventId===game.canonicalEventId||row.teamId!==null&&ids.has(row.teamId)).map(row=>({...row,failedAt:Date.parse(row.failedAt)>Date.parse(capturedAt)?capturedAt:row.failedAt})),market=this.market(game,state,capturedAt);if(state.marketFailure)failures.push({provider:'The Odds API',requestCategory:'EXTERNAL_MARKET_BENCHMARK',canonicalEventId:game.canonicalEventId,teamId:null,failedAt:capturedAt,errorClass:'SOURCE_DOWN',attempts:1,retryState:'NOT_RETRIED',finalAvailability:'UNAVAILABLE',message:state.marketFailure});const modelA=state.modelForecasts.get(game.canonicalEventId)??{status:'MODEL_UNAVAILABLE',forecastAt:capturedAt,modelVersion:'college-score-ridge-v1',dataVersion:'unavailable',homeScore:null,awayScore:null,homeMargin:null,historyHash:null};
    return{schemaVersion:COLLEGE_FORWARD_RESEARCH_VERSION,partition:'FORWARD_VALIDATION_2026',window:'ACTUAL_PREKICK',capturedAt,forecastAt:capturedAt,identity:{canonicalEventId:game.canonicalEventId,providerEventIds:{ESPN:game.canonicalEventId,...(payload.provider?{ODDS_API:payload.provider.id}:{})},season:2026,week:Number.isInteger(payload.event?.week?.number)?payload.event.week.number:null,kickoff:game.latestVerifiedKickoff!,home:{canonicalId:String(payload.home.team.id),name:String(payload.home.team.displayName??payload.home.team.name),subdivision:game.homeSubdivision,conference:safeConference(payload.home.team)},away:{canonicalId:String(payload.away.team.id),name:String(payload.away.team.displayName??payload.away.team.name),subdivision:game.awaySubdivision,conference:safeConference(payload.away.team)},neutralSite:payload.competition.neutralSite===true,conferenceGame:typeof payload.competition.conferenceCompetition==='boolean'?payload.competition.conferenceCompetition:null,venue:{id:payload.competition.venue?.id?String(payload.competition.venue.id):null,name:payload.competition.venue?.fullName??null,indoor:typeof payload.competition.venue?.indoor==='boolean'?payload.competition.venue.indoor:null}},applicationRelease:PAPER_APPLICATION_RELEASE,featureSchemaVersion:COLLEGE_CONTEXT_EVIDENCE_VERSION,modelA:{...modelA,forecastAt:modelA.forecastAt>capturedAt?capturedAt:modelA.forecastAt},shadowModels:[],footballEvidence,diagnostics,failures,market};}
  private teams(games:ForwardDiscoveredGame[]):ForwardTeamSeed[]{const rows:ForwardTeamSeed[]=[];for(const game of games){const payload=game.payload as RuntimeGamePayload;for(const [side,team,division]of [['home',payload.home,game.homeSubdivision],['away',payload.away,game.awaySubdivision]] as const)rows.push({canonicalId:String(team.team.id),name:String(team.team.displayName??team.team.name),subdivision:division,conference:safeConference(team.team),aliases:[team.team.shortDisplayName,team.team.location,team.team.abbreviation].filter(Boolean),eventId:game.canonicalEventId});}return[...new Map(rows.map(row=>[`${row.eventId}:${row.canonicalId}`,row])).values()];}
  private primeCfbdCache(cache:BoundedForwardSourceCache){const dir=path.join(this.root,'college_forward_research','v1','raw');if(!fs.existsSync(dir))return;for(const file of fs.readdirSync(dir).filter(name=>name.endsWith('.json'))){try{const row=JSON.parse(fs.readFileSync(path.join(dir,file),'utf8'));if(row.provider!=='CollegeFootballData')continue;const key=String(row.url).includes('/ratings/core')?'core':String(row.url).includes('classification=fbs')?'fbsGames':String(row.url).includes('/games?')?'fcsGames':String(row.url).includes('/ratings/srs/expanded')?'fcsSrs':null;if(key)cache.prime(key,row.payload,row.retrievedAt);}catch{}}}
  private market(game:ForwardDiscoveredGame,state:RuntimeState,forecastAt:string):ForwardMarketEvidence|null{const payload=game.payload as RuntimeGamePayload,event=state.rawOdds.find(row=>row.id===payload.provider?.id);if(!event||!state.marketRetrievedAt)return null;const quotes=flattenNflQuotes(event,['spreads'],Date.parse(forecastAt)).filter(row=>!row.stale&&row.line!==null&&row.updatedAt&&Date.parse(row.updatedAt)<=Date.parse(forecastAt)),pairs=[] as Array<{home:any;away:any}>;for(const home of quotes.filter(row=>row.side===event.home_team))for(const away of quotes.filter(row=>row.side===event.away_team))if(home.bookKey===away.bookKey&&Math.abs(Number(home.line)+Number(away.line))<1e-9)pairs.push({home,away});const pair=pairs.sort((a,b)=>a.home.bookKey.localeCompare(b.home.bookKey)||String(b.home.updatedAt).localeCompare(String(a.home.updatedAt)))[0];if(!pair)return null;return{namespace:'EXTERNAL_MARKET_BENCHMARK',sportsbook:pair.home.book,market:'spreads',homeSpread:Number(pair.home.line),homePrice:pair.home.price,awaySpread:Number(pair.away.line),awayPrice:pair.away.price,quoteTimestamp:String(pair.home.updatedAt),retrievedAt:state.marketRetrievedAt,providerEventId:event.id,rawPayloadHash:sha(event),acquisition:'NETWORK',requestAttempts:1};}
  private async modelA(games:ForwardDiscoveredGame[]){const forecasts=new Map<string,ModelAForwardForecast>(),asOf=new Date(this.now()).toISOString();try{const bundle=loadCollegeModelBundle(),season=nflSeason(asOf),sources=[] as any[];for(const group of [80,81]){const url=`${ESPN_COLLEGE}/scoreboard?dates=${season}0801-${toDay(this.now())}&groups=${group}&limit=1000`,data=await this.get(url);sources.push({url,data});}const parsed=sources.map(row=>parseCollegeResults(row.data,season).games),history=mergeCollegeResults([bundle.payload.history,...parsed]),model=fitCollegeScores(history,Date.parse(asOf),bundle.payload.config),historyHash=sha({bundle:bundle.sha256,sources:sources.map(row=>({url:row.url,hash:sha(row.data)}))});for(const game of games){const payload=game.payload as RuntimeGamePayload,prediction=model.predict(String(payload.home.team.id),String(payload.away.team.id),payload.competition.neutralSite===true);forecasts.set(game.canonicalEventId,prediction?{status:'PROJECTED',forecastAt:asOf,modelVersion:bundle.payload.version,dataVersion:bundle.sha256,homeScore:prediction.homeScore,awayScore:prediction.awayScore,homeMargin:prediction.homeMargin,historyHash}:{status:'MODEL_UNAVAILABLE',forecastAt:asOf,modelVersion:bundle.payload.version,dataVersion:bundle.sha256,homeScore:null,awayScore:null,homeMargin:null,historyHash});}return{forecasts,failure:null,requests:2};}catch(error){return{forecasts,failure:String(error instanceof Error?error.message:error),requests:2};}}
}
