import * as fs from 'fs';
import * as path from 'path';
import {createHash,randomUUID} from 'crypto';
import {stableStringify} from './collegeEdgeResearch';
import {NFL_FORWARD_POLICY,NflEvidenceClass,NflForwardTrigger} from '../config/nflForwardPolicy';
import {GameDayAvailabilityState} from './nflGameDayAvailability';
import type {NflOpportunityProjection} from './nflOpportunityEngine';
import {detectNflFeatureChanges,NflCaptureWindow,NflCriticalFeatureHealth,NflFeatureChangeEvent,NflFeatureCoverageRow,NflForwardFeatureRecord,NflForwardTargetRecord,validateNflForwardFeature,validateNflTargetRecord} from './nflForwardFeatures';

export const NFL_FORWARD_RESEARCH_VERSION='nfl-forward-research-v1';
export type NflStage='PASS'|'PARTIAL'|'FAIL'|'UNKNOWN';
export type NflScheduleState='SCHEDULED'|'POSTPONED'|'CANCELED'|'ABANDONED'|'IN_PROGRESS'|'FINAL'|'UNKNOWN';
export type NflTeamCategory='SCHEDULE'|'ROSTER'|'STARTING_QB'|'QB_AVAILABILITY'|'INJURIES'|'OFFENSIVE_LINE'|'OFFENSIVE_EFFICIENCY'|'DEFENSIVE_EFFICIENCY'|'RUSH_EFFICIENCY'|'PASS_EFFICIENCY'|'PACE_PLAY_VOLUME'|'COACHING_PLAY_CALLER'|'WEATHER'|'VENUE'|'CURRENT_SEASON_SAMPLE';
export type NflPlayerCategory='PLAYER_IDENTITY'|'ACTIVE_ROSTER'|'DEPTH_CHART_POSITION'|'STARTER_STATUS'|'INJURY_STATUS'|'GAME_DAY_AVAILABILITY'|'SNAP_SHARE'|'ROUTE_PARTICIPATION'|'TARGET_SHARE'|'CARRY_SHARE'|'GOAL_LINE_USAGE'|'RED_ZONE_USAGE'|'QB_RELATIONSHIP'|'TEAM_ROLE'|'RECENT_OPPORTUNITY'|'OPPONENT'|'MARKET_AVAILABILITY';
export const NFL_TEAM_CATEGORIES:NflTeamCategory[]=['SCHEDULE','ROSTER','STARTING_QB','QB_AVAILABILITY','INJURIES','OFFENSIVE_LINE','OFFENSIVE_EFFICIENCY','DEFENSIVE_EFFICIENCY','RUSH_EFFICIENCY','PASS_EFFICIENCY','PACE_PLAY_VOLUME','COACHING_PLAY_CALLER','WEATHER','VENUE','CURRENT_SEASON_SAMPLE'];
export const NFL_PLAYER_CATEGORIES:NflPlayerCategory[]=['PLAYER_IDENTITY','ACTIVE_ROSTER','DEPTH_CHART_POSITION','STARTER_STATUS','INJURY_STATUS','GAME_DAY_AVAILABILITY','SNAP_SHARE','ROUTE_PARTICIPATION','TARGET_SHARE','CARRY_SHARE','GOAL_LINE_USAGE','RED_ZONE_USAGE','QB_RELATIONSHIP','TEAM_ROLE','RECENT_OPPORTUNITY','OPPONENT','MARKET_AVAILABILITY'];
export interface SixStageDiagnostic {scope:'GAME'|'TEAM'|'PLAYER';category:NflTeamCategory|NflPlayerCategory;entityId:string;forecastAt:string;stages:{SOURCE_RETRIEVAL:NflStage;NORMALIZATION:NflStage;ENTITY_MATCHING:NflStage;CONTEXT_ATTACHMENT:NflStage;FIELD_VALIDITY:NflStage;FRESHNESS_AT_FORECAST_TIME:NflStage};availableFields:number;requiredFields:number;notes:string[];}
export interface CanonicalNflTeam {canonicalTeamId:string;name:string;abbreviation:string|null;}
export interface CanonicalNflGame {canonicalGameId:string;providerGameIds:Record<string,string>;season:2026;seasonType:'PRE'|'REG'|'POST'|'UNKNOWN';week:number|null;away:CanonicalNflTeam;home:CanonicalNflTeam;scheduledKickoff:string;venue:{id:string|null;name:string|null;indoor:boolean|null};neutralSite:boolean;international:boolean;status:NflScheduleState;}
export interface CanonicalNflPlayer {canonicalPlayerId:string;providerPlayerIds:Record<string,string>;name:string;teamId:string;position:string;season:2026;effectiveAt:string;rookie:'YES'|'NO'|'UNKNOWN';newTeam:'YES'|'NO'|'UNKNOWN';teamChange:'CHANGED'|'UNCHANGED'|'UNKNOWN';positionChange:'CHANGED'|'UNCHANGED'|'UNKNOWN';}
export interface NflForwardSource {provider:string;url:string;providerRecordId:string|null;retrievedAt:string;effectiveAt:string|null;rawPayloadHash:string;}
export interface NflFootballEvidence {scope:'TEAM'|'PLAYER';entityId:string;category:NflTeamCategory|NflPlayerCategory;field:string;value:unknown;source:NflForwardSource;validity:'VALID'|'INVALID'|'UNKNOWN';freshness:'FRESH'|'STALE'|'UNKNOWN';}
export interface NflMarketQuoteEvidence {kind:'GAME'|'PROP';canonicalGameId:string;canonicalPlayerId:string|null;market:string;participant:string|null;side:string;line:number|null;price:number;sportsbook:string;providerEventId:string;quoteTimestamp:string;captureTimestamp:string;rawPayloadHash:string;label:'CONTEMPORANEOUS_QUOTE'|'LAST_VERIFIED_PREGAME_QUOTE';}
export interface NflPropUniverseRow {market:string;participant:string;state:'PROP_MARKET_AVAILABLE'|'PROP_NOT_POSTED'|'MARKET_UNAVAILABLE'|'PLAYER_IDENTITY_UNRESOLVED';canonicalPlayerId:string|null;modelState:'MODEL_AVAILABLE'|'MODEL_UNAVAILABLE';researchState:'RESEARCH_ELIGIBLE'|'RESEARCH_INELIGIBLE';recommendationState:'NOT_EVALUATED_PHASE_2';availability:GameDayAvailabilityState;projection:number|null;projectionVersion:string|null;}
export interface NflApiUsage {provider:string;requests:number;estimatedCredits:number;actualCredits:number|null;cacheHits:number;retries:number;failures:number;deferred:string[];}
export interface NewNflForwardSnapshot {schemaVersion:typeof NFL_FORWARD_RESEARCH_VERSION;evidenceClass:NflEvidenceClass;capturedAt:string;forecastAt:string;trigger:NflForwardTrigger;captureEventId:string;scheduledFor:string|null;minutesToKickoff:number;hoursToKickoff:number;captureWindow?:Exclude<NflCaptureWindow,'LAST_VERIFIED_PREGAME'>;game:CanonicalNflGame;players:CanonicalNflPlayer[];footballEvidence:NflFootballEvidence[];featureRecords?:NflForwardFeatureRecord[];featureEvents?:NflFeatureChangeEvent[];featureCoverage?:NflFeatureCoverageRow[];criticalFeatureHealth?:NflCriticalFeatureHealth;diagnostics:SixStageDiagnostic[];inactiveEvidence:{state:'COMPLETE_GAME_LISTS'|'SEASON_PENDING'|'MALFORMED_OR_UNVERIFIED';source:NflForwardSource;players:Array<{canonicalPlayerId:string;state:GameDayAvailabilityState;reason:string}>};gameMarkets:NflMarketQuoteEvidence[];propMarkets:NflMarketQuoteEvidence[];propUniverse:NflPropUniverseRow[];opportunityProjections?:NflOpportunityProjection[];model:{gameProjection:{status:'PROJECTED'|'MODEL_UNAVAILABLE';homeScore:number|null;awayScore:number|null;homeMargin:number|null;version:string}|null};apiUsage:NflApiUsage[];failures:Array<{provider:string;category:string;message:string;at:string}>;}
export interface NflForwardSnapshot extends NewNflForwardSnapshot {snapshotId:string;componentHashes:Record<string,string[]>;}
interface Index {schema:1;version:typeof NFL_FORWARD_RESEARCH_VERSION;snapshots:Array<{id:string;gameId:string;capturedAt:string;captureEventId:string}>;records:Array<{kind:string;id:string;recordedAt:string}>;}
export interface NflForwardArchiveRecord {id:string;kind:string;recordedAt:string;[key:string]:unknown;}
const sha=(value:unknown)=>createHash('sha256').update(stableStringify(value)).digest('hex');
const stamp=(value:string,label:string)=>{const n=Date.parse(value);if(!Number.isFinite(n))throw Error(`Invalid ${label} timestamp.`);return n;};
const safe=(value:string,label:string)=>{if(!/^[A-Za-z0-9._:-]{1,180}$/.test(value))throw Error(`Invalid ${label}.`);return value;};
const validHash=(value:string)=>/^[a-f0-9]{64}$/.test(value);
const authority=(root:string)=>path.join(root,'nfl_forward_research','v1');
const contentFile=(root:string,kind:string,id:string)=>path.join(authority(root),kind,safe(id,`${kind} ID`)+'.json');
const empty=():Index=>({schema:1,version:NFL_FORWARD_RESEARCH_VERSION,snapshots:[],records:[]});
function loadIndex(root:string):Index{const file=path.join(authority(root),'index.json');if(!fs.existsSync(file))return empty();const row=JSON.parse(fs.readFileSync(file,'utf8'));if(row?.schema!==1||row?.version!==NFL_FORWARD_RESEARCH_VERSION||!Array.isArray(row.snapshots)||!Array.isArray(row.records))throw Error('Invalid NFL forward index.');return row;}
function saveIndex(root:string,index:Index){const dir=authority(root);fs.mkdirSync(dir,{recursive:true});const target=path.join(dir,'index.json'),tmp=path.join(dir,randomUUID()+'.tmp');fs.writeFileSync(tmp,JSON.stringify(index,null,2),{flag:'wx'});fs.renameSync(tmp,target);}
function writeImmutable(file:string,value:unknown){const body=JSON.stringify(value,null,2);fs.mkdirSync(path.dirname(file),{recursive:true});try{fs.writeFileSync(file,body,{flag:'wx'});return true;}catch(error:any){if(error?.code==='EEXIST'&&fs.readFileSync(file,'utf8')===body)return false;throw Error(`Immutable archive collision at ${file}.`);}}
function component(root:string,kind:string,value:unknown){const id=sha(value);writeImmutable(contentFile(root,`objects/${kind}`,id),{id,kind,value});return id;}
const forbidden=/(^|[._ -])(spread|total|moneyline|sportsbook|consensus|implied.?probability|prop.?line|line.?movement)([._ -]|$)/i;

export function validateNflForwardSnapshot(input:NewNflForwardSnapshot){const forecast=stamp(input.forecastAt,'forecast'),capture=stamp(input.capturedAt,'capture'),kickoff=stamp(input.game.scheduledKickoff,'kickoff'),cutoff=Date.parse(NFL_FORWARD_POLICY.protectedCutoff);
  if(input.schemaVersion!==NFL_FORWARD_RESEARCH_VERSION||input.game.season!==NFL_FORWARD_POLICY.season)throw Error('Invalid NFL forward schema/season.');
  if(input.evidenceClass!=='LIVE_FORWARD')throw Error('Only LIVE_FORWARD may enter the protected forward snapshot archive.');
  if(capture<cutoff||forecast>capture||capture>=kickoff)throw Error('Protected cutoff or post-kickoff leakage violation.');
  if(input.game.status!=='SCHEDULED')throw Error('Only scheduled pregame events may be captured.');
  safe(input.game.canonicalGameId,'canonical game ID');safe(input.game.home.canonicalTeamId,'home team ID');safe(input.game.away.canonicalTeamId,'away team ID');if(input.game.home.canonicalTeamId===input.game.away.canonicalTeamId)throw Error('Duplicate game team identity.');
  if(!Number.isFinite(input.minutesToKickoff)||Math.abs(input.minutesToKickoff-(kickoff-capture)/60_000)>1e-6||Math.abs(input.hoursToKickoff-input.minutesToKickoff/60)>1e-6)throw Error('Actual snapshot timing is inconsistent.');
  const playerIds=new Set<string>();for(const player of input.players){safe(player.canonicalPlayerId,'player ID');if(playerIds.has(player.canonicalPlayerId))throw Error('Duplicate canonical player identity.');playerIds.add(player.canonicalPlayerId);if(player.season!==2026||![input.game.home.canonicalTeamId,input.game.away.canonicalTeamId].includes(player.teamId)||stamp(player.effectiveAt,'player effective')>forecast)throw Error('Invalid or future player identity.');}
  for(const evidence of input.footballEvidence){if(forbidden.test(evidence.field)||forbidden.test(evidence.category)||forbidden.test(evidence.source.provider))throw Error('MARKET_CONTAMINATION_VIOLATION');if(stamp(evidence.source.retrievedAt,'evidence retrieval')>forecast||evidence.source.effectiveAt&&stamp(evidence.source.effectiveAt,'evidence effective')>forecast)throw Error('LEAKAGE_VIOLATION');if(!validHash(evidence.source.rawPayloadHash))throw Error('Invalid evidence hash.');}
  for(const evidence of input.featureRecords??[]){validateNflForwardFeature(evidence);if(evidence.gameId!==input.game.canonicalGameId||evidence.forecastTimestamp!==input.forecastAt||evidence.captureTimestamp!==input.capturedAt||evidence.kickoffTimestamp!==input.game.scheduledKickoff)throw Error('Invalid feature context attachment.');if(evidence.teamId&&!([input.game.home.canonicalTeamId,input.game.away.canonicalTeamId].includes(evidence.teamId))||evidence.playerId&&!playerIds.has(evidence.playerId))throw Error('Invalid feature entity matching.');}
  for(const event of input.featureEvents??[]){if(event.gameId!==input.game.canonicalGameId||stamp(event.capturedAt,'feature event')!==capture||event.currentRecordId&&!validHash(event.currentRecordId)||event.previousRecordId&&!validHash(event.previousRecordId))throw Error('Invalid immutable feature change event.');}
  if(input.captureWindow&&input.featureRecords?.some(row=>row.captureWindow!==input.captureWindow))throw Error('Inconsistent actual capture window.');
  for(const diagnostic of input.diagnostics){if(diagnostic.forecastAt!==input.forecastAt||diagnostic.availableFields<0||diagnostic.availableFields>diagnostic.requiredFields)throw Error('Invalid six-stage diagnostic.');for(const state of Object.values(diagnostic.stages))if(!['PASS','PARTIAL','FAIL','UNKNOWN'].includes(state))throw Error('Invalid diagnostic state.');}
  for(const team of [input.game.home,input.game.away])for(const category of NFL_TEAM_CATEGORIES)if(!input.diagnostics.some(row=>row.scope==='TEAM'&&row.entityId===team.canonicalTeamId&&row.category===category))throw Error(`Missing team diagnostic ${category}/${team.canonicalTeamId}.`);
  for(const player of input.players)for(const category of NFL_PLAYER_CATEGORIES)if(!input.diagnostics.some(row=>row.scope==='PLAYER'&&row.entityId===player.canonicalPlayerId&&row.category===category))throw Error(`Missing player diagnostic ${category}/${player.canonicalPlayerId}.`);
  for(const quote of [...input.gameMarkets,...input.propMarkets]){if(quote.canonicalGameId!==input.game.canonicalGameId||stamp(quote.quoteTimestamp,'quote')>forecast||stamp(quote.captureTimestamp,'market capture')!==capture||!validHash(quote.rawPayloadHash)||!Number.isFinite(quote.price)||quote.kind==='PROP'&&(!quote.canonicalPlayerId||!playerIds.has(quote.canonicalPlayerId)))throw Error('Invalid, mismatched, or future market evidence.');}
  for(const row of input.propUniverse)if(row.state==='PROP_MARKET_AVAILABLE'&&!row.canonicalPlayerId||row.canonicalPlayerId&&!playerIds.has(row.canonicalPlayerId))throw Error('Invalid prop universe identity state.');
  for(const row of input.opportunityProjections??[]){if(row.researchOnly!==true||row.productionEnabled!==false||row.marketInputsUsed!==false||row.canonicalGameId!==input.game.canonicalGameId||!playerIds.has(row.canonicalPlayerId)||row.forecastAt!==input.forecastAt||stamp(row.modelTimestamp,'opportunity model')>forecast||row.featureTimestamp!==null&&stamp(row.featureTimestamp,'opportunity feature')>=forecast)throw Error('Invalid or future shadow opportunity projection.');const numeric=[row.expectedTeamPassAttempts,row.expectedTeamRushAttempts,row.expectedPassAttempts,row.expectedCompletionsOpportunities,row.expectedDesignedRushes,row.expectedScrambleOpportunities,row.expectedCarries,row.expectedRoutes,row.expectedTargets,row.expectedGoalLineOpportunities,row.targetShare,row.carryShare,row.routeParticipation,row.snapShare,row.roleVolatility];if(numeric.some(value=>value!==null&&(!Number.isFinite(value)||value<0)))throw Error('Invalid shadow opportunity metric.');}
  if(stamp(input.inactiveEvidence.source.retrievedAt,'inactive retrieval')>forecast||!validHash(input.inactiveEvidence.source.rawPayloadHash))throw Error('Invalid inactive evidence.');
  return{contentHash:sha(input)};
}

export class NflForwardArchive {
  constructor(private root:string){}
  capture(input:NewNflForwardSnapshot){const index=loadIndex(this.root),previousMeta=[...index.snapshots].filter(row=>row.gameId===input.game.canonicalGameId&&row.capturedAt<input.capturedAt).sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt))[0],previous=previousMeta?JSON.parse(fs.readFileSync(contentFile(this.root,'snapshots',previousMeta.id),'utf8')) as NflForwardSnapshot:null,enriched:NewNflForwardSnapshot=input.featureRecords?{...input,featureEvents:[...(input.featureEvents??[]),...detectNflFeatureChanges(previous?.featureRecords??[],input.featureRecords,input.capturedAt)].filter((row,index,all)=>all.findIndex(item=>item.eventId===row.eventId)===index).sort((a,b)=>a.eventId.localeCompare(b.eventId))}:input,{contentHash:snapshotId}=validateNflForwardSnapshot(enriched),same=index.snapshots.find(row=>row.captureEventId===input.captureEventId&&row.gameId===input.game.canonicalGameId);if(same&&same.id!==snapshotId)return{snapshotId:same.id,created:false,status:'RETRY_DUPLICATE' as const};
    // Each category is a separate content-addressed object, while its rows are
    // bundled deterministically. This preserves separation without creating a
    // repository file for every sportsbook outcome on every scheduled run.
    const componentHashes={gameIdentity:[component(this.root,'game_identity',enriched.game)],playerIdentity:enriched.players.length?[component(this.root,'player_identity',enriched.players)]:[],model:[component(this.root,'model_projection',enriched.model)],teamPlayerContext:enriched.footballEvidence.length?[component(this.root,'context',enriched.footballEvidence)]:[],...(enriched.featureRecords?{forwardFeatures:enriched.featureRecords.length?[component(this.root,'forward_feature',enriched.featureRecords)]:[],featureEvents:(enriched.featureEvents??[]).length?[component(this.root,'feature_event',enriched.featureEvents)]:[],featureCoverage:enriched.featureCoverage?[component(this.root,'feature_coverage',enriched.featureCoverage)]:[],criticalFeatureHealth:enriched.criticalFeatureHealth?[component(this.root,'critical_feature_health',enriched.criticalFeatureHealth)]:[]}:{}),inactive:[component(this.root,'inactive_evidence',enriched.inactiveEvidence)],diagnostics:enriched.diagnostics.length?[component(this.root,'diagnostic',enriched.diagnostics)]:[],gameMarkets:enriched.gameMarkets.length?[component(this.root,'game_market',enriched.gameMarkets)]:[],propMarkets:enriched.propMarkets.length?[component(this.root,'prop_market',enriched.propMarkets)]:[],...(enriched.opportunityProjections?{opportunity:enriched.opportunityProjections.length?[component(this.root,'opportunity_projection',enriched.opportunityProjections)]:[]}:{}),failures:enriched.failures.length?[component(this.root,'failure',enriched.failures)]:[]};
    const snapshot:NflForwardSnapshot={snapshotId,...structuredClone(enriched),componentHashes},created=writeImmutable(contentFile(this.root,'snapshots',snapshotId),snapshot);if(!index.snapshots.some(row=>row.id===snapshotId)){index.snapshots.push({id:snapshotId,gameId:enriched.game.canonicalGameId,capturedAt:enriched.capturedAt,captureEventId:enriched.captureEventId});index.snapshots.sort((a,b)=>a.capturedAt.localeCompare(b.capturedAt)||a.id.localeCompare(b.id));saveIndex(this.root,index);}return{snapshotId,created,status:created?'NEW_POINT_IN_TIME_SNAPSHOT' as const:'RETRY_DUPLICATE' as const};}
  append(kind:'schedule_changes'|'corrections'|'final_results'|'player_final_stats'|'forward_targets'|'settlement_evidence'|'failures',value:{recordedAt:string;[key:string]:unknown}){stamp(value.recordedAt,'record');const id=sha({kind,value}),created=writeImmutable(contentFile(this.root,kind,id),{id,kind,...structuredClone(value)}),index=loadIndex(this.root);if(!index.records.some(row=>row.id===id)){index.records.push({kind,id,recordedAt:value.recordedAt});index.records.sort((a,b)=>a.recordedAt.localeCompare(b.recordedAt)||a.id.localeCompare(b.id));saveIndex(this.root,index);}return{id,created};}
  appendTarget(input:Omit<NflForwardTargetRecord,'targetId'>){const target=validateNflTargetRecord(input);return{target,...this.append('forward_targets',{recordedAt:target.recordedAt,target})};}
  load(){const index=loadIndex(this.root),snapshots=index.snapshots.map(row=>JSON.parse(fs.readFileSync(contentFile(this.root,'snapshots',row.id),'utf8')) as NflForwardSnapshot);return{index,snapshots};}
  loadRecords():NflForwardArchiveRecord[]{const index=loadIndex(this.root);return index.records.map(meta=>{const file=contentFile(this.root,meta.kind,meta.id);if(!fs.existsSync(file))throw Error(`Missing append-only record: ${meta.id}`);const row=JSON.parse(fs.readFileSync(file,'utf8')) as NflForwardArchiveRecord,body={...row};delete body.id;delete body.kind;if(row.id!==meta.id||row.kind!==meta.kind||row.recordedAt!==meta.recordedAt||sha({kind:row.kind,value:body})!==row.id)throw Error(`Append-only record hash mismatch: ${meta.id}`);return row;});}
  verify(){const data=this.load(),kinds:Record<string,string>={gameIdentity:'game_identity',playerIdentity:'player_identity',model:'model_projection',teamPlayerContext:'context',forwardFeatures:'forward_feature',featureEvents:'feature_event',featureCoverage:'feature_coverage',criticalFeatureHealth:'critical_feature_health',inactive:'inactive_evidence',diagnostics:'diagnostic',gameMarkets:'game_market',propMarkets:'prop_market',opportunity:'opportunity_projection',failures:'failure'};for(const row of data.snapshots){const body={...row};delete body.snapshotId;delete body.componentHashes;if(sha(body)!==row.snapshotId)throw Error(`Snapshot hash mismatch: ${row.snapshotId}`);for(const [label,ids] of Object.entries(row.componentHashes))for(const id of ids){if(!validHash(id)||!kinds[label])throw Error('Invalid component hash.');const file=contentFile(this.root,`objects/${kinds[label]}`,id);if(!fs.existsSync(file))throw Error(`Missing component object: ${id}`);const object=JSON.parse(fs.readFileSync(file,'utf8'));if(object.id!==id||object.kind!==kinds[label]||sha(object.value)!==id)throw Error(`Component hash mismatch: ${id}`);}}
    this.loadRecords();
    return{durableRoot:path.resolve(this.root),snapshots:data.snapshots.length,records:data.index.records.length,status:'PASS' as const};}
  export(createdAt:string){stamp(createdAt,'export');const data=this.load(),records=[...data.snapshots.map(value=>({kind:'SNAPSHOT',value})),...data.index.records].sort((a,b)=>stableStringify(a).localeCompare(stableStringify(b))),datasetHash=sha(records);return{schemaVersion:'nfl-forward-export-v1',createdAt,datasetHash,counts:{snapshots:data.snapshots.length,records:data.index.records.length},records};}
}

export function makeDiagnostic(scope:SixStageDiagnostic['scope'],category:SixStageDiagnostic['category'],entityId:string,forecastAt:string,availableFields:number,requiredFields:number,stages:Partial<SixStageDiagnostic['stages']>={},notes:string[]=[]):SixStageDiagnostic{const fallback:NflStage=availableFields===requiredFields&&requiredFields>0?'PASS':availableFields>0?'PARTIAL':'UNKNOWN';return{scope,category,entityId,forecastAt,availableFields,requiredFields,notes,stages:{SOURCE_RETRIEVAL:stages.SOURCE_RETRIEVAL??fallback,NORMALIZATION:stages.NORMALIZATION??fallback,ENTITY_MATCHING:stages.ENTITY_MATCHING??fallback,CONTEXT_ATTACHMENT:stages.CONTEXT_ATTACHMENT??fallback,FIELD_VALIDITY:stages.FIELD_VALIDITY??fallback,FRESHNESS_AT_FORECAST_TIME:stages.FRESHNESS_AT_FORECAST_TIME??fallback}};}

export function inactiveCoverage(snapshots:NflForwardSnapshot[]){const latest=new Map<string,{state:GameDayAvailabilityState}>();for(const snapshot of [...snapshots].sort((a,b)=>a.capturedAt.localeCompare(b.capturedAt)))for(const row of snapshot.inactiveEvidence.players)latest.set(`${snapshot.game.canonicalGameId}:${row.canonicalPlayerId}`,row);const rows=[...latest.values()],count=(state:GameDayAvailabilityState)=>rows.filter(row=>row.state===state).length,verified=count('ACTIVE_VERIFIED')+count('INACTIVE_VERIFIED');return{eligiblePropPlayers:rows.length,verifiedActive:count('ACTIVE_VERIFIED'),verifiedInactive:count('INACTIVE_VERIFIED'),pending:count('STATUS_PENDING'),unknown:count('STATUS_UNKNOWN'),verifiedParticipationPercent:rows.length?Number((verified/rows.length*100).toFixed(1)):null};}

// This is intentionally not named a closing line. It selects only the latest
// quote the bounded 7 AM / 2 PM / manual protocol actually observed before
// kickoff; no polling or reconstructed market is implied.
export function boundedLastVerifiedPregameQuotes(snapshots:NflForwardSnapshot[]){const latest=new Map<string,NflMarketQuoteEvidence>();for(const snapshot of snapshots)for(const quote of [...snapshot.gameMarkets,...snapshot.propMarkets]){if(Date.parse(quote.quoteTimestamp)>=Date.parse(snapshot.game.scheduledKickoff))continue;const key=[quote.canonicalGameId,quote.kind,quote.canonicalPlayerId??'',quote.market,quote.participant??'',quote.side,quote.sportsbook].join('|'),old=latest.get(key);if(!old||Date.parse(quote.quoteTimestamp)>Date.parse(old.quoteTimestamp))latest.set(key,{...quote,label:'LAST_VERIFIED_PREGAME_QUOTE'});}return[...latest.values()].sort((a,b)=>a.canonicalGameId.localeCompare(b.canonicalGameId)||a.market.localeCompare(b.market)||a.side.localeCompare(b.side)||a.sportsbook.localeCompare(b.sportsbook));}
