import * as fs from 'fs';
import * as path from 'path';
import {createHash,randomUUID} from 'crypto';
import {NFL_FORWARD_POLICY,NflForwardTrigger} from '../config/nflForwardPolicy';
import {inactiveCoverage,NewNflForwardSnapshot,NflForwardArchive,NflScheduleState} from './nflForwardResearch';
import {NFL_FEATURE_SCORECARD_CATEGORIES,NflFeatureCoverageRow,NflFeatureStageState} from './nflForwardFeatures';

export type NflRunStatus='SUCCESS'|'DEGRADED'|'FAILED'|'DRY_RUN';
export type NflHealth='HEALTHY'|'DEGRADED'|'STALE'|'FAILED'|'NOT_CONFIGURED';
export interface NflDiscoveredGame {gameId:string;kickoff:string;status:NflScheduleState;missingIdentity:number;payload:unknown;}
export interface NflRequestPlan {provider:string;category:string;maximumRequests:number;estimatedCredits:number;priority:number;scope:string;}
export interface NflPreparedRun {state:unknown;apiUsage:Array<{provider:string;requests:number;estimatedCredits:number;actualCredits:number|null;cacheHits:number;retries:number;failures:number;deferred:string[]}>;failures:string[];deferred:string[];}
export interface NflCollectorAdapter {discover(at:string):Promise<{games:NflDiscoveredGame[];requests:number;failures:string[]}>;plan(games:NflDiscoveredGame[],at:string):NflRequestPlan[];prepare(games:NflDiscoveredGame[],at:string):Promise<NflPreparedRun>;capture(game:NflDiscoveredGame,prepared:NflPreparedRun,meta:{trigger:NflForwardTrigger;captureEventId:string;scheduledFor:string|null}):Promise<NewNflForwardSnapshot>;}
export interface NflManualCollectionSummary {gamesEligible:number;gamesCaptured:number;gamesSkipped:number;startedGamesSkipped:number;teamRecordsCaptured:number;playerRecordsCaptured:number;marketQuotes:number;propQuotes:number;qbRecords:number;injuryRecords:number;depthChartRecords:number;snapRecords:number;routeRecords:number;weatherRecords:number;apiRequests:number;estimatedPaidCredits:number;actualPaidCredits:number|null;cacheHits:number;retries:number;failures:number;deferredFeatures:string[];unavailableFeatures:string[];}
export interface NflOperationalRun {runId:string;captureEventId:string;trigger:NflForwardTrigger;startedAt:string;completedAt:string;scheduledFor:string|null;dryRun:boolean;status:NflRunStatus;eligibleGames:number;plannedRequests:NflRequestPlan[];observations:Array<{gameId:string;status:'CAPTURED'|'RETRY_DUPLICATE'|'WOULD_CAPTURE'|'SKIPPED_STARTED'|'SKIPPED_STATUS'|'FAILED';snapshotId:string|null;message:string}>;apiUsage:NflPreparedRun['apiUsage'];discoveryFailures:string[];providerFailures:string[];deferred:string[];summary:NflManualCollectionSummary;featureScorecard:NflFeatureCoverageRow[];}
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
function localParts(ms:number){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:NFL_FORWARD_POLICY.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(ms),get=(type:string)=>parts.find(row=>row.type===type)?.value??'';return{date:`${get('year')}-${get('month')}-${get('day')}`,hour:Number(get('hour')),minute:Number(get('minute'))};}
export function centralScheduledInstant(date:string,hour:7|14){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Invalid Central calendar date.');const center=Date.parse(`${date}T${String(hour).padStart(2,'0')}:00:00Z`);for(let ms=center-12*3600_000;ms<=center+12*3600_000;ms+=60_000){const p=localParts(ms);if(p.date===date&&p.hour===hour&&p.minute===0)return new Date(ms).toISOString();}throw Error('Central schedule could not be resolved.');}
export function nextNflCentralRun(now:number){const day=localParts(now).date;for(let offset=0;offset<4;offset++){const date=new Date(Date.parse(`${day}T12:00:00Z`)+offset*86400_000).toISOString().slice(0,10);for(const item of [{hour:7 as const,trigger:'SCHEDULED_0700_CT' as const},{hour:14 as const,trigger:'SCHEDULED_1400_CT' as const}]){const at=centralScheduledInstant(date,item.hour);if(Date.parse(at)>now)return{trigger:item.trigger,at};}}throw Error('Next NFL run unavailable.');}
export function nflCaptureEventId(trigger:NflForwardTrigger,now:number,key?:string){if(trigger==='MANUAL'){if(!key||key.length>160)throw Error('Manual collection requires a bounded idempotency key.');return`manual-${sha(key).slice(0,32)}`;}return`${localParts(now).date}-${trigger==='SCHEDULED_0700_CT'?'0700':'1400'}-ct`;}
export function nflScheduledFor(trigger:NflForwardTrigger,now:number){return trigger==='MANUAL'?null:centralScheduledInstant(localParts(now).date,trigger==='SCHEDULED_0700_CT'?7:14);}
const operationRoot=(root:string)=>path.join(root,'nfl_forward_research','v1','operations');
function writeRun(root:string,run:NflOperationalRun){const dir=operationRoot(root),target=path.join(dir,`${run.runId}.json`);fs.mkdirSync(dir,{recursive:true});try{fs.writeFileSync(target,JSON.stringify(run,null,2),{flag:'wx'});}catch(error:any){if(error?.code!=='EEXIST'||fs.readFileSync(target,'utf8')!==JSON.stringify(run,null,2))throw error;}}
export function loadNflRuns(root:string):NflOperationalRun[]{const dir=operationRoot(root);if(!fs.existsSync(dir))return[];return fs.readdirSync(dir).filter(name=>name.endsWith('.json')).map(name=>JSON.parse(fs.readFileSync(path.join(dir,name),'utf8'))).sort((a,b)=>a.startedAt.localeCompare(b.startedAt));}
function aggregateScorecards(rows:NflFeatureCoverageRow[][]):NflFeatureCoverageRow[]{return NFL_FEATURE_SCORECARD_CATEGORIES.map(category=>{const found=rows.flat().filter(row=>row.category===category),recordsExpected=found.reduce((n,row)=>n+row.recordsExpected,0),recordsObtained=found.reduce((n,row)=>n+row.recordsObtained,0),status:NflFeatureStageState=!found.length?'UNKNOWN':found.some(row=>row.status==='FAIL')?'FAIL':found.some(row=>row.status==='PARTIAL')?'PARTIAL':found.every(row=>row.status==='PASS')?'PASS':'UNKNOWN',stages=['SOURCE_RETRIEVAL','NORMALIZATION','ENTITY_MATCHING','CONTEXT_ATTACHMENT','FIELD_VALIDITY','FRESHNESS'] as const,integrity=Object.fromEntries(stages.map(stage=>{const values=found.map(row=>row.integrity[stage]);return[stage,values.includes('FAIL')?'FAIL':values.includes('PARTIAL')?'PARTIAL':values.length&&values.every(value=>value==='PASS')?'PASS':'UNKNOWN'];})) as unknown as NflFeatureCoverageRow['integrity'];return{category,status,recordsExpected,recordsObtained,coveragePercentage:recordsExpected?Number((recordsObtained/recordsExpected*100).toFixed(1)):null,integrity,notes:found.flatMap(row=>row.notes)};});}
function dryScorecard(eligible:number):NflFeatureCoverageRow[]{const zero={SOURCE_RETRIEVAL:'UNKNOWN' as const,NORMALIZATION:'UNKNOWN' as const,ENTITY_MATCHING:'UNKNOWN' as const,CONTEXT_ATTACHMENT:'UNKNOWN' as const,FIELD_VALIDITY:'UNKNOWN' as const,FRESHNESS:'UNKNOWN' as const};return NFL_FEATURE_SCORECARD_CATEGORIES.map(category=>({category,status:'UNKNOWN',recordsExpected:['WEATHER','MARKET'].includes(category)?eligible:['TEAM_VOLUME','PASS_RUN_TENDENCY','OFFENSIVE_EFFICIENCY','DEFENSIVE_EFFICIENCY','QB','REST','COACHING'].includes(category)?eligible*2:0,recordsObtained:0,coveragePercentage:null,integrity:zero,notes:['Dry run estimated source/request availability only; no feature record was fetched or written.']}));}
function manualSummary(input:{eligible:number;observations:NflOperationalRun['observations'];snapshots:any[];apiUsage:NflPreparedRun['apiUsage'];discoveryRequests:number;discoveryFailures:string[];providerFailures:string[];deferred:string[];planned:NflRequestPlan[];dryRun:boolean}):NflManualCollectionSummary{const features=input.snapshots.flatMap(row=>row.featureRecords??[]),count=(category:string)=>features.filter((row:any)=>row.category===category&&row.qualityState!=='UNAVAILABLE').length,actual=input.apiUsage.map(row=>row.actualCredits),estimatedPaidCredits=input.planned.reduce((n,row)=>n+row.estimatedCredits,0),actualPaidCredits=input.dryRun?0:actual.some(value=>value===null)?null:actual.reduce((n,value)=>n+(value??0),0),unavailableFeatures=input.dryRun?['ROUTES','RED_ZONE','OFFENSIVE_EFFICIENCY','DEFENSIVE_EFFICIENCY','COACHING']:[...new Set(input.snapshots.flatMap(row=>(row.featureCoverage??[]).filter((item:any)=>['FAIL','UNKNOWN'].includes(item.status)).map((item:any)=>String(item.category))))].sort();return{gamesEligible:input.eligible,gamesCaptured:input.observations.filter(row=>row.status==='CAPTURED').length,gamesSkipped:input.observations.filter(row=>['SKIPPED_STARTED','SKIPPED_STATUS'].includes(row.status)).length,startedGamesSkipped:input.observations.filter(row=>row.status==='SKIPPED_STARTED').length,teamRecordsCaptured:features.filter((row:any)=>row.teamId&&!row.playerId&&row.qualityState!=='UNAVAILABLE').length,playerRecordsCaptured:features.filter((row:any)=>row.playerId&&row.qualityState!=='UNAVAILABLE').length,marketQuotes:input.snapshots.reduce((n,row)=>n+(row.gameMarkets?.length??0),0),propQuotes:input.snapshots.reduce((n,row)=>n+(row.propMarkets?.length??0),0),qbRecords:count('QB'),injuryRecords:count('INJURIES'),depthChartRecords:count('DEPTH_CHART'),snapRecords:count('SNAPS'),routeRecords:count('ROUTES'),weatherRecords:count('WEATHER'),apiRequests:input.discoveryRequests+input.apiUsage.reduce((n,row)=>n+row.requests,0),estimatedPaidCredits,actualPaidCredits,cacheHits:input.apiUsage.reduce((n,row)=>n+row.cacheHits,0),retries:input.apiUsage.reduce((n,row)=>n+row.retries,0),failures:input.discoveryFailures.length+input.providerFailures.length+input.apiUsage.reduce((n,row)=>n+row.failures,0)+input.observations.filter(row=>row.status==='FAILED').length,deferredFeatures:[...new Set(input.deferred)].sort(),unavailableFeatures};}
export class NflForwardOperationalCollector {constructor(private root:string,private adapter:NflCollectorAdapter,private now=()=>Date.now()){}
  async run(options:{trigger:NflForwardTrigger;dryRun:boolean;idempotencyKey?:string}){const started=this.now(),startedAt=new Date(started).toISOString(),captureEventId=nflCaptureEventId(options.trigger,started,options.idempotencyKey),scheduledFor=nflScheduledFor(options.trigger,started),prior=loadNflRuns(this.root).find(row=>row.captureEventId===captureEventId&&!row.dryRun);if(prior&&!options.dryRun)return{...prior,retry:'RETRY_DUPLICATE' as const};
    const discovery=await this.adapter.discover(startedAt),games=discovery.games.sort((a,b)=>Date.parse(a.kickoff)-Date.parse(b.kickoff)||b.missingIdentity-a.missingIdentity||a.gameId.localeCompare(b.gameId)),plannedRequests=this.adapter.plan(games,startedAt),observations:NflOperationalRun['observations']=[];
    if(options.dryRun){for(const game of games)observations.push({gameId:game.gameId,status:game.status==='SCHEDULED'&&Date.parse(game.kickoff)>started?'WOULD_CAPTURE':'SKIPPED_STATUS',snapshotId:null,message:'Dry run; archive unchanged.'});const eligible=games.filter(game=>game.status==='SCHEDULED'&&Date.parse(game.kickoff)>started).length,summary=manualSummary({eligible,observations,snapshots:[],apiUsage:[],discoveryRequests:discovery.requests,discoveryFailures:discovery.failures,providerFailures:[],deferred:[],planned:plannedRequests,dryRun:true});return{runId:`dry-${randomUUID()}`,captureEventId,trigger:options.trigger,startedAt,completedAt:new Date(this.now()).toISOString(),scheduledFor,dryRun:true,status:'DRY_RUN' as const,eligibleGames:eligible,plannedRequests,observations,apiUsage:[],discoveryFailures:discovery.failures,providerFailures:[],deferred:[],summary,featureScorecard:dryScorecard(eligible)};}
    const eligible=games.filter(game=>{if(Date.parse(game.kickoff)<=started){observations.push({gameId:game.gameId,status:'SKIPPED_STARTED',snapshotId:null,message:'Kickoff has passed; pregame capture rejected.'});return false;}if(game.status!=='SCHEDULED'){observations.push({gameId:game.gameId,status:'SKIPPED_STATUS',snapshotId:null,message:`Schedule status ${game.status}; no pregame snapshot.`});return false;}return true;}),prepared=await this.adapter.prepare(eligible,startedAt),archive=new NflForwardArchive(this.root);
    for(const game of eligible)try{const input=await this.adapter.capture(game,prepared,{trigger:options.trigger,captureEventId,scheduledFor}),result=archive.capture(input);observations.push({gameId:game.gameId,status:result.created?'CAPTURED':'RETRY_DUPLICATE',snapshotId:result.snapshotId,message:result.created?'Immutable forward snapshot archived.':'Exact retry deduplicated.'});}catch(error){observations.push({gameId:game.gameId,status:'FAILED',snapshotId:null,message:error instanceof Error?error.message:String(error)});}
    const capturedIds=new Set(observations.map(row=>row.snapshotId).filter(Boolean)),snapshots=archive.load().snapshots.filter(row=>capturedIds.has(row.snapshotId)),failed=observations.filter(row=>row.status==='FAILED').length,status:NflRunStatus=observations.some(row=>row.status==='CAPTURED')?(failed||prepared.failures.length||discovery.failures.length?'DEGRADED':'SUCCESS'):'FAILED',completedAt=new Date(this.now()).toISOString(),runId=sha(`${captureEventId}|${startedAt}`).slice(0,32),summary=manualSummary({eligible:eligible.length,observations,snapshots,apiUsage:prepared.apiUsage,discoveryRequests:discovery.requests,discoveryFailures:discovery.failures,providerFailures:prepared.failures,deferred:prepared.deferred,planned:plannedRequests,dryRun:false}),featureScorecard=aggregateScorecards(snapshots.map(row=>row.featureCoverage??[])),run:NflOperationalRun={runId,captureEventId,trigger:options.trigger,startedAt,completedAt,scheduledFor,dryRun:false,status,eligibleGames:eligible.length,plannedRequests,observations,apiUsage:prepared.apiUsage,discoveryFailures:discovery.failures,providerFailures:prepared.failures,deferred:prepared.deferred,summary,featureScorecard};writeRun(this.root,run);return run;}
}
export function buildNflOperationalStatus(root:string,now:number,configured:{scheduler:boolean;durableStorage:boolean;collectionMode?:'MANUAL_ONLY'|'SCHEDULED'}){const runs=loadNflRuns(root),archiveInstance=new NflForwardArchive(root),archive=archiveInstance.load(),latest=(trigger:NflForwardTrigger)=>[...runs].filter(row=>row.trigger===trigger).sort((a,b)=>b.completedAt.localeCompare(a.completedAt))[0]??null,collectionMode=configured.collectionMode??(configured.scheduler?'SCHEDULED':'MANUAL_ONLY'),manualOnly=collectionMode==='MANUAL_ONLY',next=manualOnly?null:nextNflCentralRun(now),lastScheduled=[...runs].filter(row=>row.trigger!=='MANUAL').sort((a,b)=>b.completedAt.localeCompare(a.completedAt))[0]??null,lastManual=latest('MANUAL'),age=lastScheduled?(now-Date.parse(lastScheduled.completedAt))/3600_000:Infinity,failures=runs.reduce((n,row)=>n+row.providerFailures.length+row.discoveryFailures.length,0),props=archive.snapshots.reduce((n,row)=>n+row.propMarkets.length,0),notPosted=archive.snapshots.reduce((n,row)=>n+row.propUniverse.filter(p=>p.state==='PROP_NOT_POSTED').length,0),identityFailures=archive.snapshots.reduce((n,row)=>n+row.propUniverse.filter(p=>p.state==='PLAYER_IDENTITY_UNRESOLVED').length,0),health:NflHealth=!configured.durableStorage?'NOT_CONFIGURED':manualOnly?(lastManual?.status==='FAILED'?'FAILED':failures?'DEGRADED':'HEALTHY'):!configured.scheduler?'NOT_CONFIGURED':lastScheduled?.status==='FAILED'?'FAILED':age>30?'STALE':failures?'DEGRADED':'HEALTHY',latestSnapshot=[...archive.snapshots].sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt))[0]??null;return{version:'nfl-forward-operations-v1',collectionMode,scheduledCollection:manualOnly?'DISABLED_BY_CONFIGURATION':'ENABLED',manualCollection:'AVAILABLE',health,last7AmRun:latest('SCHEDULED_0700_CT'),last2PmRun:latest('SCHEDULED_1400_CT'),lastManualRun:lastManual,lastCollectionSummary:lastManual?.summary??null,featureCoverage:lastManual?.featureScorecard??latestSnapshot?.featureCoverage??[],criticalFeatureHealth:latestSnapshot?.criticalFeatureHealth??null,archiveHealth:archiveInstance.verify().status,nextExpectedRun:next,missedScheduledRuns:manualOnly?[]:undefined,runStatus:runs.at(-1)?.status??null,upcomingEligibleGames:runs.at(-1)?.eligibleGames??null,gamesCaptured:archive.snapshots.length,propMarketsCaptured:props,propNotPostedCount:notPosted,playerIdentityFailures:identityFailures,inactiveCoverage:inactiveCoverage(archive.snapshots),providerFailures:failures,deferredWork:runs.flatMap(row=>row.deferred),apiRequestCounts:runs.flatMap(row=>row.apiUsage).reduce((o,row)=>(o[row.provider]=(o[row.provider]??0)+row.requests,o),{} as Record<string,number>),cacheHits:runs.flatMap(row=>row.apiUsage).reduce((n,row)=>n+row.cacheHits,0),totalForwardSnapshots:archive.snapshots.length,durableStorageConfigured:configured.durableStorage,schedulerConfigured:configured.scheduler};}
