import * as fs from 'fs';
import * as path from 'path';
import {createHash,randomUUID} from 'crypto';
import {NFL_FORWARD_POLICY,NflForwardTrigger} from '../config/nflForwardPolicy';
import {inactiveCoverage,NewNflForwardSnapshot,NflForwardArchive,NflScheduleState} from './nflForwardResearch';

export type NflRunStatus='SUCCESS'|'DEGRADED'|'FAILED'|'DRY_RUN';
export type NflHealth='HEALTHY'|'DEGRADED'|'STALE'|'FAILED'|'NOT_CONFIGURED';
export interface NflDiscoveredGame {gameId:string;kickoff:string;status:NflScheduleState;missingIdentity:number;payload:unknown;}
export interface NflRequestPlan {provider:string;category:string;maximumRequests:number;estimatedCredits:number;priority:number;scope:string;}
export interface NflPreparedRun {state:unknown;apiUsage:Array<{provider:string;requests:number;estimatedCredits:number;actualCredits:number|null;cacheHits:number;retries:number;failures:number;deferred:string[]}>;failures:string[];deferred:string[];}
export interface NflCollectorAdapter {discover(at:string):Promise<{games:NflDiscoveredGame[];requests:number;failures:string[]}>;plan(games:NflDiscoveredGame[],at:string):NflRequestPlan[];prepare(games:NflDiscoveredGame[],at:string):Promise<NflPreparedRun>;capture(game:NflDiscoveredGame,prepared:NflPreparedRun,meta:{trigger:NflForwardTrigger;captureEventId:string;scheduledFor:string|null}):Promise<NewNflForwardSnapshot>;}
export interface NflOperationalRun {runId:string;captureEventId:string;trigger:NflForwardTrigger;startedAt:string;completedAt:string;scheduledFor:string|null;dryRun:boolean;status:NflRunStatus;eligibleGames:number;plannedRequests:NflRequestPlan[];observations:Array<{gameId:string;status:'CAPTURED'|'RETRY_DUPLICATE'|'WOULD_CAPTURE'|'SKIPPED_STARTED'|'SKIPPED_STATUS'|'FAILED';snapshotId:string|null;message:string}>;apiUsage:NflPreparedRun['apiUsage'];discoveryFailures:string[];providerFailures:string[];deferred:string[];}
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
function localParts(ms:number){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:NFL_FORWARD_POLICY.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(ms),get=(type:string)=>parts.find(row=>row.type===type)?.value??'';return{date:`${get('year')}-${get('month')}-${get('day')}`,hour:Number(get('hour')),minute:Number(get('minute'))};}
export function centralScheduledInstant(date:string,hour:7|14){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Invalid Central calendar date.');const center=Date.parse(`${date}T${String(hour).padStart(2,'0')}:00:00Z`);for(let ms=center-12*3600_000;ms<=center+12*3600_000;ms+=60_000){const p=localParts(ms);if(p.date===date&&p.hour===hour&&p.minute===0)return new Date(ms).toISOString();}throw Error('Central schedule could not be resolved.');}
export function nextNflCentralRun(now:number){const day=localParts(now).date;for(let offset=0;offset<4;offset++){const date=new Date(Date.parse(`${day}T12:00:00Z`)+offset*86400_000).toISOString().slice(0,10);for(const item of [{hour:7 as const,trigger:'SCHEDULED_0700_CT' as const},{hour:14 as const,trigger:'SCHEDULED_1400_CT' as const}]){const at=centralScheduledInstant(date,item.hour);if(Date.parse(at)>now)return{trigger:item.trigger,at};}}throw Error('Next NFL run unavailable.');}
export function nflCaptureEventId(trigger:NflForwardTrigger,now:number,key?:string){if(trigger==='MANUAL'){if(!key||key.length>160)throw Error('Manual collection requires a bounded idempotency key.');return`manual-${sha(key).slice(0,32)}`;}return`${localParts(now).date}-${trigger==='SCHEDULED_0700_CT'?'0700':'1400'}-ct`;}
export function nflScheduledFor(trigger:NflForwardTrigger,now:number){return trigger==='MANUAL'?null:centralScheduledInstant(localParts(now).date,trigger==='SCHEDULED_0700_CT'?7:14);}
const operationRoot=(root:string)=>path.join(root,'nfl_forward_research','v1','operations');
function writeRun(root:string,run:NflOperationalRun){const dir=operationRoot(root),target=path.join(dir,`${run.runId}.json`);fs.mkdirSync(dir,{recursive:true});try{fs.writeFileSync(target,JSON.stringify(run,null,2),{flag:'wx'});}catch(error:any){if(error?.code!=='EEXIST'||fs.readFileSync(target,'utf8')!==JSON.stringify(run,null,2))throw error;}}
export function loadNflRuns(root:string):NflOperationalRun[]{const dir=operationRoot(root);if(!fs.existsSync(dir))return[];return fs.readdirSync(dir).filter(name=>name.endsWith('.json')).map(name=>JSON.parse(fs.readFileSync(path.join(dir,name),'utf8'))).sort((a,b)=>a.startedAt.localeCompare(b.startedAt));}
export class NflForwardOperationalCollector {constructor(private root:string,private adapter:NflCollectorAdapter,private now=()=>Date.now()){}
  async run(options:{trigger:NflForwardTrigger;dryRun:boolean;idempotencyKey?:string}){const started=this.now(),startedAt=new Date(started).toISOString(),captureEventId=nflCaptureEventId(options.trigger,started,options.idempotencyKey),scheduledFor=nflScheduledFor(options.trigger,started),prior=loadNflRuns(this.root).find(row=>row.captureEventId===captureEventId&&!row.dryRun);if(prior&&!options.dryRun)return{...prior,retry:'RETRY_DUPLICATE' as const};
    const discovery=await this.adapter.discover(startedAt),games=discovery.games.sort((a,b)=>Date.parse(a.kickoff)-Date.parse(b.kickoff)||b.missingIdentity-a.missingIdentity||a.gameId.localeCompare(b.gameId)),plannedRequests=this.adapter.plan(games,startedAt),observations:NflOperationalRun['observations']=[];
    if(options.dryRun){for(const game of games)observations.push({gameId:game.gameId,status:game.status==='SCHEDULED'&&Date.parse(game.kickoff)>started?'WOULD_CAPTURE':'SKIPPED_STATUS',snapshotId:null,message:'Dry run; archive unchanged.'});return{runId:`dry-${randomUUID()}`,captureEventId,trigger:options.trigger,startedAt,completedAt:new Date(this.now()).toISOString(),scheduledFor,dryRun:true,status:'DRY_RUN' as const,eligibleGames:games.filter(game=>game.status==='SCHEDULED'&&Date.parse(game.kickoff)>started).length,plannedRequests,observations,apiUsage:[],discoveryFailures:discovery.failures,providerFailures:[],deferred:[]};}
    const eligible=games.filter(game=>{if(Date.parse(game.kickoff)<=started){observations.push({gameId:game.gameId,status:'SKIPPED_STARTED',snapshotId:null,message:'Kickoff has passed; pregame capture rejected.'});return false;}if(game.status!=='SCHEDULED'){observations.push({gameId:game.gameId,status:'SKIPPED_STATUS',snapshotId:null,message:`Schedule status ${game.status}; no pregame snapshot.`});return false;}return true;}),prepared=await this.adapter.prepare(eligible,startedAt),archive=new NflForwardArchive(this.root);
    for(const game of eligible)try{const input=await this.adapter.capture(game,prepared,{trigger:options.trigger,captureEventId,scheduledFor}),result=archive.capture(input);observations.push({gameId:game.gameId,status:result.created?'CAPTURED':'RETRY_DUPLICATE',snapshotId:result.snapshotId,message:result.created?'Immutable forward snapshot archived.':'Exact retry deduplicated.'});}catch(error){observations.push({gameId:game.gameId,status:'FAILED',snapshotId:null,message:error instanceof Error?error.message:String(error)});}
    const failed=observations.filter(row=>row.status==='FAILED').length,status:NflRunStatus=observations.some(row=>row.status==='CAPTURED')?(failed||prepared.failures.length||discovery.failures.length?'DEGRADED':'SUCCESS'):'FAILED',completedAt=new Date(this.now()).toISOString(),runId=sha(`${captureEventId}|${startedAt}`).slice(0,32),run:NflOperationalRun={runId,captureEventId,trigger:options.trigger,startedAt,completedAt,scheduledFor,dryRun:false,status,eligibleGames:eligible.length,plannedRequests,observations,apiUsage:prepared.apiUsage,discoveryFailures:discovery.failures,providerFailures:prepared.failures,deferred:prepared.deferred};writeRun(this.root,run);return run;}
}
export function buildNflOperationalStatus(root:string,now:number,configured:{scheduler:boolean;durableStorage:boolean}){const runs=loadNflRuns(root),archive=new NflForwardArchive(root).load(),latest=(trigger:NflForwardTrigger)=>[...runs].filter(row=>row.trigger===trigger).sort((a,b)=>b.completedAt.localeCompare(a.completedAt))[0]??null,next=nextNflCentralRun(now),lastScheduled=[...runs].filter(row=>row.trigger!=='MANUAL').sort((a,b)=>b.completedAt.localeCompare(a.completedAt))[0]??null,age=lastScheduled?(now-Date.parse(lastScheduled.completedAt))/3600_000:Infinity,failures=runs.reduce((n,row)=>n+row.providerFailures.length+row.discoveryFailures.length,0),props=archive.snapshots.reduce((n,row)=>n+row.propMarkets.length,0),notPosted=archive.snapshots.reduce((n,row)=>n+row.propUniverse.filter(p=>p.state==='PROP_NOT_POSTED').length,0),identityFailures=archive.snapshots.reduce((n,row)=>n+row.propUniverse.filter(p=>p.state==='PLAYER_IDENTITY_UNRESOLVED').length,0),health:NflHealth=!configured.scheduler||!configured.durableStorage?'NOT_CONFIGURED':lastScheduled?.status==='FAILED'?'FAILED':age>30?'STALE':failures?'DEGRADED':'HEALTHY';return{version:'nfl-forward-operations-v1',health,last7AmRun:latest('SCHEDULED_0700_CT'),last2PmRun:latest('SCHEDULED_1400_CT'),lastManualRun:latest('MANUAL'),nextExpectedRun:next,runStatus:runs.at(-1)?.status??null,upcomingEligibleGames:runs.at(-1)?.eligibleGames??null,gamesCaptured:archive.snapshots.length,propMarketsCaptured:props,propNotPostedCount:notPosted,playerIdentityFailures:identityFailures,inactiveCoverage:inactiveCoverage(archive.snapshots),providerFailures:failures,deferredWork:runs.flatMap(row=>row.deferred),apiRequestCounts:runs.flatMap(row=>row.apiUsage).reduce((o,row)=>(o[row.provider]=(o[row.provider]??0)+row.requests,o),{} as Record<string,number>),cacheHits:runs.flatMap(row=>row.apiUsage).reduce((n,row)=>n+row.cacheHits,0),totalForwardSnapshots:archive.snapshots.length,durableStorageConfigured:configured.durableStorage,schedulerConfigured:configured.scheduler};}
