import {createHash} from 'crypto';
import {getNflForwardEventMarkets,getUpcomingEvents,UpcomingEvent} from '../api/oddsApiClient';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';
import {NFL} from '../config/productionFocus';
import {RawEvent} from '../types/odds';
import {buildNflForecast} from './nflForecast';
import {attachOddsEvent,canonicalNflGame,canonicalPlayer,resolvePropPlayer,RosterSeed} from './nflForwardIdentities';
import {NflCollectorAdapter,NflDiscoveredGame,NflPreparedRun,NflRequestPlan} from './nflForwardOperations';
import {CanonicalNflGame,CanonicalNflPlayer,makeDiagnostic,NewNflForwardSnapshot,NFL_PLAYER_CATEGORIES,NFL_TEAM_CATEGORIES,NflFootballEvidence,NflMarketQuoteEvidence,SixStageDiagnostic} from './nflForwardResearch';
import {fetchOfficialInactives,OfficialInactiveObservation,resolveGameDayAvailability} from './nflGameDayAvailability';
import {flattenNflQuotes} from './nflMarketBoard';
import {ESPN_NFL,fetchNflJson,NflResearch,nflName} from './nflResearch';
import {buildNflOpportunityProjection,NflOpportunityFlag,NflOpportunityHistoryRow,opportunityHistoryFromForecast,opportunityMetricForMarket} from './nflOpportunityEngine';
import {buildNflCriticalFeatureHealth,buildNflFeatureScorecard,createNflForwardFeature,NflForwardFeatureRecord,nflCaptureWindow,nflPositionImportanceGroup,nflRestFeatures,normalizeNflForwardRole,rawShare,unavailableNflFeature} from './nflForwardFeatures';
import {OfficialNflInjuryReport,OfficialNflInjuryReports} from './nflOfficialReports';

const sha=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const day=(ms:number)=>new Date(ms).toISOString().slice(0,10).replace(/-/g,'');
interface RuntimeGame {espnEvent:any;game:CanonicalNflGame;provider:UpcomingEvent|null;}
interface GameContext {players:CanonicalNflPlayer[];rosterStatus:Map<string,'PASS'|'FAIL'>;depth:any[];summary:any|null;sources:Array<{provider:string;url:string;retrievedAt:string;payload:unknown}>;}
interface OpportunitySeed {history:NflOpportunityHistoryRow[];snapShare:Array<{date:string;season:number;offenseSnaps:number;offensePct:number}>;snapRetrievedAt:string;rosterStatus:string;injuryStatuses:string[];}
interface RuntimeState {at:string;contexts:Map<string,GameContext>;markets:Map<string,RawEvent>;marketUsage:Map<string,{credits:number|null}>;inactive:OfficialInactiveObservation;injuryReports:Map<number,OfficialNflInjuryReport>;projections:Map<string,{projection:number;version:string}>;opportunitySeeds:Map<string,OpportunitySeed>;apiUsage:NflPreparedRun['apiUsage'];failures:string[];deferred:string[];}
function competitors(event:any){const c=event?.competitions?.[0],home=(c?.competitors??[]).find((row:any)=>row.homeAway==='home'),away=(c?.competitors??[]).find((row:any)=>row.homeAway==='away');return{competition:c,home,away};}
function source(provider:string,url:string,retrievedAt:string,payload:unknown,effectiveAt:string|null=null){return{provider,url,providerRecordId:null,retrievedAt,effectiveAt,rawPayloadHash:sha(payload)};}
function rosterRows(payload:any,team:CanonicalNflGame['home'],at:string):RosterSeed[]{const rows:RosterSeed[]=[];for(const group of payload?.athletes??[])for(const item of group?.items??[]){if(!item?.id||!item?.displayName||!item?.position?.abbreviation)continue;rows.push({id:String(item.id),name:String(item.displayName),teamId:team.canonicalTeamId,teamName:team.name,position:String(item.position.abbreviation),status:String(item.status?.name??'UNKNOWN'),rookie:typeof item.experience?.years==='number'?item.experience.years===0:undefined});}return rows;}
function exactDepth(payload:any,players:CanonicalNflPlayer[]){const result=[] as any[];for(const chart of payload?.depthchart??[])for(const [position,block] of Object.entries(chart?.positions??{}) as Array<[string,any]>)for(let i=0;i<(block?.athletes??[]).length;i++){const athlete=block.athletes[i],matches=players.filter(player=>player.providerPlayerIds.ESPN===String(athlete?.id??'')&&nflName(player.name)===nflName(athlete?.displayName));if(matches.length===1)result.push({playerId:matches[0].canonicalPlayerId,position,listedOrder:i+1,formation:String(chart?.name??'UNKNOWN')});}return result;}
function quoteEvidence(event:RawEvent,game:CanonicalNflGame,players:CanonicalNflPlayer[],at:string){const rawHash=sha(event),all=flattenNflQuotes(event,[...NFL_FORWARD_POLICY.coreGameMarkets,...NFL_FORWARD_POLICY.corePropMarkets],Date.parse(at)).filter(row=>!row.stale&&row.updatedAt&&Date.parse(row.updatedAt)<=Date.parse(at)),gameMarkets:NflMarketQuoteEvidence[]=[],propMarkets:NflMarketQuoteEvidence[]=[],unresolved=new Map<string,string>();for(const row of all){const base={canonicalGameId:game.canonicalGameId,market:row.market,side:row.side,line:row.line,price:row.price,sportsbook:row.book,providerEventId:event.id,quoteTimestamp:String(row.updatedAt),captureTimestamp:at,rawPayloadHash:rawHash,label:'CONTEMPORANEOUS_QUOTE' as const};if((NFL_FORWARD_POLICY.coreGameMarkets as readonly string[]).includes(row.market))gameMarkets.push({kind:'GAME',canonicalPlayerId:null,participant:row.participant||null,...base});else{const matched=resolvePropPlayer(row.participant,players,game);if(!matched.player){unresolved.set(`${row.market}:${row.participant}`,matched.reason!);continue;}propMarkets.push({kind:'PROP',canonicalPlayerId:matched.player.canonicalPlayerId,participant:matched.player.name,...base});}}
  return{gameMarkets,propMarkets,unresolved,available:new Set(all.map(row=>row.market))};}

function buildFeaturePackage(input:{game:CanonicalNflGame;at:string;context:GameContext;state:RuntimeState;players:CanonicalNflPlayer[];inactivePlayers:NewNflForwardSnapshot['inactiveEvidence']['players'];market:{gameMarkets:NflMarketQuoteEvidence[];propMarkets:NflMarketQuoteEvidence[]};opportunityProjections:Array<{canonicalPlayerId:string;roleState:string}>}){
  const {game,at,context,state,players,inactivePlayers,market}=input,records:NflForwardFeatureRecord[]=[],kickoffTimestamp=game.scheduledKickoff,depthRetrievedAt=context.sources.find(row=>row.url.includes('/depthcharts'))?.retrievedAt??at,summaryRetrievedAt=context.sources.find(row=>row.url.includes('/summary?'))?.retrievedAt??at,pass=(overrides:any)=>({SOURCE_RETRIEVAL:'PASS',NORMALIZATION:'PASS',ENTITY_MATCHING:'PASS',CONTEXT_ATTACHMENT:'PASS',FIELD_VALIDITY:'PASS',FRESHNESS:'PASS',...overrides});
  const add=(row:any)=>records.push(createNflForwardFeature({gameId:game.canonicalGameId,teamId:null,playerId:null,captureTimestamp:at,forecastTimestamp:at,kickoffTimestamp,sourceTimestamp:null,retrievalTimestamp:at,numerator:null,denominator:null,qualityState:'VERIFIED',freshnessState:'FRESH',integrity:pass({FRESHNESS:'UNKNOWN'}),correctionOf:null,notes:[],...row}));
  add({category:'GAME_IDENTITY',field:'game.canonical_identity',normalizedValue:{gameId:game.canonicalGameId,homeTeamId:game.home.canonicalTeamId,awayTeamId:game.away.canonicalTeamId,kickoff:game.scheduledKickoff},source:'ESPN_SCOREBOARD',rawEvidenceReference:sha((context as any).espnEvent??game)});
  add({category:'VENUE',field:'venue.static_metadata',normalizedValue:{...game.venue,neutralSite:game.neutralSite,international:game.international},source:'ESPN_SCOREBOARD',rawEvidenceReference:sha(game.venue)});
  for(const team of [game.home,game.away]){
    const teamPlayers=context.players.filter(row=>row.teamId===team.canonicalTeamId),qb=context.depth.find(row=>row.position==='QB'&&row.listedOrder===1&&teamPlayers.some(player=>player.canonicalPlayerId===row.playerId)),backup=context.depth.find(row=>row.position==='QB'&&row.listedOrder===2&&teamPlayers.some(player=>player.canonicalPlayerId===row.playerId)),qbPlayer=teamPlayers.find(row=>row.canonicalPlayerId===qb?.playerId),qbInactive=inactivePlayers.find(row=>row.canonicalPlayerId===qb?.playerId),report=game.week?state.injuryReports.get(game.week):null,injuryRows=report?.rows.filter(row=>nflName(team.name).endsWith(nflName(row.team)))??[],qbInjury=injuryRows.find(row=>qbPlayer&&nflName(row.player)===nflName(qbPlayer.name));
    if(qb)add({teamId:team.canonicalTeamId,category:'QB',field:'qb.projected_starter',normalizedValue:{projectedStarter:qb.playerId,confirmedStarter:null,backup:backup?.playerId??null,rookie:qbPlayer?.rookie??'UNKNOWN',newTeam:qbPlayer?.newTeam??'UNKNOWN',injuryDesignation:qbInjury?.gameStatus||'UNKNOWN',practiceStatus:qbInjury?.practiceStatus||'UNKNOWN',gameDayInactiveStatus:qbInactive?.state??'STATUS_UNKNOWN'},source:'ESPN_DEPTH_CHART_AND_NFL_OFFICIAL_INJURY_REPORT',sourceTimestamp:null,retrievalTimestamp:report&&Date.parse(report.fetchedAt)>Date.parse(depthRetrievedAt)?report.fetchedAt:depthRetrievedAt,rawEvidenceReference:sha({qb,backup,qbPlayer,qbInactive,qbInjury}),qualityState:'PARTIAL',notes:['Depth-chart order is projected evidence, not confirmed game-day starter evidence.']});
    else records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'QB',field:'qb.projected_starter',captureTimestamp:at,kickoffTimestamp,reason:'QB_STARTER_UNRESOLVED'}));
    const teamHistory=new Map<string,{date:string;pass:number|null;rush:number|null}>();
    for(const player of players.filter(row=>row.teamId===team.canonicalTeamId)){const seed=state.opportunitySeeds.get(`${game.canonicalGameId}:${player.canonicalPlayerId}`);for(const row of seed?.history??[]){if(row.season!==game.season||row.teamId!==team.canonicalTeamId||row.teamOpportunity===null)continue;const key=row.eventId,old=teamHistory.get(key)??{date:row.date,pass:null,rush:null};if(row.metric==='PASS_ATTEMPTS')old.pass=row.teamOpportunity;if(row.metric==='RUSH_ATTEMPTS')old.rush=row.teamOpportunity;teamHistory.set(key,old);}}
    for(const [eventId,row] of [...teamHistory].sort((a,b)=>a[1].date.localeCompare(b[1].date))){if(row.pass!==null)add({teamId:team.canonicalTeamId,category:'TEAM_VOLUME',field:'team.pass_attempts.prior_game',normalizedValue:{eventId,value:row.pass},numerator:row.pass,denominator:null,source:'ESPN_VERIFIED_POSTGAME_SUMMARY',sourceTimestamp:row.date,retrievalTimestamp:at,rawEvidenceReference:sha({eventId,pass:row.pass})});if(row.rush!==null)add({teamId:team.canonicalTeamId,category:'TEAM_VOLUME',field:'team.rush_attempts.prior_game',normalizedValue:{eventId,value:row.rush},numerator:row.rush,denominator:null,source:'ESPN_VERIFIED_POSTGAME_SUMMARY',sourceTimestamp:row.date,retrievalTimestamp:at,rawEvidenceReference:sha({eventId,rush:row.rush})});if(row.pass!==null&&row.rush!==null){const volume=row.pass+row.rush;add({teamId:team.canonicalTeamId,category:'PASS_RUN_TENDENCY',field:'team.pass_rate.prior_game',normalizedValue:{eventId,...rawShare(row.pass,volume,'TARGET_SHARE')},numerator:row.pass,denominator:volume,source:'ESPN_VERIFIED_POSTGAME_SUMMARY',sourceTimestamp:row.date,retrievalTimestamp:at,rawEvidenceReference:sha({eventId,pass:row.pass,rush:row.rush})});}}
    if(!teamHistory.size){records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'TEAM_VOLUME',field:'team.recent_play_volume',captureTimestamp:at,kickoffTimestamp,reason:'CURRENT_SEASON_TEAM_VOLUME_UNAVAILABLE'}),unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'PASS_RUN_TENDENCY',field:'team.pass_run_tendency',captureTimestamp:at,kickoffTimestamp,reason:'CURRENT_SEASON_PASS_RUN_TENDENCY_UNAVAILABLE'}));}
    records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'OFFENSIVE_EFFICIENCY',field:'team.offensive_efficiency',captureTimestamp:at,kickoffTimestamp,reason:'TRUSTWORTHY_PREGAME_OFFENSIVE_EFFICIENCY_FEED_NOT_ATTACHED'}),unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'DEFENSIVE_EFFICIENCY',field:'team.defensive_efficiency',captureTimestamp:at,kickoffTimestamp,reason:'TRUSTWORTHY_PREGAME_DEFENSIVE_EFFICIENCY_FEED_NOT_ATTACHED'}),unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'COACHING',field:'team.coaching_play_caller',captureTimestamp:at,kickoffTimestamp,reason:'POINT_IN_TIME_COACHING_PLAY_CALLER_SOURCE_UNAVAILABLE'}));
    const prior=[...teamHistory.values()].map(row=>({kickoff:row.date,final:true,overtime:false,away:false,international:false}));if(prior.length)add({teamId:team.canonicalTeamId,category:'REST',field:'schedule.rest_context',normalizedValue:nflRestFeatures({kickoffTimestamp,priorKickoffs:prior}),source:'ESPN_VERIFIED_POSTGAME_SCHEDULE',sourceTimestamp:prior.sort((a,b)=>b.kickoff.localeCompare(a.kickoff))[0].kickoff,rawEvidenceReference:sha(prior)});else records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:team.canonicalTeamId,category:'REST',field:'schedule.rest_context',captureTimestamp:at,kickoffTimestamp,reason:'NO_VERIFIED_PRIOR_2026_GAME_FOR_REST_CONTEXT'}));
    add({teamId:team.canonicalTeamId,category:'CURRENT_SEASON_SAMPLE',field:'team.completed_current_season_games',normalizedValue:teamHistory.size,numerator:teamHistory.size,source:'ESPN_VERIFIED_POSTGAME_SUMMARY',sourceTimestamp:teamHistory.size?[...teamHistory.values()].sort((a,b)=>b.date.localeCompare(a.date))[0].date:null,rawEvidenceReference:sha([...teamHistory]),qualityState:teamHistory.size?'VERIFIED':'PARTIAL',freshnessState:teamHistory.size?'FRESH':'UNKNOWN',integrity:pass(teamHistory.size?{}:{SOURCE_RETRIEVAL:'PARTIAL',FIELD_VALIDITY:'PARTIAL',FRESHNESS:'UNKNOWN'}),notes:teamHistory.size?[]:['No completed 2026 sample was attached; zero is preserved as an early-season fact.']});
  }
  const weather=context.summary?.gameInfo?.weather??null,venue=context.summary?.gameInfo?.venue??null;if(weather&&Object.keys(weather).length)add({category:'WEATHER',field:'weather.pregame_forecast',normalizedValue:{temperatureF:weather.temperature??null,windMph:weather.windSpeed??null,gustMph:weather.gust??null,precipitationProbability:weather.precipitation??null,precipitationType:weather.conditionId??null,humidity:weather.humidity??null,indoor:typeof venue?.indoor==='boolean'?venue.indoor:game.venue.indoor},source:'ESPN_PREGAME_SUMMARY',retrievalTimestamp:summaryRetrievedAt,rawEvidenceReference:sha(weather),qualityState:'PARTIAL',notes:['The feed is pregame-accessible but does not expose a separate forecast issuance timestamp.']});
  else records.push(unavailableNflFeature({gameId:game.canonicalGameId,category:'WEATHER',field:'weather.pregame_forecast',captureTimestamp:at,kickoffTimestamp,reason:'PREGAME_WEATHER_FORECAST_UNAVAILABLE'}));
  for(const player of players){const seed=state.opportunitySeeds.get(`${game.canonicalGameId}:${player.canonicalPlayerId}`),depth=context.depth.find(row=>row.playerId===player.canonicalPlayerId),inactive=inactivePlayers.find(row=>row.canonicalPlayerId===player.canonicalPlayerId),team=player.teamId===game.home.canonicalTeamId?game.home:game.away,report=game.week?state.injuryReports.get(game.week):null,officialRows=(report?.rows??[]).filter(row=>nflName(team.name).endsWith(nflName(row.team))&&nflName(row.player)===nflName(player.name));if(depth)add({teamId:player.teamId,playerId:player.canonicalPlayerId,category:'DEPTH_CHART',field:'player.depth_order',normalizedValue:{position:depth.position,listedOrder:depth.listedOrder,formation:depth.formation},source:'ESPN_DEPTH_CHART',retrievalTimestamp:depthRetrievedAt,rawEvidenceReference:sha(depth),qualityState:'PARTIAL'});else records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:player.teamId,playerId:player.canonicalPlayerId,category:'DEPTH_CHART',field:'player.depth_order',captureTimestamp:at,kickoffTimestamp,reason:'DEPTH_CHART_POSITION_UNAVAILABLE'}));if(inactive)add({teamId:player.teamId,playerId:player.canonicalPlayerId,category:'INJURIES',field:'player.game_day_availability',normalizedValue:{state:inactive.state,positionGroup:nflPositionImportanceGroup(player.position)},source:'NFL_OFFICIAL_INACTIVES',sourceTimestamp:state.inactive.sourceTimestamp,retrievalTimestamp:state.inactive.retrievedAt,rawEvidenceReference:state.inactive.rawPayloadHash,qualityState:['ACTIVE_VERIFIED','INACTIVE_VERIFIED'].includes(inactive.state)?'VERIFIED':'PARTIAL',freshnessState:['ACTIVE_VERIFIED','INACTIVE_VERIFIED'].includes(inactive.state)?'FRESH':'UNKNOWN',integrity:pass(['ACTIVE_VERIFIED','INACTIVE_VERIFIED'].includes(inactive.state)?{}:{FIELD_VALIDITY:'PARTIAL',FRESHNESS:'UNKNOWN'}),notes:[inactive.reason]});if(officialRows.length===1)add({teamId:player.teamId,playerId:player.canonicalPlayerId,category:'INJURIES',field:'player.official_practice_and_game_designation',normalizedValue:{injury:officialRows[0].injury,practiceStatus:officialRows[0].practiceStatus,gameStatus:officialRows[0].gameStatus,positionGroup:nflPositionImportanceGroup(player.position)},source:'NFL_OFFICIAL_INJURY_REPORT',retrievalTimestamp:report!.fetchedAt,sourceTimestamp:null,rawEvidenceReference:sha(officialRows[0]),qualityState:'VERIFIED',freshnessState:'FRESH',integrity:pass({FRESHNESS:'PARTIAL'}),notes:['Official weekly report does not publish a separate source timestamp; retrieval time is preserved.']});
    const projection=input.opportunityProjections.find(row=>row.canonicalPlayerId===player.canonicalPlayerId);if(projection?.roleState)add({teamId:player.teamId,playerId:player.canonicalPlayerId,category:'PLAYER_ROLE',field:'player.role_state',normalizedValue:normalizeNflForwardRole(player.position,projection.roleState),source:'DEPTH_AND_PRIOR_USAGE_CLASSIFICATION',rawEvidenceReference:sha({depth,history:seed?.history??[]}),qualityState:'PARTIAL'});
    for(const row of seed?.snapShare??[])add({teamId:player.teamId,playerId:player.canonicalPlayerId,category:'SNAPS',field:'player.snap_usage.prior_game',normalizedValue:{date:row.date,offensiveSnaps:row.offenseSnaps,snapShare:row.offensePct},numerator:row.offenseSnaps,denominator:null,source:'NFLVERSE_POSTGAME_SNAPS',sourceTimestamp:row.date,retrievalTimestamp:seed!.snapRetrievedAt,rawEvidenceReference:sha(row)});
    for(const row of seed?.history??[]){const category=row.metric==='TARGETS'?'TARGETS':row.metric==='RUSH_ATTEMPTS'?'CARRIES':'QB',field=row.metric==='TARGETS'?'player.targets.prior_game':row.metric==='RUSH_ATTEMPTS'?'player.carries.prior_game':'player.pass_attempts.prior_game',share=row.teamOpportunity===null?null:rawShare(row.opportunity,row.teamOpportunity,row.metric==='RUSH_ATTEMPTS'?'CARRY_SHARE':'TARGET_SHARE');add({teamId:player.teamId,playerId:player.canonicalPlayerId,category,field,normalizedValue:{eventId:row.eventId,value:row.opportunity,share},numerator:row.opportunity,denominator:row.teamOpportunity,source:'ESPN_VERIFIED_POSTGAME_SUMMARY',sourceTimestamp:row.date,retrievalTimestamp:row.sourceRetrievedAt,rawEvidenceReference:sha(row)});}
    if(!seed?.snapShare.length)records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:player.teamId,playerId:player.canonicalPlayerId,category:'SNAPS',field:'player.snap_usage',captureTimestamp:at,kickoffTimestamp,reason:'POINT_IN_TIME_PRIOR_SNAP_USAGE_UNAVAILABLE'}));const skill=['RB','HB','FB','WR','TE'].includes(player.position.toUpperCase());if(skill){const teammateRows=inactivePlayers.filter(row=>row.canonicalPlayerId!==player.canonicalPlayerId&&players.some(item=>item.canonicalPlayerId===row.canonicalPlayerId&&item.teamId===player.teamId)).map(row=>({canonicalPlayerId:row.canonicalPlayerId,state:row.state}));add({teamId:player.teamId,playerId:player.canonicalPlayerId,category:'TEAMMATE_AVAILABILITY',field:'player.relevant_teammate_availability',normalizedValue:teammateRows,source:'NFL_OFFICIAL_INACTIVES',sourceTimestamp:state.inactive.sourceTimestamp,retrievalTimestamp:state.inactive.retrievedAt,rawEvidenceReference:state.inactive.rawPayloadHash,qualityState:state.inactive.pageState==='COMPLETE_GAME_LISTS'?'VERIFIED':'PARTIAL',freshnessState:state.inactive.pageState==='COMPLETE_GAME_LISTS'?'FRESH':'UNKNOWN',integrity:pass(state.inactive.pageState==='COMPLETE_GAME_LISTS'?{}:{FIELD_VALIDITY:'PARTIAL',FRESHNESS:'UNKNOWN'}),notes:['Evidence only; no workload redistribution percentage is assigned.']});records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:player.teamId,playerId:player.canonicalPlayerId,category:'ROUTES',field:'player.route_participation',captureTimestamp:at,kickoffTimestamp,reason:'ROUTE_DATA_UNAVAILABLE'}),unavailableNflFeature({gameId:game.canonicalGameId,teamId:player.teamId,playerId:player.canonicalPlayerId,category:'RED_ZONE',field:'player.red_zone_goal_line_opportunity',captureTimestamp:at,kickoffTimestamp,reason:'TRUSTWORTHY_POINT_IN_TIME_RED_ZONE_DATA_UNAVAILABLE'}));if(!seed?.history.some(row=>row.metric==='TARGETS'))records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:player.teamId,playerId:player.canonicalPlayerId,category:'TARGETS',field:'player.targets',captureTimestamp:at,kickoffTimestamp,reason:'PRIOR_TARGET_DATA_UNAVAILABLE'}));}if(['RB','HB','FB'].includes(player.position.toUpperCase())&&!seed?.history.some(row=>row.metric==='RUSH_ATTEMPTS'))records.push(unavailableNflFeature({gameId:game.canonicalGameId,teamId:player.teamId,playerId:player.canonicalPlayerId,category:'CARRIES',field:'player.carries',captureTimestamp:at,kickoffTimestamp,reason:'PRIOR_CARRY_DATA_UNAVAILABLE'}));
  }
  const expected:any={TEAM_VOLUME:4,PASS_RUN_TENDENCY:2,OFFENSIVE_EFFICIENCY:2,DEFENSIVE_EFFICIENCY:2,QB:2,INJURIES:players.length,DEPTH_CHART:players.length,SNAPS:players.length,ROUTES:players.filter(player=>['RB','HB','FB','WR','TE'].includes(player.position.toUpperCase())).length,TARGETS:players.filter(player=>['RB','HB','FB','WR','TE'].includes(player.position.toUpperCase())).length,CARRIES:players.filter(player=>['RB','HB','FB'].includes(player.position.toUpperCase())).length,RED_ZONE:players.filter(player=>['RB','HB','FB','WR','TE'].includes(player.position.toUpperCase())).length,WEATHER:game.venue.indoor===true?0:1,REST:2,COACHING:2,MARKET:1};
  const featureCoverage=buildNflFeatureScorecard(records,expected,market.gameMarkets.length),criticalFeatureHealth=buildNflCriticalFeatureHealth({startingQb:records.filter(row=>row.category==='QB'&&row.field==='qb.projected_starter'&&row.qualityState!=='UNAVAILABLE').length===2?'PASS':'FAIL',gameIdentity:'PASS',kickoff:'PASS',marketIdentity:game.providerGameIds.ODDS_API&&market.gameMarkets.length?'PASS':game.providerGameIds.ODDS_API?'PARTIAL':'FAIL',injuryInactiveEvidence:state.inactive.pageState==='COMPLETE_GAME_LISTS'?'PASS':state.inactive.pageState==='SEASON_PENDING'?'PARTIAL':'FAIL',currentSeasonTeamSample:records.filter(row=>row.category==='CURRENT_SEASON_SAMPLE'&&Number(row.normalizedValue)>0).length===2?'PASS':'PARTIAL'});
  return{featureRecords:records.sort((a,b)=>a.recordId.localeCompare(b.recordId)),featureCoverage,criticalFeatureHealth,captureWindow:nflCaptureWindow((Date.parse(kickoffTimestamp)-Date.parse(at))/60_000)};
}

export class LiveNflForwardCollectorAdapter implements NflCollectorAdapter {
  constructor(private now=()=>Date.now(),private get=fetchNflJson,private eventMarkets=getNflForwardEventMarkets,private events=()=>getUpcomingEvents(NFL),private inactives=fetchOfficialInactives,private injuries=new OfficialNflInjuryReports()){}
  async discover(at:string){
    const now=Date.parse(at),end=now+NFL_FORWARD_POLICY.horizonHours*3600_000;
    const url=`${ESPN_NFL}/scoreboard?dates=${day(now-86400_000)}-${day(end+86400_000)}&limit=200`;
    const failures:string[]=[],provider:UpcomingEvent[]=[];
    try{provider.push(...await this.events());}catch(error){failures.push(`Odds event discovery unavailable: ${error instanceof Error?error.message:String(error)}`);}
    let payload:any={events:[]};
    try{payload=await this.get(url);}catch(error){failures.push(`ESPN schedule discovery unavailable: ${error instanceof Error?error.message:String(error)}`);}
    const games:NflDiscoveredGame[]=[];
    for(const event of payload?.events??[])try{
      let game=canonicalNflGame(event,at);
      if(Date.parse(game.scheduledKickoff)>end||Date.parse(game.scheduledKickoff)<now-86400_000)continue;
      const attached=attachOddsEvent(game,provider);game=attached.game;
      games.push({gameId:game.canonicalGameId,kickoff:game.scheduledKickoff,status:game.status,missingIdentity:attached.provider?0:1,payload:{espnEvent:event,game,provider:attached.provider} satisfies RuntimeGame});
    }catch(error){failures.push(`NFL event identity rejected: ${error instanceof Error?error.message:String(error)}`);}
    return{games,requests:2,failures};
  }
  plan(games:NflDiscoveredGame[],at:string):NflRequestPlan[]{const marketGames=Math.min(games.filter(row=>(row.payload as RuntimeGame).provider).length,NFL_FORWARD_POLICY.maxOddsRequestsPerRun);return[
    {provider:'ESPN',category:'ROSTER_DEPTH_SUMMARY',maximumRequests:games.length*5,estimatedCredits:0,priority:1,scope:'Every eligible game; shared team payloads are cached per run.'},
    {provider:'NFL.com',category:'OFFICIAL_GAME_DAY_INACTIVES',maximumRequests:1,estimatedCredits:0,priority:2,scope:'One official-page observation for all eligible games.'},
    {provider:'NFL.com',category:'OFFICIAL_WEEKLY_INJURY_REPORT',maximumRequests:new Set(games.map(row=>(row.payload as RuntimeGame)?.game?.week).filter(Boolean)).size,estimatedCredits:0,priority:2,scope:'One shared official weekly report per distinct eligible week.'},
    {provider:'The Odds API',category:'CORE_GAME_AND_PROP_MARKETS',maximumRequests:marketGames,estimatedCredits:marketGames*(NFL_FORWARD_POLICY.coreGameMarkets.length+NFL_FORWARD_POLICY.corePropMarkets.length),priority:3,scope:'One bounded no-retry request per matched event, nearest kickoff first.'},
  ];}
  async prepare(games:NflDiscoveredGame[],at:string):Promise<NflPreparedRun>{const contexts=new Map<string,GameContext>(),failures:string[]=[],deferred:string[]=[],teamCache=new Map<string,{roster:any;depth:any;retrievedAt:string}>(),espnUsage={provider:'ESPN',requests:0,estimatedCredits:0,actualCredits:0,cacheHits:0,retries:0,failures:0,deferred:[] as string[]};for(const discovered of games){const runtime=discovered.payload as RuntimeGame,players:CanonicalNflPlayer[]=[],rosterStatus=new Map<string,'PASS'|'FAIL'>(),sources:GameContext['sources']=[],depthRows:any[]=[];for(const team of [runtime.game.home,runtime.game.away]){let cached=teamCache.get(team.canonicalTeamId);if(cached)espnUsage.cacheHits+=2;else{const teamId=team.canonicalTeamId.replace('espn-team:',''),rosterUrl=`${ESPN_NFL}/teams/${teamId}/roster`,depthUrl=`${ESPN_NFL}/teams/${teamId}/depthcharts`;try{const [roster,depth]=await Promise.all([this.get(rosterUrl),this.get(depthUrl)]),retrievedAt=new Date(this.now()).toISOString();espnUsage.requests+=2;cached={roster,depth,retrievedAt};teamCache.set(team.canonicalTeamId,cached);sources.push({provider:'ESPN',url:rosterUrl,retrievedAt,payload:roster},{provider:'ESPN',url:depthUrl,retrievedAt,payload:depth});}catch(error){espnUsage.failures++;rosterStatus.set(team.canonicalTeamId,'FAIL');failures.push(`${runtime.game.canonicalGameId}/${team.name}: roster/depth unavailable.`);continue;}}
        try{const seeds=rosterRows(cached.roster,team,at);if(Number(cached.roster?.season?.year)!==2026||String(cached.roster?.team?.id)!==team.canonicalTeamId.replace('espn-team:','')||!seeds.length)throw Error('roster mismatch');const teamPlayers=seeds.map(seed=>canonicalPlayer(seed,at));players.push(...teamPlayers);depthRows.push(...exactDepth(cached.depth,teamPlayers));rosterStatus.set(team.canonicalTeamId,'PASS');}catch{rosterStatus.set(team.canonicalTeamId,'FAIL');failures.push(`${runtime.game.canonicalGameId}/${team.name}: roster failed identity validation.`);}}
      let summary:any=null;const summaryUrl=`${ESPN_NFL}/summary?event=${runtime.game.providerGameIds.ESPN}`;try{summary=await this.get(summaryUrl);espnUsage.requests++;sources.push({provider:'ESPN',url:summaryUrl,retrievedAt:new Date(this.now()).toISOString(),payload:summary});}catch{espnUsage.failures++;failures.push(`${runtime.game.canonicalGameId}: summary unavailable.`);}contexts.set(discovered.gameId,{players,rosterStatus,depth:depthRows,summary,sources});}
    const inactive=await this.inactives(()=>Date.parse(at)),injuryReports=new Map<number,OfficialNflInjuryReport>();for(const week of [...new Set(games.map(row=>(row.payload as RuntimeGame).game.week).filter((value):value is number=>Boolean(value)))]){const report=await this.injuries.report(2026,week);injuryReports.set(week,report);if(!['PARTIAL_SUCCESS','SOURCE_RETURNED_EMPTY'].includes(report.status))failures.push(`NFL official injury report week ${week}: ${report.note}`);}const marketMap=new Map<string,RawEvent>(),marketUsage=new Map<string,{credits:number|null}>(),oddsUsage={provider:'The Odds API',requests:0,estimatedCredits:0,actualCredits:0 as number|null,cacheHits:0,retries:0,failures:0,deferred:[] as string[]},eligible=[...games].filter(row=>(row.payload as RuntimeGame).provider).slice(0,NFL_FORWARD_POLICY.maxOddsRequestsPerRun);let estimated=0,actual=0,actualKnown=true;for(const discovered of eligible){const runtime=discovered.payload as RuntimeGame,cost=NFL_FORWARD_POLICY.coreGameMarkets.length+NFL_FORWARD_POLICY.corePropMarkets.length;if(estimated+cost>NFL_FORWARD_POLICY.maxOddsCreditsPerRun){deferred.push(`${discovered.gameId}: odds budget cap`);oddsUsage.deferred.push(discovered.gameId);continue;}estimated+=cost;try{const result=await this.eventMarkets(runtime.provider!.id,[...NFL_FORWARD_POLICY.coreGameMarkets,...NFL_FORWARD_POLICY.corePropMarkets]);oddsUsage.requests++;oddsUsage.estimatedCredits+=cost;if(result.creditsUsed===null)actualKnown=false;else actual+=result.creditsUsed;if(result.event)marketMap.set(discovered.gameId,result.event);marketUsage.set(discovered.gameId,{credits:result.creditsUsed});}catch(error){oddsUsage.requests++;oddsUsage.failures++;actualKnown=false;failures.push(`${discovered.gameId}: ${error instanceof Error?error.message:String(error)}`);}}
    oddsUsage.actualCredits=actualKnown?actual:null;const projections=new Map<string,{projection:number;version:string}>(),opportunitySeeds=new Map<string,OpportunitySeed>(),research=new NflResearch(this.get,()=>Date.parse(at)),legacyMarkets=['player_pass_yds','player_rush_yds','player_reception_yds','player_receptions'],sourceMarket=(market:string)=>['player_pass_attempts','player_pass_completions'].includes(market)?'player_pass_yds':market==='player_rush_attempts'?'player_rush_yds':market,forecastTasks:Array<{game:NflDiscoveredGame;markets:string[];sourceMarket:string;player:CanonicalNflPlayer;event:UpcomingEvent}>=[];for(const discovered of games){const runtime=discovered.payload as RuntimeGame,event=marketMap.get(discovered.gameId),context=contexts.get(discovered.gameId);if(!runtime.provider||!event||!context)continue;const parsed=quoteEvidence(event,runtime.game,context.players,at);for(const quote of parsed.propMarkets){const player=context.players.find(row=>row.canonicalPlayerId===quote.canonicalPlayerId)!,source=sourceMarket(quote.market),metric=opportunityMetricForMarket(quote.market);if(!metric)continue;const old=forecastTasks.find(row=>row.game.gameId===discovered.gameId&&row.sourceMarket===source&&row.player.canonicalPlayerId===player.canonicalPlayerId);if(old){if(!old.markets.includes(quote.market))old.markets.push(quote.market);}else forecastTasks.push({game:discovered,markets:[quote.market],sourceMarket:source,player,event:runtime.provider});}}
    for(const task of forecastTasks.slice(0,8))try{const input=await research.forecastInputs(task.event,task.player.name,task.sourceMarket),metric=opportunityMetricForMarket(task.sourceMarket),seedKey=`${task.game.gameId}:${task.player.canonicalPlayerId}`;for(const market of task.markets.filter(value=>legacyMarkets.includes(value))){const forecast=buildNflForecast(input,task.event,market,Date.parse(at));if(forecast.point)projections.set(`${seedKey}:${market}`,{projection:forecast.point.projection,version:forecast.version});}if(metric){const old=opportunitySeeds.get(seedKey),history=opportunityHistoryFromForecast(input,task.player.canonicalPlayerId,metric),dedup=new Map([...(old?.history??[]),...history].map(row=>[`${row.eventId}:${row.metric}`,row]));opportunitySeeds.set(seedKey,{history:[...dedup.values()],snapShare:input.snapContext?.recent.map(row=>({date:row.date,season:row.season,offenseSnaps:row.offenseSnaps,offensePct:row.offensePct}))??old?.snapShare??[],snapRetrievedAt:input.snapContext?.fetchedAt??old?.snapRetrievedAt??at,rosterStatus:input.player.rosterStatus,injuryStatuses:input.player.injuries.map(row=>row.status)});}}catch{/* Model/opportunity availability is represented explicitly in the snapshot. */}
    if(forecastTasks.length>8)deferred.push(`${forecastTasks.length-8} existing-formula prop projections deferred by public-source request cap.`);const injuryFailures=[...injuryReports.values()].filter(report=>!['PARTIAL_SUCCESS','SOURCE_RETURNED_EMPTY'].includes(report.status)).length,captureAt=new Date(this.now()).toISOString(),state:RuntimeState={at:captureAt,contexts,markets:marketMap,marketUsage,inactive,injuryReports,projections,opportunitySeeds,apiUsage:[espnUsage,{provider:'NFL.com',requests:1+injuryReports.size,estimatedCredits:0,actualCredits:0,cacheHits:0,retries:0,failures:(inactive.pageState==='MALFORMED_OR_UNVERIFIED'?1:0)+injuryFailures,deferred:[]},oddsUsage],failures,deferred};return{state,apiUsage:state.apiUsage,failures,deferred};}
  async capture(discovered:NflDiscoveredGame,prepared:NflPreparedRun,meta:{trigger:any;captureEventId:string;scheduledFor:string|null}):Promise<NewNflForwardSnapshot>{const state=prepared.state as RuntimeState,runtime=discovered.payload as RuntimeGame,context=state.contexts.get(discovered.gameId)!;let game=runtime.game,event=state.markets.get(discovered.gameId);if(event&&Date.parse(event.commence_time)!==Date.parse(game.scheduledKickoff))game={...game,scheduledKickoff:event.commence_time};const at=state.at,minutes=(Date.parse(game.scheduledKickoff)-Date.parse(at))/60_000;if(minutes<=0)throw Error('LEAKAGE_VIOLATION: provider kickoff moved to or before capture time.');const market=event?quoteEvidence(event,game,context.players,at):{gameMarkets:[],propMarkets:[],unresolved:new Map<string,string>(),available:new Set<string>()},footballEvidence:NflFootballEvidence[]=[],diagnostics:SixStageDiagnostic[]=[];
    const scheduleSource=source('ESPN',`${ESPN_NFL}/scoreboard`,at,runtime.espnEvent);
    for(const team of [game.home,game.away]){footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'SCHEDULE',field:'schedule.scheduled_kickoff',value:game.scheduledKickoff,source:scheduleSource,validity:'VALID',freshness:'FRESH'},{scope:'TEAM',entityId:team.canonicalTeamId,category:'VENUE',field:'venue.context',value:game.venue,source:scheduleSource,validity:'VALID',freshness:'FRESH'});const rosterOk=context.rosterStatus.get(team.canonicalTeamId)==='PASS',teamPlayers=context.players.filter(row=>row.teamId===team.canonicalTeamId),qb=context.depth.find(row=>row.position==='QB'&&row.listedOrder===1&&teamPlayers.some(player=>player.canonicalPlayerId===row.playerId)),summarySource=context.sources.find(row=>row.url.includes('/summary?')),weather=context.summary?.gameInfo?.weather??{},venue=context.summary?.gameInfo?.venue??{};if(rosterOk)footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'ROSTER',field:'roster.player_count',value:teamPlayers.length,source:source('ESPN',context.sources.find(row=>row.url.includes('/roster'))?.url??ESPN_NFL,at,{teamPlayers:teamPlayers.map(row=>row.canonicalPlayerId)}),validity:'VALID',freshness:'FRESH'});if(qb)footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'STARTING_QB',field:'starting_qb.expected_player',value:{canonicalPlayerId:qb.playerId,status:'PROBABLE'},source:source('ESPN',context.sources.find(row=>row.url.includes('/depthcharts'))?.url??ESPN_NFL,at,qb),validity:'VALID',freshness:'FRESH'});if(Object.keys(weather).length)footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'WEATHER',field:'weather.pregame_forecast',value:{temperatureF:weather.temperature??null,windMph:weather.windSpeed??null,gustMph:weather.gust??null,precipitationProbability:weather.precipitation??null,indoor:typeof venue.indoor==='boolean'?venue.indoor:null,forecastTimestamp:null},source:source('ESPN',summarySource?.url??ESPN_NFL,at,weather),validity:'VALID',freshness:'UNKNOWN'});
      for(const category of NFL_TEAM_CATEGORIES){const count=footballEvidence.filter(row=>row.entityId===team.canonicalTeamId&&row.category===category).length,base=category==='SCHEDULE'||category==='VENUE'?1:count;diagnostics.push(makeDiagnostic('TEAM',category,team.canonicalTeamId,at,base,1,category==='SCHEDULE'||category==='VENUE'?{SOURCE_RETRIEVAL:'PASS',NORMALIZATION:'PASS',ENTITY_MATCHING:'PASS',CONTEXT_ATTACHMENT:'PASS',FIELD_VALIDITY:'PASS',FRESHNESS_AT_FORECAST_TIME:'PASS'}:{},count?[]:[`${category} is unavailable at this forecast timestamp; no value was invented.`]));}}
    const propPlayerIds=new Set(market.propMarkets.map(row=>row.canonicalPlayerId).filter((id):id is string=>Boolean(id))),snapshotPlayers=context.players.filter(player=>propPlayerIds.has(player.canonicalPlayerId));
    const inactivePlayers=[] as NewNflForwardSnapshot['inactiveEvidence']['players'];for(const player of snapshotPlayers){const status=resolveGameDayAvailability(state.inactive,{providerGameId:game.providerGameIds.NFL,homeTeam:game.home.name,awayTeam:game.away.name},{providerPlayerId:player.providerPlayerIds.NFL,name:player.name,team:player.teamId===game.home.canonicalTeamId?game.home.name:game.away.name});inactivePlayers.push({canonicalPlayerId:player.canonicalPlayerId,state:status.state,reason:status.reason});const depth=context.depth.find(row=>row.playerId===player.canonicalPlayerId),hasMarket=market.propMarkets.some(row=>row.canonicalPlayerId===player.canonicalPlayerId);for(const category of NFL_PLAYER_CATEGORIES){const available=category==='PLAYER_IDENTITY'||category==='ACTIVE_ROSTER'||category==='OPPONENT'?1:category==='DEPTH_CHART_POSITION'||category==='STARTER_STATUS'?Number(Boolean(depth)):category==='GAME_DAY_AVAILABILITY'?Number(['ACTIVE_VERIFIED','INACTIVE_VERIFIED'].includes(status.state)):category==='MARKET_AVAILABILITY'?Number(hasMarket):0;diagnostics.push(makeDiagnostic('PLAYER',category,player.canonicalPlayerId,at,available,1,{},available?[]:[`${category} remains UNKNOWN at forecast time.`]));}}
    const propUniverse=[] as NewNflForwardSnapshot['propUniverse'];for(const key of NFL_FORWARD_POLICY.corePropMarkets){const rows=market.propMarkets.filter(row=>row.market===key),unresolved=[...market.unresolved.entries()].filter(([name])=>name.startsWith(`${key}:`));if(!rows.length&&!unresolved.length)propUniverse.push({market:key,participant:'',state:event?'PROP_NOT_POSTED':'MARKET_UNAVAILABLE',canonicalPlayerId:null,modelState:'MODEL_UNAVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:event?'STATUS_PENDING':'STATUS_UNKNOWN',projection:null,projectionVersion:null});for(const [name] of unresolved)propUniverse.push({market:key,participant:name.slice(key.length+1),state:'PLAYER_IDENTITY_UNRESOLVED',canonicalPlayerId:null,modelState:'MODEL_UNAVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:'STATUS_UNKNOWN',projection:null,projectionVersion:null});for(const playerId of new Set(rows.map(row=>row.canonicalPlayerId!))){const player=context.players.find(row=>row.canonicalPlayerId===playerId)!,availability=inactivePlayers.find(row=>row.canonicalPlayerId===playerId)?.state??'STATUS_UNKNOWN',projection=state.projections.get(`${discovered.gameId}:${playerId}:${key}`);propUniverse.push({market:key,participant:player.name,state:'PROP_MARKET_AVAILABLE',canonicalPlayerId:playerId,modelState:projection?'MODEL_AVAILABLE':'MODEL_UNAVAILABLE',researchState:projection&&availability==='ACTIVE_VERIFIED'?'RESEARCH_ELIGIBLE':'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability,projection:projection?.projection??null,projectionVersion:projection?.version??null});}}
    const opportunityProjections=snapshotPlayers.map(player=>{const seed=state.opportunitySeeds.get(`${discovered.gameId}:${player.canonicalPlayerId}`),availability=inactivePlayers.find(row=>row.canonicalPlayerId===player.canonicalPlayerId)?.state??'STATUS_UNKNOWN',flags:NflOpportunityFlag[]=[...(player.rookie==='YES'?['ROOKIE' as const]:[]),...(player.newTeam==='YES'?['NEW_TEAM' as const]:[])],teammateInactive=inactivePlayers.some(row=>row.canonicalPlayerId!==player.canonicalPlayerId&&row.state==='INACTIVE_VERIFIED'&&snapshotPlayers.find(item=>item.canonicalPlayerId===row.canonicalPlayerId)?.teamId===player.teamId);return buildNflOpportunityProjection({game,player,forecastAt:at,phase2Availability:availability,rosterStatus:seed?.rosterStatus??'UNKNOWN',injuryStatuses:seed?.injuryStatuses??[],depth:context.depth,depthRetrievedAt:at,history:seed?.history??[],snapShare:seed?.snapShare??[],snapRetrievedAt:seed?.snapRetrievedAt??at,teammateDependency:teammateInactive?'TEAMMATE_ROLE_CHANGE_DETECTED':'REDISTRIBUTION_UNKNOWN',flags});});
    const featurePackage=buildFeaturePackage({game,at,context,state,players:snapshotPlayers,inactivePlayers,market,opportunityProjections});
    const inactiveSource=source('NFL.com',state.inactive.source,state.inactive.retrievedAt,{pageState:state.inactive.pageState,hash:state.inactive.rawPayloadHash},state.inactive.sourceTimestamp);inactiveSource.rawPayloadHash=state.inactive.rawPayloadHash;return{schemaVersion:'nfl-forward-research-v1',evidenceClass:'LIVE_FORWARD',capturedAt:at,forecastAt:at,trigger:meta.trigger,captureEventId:meta.captureEventId,scheduledFor:meta.scheduledFor,minutesToKickoff:minutes,hoursToKickoff:minutes/60,...featurePackage,game,players:snapshotPlayers,footballEvidence,diagnostics,inactiveEvidence:{state:state.inactive.pageState,source:inactiveSource,players:inactivePlayers},gameMarkets:market.gameMarkets,propMarkets:market.propMarkets,propUniverse,opportunityProjections,model:{gameProjection:{status:'MODEL_UNAVAILABLE',homeScore:null,awayScore:null,homeMargin:null,version:'nfl-game-line-ridge-research-v2-audit-metrics'}},apiUsage:state.apiUsage,failures:state.failures.map(message=>({provider:'FORWARD_PIPELINE',category:'COLLECTION',message,at}))};}
}
