import {createHash} from 'crypto';
import {getNflForwardEventMarkets,getUpcomingEvents,UpcomingEvent} from '../api/oddsApiClient';
import {NFL_FORWARD_POLICY} from '../config/nflForwardPolicy';
import {NFL} from '../config/productionFocus';
import {RawEvent} from '../types/odds';
import {buildNflForecast} from './nflForecast';
import {attachOddsEvent,canonicalNflGame,canonicalPlayer,resolvePropPlayer,RosterSeed} from './nflForwardIdentities';
import {NflCollectorAdapter,NflDiscoveredGame,NflPreparedRun,NflRequestPlan} from './nflForwardOperations';
import {CanonicalNflGame,CanonicalNflPlayer,makeDiagnostic,NewNflForwardSnapshot,NFL_PLAYER_CATEGORIES,NFL_TEAM_CATEGORIES,NflFootballEvidence,NflMarketQuoteEvidence,SixStageDiagnostic} from './nflForwardResearch';
import {fetchOfficialInactives,OfficialInactiveObservation,resolveGameDayAvailability} from './nflGameDayAvailability';
import {flattenNflQuotes} from './nflMarketBoard';
import {ESPN_NFL,fetchNflJson,NflResearch,nflName} from './nflResearch';
import {buildNflOpportunityProjection,NflOpportunityFlag,NflOpportunityHistoryRow,opportunityHistoryFromForecast,opportunityMetricForMarket} from './nflOpportunityEngine';

const sha=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const day=(ms:number)=>new Date(ms).toISOString().slice(0,10).replace(/-/g,'');
interface RuntimeGame {espnEvent:any;game:CanonicalNflGame;provider:UpcomingEvent|null;}
interface GameContext {players:CanonicalNflPlayer[];rosterStatus:Map<string,'PASS'|'FAIL'>;depth:any[];summary:any|null;sources:Array<{provider:string;url:string;retrievedAt:string;payload:unknown}>;}
interface OpportunitySeed {history:NflOpportunityHistoryRow[];snapShare:Array<{date:string;season:number;offenseSnaps:number;offensePct:number}>;snapRetrievedAt:string;rosterStatus:string;injuryStatuses:string[];}
interface RuntimeState {at:string;contexts:Map<string,GameContext>;markets:Map<string,RawEvent>;marketUsage:Map<string,{credits:number|null}>;inactive:OfficialInactiveObservation;projections:Map<string,{projection:number;version:string}>;opportunitySeeds:Map<string,OpportunitySeed>;apiUsage:NflPreparedRun['apiUsage'];failures:string[];deferred:string[];}
function competitors(event:any){const c=event?.competitions?.[0],home=(c?.competitors??[]).find((row:any)=>row.homeAway==='home'),away=(c?.competitors??[]).find((row:any)=>row.homeAway==='away');return{competition:c,home,away};}
function source(provider:string,url:string,retrievedAt:string,payload:unknown,effectiveAt:string|null=null){return{provider,url,providerRecordId:null,retrievedAt,effectiveAt,rawPayloadHash:sha(payload)};}
function rosterRows(payload:any,team:CanonicalNflGame['home'],at:string):RosterSeed[]{const rows:RosterSeed[]=[];for(const group of payload?.athletes??[])for(const item of group?.items??[]){if(!item?.id||!item?.displayName||!item?.position?.abbreviation)continue;rows.push({id:String(item.id),name:String(item.displayName),teamId:team.canonicalTeamId,teamName:team.name,position:String(item.position.abbreviation),status:String(item.status?.name??'UNKNOWN'),rookie:typeof item.experience?.years==='number'?item.experience.years===0:undefined});}return rows;}
function exactDepth(payload:any,players:CanonicalNflPlayer[]){const result=[] as any[];for(const chart of payload?.depthchart??[])for(const [position,block] of Object.entries(chart?.positions??{}) as Array<[string,any]>)for(let i=0;i<(block?.athletes??[]).length;i++){const athlete=block.athletes[i],matches=players.filter(player=>player.providerPlayerIds.ESPN===String(athlete?.id??'')&&nflName(player.name)===nflName(athlete?.displayName));if(matches.length===1)result.push({playerId:matches[0].canonicalPlayerId,position,listedOrder:i+1,formation:String(chart?.name??'UNKNOWN')});}return result;}
function quoteEvidence(event:RawEvent,game:CanonicalNflGame,players:CanonicalNflPlayer[],at:string){const rawHash=sha(event),all=flattenNflQuotes(event,[...NFL_FORWARD_POLICY.coreGameMarkets,...NFL_FORWARD_POLICY.corePropMarkets],Date.parse(at)).filter(row=>!row.stale&&row.updatedAt&&Date.parse(row.updatedAt)<=Date.parse(at)),gameMarkets:NflMarketQuoteEvidence[]=[],propMarkets:NflMarketQuoteEvidence[]=[],unresolved=new Map<string,string>();for(const row of all){const base={canonicalGameId:game.canonicalGameId,market:row.market,side:row.side,line:row.line,price:row.price,sportsbook:row.book,providerEventId:event.id,quoteTimestamp:String(row.updatedAt),captureTimestamp:at,rawPayloadHash:rawHash,label:'CONTEMPORANEOUS_QUOTE' as const};if((NFL_FORWARD_POLICY.coreGameMarkets as readonly string[]).includes(row.market))gameMarkets.push({kind:'GAME',canonicalPlayerId:null,participant:row.participant||null,...base});else{const matched=resolvePropPlayer(row.participant,players,game);if(!matched.player){unresolved.set(`${row.market}:${row.participant}`,matched.reason!);continue;}propMarkets.push({kind:'PROP',canonicalPlayerId:matched.player.canonicalPlayerId,participant:matched.player.name,...base});}}
  return{gameMarkets,propMarkets,unresolved,available:new Set(all.map(row=>row.market))};}

export class LiveNflForwardCollectorAdapter implements NflCollectorAdapter {
  constructor(private now=()=>Date.now(),private get=fetchNflJson,private eventMarkets=getNflForwardEventMarkets,private events=()=>getUpcomingEvents(NFL),private inactives=fetchOfficialInactives){}
  async discover(at:string){
    const now=Date.parse(at),end=now+NFL_FORWARD_POLICY.horizonHours*3600_000;
    const url=`${ESPN_NFL}/scoreboard?dates=${day(now-86400_000)}-${day(end+86400_000)}&limit=200`;
    const failures:string[]=[],provider:UpcomingEvent[]=[];
    try{provider.push(...await this.events());}catch(error){failures.push(`Odds event discovery unavailable: ${error instanceof Error?error.message:String(error)}`);}
    let payload:any={events:[]};
    try{payload=await this.get(url);}catch(error){failures.push(`ESPN schedule discovery unavailable: ${error instanceof Error?error.message:String(error)}`);}
    const games:NflDiscoveredGame[]=[];
    for(const event of payload?.events??[])try{
      let game=canonicalNflGame(event,at);
      if(Date.parse(game.scheduledKickoff)>end||Date.parse(game.scheduledKickoff)<now-86400_000)continue;
      const attached=attachOddsEvent(game,provider);game=attached.game;
      games.push({gameId:game.canonicalGameId,kickoff:game.scheduledKickoff,status:game.status,missingIdentity:attached.provider?0:1,payload:{espnEvent:event,game,provider:attached.provider} satisfies RuntimeGame});
    }catch(error){failures.push(`NFL event identity rejected: ${error instanceof Error?error.message:String(error)}`);}
    return{games,requests:2,failures};
  }
  plan(games:NflDiscoveredGame[],at:string):NflRequestPlan[]{const marketGames=Math.min(games.filter(row=>(row.payload as RuntimeGame).provider).length,NFL_FORWARD_POLICY.maxOddsRequestsPerRun);return[
    {provider:'ESPN',category:'ROSTER_DEPTH_SUMMARY',maximumRequests:games.length*5,estimatedCredits:0,priority:1,scope:'Every eligible game; shared team payloads are cached per run.'},
    {provider:'NFL.com',category:'OFFICIAL_GAME_DAY_INACTIVES',maximumRequests:1,estimatedCredits:0,priority:2,scope:'One official-page observation for all eligible games.'},
    {provider:'The Odds API',category:'CORE_GAME_AND_PROP_MARKETS',maximumRequests:marketGames,estimatedCredits:marketGames*(NFL_FORWARD_POLICY.coreGameMarkets.length+NFL_FORWARD_POLICY.corePropMarkets.length),priority:3,scope:'One bounded no-retry request per matched event, nearest kickoff first.'},
  ];}
  async prepare(games:NflDiscoveredGame[],at:string):Promise<NflPreparedRun>{const contexts=new Map<string,GameContext>(),failures:string[]=[],deferred:string[]=[],teamCache=new Map<string,{roster:any;depth:any;retrievedAt:string}>(),espnUsage={provider:'ESPN',requests:0,estimatedCredits:0,actualCredits:0,cacheHits:0,retries:0,failures:0,deferred:[] as string[]};for(const discovered of games){const runtime=discovered.payload as RuntimeGame,players:CanonicalNflPlayer[]=[],rosterStatus=new Map<string,'PASS'|'FAIL'>(),sources:GameContext['sources']=[],depthRows:any[]=[];for(const team of [runtime.game.home,runtime.game.away]){let cached=teamCache.get(team.canonicalTeamId);if(cached)espnUsage.cacheHits+=2;else{const teamId=team.canonicalTeamId.replace('espn-team:',''),rosterUrl=`${ESPN_NFL}/teams/${teamId}/roster`,depthUrl=`${ESPN_NFL}/teams/${teamId}/depthcharts`;try{const [roster,depth]=await Promise.all([this.get(rosterUrl),this.get(depthUrl)]);espnUsage.requests+=2;cached={roster,depth,retrievedAt:at};teamCache.set(team.canonicalTeamId,cached);sources.push({provider:'ESPN',url:rosterUrl,retrievedAt:at,payload:roster},{provider:'ESPN',url:depthUrl,retrievedAt:at,payload:depth});}catch(error){espnUsage.failures++;rosterStatus.set(team.canonicalTeamId,'FAIL');failures.push(`${runtime.game.canonicalGameId}/${team.name}: roster/depth unavailable.`);continue;}}
        try{const seeds=rosterRows(cached.roster,team,at);if(Number(cached.roster?.season?.year)!==2026||String(cached.roster?.team?.id)!==team.canonicalTeamId.replace('espn-team:','')||!seeds.length)throw Error('roster mismatch');const teamPlayers=seeds.map(seed=>canonicalPlayer(seed,at));players.push(...teamPlayers);depthRows.push(...exactDepth(cached.depth,teamPlayers));rosterStatus.set(team.canonicalTeamId,'PASS');}catch{rosterStatus.set(team.canonicalTeamId,'FAIL');failures.push(`${runtime.game.canonicalGameId}/${team.name}: roster failed identity validation.`);}}
      let summary:any=null;const summaryUrl=`${ESPN_NFL}/summary?event=${runtime.game.providerGameIds.ESPN}`;try{summary=await this.get(summaryUrl);espnUsage.requests++;sources.push({provider:'ESPN',url:summaryUrl,retrievedAt:at,payload:summary});}catch{espnUsage.failures++;failures.push(`${runtime.game.canonicalGameId}: summary unavailable.`);}contexts.set(discovered.gameId,{players,rosterStatus,depth:depthRows,summary,sources});}
    const inactive=await this.inactives(()=>Date.parse(at));const marketMap=new Map<string,RawEvent>(),marketUsage=new Map<string,{credits:number|null}>(),oddsUsage={provider:'The Odds API',requests:0,estimatedCredits:0,actualCredits:0 as number|null,cacheHits:0,retries:0,failures:0,deferred:[] as string[]},eligible=[...games].filter(row=>(row.payload as RuntimeGame).provider).slice(0,NFL_FORWARD_POLICY.maxOddsRequestsPerRun);let estimated=0,actual=0,actualKnown=true;for(const discovered of eligible){const runtime=discovered.payload as RuntimeGame,cost=NFL_FORWARD_POLICY.coreGameMarkets.length+NFL_FORWARD_POLICY.corePropMarkets.length;if(estimated+cost>NFL_FORWARD_POLICY.maxOddsCreditsPerRun){deferred.push(`${discovered.gameId}: odds budget cap`);oddsUsage.deferred.push(discovered.gameId);continue;}estimated+=cost;try{const result=await this.eventMarkets(runtime.provider!.id,[...NFL_FORWARD_POLICY.coreGameMarkets,...NFL_FORWARD_POLICY.corePropMarkets]);oddsUsage.requests++;oddsUsage.estimatedCredits+=cost;if(result.creditsUsed===null)actualKnown=false;else actual+=result.creditsUsed;if(result.event)marketMap.set(discovered.gameId,result.event);marketUsage.set(discovered.gameId,{credits:result.creditsUsed});}catch(error){oddsUsage.requests++;oddsUsage.failures++;actualKnown=false;failures.push(`${discovered.gameId}: ${error instanceof Error?error.message:String(error)}`);}}
    oddsUsage.actualCredits=actualKnown?actual:null;const projections=new Map<string,{projection:number;version:string}>(),opportunitySeeds=new Map<string,OpportunitySeed>(),research=new NflResearch(this.get,()=>Date.parse(at)),legacyMarkets=['player_pass_yds','player_rush_yds','player_reception_yds','player_receptions'],sourceMarket=(market:string)=>['player_pass_attempts','player_pass_completions'].includes(market)?'player_pass_yds':market==='player_rush_attempts'?'player_rush_yds':market,forecastTasks:Array<{game:NflDiscoveredGame;markets:string[];sourceMarket:string;player:CanonicalNflPlayer;event:UpcomingEvent}>=[];for(const discovered of games){const runtime=discovered.payload as RuntimeGame,event=marketMap.get(discovered.gameId),context=contexts.get(discovered.gameId);if(!runtime.provider||!event||!context)continue;const parsed=quoteEvidence(event,runtime.game,context.players,at);for(const quote of parsed.propMarkets){const player=context.players.find(row=>row.canonicalPlayerId===quote.canonicalPlayerId)!,source=sourceMarket(quote.market),metric=opportunityMetricForMarket(quote.market);if(!metric)continue;const old=forecastTasks.find(row=>row.game.gameId===discovered.gameId&&row.sourceMarket===source&&row.player.canonicalPlayerId===player.canonicalPlayerId);if(old){if(!old.markets.includes(quote.market))old.markets.push(quote.market);}else forecastTasks.push({game:discovered,markets:[quote.market],sourceMarket:source,player,event:runtime.provider});}}
    for(const task of forecastTasks.slice(0,8))try{const input=await research.forecastInputs(task.event,task.player.name,task.sourceMarket),metric=opportunityMetricForMarket(task.sourceMarket),seedKey=`${task.game.gameId}:${task.player.canonicalPlayerId}`;for(const market of task.markets.filter(value=>legacyMarkets.includes(value))){const forecast=buildNflForecast(input,task.event,market,Date.parse(at));if(forecast.point)projections.set(`${seedKey}:${market}`,{projection:forecast.point.projection,version:forecast.version});}if(metric){const old=opportunitySeeds.get(seedKey),history=opportunityHistoryFromForecast(input,task.player.canonicalPlayerId,metric),dedup=new Map([...(old?.history??[]),...history].map(row=>[`${row.eventId}:${row.metric}`,row]));opportunitySeeds.set(seedKey,{history:[...dedup.values()],snapShare:input.snapContext?.recent.map(row=>({date:row.date,season:row.season,offenseSnaps:row.offenseSnaps,offensePct:row.offensePct}))??old?.snapShare??[],snapRetrievedAt:input.snapContext?.fetchedAt??old?.snapRetrievedAt??at,rosterStatus:input.player.rosterStatus,injuryStatuses:input.player.injuries.map(row=>row.status)});}}catch{/* Model/opportunity availability is represented explicitly in the snapshot. */}
    if(forecastTasks.length>8)deferred.push(`${forecastTasks.length-8} existing-formula prop projections deferred by public-source request cap.`);const state:RuntimeState={at,contexts,markets:marketMap,marketUsage,inactive,projections,opportunitySeeds,apiUsage:[espnUsage,{provider:'NFL.com',requests:1,estimatedCredits:0,actualCredits:0,cacheHits:0,retries:0,failures:inactive.pageState==='MALFORMED_OR_UNVERIFIED'?1:0,deferred:[]},oddsUsage],failures,deferred};return{state,apiUsage:state.apiUsage,failures,deferred};}
  async capture(discovered:NflDiscoveredGame,prepared:NflPreparedRun,meta:{trigger:any;captureEventId:string;scheduledFor:string|null}):Promise<NewNflForwardSnapshot>{const state=prepared.state as RuntimeState,runtime=discovered.payload as RuntimeGame,context=state.contexts.get(discovered.gameId)!;let game=runtime.game,event=state.markets.get(discovered.gameId);if(event&&Date.parse(event.commence_time)!==Date.parse(game.scheduledKickoff))game={...game,scheduledKickoff:event.commence_time};const at=state.at,minutes=(Date.parse(game.scheduledKickoff)-Date.parse(at))/60_000;if(minutes<=0)throw Error('LEAKAGE_VIOLATION: provider kickoff moved to or before capture time.');const market=event?quoteEvidence(event,game,context.players,at):{gameMarkets:[],propMarkets:[],unresolved:new Map<string,string>(),available:new Set<string>()},footballEvidence:NflFootballEvidence[]=[],diagnostics:SixStageDiagnostic[]=[];
    const scheduleSource=source('ESPN',`${ESPN_NFL}/scoreboard`,at,runtime.espnEvent);
    for(const team of [game.home,game.away]){footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'SCHEDULE',field:'schedule.scheduled_kickoff',value:game.scheduledKickoff,source:scheduleSource,validity:'VALID',freshness:'FRESH'},{scope:'TEAM',entityId:team.canonicalTeamId,category:'VENUE',field:'venue.context',value:game.venue,source:scheduleSource,validity:'VALID',freshness:'FRESH'});const rosterOk=context.rosterStatus.get(team.canonicalTeamId)==='PASS',teamPlayers=context.players.filter(row=>row.teamId===team.canonicalTeamId),qb=context.depth.find(row=>row.position==='QB'&&row.listedOrder===1&&teamPlayers.some(player=>player.canonicalPlayerId===row.playerId)),summarySource=context.sources.find(row=>row.url.includes('/summary?')),weather=context.summary?.gameInfo?.weather??{},venue=context.summary?.gameInfo?.venue??{};if(rosterOk)footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'ROSTER',field:'roster.player_count',value:teamPlayers.length,source:source('ESPN',context.sources.find(row=>row.url.includes('/roster'))?.url??ESPN_NFL,at,{teamPlayers:teamPlayers.map(row=>row.canonicalPlayerId)}),validity:'VALID',freshness:'FRESH'});if(qb)footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'STARTING_QB',field:'starting_qb.expected_player',value:{canonicalPlayerId:qb.playerId,status:'PROBABLE'},source:source('ESPN',context.sources.find(row=>row.url.includes('/depthcharts'))?.url??ESPN_NFL,at,qb),validity:'VALID',freshness:'FRESH'});if(Object.keys(weather).length)footballEvidence.push({scope:'TEAM',entityId:team.canonicalTeamId,category:'WEATHER',field:'weather.observation',value:{temperatureF:weather.temperature??null,windMph:weather.windSpeed??null,gustMph:weather.gust??null,precipitationProbability:weather.precipitation??null,indoor:typeof venue.indoor==='boolean'?venue.indoor:null},source:source('ESPN',summarySource?.url??ESPN_NFL,at,weather),validity:'VALID',freshness:'FRESH'});
      for(const category of NFL_TEAM_CATEGORIES){const count=footballEvidence.filter(row=>row.entityId===team.canonicalTeamId&&row.category===category).length,base=category==='SCHEDULE'||category==='VENUE'?1:count;diagnostics.push(makeDiagnostic('TEAM',category,team.canonicalTeamId,at,base,1,category==='SCHEDULE'||category==='VENUE'?{SOURCE_RETRIEVAL:'PASS',NORMALIZATION:'PASS',ENTITY_MATCHING:'PASS',CONTEXT_ATTACHMENT:'PASS',FIELD_VALIDITY:'PASS',FRESHNESS_AT_FORECAST_TIME:'PASS'}:{},count?[]:[`${category} is unavailable at this forecast timestamp; no value was invented.`]));}}
    const propPlayerIds=new Set(market.propMarkets.map(row=>row.canonicalPlayerId).filter((id):id is string=>Boolean(id))),snapshotPlayers=context.players.filter(player=>propPlayerIds.has(player.canonicalPlayerId));
    const inactivePlayers=[] as NewNflForwardSnapshot['inactiveEvidence']['players'];for(const player of snapshotPlayers){const status=resolveGameDayAvailability(state.inactive,{providerGameId:game.providerGameIds.NFL,homeTeam:game.home.name,awayTeam:game.away.name},{providerPlayerId:player.providerPlayerIds.NFL,name:player.name,team:player.teamId===game.home.canonicalTeamId?game.home.name:game.away.name});inactivePlayers.push({canonicalPlayerId:player.canonicalPlayerId,state:status.state,reason:status.reason});const depth=context.depth.find(row=>row.playerId===player.canonicalPlayerId),hasMarket=market.propMarkets.some(row=>row.canonicalPlayerId===player.canonicalPlayerId);for(const category of NFL_PLAYER_CATEGORIES){const available=category==='PLAYER_IDENTITY'||category==='ACTIVE_ROSTER'||category==='OPPONENT'?1:category==='DEPTH_CHART_POSITION'||category==='STARTER_STATUS'?Number(Boolean(depth)):category==='GAME_DAY_AVAILABILITY'?Number(['ACTIVE_VERIFIED','INACTIVE_VERIFIED'].includes(status.state)):category==='MARKET_AVAILABILITY'?Number(hasMarket):0;diagnostics.push(makeDiagnostic('PLAYER',category,player.canonicalPlayerId,at,available,1,{},available?[]:[`${category} remains UNKNOWN at forecast time.`]));}}
    const propUniverse=[] as NewNflForwardSnapshot['propUniverse'];for(const key of NFL_FORWARD_POLICY.corePropMarkets){const rows=market.propMarkets.filter(row=>row.market===key),unresolved=[...market.unresolved.entries()].filter(([name])=>name.startsWith(`${key}:`));if(!rows.length&&!unresolved.length)propUniverse.push({market:key,participant:'',state:event?'PROP_NOT_POSTED':'MARKET_UNAVAILABLE',canonicalPlayerId:null,modelState:'MODEL_UNAVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:event?'STATUS_PENDING':'STATUS_UNKNOWN',projection:null,projectionVersion:null});for(const [name] of unresolved)propUniverse.push({market:key,participant:name.slice(key.length+1),state:'PLAYER_IDENTITY_UNRESOLVED',canonicalPlayerId:null,modelState:'MODEL_UNAVAILABLE',researchState:'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability:'STATUS_UNKNOWN',projection:null,projectionVersion:null});for(const playerId of new Set(rows.map(row=>row.canonicalPlayerId!))){const player=context.players.find(row=>row.canonicalPlayerId===playerId)!,availability=inactivePlayers.find(row=>row.canonicalPlayerId===playerId)?.state??'STATUS_UNKNOWN',projection=state.projections.get(`${discovered.gameId}:${playerId}:${key}`);propUniverse.push({market:key,participant:player.name,state:'PROP_MARKET_AVAILABLE',canonicalPlayerId:playerId,modelState:projection?'MODEL_AVAILABLE':'MODEL_UNAVAILABLE',researchState:projection&&availability==='ACTIVE_VERIFIED'?'RESEARCH_ELIGIBLE':'RESEARCH_INELIGIBLE',recommendationState:'NOT_EVALUATED_PHASE_2',availability,projection:projection?.projection??null,projectionVersion:projection?.version??null});}}
    const opportunityProjections=snapshotPlayers.map(player=>{const seed=state.opportunitySeeds.get(`${discovered.gameId}:${player.canonicalPlayerId}`),availability=inactivePlayers.find(row=>row.canonicalPlayerId===player.canonicalPlayerId)?.state??'STATUS_UNKNOWN',flags:NflOpportunityFlag[]=[...(player.rookie==='YES'?['ROOKIE' as const]:[]),...(player.newTeam==='YES'?['NEW_TEAM' as const]:[])],teammateInactive=inactivePlayers.some(row=>row.canonicalPlayerId!==player.canonicalPlayerId&&row.state==='INACTIVE_VERIFIED'&&snapshotPlayers.find(item=>item.canonicalPlayerId===row.canonicalPlayerId)?.teamId===player.teamId);return buildNflOpportunityProjection({game,player,forecastAt:at,phase2Availability:availability,rosterStatus:seed?.rosterStatus??'UNKNOWN',injuryStatuses:seed?.injuryStatuses??[],depth:context.depth,depthRetrievedAt:at,history:seed?.history??[],snapShare:seed?.snapShare??[],snapRetrievedAt:seed?.snapRetrievedAt??at,teammateDependency:teammateInactive?'TEAMMATE_ROLE_CHANGE_DETECTED':'REDISTRIBUTION_UNKNOWN',flags});});
    const inactiveSource=source('NFL.com',state.inactive.source,state.inactive.retrievedAt,{pageState:state.inactive.pageState,hash:state.inactive.rawPayloadHash},state.inactive.sourceTimestamp);inactiveSource.rawPayloadHash=state.inactive.rawPayloadHash;return{schemaVersion:'nfl-forward-research-v1',evidenceClass:'LIVE_FORWARD',capturedAt:at,forecastAt:at,trigger:meta.trigger,captureEventId:meta.captureEventId,scheduledFor:meta.scheduledFor,minutesToKickoff:minutes,hoursToKickoff:minutes/60,game,players:snapshotPlayers,footballEvidence,diagnostics,inactiveEvidence:{state:state.inactive.pageState,source:inactiveSource,players:inactivePlayers},gameMarkets:market.gameMarkets,propMarkets:market.propMarkets,propUniverse,opportunityProjections,model:{gameProjection:{status:'MODEL_UNAVAILABLE',homeScore:null,awayScore:null,homeMargin:null,version:'nfl-game-line-ridge-research-v2-audit-metrics'}},apiUsage:state.apiUsage,failures:state.failures.map(message=>({provider:'FORWARD_PIPELINE',category:'COLLECTION',message,at}))};}
}
