import {createHash} from 'crypto';
import {UpcomingEvent} from '../api/oddsApiClient';
import {CanonicalNflGame,CanonicalNflPlayer,NflScheduleState} from './nflForwardResearch';
import {nflName} from './nflResearch';

const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
function team(competition:any,side:'home'|'away'){const rows=(competition?.competitors??[]).filter((row:any)=>row.homeAway===side);if(rows.length!==1||!rows[0]?.team?.id)throw Error(`Canonical ${side} team identity unresolved.`);return rows[0].team;}
export function nflExplicitScheduleState(event:any):NflScheduleState{const type=event?.status?.type,name=String(type?.name??'').toUpperCase(),state=String(type?.state??'').toLowerCase();if(type?.completed===true&&state==='post'&&['STATUS_FINAL','STATUS_FINAL_OVERTIME'].includes(name))return'FINAL';if(['STATUS_CANCELED','STATUS_CANCELLED'].includes(name))return'CANCELED';if(name==='STATUS_POSTPONED')return'POSTPONED';if(name==='STATUS_ABANDONED')return'ABANDONED';if(state==='in'||['STATUS_IN_PROGRESS','STATUS_HALFTIME','STATUS_DELAYED'].includes(name))return'IN_PROGRESS';if(state==='pre'&&['STATUS_SCHEDULED','STATUS_TIME_TBD'].includes(name))return'SCHEDULED';return'UNKNOWN';}
export function canonicalNflGame(event:any,retrievedAt:string):CanonicalNflGame{const competition=event?.competitions?.[0],home=team(competition,'home'),away=team(competition,'away'),kickoff=String(event?.date??''),season=Number(event?.season?.year),seasonType=Number(event?.season?.type)===1?'PRE':Number(event?.season?.type)===2?'REG':Number(event?.season?.type)===3?'POST':'UNKNOWN';if(season!==2026||!/^\d+$/.test(String(event?.id??''))||!Number.isFinite(Date.parse(kickoff)))throw Error('Canonical NFL game identity unresolved.');const venue=competition?.venue??{},country=String(venue?.address?.country??'').toUpperCase();return{canonicalGameId:`espn:${event.id}`,providerGameIds:{ESPN:String(event.id)},season:2026,seasonType,week:Number.isInteger(Number(event?.week?.number))?Number(event.week.number):null,away:{canonicalTeamId:`espn-team:${away.id}`,name:String(away.displayName??away.name),abbreviation:away.abbreviation??null},home:{canonicalTeamId:`espn-team:${home.id}`,name:String(home.displayName??home.name),abbreviation:home.abbreviation??null},scheduledKickoff:kickoff,venue:{id:venue.id==null?null:String(venue.id),name:venue.fullName??null,indoor:typeof venue.indoor==='boolean'?venue.indoor:null},neutralSite:competition?.neutralSite===true,international:Boolean(country&&country!=='USA'&&country!=='US'&&country!=='UNITED STATES'),status:nflExplicitScheduleState(event)};}
export function attachOddsEvent(game:CanonicalNflGame,events:UpcomingEvent[]){const matches=events.filter(row=>nflName(row.homeTeam)===nflName(game.home.name)&&nflName(row.awayTeam)===nflName(game.away.name)&&Math.abs(Date.parse(row.commenceTime)-Date.parse(game.scheduledKickoff))<=3*3600_000);if(matches.length!==1)return{game,provider:null,reason:matches.length?'Ambiguous odds-provider game identity.':'No exact odds-provider game identity match.'};return{game:{...game,providerGameIds:{...game.providerGameIds,ODDS_API:matches[0].id}},provider:matches[0],reason:null};}
export interface RosterSeed {id:string;name:string;teamId:string;teamName:string;position:string;status:string;rookie?:boolean;previousTeamId?:string|null;previousPosition?:string|null;}
export function canonicalPlayer(seed:RosterSeed,effectiveAt:string):CanonicalNflPlayer{if(!/^\d+$/.test(seed.id)||!seed.teamId||!seed.name||!seed.position)throw Error('Canonical player identity unresolved.');return{canonicalPlayerId:`espn-player:${seed.id}`,providerPlayerIds:{ESPN:seed.id},name:seed.name,teamId:seed.teamId,position:seed.position,season:2026,effectiveAt,rookie:seed.rookie===true?'YES':seed.rookie===false?'NO':'UNKNOWN',newTeam:seed.previousTeamId==null?'UNKNOWN':seed.previousTeamId===seed.teamId?'NO':'YES',teamChange:seed.previousTeamId==null?'UNKNOWN':seed.previousTeamId===seed.teamId?'UNCHANGED':'CHANGED',positionChange:seed.previousPosition==null?'UNKNOWN':seed.previousPosition===seed.position?'UNCHANGED':'CHANGED'};}
export function resolvePropPlayer(participant:string,players:CanonicalNflPlayer[],game:CanonicalNflGame){const normalized=nflName(participant),teams=new Set([game.home.canonicalTeamId,game.away.canonicalTeamId]),matches=players.filter(row=>teams.has(row.teamId)&&nflName(row.name)===normalized);if(matches.length!==1)return{player:null,reason:matches.length?'Duplicate player name across game rosters.':'Player is absent from current game rosters.'};return{player:matches[0],reason:null};}
export function fallbackCanonicalGameId(season:number,week:number|null,awayId:string,homeId:string,kickoff:string){return`nfl:${sha(`${season}|${week??'unknown'}|${awayId}|${homeId}|${kickoff}`).slice(0,24)}`;}
