import {NFL_OPPORTUNITY_POLICY,NflOpportunityMetric} from './nflOpportunityEngine';

export const NFL_OPPORTUNITY_EVALUATION_VERSION='nfl-opportunity-evaluation-v1';
export type OpportunityPartition='DEVELOPMENT'|'VALIDATION'|'LOCKED_HOLDOUT';
export type OpportunityCandidate='LAST_GAME'|'LAST_3_AVERAGE'|'SEASON_AVERAGE'|'PREVIOUS_SEASON_AVERAGE'|'WEIGHTED_RECENT_ROLE'|'SHARE_TEAM_VOLUME'|'EARLY_SEASON_PRIOR_BLEND';
export interface OpportunityTargetRow {playerId:string;playerName:string;gameId:string;date:string;season:number;teamId:string;position:'QB'|'RB'|'WR'|'TE';metric:NflOpportunityMetric;actual:number;teamOpportunity:number|null;}
export interface OpportunityEvaluationPolicy {validationStart:string;holdoutStart:string;end:string;minimumHistory:number;minimumEvaluationN:number;minimumImprovement:number;maximumAbsoluteBias:number;requiredPositions:Array<'QB'|'RB'|'WR'|'TE'>;}
export const DEFAULT_OPPORTUNITY_EVALUATION_POLICY:OpportunityEvaluationPolicy=Object.freeze({validationStart:'2025-08-01T00:00:00.000Z',holdoutStart:'2025-10-16T00:00:00.000Z',end:'2026-02-16T00:00:00.000Z',minimumHistory:4,minimumEvaluationN:200,minimumImprovement:.02,maximumAbsoluteBias:1.5,requiredPositions:['QB','RB','WR','TE'] as Array<'QB'|'RB'|'WR'|'TE'>});
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
const prediction=(candidate:OpportunityCandidate,history:OpportunityTargetRow[],target:OpportunityTargetRow)=>{const ordered=[...history].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).slice(-NFL_OPPORTUNITY_POLICY.maximumHistory),recent=ordered.slice(-3),current=ordered.filter(row=>row.season===target.season),prior=ordered.filter(row=>row.season===target.season-1),avg=(rows:OpportunityTargetRow[])=>mean(rows.map(row=>row.actual));if(ordered.length<NFL_OPPORTUNITY_POLICY.minimumHistory)return null;
  if(candidate==='LAST_GAME')return ordered.at(-1)!.actual;if(candidate==='LAST_3_AVERAGE')return avg(recent);if(candidate==='SEASON_AVERAGE')return avg(current.length?current:prior);if(candidate==='PREVIOUS_SEASON_AVERAGE')return avg(prior);
  if(candidate==='WEIGHTED_RECENT_ROLE'){const a=avg(ordered),r=avg(recent);return a===null||r===null?null:.6*r+.4*a;}
  if(candidate==='SHARE_TEAM_VOLUME'){const usable=ordered.filter(row=>row.teamOpportunity!==null&&row.teamOpportunity>0),r=usable.slice(-3);if(usable.length<NFL_OPPORTUNITY_POLICY.minimumHistory)return null;const longShare=mean(usable.map(row=>row.actual/row.teamOpportunity!)),recentShare=mean(r.map(row=>row.actual/row.teamOpportunity!)),longVolume=mean(usable.map(row=>row.teamOpportunity!)),recentVolume=mean(r.map(row=>row.teamOpportunity!));return[longShare,recentShare,longVolume,recentVolume].some(value=>value===null)?null:(.6*recentShare!+.4*longShare!)*(.6*recentVolume!+.4*longVolume!);}
  const priorMean=avg(prior),currentMean=avg(current);if(priorMean===null&&currentMean===null)return null;if(priorMean===null)return currentMean;if(currentMean===null)return priorMean;const currentWeight=Math.min(1,current.length/NFL_OPPORTUNITY_POLICY.earlySeasonTransitionGames);return currentWeight*currentMean+(1-currentWeight)*priorMean;};
export function opportunityPartition(date:string,policy:OpportunityEvaluationPolicy=DEFAULT_OPPORTUNITY_EVALUATION_POLICY):OpportunityPartition|null{const at=Date.parse(date);if(!Number.isFinite(at)||at>=Date.parse(policy.end))return null;if(at<Date.parse(policy.validationStart))return'DEVELOPMENT';return at<Date.parse(policy.holdoutStart)?'VALIDATION':'LOCKED_HOLDOUT';}
function metrics(rows:Array<{actual:number;prediction:number}>){const errors=rows.map(row=>row.actual-row.prediction),mae=mean(errors.map(Math.abs)),mse=mean(errors.map(value=>value**2));return{n:rows.length,mae,rmse:mse===null?null:Math.sqrt(mse),bias:mean(errors),coverage:null as number|null};}
export function evaluateOpportunityCandidates(rows:OpportunityTargetRow[],policy:OpportunityEvaluationPolicy=DEFAULT_OPPORTUNITY_EVALUATION_POLICY){const seen=new Set<string>();for(const row of rows){const key=`${row.playerId}:${row.gameId}:${row.metric}`;if(seen.has(key))throw Error('Duplicate player-game opportunity target.');seen.add(key);if(!row.playerId||!row.gameId||!row.teamId||!Number.isFinite(Date.parse(row.date))||!Number.isInteger(row.actual)||row.actual<0||row.teamOpportunity!==null&&(!Number.isInteger(row.teamOpportunity)||row.teamOpportunity<=0||row.actual>row.teamOpportunity))throw Error('Invalid opportunity target row.');}
  const ordered=[...rows].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)||a.playerId.localeCompare(b.playerId)),candidates:OpportunityCandidate[]=['LAST_GAME','LAST_3_AVERAGE','SEASON_AVERAGE','PREVIOUS_SEASON_AVERAGE','WEIGHTED_RECENT_ROLE','SHARE_TEAM_VOLUME','EARLY_SEASON_PRIOR_BLEND'],tests:Array<{candidate:OpportunityCandidate;partition:OpportunityPartition;playerId:string;gameId:string;date:string;position:string;metric:NflOpportunityMetric;actual:number;prediction:number;trainingGames:number;trainingThrough:string}>=[];
  for(const target of ordered){const partition=opportunityPartition(target.date,policy);if(!partition||partition==='DEVELOPMENT')continue;const history=ordered.filter(row=>row.playerId===target.playerId&&row.metric===target.metric&&row.teamId===target.teamId&&Date.parse(row.date)<Date.parse(target.date));for(const candidate of candidates){const value=prediction(candidate,history,target);if(value===null||!Number.isFinite(value))continue;tests.push({candidate,partition,playerId:target.playerId,gameId:target.gameId,date:target.date,position:target.position,metric:target.metric,actual:target.actual,prediction:value,trainingGames:history.length,trainingThrough:history.at(-1)!.date});}}
  const summarize=(candidate:OpportunityCandidate,partition:OpportunityPartition,subset=tests.filter(row=>row.candidate===candidate&&row.partition===partition))=>{const eligibleTargets=ordered.filter(row=>opportunityPartition(row.date,policy)===partition).length,result=metrics(subset);result.coverage=eligibleTargets?subset.length/eligibleTargets:null;return result;},summaries=Object.fromEntries(candidates.map(candidate=>[candidate,{validation:summarize(candidate,'VALIDATION'),holdout:summarize(candidate,'LOCKED_HOLDOUT')}])) as Record<OpportunityCandidate,{validation:ReturnType<typeof metrics>;holdout:ReturnType<typeof metrics>}>;
  const simple:OpportunityCandidate[]=['LAST_GAME','LAST_3_AVERAGE','SEASON_AVERAGE','PREVIOUS_SEASON_AVERAGE'],research:OpportunityCandidate[]=['WEIGHTED_RECENT_ROLE','SHARE_TEAM_VOLUME','EARLY_SEASON_PRIOR_BLEND'],best=(list:OpportunityCandidate[])=>[...list].filter(candidate=>summaries[candidate].validation.mae!==null).sort((a,b)=>summaries[a].validation.mae!-summaries[b].validation.mae!||a.localeCompare(b))[0]??null,baseline=best(simple),selected=best(research),holdoutBaseline=baseline?summaries[baseline].holdout:null,holdoutSelected=selected?summaries[selected].holdout:null,positions=[...new Set(rows.map(row=>row.position))].sort(),missingPositions=policy.requiredPositions.filter(value=>!positions.includes(value));
  const byPosition=Object.fromEntries(policy.requiredPositions.map(position=>[position,Object.fromEntries(candidates.map(candidate=>[candidate,metrics(tests.filter(row=>row.partition==='LOCKED_HOLDOUT'&&row.position===position&&row.candidate===candidate))]))])),byMetric=Object.fromEntries([...new Set(rows.map(row=>row.metric))].sort().map(metric=>[metric,Object.fromEntries(candidates.map(candidate=>[candidate,metrics(tests.filter(row=>row.partition==='LOCKED_HOLDOUT'&&row.metric===metric&&row.candidate===candidate))]))]));
  const gates={sample:Boolean(holdoutSelected&&holdoutSelected.n>=policy.minimumEvaluationN),mae:Boolean(holdoutSelected?.mae!==null&&holdoutBaseline?.mae!==null&&holdoutSelected!.mae!<=holdoutBaseline!.mae!*(1-policy.minimumImprovement)),rmse:Boolean(holdoutSelected?.rmse!==null&&holdoutBaseline?.rmse!==null&&holdoutSelected!.rmse!<=holdoutBaseline!.rmse!*(1-policy.minimumImprovement)),bias:Boolean(holdoutSelected?.bias!==null&&Math.abs(holdoutSelected!.bias!)<=policy.maximumAbsoluteBias),allMajorPositions:missingPositions.length===0,chronologicalIntegrity:tests.every(row=>Date.parse(row.trainingThrough)<Date.parse(row.date)),marketFree:true};
  const sampleLabel=(holdoutSelected?.n??0)<50?'INSUFFICIENT FOR MODEL CONCLUSION':(holdoutSelected?.n??0)<200?'PRELIMINARY':'RESEARCH-EVALUABLE',decision=missingPositions.length?'PLAYER OPPORTUNITY ENGINE BLOCKED BY DATA QUALITY':Object.values(gates).every(Boolean)?'PLAYER OPPORTUNITY ENGINE PASSES RESEARCH GATE':(holdoutSelected?.n??0)<policy.minimumEvaluationN?'PLAYER OPPORTUNITY ENGINE INCONCLUSIVE — MORE DATA REQUIRED':'PLAYER OPPORTUNITY ENGINE FAILS RESEARCH GATE';
  return{schemaVersion:NFL_OPPORTUNITY_EVALUATION_VERSION,policy,rows:rows.length,partitions:{development:ordered.filter(row=>opportunityPartition(row.date,policy)==='DEVELOPMENT').length,validation:ordered.filter(row=>opportunityPartition(row.date,policy)==='VALIDATION').length,lockedHoldout:ordered.filter(row=>opportunityPartition(row.date,policy)==='LOCKED_HOLDOUT').length},candidates:summaries,selectedCandidate:selected,baseline,byPosition,byMetric,gates,positions,missingPositions,sampleLabel,tests,decision,note:'Opportunity targets are final box-score counts. Every predictor uses only earlier games. No odds, prices, betting outcomes, or target-game workload enter a prediction.'};
}
