import {CanonicalNflGame,CanonicalNflPlayer} from './nflForwardResearch';
import {GameDayAvailabilityState} from './nflGameDayAvailability';
import {NflForecastInput} from './nflForecast';
import {nflSeason} from './nflResearch';

export const NFL_OPPORTUNITY_MODEL_VERSION='nfl-player-opportunity-shadow-v1';
export const NFL_OPPORTUNITY_POLICY=Object.freeze({minimumHistory:4,recentGames:3,maximumHistory:20,earlySeasonTransitionGames:6,stableShareRange:0.18});
export type NflOpportunityMetric='PASS_ATTEMPTS'|'RUSH_ATTEMPTS'|'TARGETS';
export type NflOpportunityAvailability='ACTIVE_VERIFIED'|'EXPECTED_ACTIVE'|'QUESTIONABLE'|'DOUBTFUL'|'INACTIVE_VERIFIED'|'STATUS_PENDING'|'STATUS_UNKNOWN';
export type NflOpportunityRole='QB1'|'QB2'|'STARTER_UNVERIFIED'|'COMMITTEE_PACKAGE_ROLE'|'RB1'|'RB2'|'RB3'|'COMMITTEE'|'PASSING_DOWN_BACK'|'SHORT_YARDAGE_GOAL_LINE'|'WR1'|'WR2'|'WR3'|'SLOT'|'OUTSIDE'|'ROTATIONAL'|'TE1'|'TE2'|'BLOCKING_HEAVY'|'UNKNOWN';
export type NflOpportunityUncertainty='LOW_UNCERTAINTY'|'MODERATE_UNCERTAINTY'|'HIGH_UNCERTAINTY'|'MODEL_UNAVAILABLE';
export type NflOpportunityStatus='PROJECTED_SHADOW'|'INACTIVE_VERIFIED'|'AVAILABILITY_PENDING'|'OPPORTUNITY_DATA_INSUFFICIENT'|'OPPORTUNITY_MODEL_UNAVAILABLE'|'LEAKAGE_VIOLATION'|'MARKET_CONTAMINATION';
export type NflOpportunityFlag='ROOKIE'|'NEW_TEAM'|'NEW_QB'|'NEW_OC'|'ROLE_CHANGE'|'RETURNING_FROM_INJURY'|'LIMITED_SAMPLE';
export type NflTeammateDependency='TEAMMATE_ROLE_CHANGE_DETECTED'|'REDISTRIBUTION_RESEARCH_AVAILABLE'|'REDISTRIBUTION_UNKNOWN';

export interface NflOpportunityHistoryRow {eventId:string;date:string;season:number;playerId:string;teamId:string;metric:NflOpportunityMetric;opportunity:number;teamOpportunity:number|null;sourceRetrievedAt:string;evidenceClass:'VERIFIED_POINT_IN_TIME'|'SAFE_HISTORICAL_SNAPSHOT'|'RECONSTRUCTED_WITHOUT_FUTURE_INFO';}
export interface NflOpportunityInput {game:CanonicalNflGame;player:CanonicalNflPlayer;forecastAt:string;phase2Availability:GameDayAvailabilityState;rosterStatus:string;injuryStatuses:string[];depth:Array<{playerId:string;position:string;listedOrder:number;formation:string}>;depthRetrievedAt:string;history:NflOpportunityHistoryRow[];snapShare:Array<{date:string;season:number;offenseSnaps:number;offensePct:number}>;snapRetrievedAt:string;teammateDependency:NflTeammateDependency;flags:NflOpportunityFlag[];}
export interface NflOpportunityProjection {schemaVersion:'nfl-player-opportunity-v1';opportunityModelVersion:typeof NFL_OPPORTUNITY_MODEL_VERSION;researchOnly:true;productionEnabled:false;canonicalGameId:string;canonicalPlayerId:string;teamId:string;position:string;forecastAt:string;featureTimestamp:string|null;modelTimestamp:string;availabilityState:NflOpportunityAvailability;roleState:NflOpportunityRole;teammateDependency:NflTeammateDependency;flags:NflOpportunityFlag[];status:NflOpportunityStatus;uncertainty:NflOpportunityUncertainty;currentSeasonGames:number;priorSeasonGames:number;priorSeasonWeight:number|null;currentSeasonWeight:number|null;expectedTeamPassAttempts:number|null;expectedTeamRushAttempts:number|null;expectedPassAttempts:number|null;expectedCompletionsOpportunities:number|null;expectedDesignedRushes:number|null;expectedScrambleOpportunities:number|null;expectedCarries:number|null;expectedRoutes:number|null;expectedTargets:number|null;expectedGoalLineOpportunities:number|null;targetShare:number|null;carryShare:number|null;routeParticipation:number|null;snapShare:number|null;roleVolatility:number|null;marketInputsUsed:false;failureStates:string[];method:string;}

const forbidden=/(^|[._ -])(spread|total|moneyline|sportsbook|consensus|implied.?probability|prop.?line|over.?price|under.?price|line.?movement)([._ -]|$)/i;
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
const weighted=(rows:NflOpportunityHistoryRow[],key:'opportunity'|'teamOpportunity')=>{const usable=rows.filter(row=>typeof row[key]==='number') as Array<NflOpportunityHistoryRow&{teamOpportunity:number}>,recent=usable.slice(-NFL_OPPORTUNITY_POLICY.recentGames),all=usable.slice(-NFL_OPPORTUNITY_POLICY.maximumHistory),a=avg(all.map(row=>Number(row[key]))),r=avg(recent.map(row=>Number(row[key])));return a===null||r===null?null:.6*r+.4*a;};
const round=(value:number|null)=>value===null?null:Number(value.toFixed(3));
function position(position:string){const value=position.toUpperCase();return value==='HB'||value==='FB'?'RB':value;}
function marketKeys(value:unknown,path='input'):string[]{if(!value||typeof value!=='object')return[];const found:string[]=[];for(const [key,row] of Object.entries(value as Record<string,unknown>)){const next=`${path}.${key}`;if(forbidden.test(key))found.push(next);else found.push(...marketKeys(row,next));}return found;}

export function opportunityAvailability(input:{phase2Availability:GameDayAvailabilityState;rosterStatus:string;injuryStatuses:string[]}):NflOpportunityAvailability{
  if(input.phase2Availability==='ACTIVE_VERIFIED')return'ACTIVE_VERIFIED';
  if(input.phase2Availability==='INACTIVE_VERIFIED')return'INACTIVE_VERIFIED';
  const injuries=input.injuryStatuses.join(' ').toLowerCase();
  if(/\bdoubtful\b/.test(injuries))return'DOUBTFUL';
  if(/\bquestionable\b/.test(injuries))return'QUESTIONABLE';
  if(input.phase2Availability==='STATUS_PENDING')return'STATUS_PENDING';
  if(input.phase2Availability==='STATUS_UNKNOWN')return'STATUS_UNKNOWN';
  return input.rosterStatus.toLowerCase()==='active'?'EXPECTED_ACTIVE':'STATUS_UNKNOWN';
}

export function classifyNflOpportunityRole(player:Pick<CanonicalNflPlayer,'canonicalPlayerId'|'position'>,depth:NflOpportunityInput['depth'],history:NflOpportunityHistoryRow[],snapShare:NflOpportunityInput['snapShare']):NflOpportunityRole{
  const group=position(player.position),row=depth.find(item=>item.playerId===player.canonicalPlayerId),shares=history.filter(item=>item.teamOpportunity&&item.teamOpportunity>0).slice(-5).map(item=>item.opportunity/item.teamOpportunity!),mean=avg(shares),volatility=shares.length>1?Math.max(...shares)-Math.min(...shares):null,snap=avg(snapShare.slice(-5).map(item=>item.offensePct));
  if(group==='QB'){if(!row)return'UNKNOWN';if(row.listedOrder===1)return'STARTER_UNVERIFIED';if(row.listedOrder===2)return'QB2';return'COMMITTEE_PACKAGE_ROLE';}
  if(group==='RB'){if(volatility!==null&&volatility>NFL_OPPORTUNITY_POLICY.stableShareRange)return'COMMITTEE';if(!row)return'UNKNOWN';if(row.listedOrder===1)return'RB1';if(row.listedOrder===2)return'RB2';if(row.listedOrder===3)return'RB3';return'ROTATIONAL';}
  if(group==='WR'){if(row?.formation.toLowerCase().includes('slot'))return'SLOT';if(!row)return'UNKNOWN';if(row.listedOrder===1)return'WR1';if(row.listedOrder===2)return'WR2';if(row.listedOrder===3)return'WR3';return'ROTATIONAL';}
  if(group==='TE'){if(row?.listedOrder===1&&snap!==null&&snap>=.65&&mean!==null&&mean<.08)return'BLOCKING_HEAVY';if(!row)return'UNKNOWN';if(row.listedOrder===1)return'TE1';if(row.listedOrder===2)return'TE2';return'ROTATIONAL';}
  return'UNKNOWN';
}

function empty(input:NflOpportunityInput,availability:NflOpportunityAvailability,role:NflOpportunityRole,status:NflOpportunityStatus,failures:string[],uncertainty:NflOpportunityUncertainty='MODEL_UNAVAILABLE'):NflOpportunityProjection{return{schemaVersion:'nfl-player-opportunity-v1',opportunityModelVersion:NFL_OPPORTUNITY_MODEL_VERSION,researchOnly:true,productionEnabled:false,canonicalGameId:input.game.canonicalGameId,canonicalPlayerId:input.player.canonicalPlayerId,teamId:input.player.teamId,position:position(input.player.position),forecastAt:input.forecastAt,featureTimestamp:null,modelTimestamp:input.forecastAt,availabilityState:availability,roleState:role,teammateDependency:input.teammateDependency,flags:[...new Set(input.flags)].sort() as NflOpportunityFlag[],status,uncertainty,currentSeasonGames:0,priorSeasonGames:0,priorSeasonWeight:null,currentSeasonWeight:null,expectedTeamPassAttempts:null,expectedTeamRushAttempts:null,expectedPassAttempts:null,expectedCompletionsOpportunities:null,expectedDesignedRushes:null,expectedScrambleOpportunities:null,expectedCarries:null,expectedRoutes:null,expectedTargets:null,expectedGoalLineOpportunities:null,targetShare:null,carryShare:null,routeParticipation:null,snapShare:null,roleVolatility:null,marketInputsUsed:false,failureStates:failures,method:'Availability → role → team volume → player opportunity. Efficiency and final production are intentionally downstream.'};}

export function buildNflOpportunityProjection(input:NflOpportunityInput):NflOpportunityProjection{
  const forecast=Date.parse(input.forecastAt),availability=opportunityAvailability(input),role=classifyNflOpportunityRole(input.player,input.depth,input.history,input.snapShare),contamination=marketKeys({history:input.history,depth:input.depth,snapShare:input.snapShare});
  if(contamination.length)return empty(input,availability,role,'MARKET_CONTAMINATION',[`Forbidden market fields: ${contamination.join(', ')}`]);
  if(!Number.isFinite(forecast)||Date.parse(input.player.effectiveAt)>forecast||Date.parse(input.depthRetrievedAt)>forecast||Date.parse(input.snapRetrievedAt)>forecast||input.snapShare.some(row=>!Number.isFinite(Date.parse(row.date))||Date.parse(row.date)>=forecast||!Number.isInteger(row.offenseSnaps)||row.offenseSnaps<0||!Number.isFinite(row.offensePct)||row.offensePct<0||row.offensePct>1)||input.game.canonicalGameId===''||!input.player.canonicalPlayerId)return empty(input,availability,role,'LEAKAGE_VIOLATION',['Invalid or future forecast, identity, depth, or snap evidence.']);
  const seen=new Set<string>(),safe:NflOpportunityHistoryRow[]=[];for(const row of input.history){const key=`${row.playerId}:${row.eventId}:${row.metric}`;if(seen.has(key))return empty(input,availability,role,'OPPORTUNITY_MODEL_UNAVAILABLE',['Duplicate player-game opportunity evidence.']);seen.add(key);if(row.playerId!==input.player.canonicalPlayerId||row.teamId!==input.player.teamId)return empty(input,availability,role,'OPPORTUNITY_MODEL_UNAVAILABLE',['Cross-player, cross-team, or traded-player history mismatch.']);if(!Number.isFinite(Date.parse(row.date))||Date.parse(row.date)>=forecast||Date.parse(row.sourceRetrievedAt)>forecast)return empty(input,availability,role,'LEAKAGE_VIOLATION',['Opportunity evidence was unavailable at forecast time.']);if(!Number.isInteger(row.opportunity)||row.opportunity<0||row.teamOpportunity!==null&&(!Number.isInteger(row.teamOpportunity)||row.teamOpportunity<=0||row.opportunity>row.teamOpportunity))return empty(input,availability,role,'OPPORTUNITY_MODEL_UNAVAILABLE',['Invalid opportunity numerator or team denominator.']);safe.push(row);}
  if(availability==='INACTIVE_VERIFIED'){const result=empty(input,availability,role,'INACTIVE_VERIFIED',['Zero-opportunity diagnostic only; no normal projection produced.'],'LOW_UNCERTAINTY');const group=position(input.player.position);if(group==='QB')result.expectedPassAttempts=0;if(group==='RB')result.expectedCarries=0;if(['RB','WR','TE'].includes(group))result.expectedTargets=0;return result;}
  if(availability==='STATUS_UNKNOWN'||availability==='DOUBTFUL')return empty(input,availability,role,'OPPORTUNITY_MODEL_UNAVAILABLE',[`Availability is ${availability}; normal workload was not assumed.`]);
  if(role==='UNKNOWN')return empty(input,availability,role,'OPPORTUNITY_MODEL_UNAVAILABLE',['ROLE_UNKNOWN']);
  const relevant=safe.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).slice(-NFL_OPPORTUNITY_POLICY.maximumHistory),current=relevant.filter(row=>row.season===input.game.season),prior=relevant.filter(row=>row.season===input.game.season-1),currentGames=new Set(current.map(row=>row.eventId)).size,priorGames=new Set(prior.map(row=>row.eventId)).size,newTeam=input.player.newTeam==='YES'||input.player.teamChange==='CHANGED';
  if(newTeam&&!current.length)return empty(input,availability,role,'OPPORTUNITY_DATA_INSUFFICIENT',['NEW_TEAM history is not transferred into a new offense without current-team evidence.']);
  if(relevant.length<NFL_OPPORTUNITY_POLICY.minimumHistory)return empty(input,availability,role,'OPPORTUNITY_DATA_INSUFFICIENT',[`Need ${NFL_OPPORTUNITY_POLICY.minimumHistory} earlier verified opportunity games; found ${relevant.length}.`]);
  const byMetric=(metric:NflOpportunityMetric)=>relevant.filter(row=>row.metric===metric),projection=(metric:NflOpportunityMetric)=>{const rows=byMetric(metric);if(rows.length<NFL_OPPORTUNITY_POLICY.minimumHistory)return null;const direct=weighted(rows,'opportunity'),withTeams=rows.filter(row=>row.teamOpportunity!==null);if(withTeams.length<NFL_OPPORTUNITY_POLICY.minimumHistory)return direct;const share=weighted(withTeams.map(row=>({...row,opportunity:row.opportunity/row.teamOpportunity!})) as any,'opportunity'),volume=weighted(withTeams,'teamOpportunity');return share===null||volume===null?direct:share*volume;};
  const group=position(input.player.position),pass=projection('PASS_ATTEMPTS'),rush=projection('RUSH_ATTEMPTS'),targets=projection('TARGETS'),teamPass=weighted(byMetric('PASS_ATTEMPTS'),'teamOpportunity'),teamRush=weighted(byMetric('RUSH_ATTEMPTS'),'teamOpportunity'),sharesFor=(metric:NflOpportunityMetric)=>byMetric(metric).filter(row=>row.teamOpportunity!==null).slice(-5).map(row=>row.opportunity/row.teamOpportunity!),carryShares=sharesFor('RUSH_ATTEMPTS'),targetShares=sharesFor('TARGETS'),roleShares=group==='RB'?carryShares:targetShares,carryShare=avg(carryShares),targetShare=avg(targetShares),volatility=roleShares.length>1?Math.max(...roleShares)-Math.min(...roleShares):null,snaps=input.snapShare.filter(row=>Date.parse(row.date)<forecast).slice(-5),snap=avg(snaps.map(row=>row.offensePct));
  const currentWeight=currentGames?Math.min(1,currentGames/NFL_OPPORTUNITY_POLICY.earlySeasonTransitionGames):0,priorWeight=priorGames?1-currentWeight:0,flags=[...new Set([...input.flags,...(currentGames<3?['LIMITED_SAMPLE' as const]:[])])].sort() as NflOpportunityFlag[];
  const expected=group==='QB'?pass:group==='RB'?(rush??targets):targets;if(expected===null)return empty({...input,flags},availability,role,'OPPORTUNITY_DATA_INSUFFICIENT',['No position-relevant opportunity series cleared minimum history.']);
  const uncertainty:NflOpportunityUncertainty=availability==='STATUS_PENDING'||availability==='QUESTIONABLE'||currentGames<2||newTeam||flags.includes('ROOKIE')?'HIGH_UNCERTAINTY':priorWeight>0||volatility!==null&&volatility>NFL_OPPORTUNITY_POLICY.stableShareRange||(['WR','TE'].includes(group)&&snap===null)?'MODERATE_UNCERTAINTY':'LOW_UNCERTAINTY';
  return{...empty({...input,flags},availability,role,availability==='STATUS_PENDING'?'AVAILABILITY_PENDING':'PROJECTED_SHADOW',[],uncertainty),featureTimestamp:relevant.at(-1)?.date??null,currentSeasonGames:currentGames,priorSeasonGames:priorGames,priorSeasonWeight:round(priorWeight),currentSeasonWeight:round(currentWeight),expectedTeamPassAttempts:round(teamPass),expectedTeamRushAttempts:round(teamRush),expectedPassAttempts:round(group==='QB'?pass:null),expectedCompletionsOpportunities:round(group==='QB'?pass:null),expectedDesignedRushes:null,expectedScrambleOpportunities:null,expectedCarries:round(group==='RB'?rush:null),expectedRoutes:null,expectedTargets:round(['RB','WR','TE'].includes(group)?targets:null),expectedGoalLineOpportunities:null,targetShare:round(['RB','WR','TE'].includes(group)?targetShare:null),carryShare:round(group==='RB'?carryShare:null),routeParticipation:null,snapShare:round(snap),roleVolatility:round(volatility),failureStates:[...(availability==='STATUS_PENDING'?['AVAILABILITY_PENDING']:[]),...(['WR','TE'].includes(group)?['ROUTE_DATA_UNAVAILABLE']:[]),...(group==='QB'?['DESIGNED_RUSH_AND_SCRAMBLE_SPLIT_UNAVAILABLE']:[]),...(input.teammateDependency==='REDISTRIBUTION_UNKNOWN'?['REDISTRIBUTION_UNKNOWN']:[])]};
}

export function opportunityMetricForMarket(market:string):NflOpportunityMetric|null{if(['player_pass_yds','player_pass_attempts','player_pass_completions'].includes(market))return'PASS_ATTEMPTS';if(['player_rush_yds','player_rush_attempts'].includes(market))return'RUSH_ATTEMPTS';if(['player_reception_yds','player_receptions'].includes(market))return'TARGETS';return null;}

export function opportunityHistoryFromForecast(input:NflForecastInput,canonicalPlayerId:string,metric:NflOpportunityMetric):NflOpportunityHistoryRow[]{const totals=new Map((input.workloadContext?.rows??[]).map(row=>[row.eventId,row.teamOpportunity]));return input.observations.map(row=>({eventId:row.eventId,date:row.date,season:nflSeason(row.date),playerId:canonicalPlayerId,teamId:`espn-team:${row.teamId}`,metric,opportunity:row.opportunity??NaN,teamOpportunity:totals.get(row.eventId)??null,sourceRetrievedAt:input.sources.find(source=>source.season===nflSeason(row.date))?.fetchedAt??input.asOf,evidenceClass:'RECONSTRUCTED_WITHOUT_FUTURE_INFO' as const})).filter(row=>Number.isFinite(row.opportunity));}
