import * as fs from 'fs';
import * as path from 'path';
import {gunzipSync} from 'zlib';
import type {EventSummary} from '../types/odds';
import {NflForwardArchive,NflForwardSnapshot,NflMarketQuoteEvidence} from './nflForwardResearch';
import {buildNflSpreadFeatureRows,NflSpreadGame,parseNflSpreadSourceCsv,predictSpread,RidgeModel} from './nflSpreadPhase3A';
import {buildNflTotalFeatureRows,NflTotalGame,parseNflTotalSourceCsv,predictTotal,TotalRidgeModel} from './nflTotalPhase3B';

export const NFL_PREDICTIVE_BOARD_VERSION='nfl-predictive-board-v1';
export const NFL_PREDICTIVE_BOARD_POLICY=Object.freeze({
  displayMinimum:60,
  protectedCutoff:'2026-09-08T02:19:07.588Z',
  collectionMode:'MANUAL_ONLY',
  scheduledCollection:'DISABLED_BY_CONFIGURATION',
  marketFreshMinutes:15,
  keyNumbers:[3,7] as const,
});

export type GradeTier='ELITE'|'STRONG'|'PLAYABLE'|'LEAN'|'WEAK / INFORMATIONAL'|'BELOW DISPLAY THRESHOLD';
export type BoardDataQuality='PASS'|'PARTIAL'|'FAIL'|'UNKNOWN';
export type ReliabilityState='PASSED'|'FAILED'|'BLOCKED'|'UNKNOWN';
export type MovementState='SUPPORTS'|'OPPOSES'|'NEUTRAL'|'UNAVAILABLE';
export type OpportunityType='SPREAD'|'MONEYLINE'|'TOTAL'|'TEAM_TOTAL'|'PLAYER_PROP'|'SGP'|'PARLAY';
export type FailureState='IDENTITY_UNRESOLVED'|'MARKET_UNAVAILABLE'|'PLAYER_INACTIVE'|'FORECAST_UNAVAILABLE'|'LEAKAGE_VIOLATION'|'DATA_INVALID'|'STARTED_GAME';

export interface GradeComponent {name:string;earned:number;maximum:number;reason:string;}
export interface GradeInput {
  market:OpportunityType;
  edgeMagnitude:number;
  edgeScale:number;
  reliability:ReliabilityState;
  dataQuality:BoardDataQuality;
  availability:'VERIFIED_ACTIVE'|'PENDING_OR_QUESTIONABLE'|'UNKNOWN'|'INACTIVE';
  roleCertainty:'VERIFIED'|'PARTIAL'|'UNKNOWN';
  stabilitySamples:number;
  bookCount:number;
  dispersion:number|null;
  price:number|null;
  matchupSupport:'SUPPORTS'|'OPPOSES'|'UNKNOWN';
  currentSeasonSamples:number;
  movement:MovementState;
  dependencySafe:boolean;
  extremeDisagreement:boolean;
}
export interface GradeResult {grade:number;tier:GradeTier;isProbability:false;components:GradeComponent[];caps:string[];}

export interface DecisionOpportunity {
  id:string;gameId:string;type:OpportunityType;label:string;direction:string;line:number|null;projection:number|null;difference:number|null;
  grade:number;tier:GradeTier;isProbability:false;price:number|null;sportsbook:string|null;consensus:number|null;range:[number,number]|null;
  dataQuality:BoardDataQuality;availability:string;role:string;marketFresh:boolean;recommendable:boolean;why:string[];risks:string[];
  components:GradeComponent[];caps:string[];modelFamily:string;thesis:string[];
}

export interface IndependentFootballForecast {
  status:'PROJECTED'|'FORECAST_UNAVAILABLE';homeScore:number|null;awayScore:number|null;homeMargin:number|null;total:number|null;
  rawMargin:number|null;rawTotal:number|null;winner:string|null;version:string;latestInputDate:string|null;currentSeasonSamples:number;
  reconciliation:string;reason:string|null;
}

export interface PredictiveGameInput {
  id:string;homeName:string;awayName:string;homeCode:string|null;awayCode:string|null;kickoff:string;seasonType:'REG'|'PRE'|'POST'|'UNKNOWN';week:number|null;
  neutral:boolean;capturedAt:string;quotes:NflMarketQuoteEvidence[];propProjections:Array<{playerId:string|null;player:string;market:string;projection:number;version:string;availability:string;role:string}>;
  dataQuality:BoardDataQuality;failures:string[];snapshotCount:number;source:'LIVE_SCAN'|'FORWARD_ARCHIVE';
}

export interface PredictiveGameBoard {
  gameId:string;matchup:string;kickoff:string;source:PredictiveGameInput['source'];capturedAt:string;forecast:IndependentFootballForecast;
  projectedWinnerStrength:string;gameScript:string;spread:DecisionOpportunity|null;moneyline:DecisionOpportunity|null;total:DecisionOpportunity|null;
  teamTotals:DecisionOpportunity[];playerProps:DecisionOpportunity[];derivatives:Array<{market:string;status:'FORECAST_UNAVAILABLE';reason:string}>;
  sgps:DecisionOpportunity[];bestGameAngle:DecisionOpportunity|null;dataQuality:BoardDataQuality;keyRisks:string[];failures:FailureState[];
}

export interface NflPredictiveBoard {
  schemaVersion:typeof NFL_PREDICTIVE_BOARD_VERSION;generatedAt:string;gradeMeaning:string;collection:{mode:'MANUAL_ONLY';scheduled:'DISABLED_BY_CONFIGURATION';protectedCutoff:string;newPaidProviderCalls:0;newPaidCredits:0};
  games:PredictiveGameBoard[];topOverall:DecisionOpportunity[];bestByType:Partial<Record<OpportunityType,DecisionOpportunity>>;parlays:DecisionOpportunity[];
  gradeDistribution:Record<'60-69'|'70-77'|'78-84'|'85-89'|'90-100',number>;below60:number;diagnostics:string[];
  finalDecision:'NFL PREDICTIVE BOARD READY WITH KNOWN RESEARCH LIMITATIONS';
}

const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
const round=(value:number,digits=1)=>Number(value.toFixed(digits));
const median=(values:number[])=>{const rows=[...values].sort((a,b)=>a-b);if(!rows.length)return null;const mid=Math.floor(rows.length/2);return rows.length%2?rows[mid]:(rows[mid-1]+rows[mid])/2;};
const range=(values:number[]):[number,number]|null=>values.length?[Math.min(...values),Math.max(...values)]:null;
const norm=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,'');
const americanDecimal=(price:number)=>price>0?1+price/100:1+100/Math.abs(price);
const decimalAmerican=(decimal:number)=>decimal>=2?Math.round((decimal-1)*100):Math.round(-100/(decimal-1));

export function gradeTier(grade:number):GradeTier {
  if(grade>=90)return'ELITE';if(grade>=85)return'STRONG';if(grade>=78)return'PLAYABLE';if(grade>=70)return'LEAN';
  if(grade>=60)return'WEAK / INFORMATIONAL';return'BELOW DISPLAY THRESHOLD';
}
export const displayedOpportunity=(grade:number)=>grade>=NFL_PREDICTIVE_BOARD_POLICY.displayMinimum;

function points(name:string,earned:number,maximum:number,reason:string):GradeComponent{return{name,earned:round(clamp(earned,0,maximum),1),maximum,reason};}
export function gradeOpportunity(input:GradeInput):GradeResult {
  const reliability={PASSED:18,UNKNOWN:9,FAILED:6,BLOCKED:4}[input.reliability];
  const quality={PASS:15,PARTIAL:9,UNKNOWN:5,FAIL:0}[input.dataQuality];
  const availability={VERIFIED_ACTIVE:10,PENDING_OR_QUESTIONABLE:4,UNKNOWN:3,INACTIVE:0}[input.availability];
  const role={VERIFIED:5,PARTIAL:3,UNKNOWN:1}[input.roleCertainty];
  const dispersionPenalty=input.dispersion===null?2:input.dispersion>1.5?4:input.dispersion>.5?2:0;
  const price=input.price===null?1:input.price<=-400?0:input.price<=-250?2:input.price<=-180?3:input.price<=-130?4:input.price<100?5:6;
  const matchup={SUPPORTS:5,OPPOSES:0,UNKNOWN:2}[input.matchupSupport];
  const movement={SUPPORTS:2,NEUTRAL:1,UNAVAILABLE:1,OPPOSES:0}[input.movement];
  const components=[
    points('MODEL_MARKET_DISAGREEMENT',input.edgeScale>0?22*input.edgeMagnitude/input.edgeScale:0,22,`${round(input.edgeMagnitude)} units versus a ${input.edgeScale}-unit full-credit reference; disagreement alone cannot dominate.`),
    points('HISTORICAL_RELIABILITY',reliability,18,`${input.reliability} research state.`),
    points('DATA_QUALITY',quality,15,`${input.dataQuality} forecast-time inputs.`),
    points('AVAILABILITY',availability,10,`${input.availability.replaceAll('_',' ')}.`),
    points('ROLE_CERTAINTY',role,5,`${input.roleCertainty} role evidence.`),
    points('PROJECTION_STABILITY',8*Math.min(input.stabilitySamples,3)/3,8,`${input.stabilitySamples} independent captured observation(s), capped at three.`),
    points('MARKET_CONSENSUS',(input.bookCount>=6?8:input.bookCount>=3?6:input.bookCount>=2?4:1)-dispersionPenalty,8,`${input.bookCount} books; dispersion ${input.dispersion===null?'unavailable':round(input.dispersion)}.`),
    points('PRICE',price,6,input.price===null?'Price unavailable.':`American price ${input.price}; expensive favorites receive less credit.`),
    points('MATCHUP_SUPPORT',matchup,5,`${input.matchupSupport} independent matchup evidence.`),
    points('CURRENT_SAMPLE',input.currentSeasonSamples>=8?4:input.currentSeasonSamples>=3?3:input.currentSeasonSamples>0?2:1,4,`${input.currentSeasonSamples} current-season input game(s).`),
    points('TIMESTAMP_SAFE_MOVEMENT',movement,2,`${input.movement} movement evidence.`),
    points('DEPENDENCY_INTEGRITY',input.dependencySafe?2:0,2,input.dependencySafe?'No detected contradiction.':'Dependency or cross-market contradiction detected.'),
  ];
  let grade=Math.round(components.reduce((sum,row)=>sum+row.earned,0)),caps:string[]=[];
  if(input.extremeDisagreement&&input.reliability!=='PASSED'){grade=Math.min(grade,69);caps.push('Extreme disagreement cannot exceed 69 while the model has not passed research validation.');}
  if(input.dataQuality==='FAIL'){grade=Math.min(grade,49);caps.push('Failed data quality blocks primary-board recommendation.');}
  if(input.availability==='INACTIVE'){grade=Math.min(grade,49);caps.push('Verified inactive player blocks normal overs and primary-board recommendation.');}
  if(input.reliability==='BLOCKED'){grade=Math.min(grade,77);caps.push('Data-quality-blocked research cannot earn STRONG or ELITE status.');}
  return{grade:clamp(grade,0,100),tier:gradeTier(grade),isProbability:false,components,caps};
}

export function reconcilePredictedScore(rawHomeMargin:number,rawTotal:number){
  if(!Number.isFinite(rawHomeMargin)||!Number.isFinite(rawTotal)||rawTotal<=0||Math.abs(rawHomeMargin)>rawTotal)throw Error('Invalid independent margin/total for score reconciliation.');
  // Half-point display units are exactly representable in binary floating
  // point, so the published score arithmetic remains literally consistent.
  const half=(value:number)=>Math.round(value*2)/2,homeScore=half((rawTotal+rawHomeMargin)/2),awayScore=half((rawTotal-rawHomeMargin)/2),total=homeScore+awayScore,homeMargin=homeScore-awayScore;
  return{homeScore,awayScore,total,homeMargin,rawHomeMargin:round(rawHomeMargin,3),rawTotal:round(rawTotal,3),method:'Algebraic midpoint: home=(independent total + independent home margin)/2; away=(independent total - independent home margin)/2. Displayed component scores are rounded to half-points, then displayed margin and total are re-derived exactly from those scores.'};
}

const teamCodes:Record<string,string>={
  'Arizona Cardinals':'ARI','Atlanta Falcons':'ATL','Baltimore Ravens':'BAL','Buffalo Bills':'BUF','Carolina Panthers':'CAR','Chicago Bears':'CHI','Cincinnati Bengals':'CIN','Cleveland Browns':'CLE','Dallas Cowboys':'DAL','Denver Broncos':'DEN','Detroit Lions':'DET','Green Bay Packers':'GB','Houston Texans':'HOU','Indianapolis Colts':'IND','Jacksonville Jaguars':'JAX','Kansas City Chiefs':'KC','Las Vegas Raiders':'LV','Los Angeles Chargers':'LAC','Los Angeles Rams':'LA','Miami Dolphins':'MIA','Minnesota Vikings':'MIN','New England Patriots':'NE','New Orleans Saints':'NO','New York Giants':'NYG','New York Jets':'NYJ','Philadelphia Eagles':'PHI','Pittsburgh Steelers':'PIT','San Francisco 49ers':'SF','Seattle Seahawks':'SEA','Tampa Bay Buccaneers':'TB','Tennessee Titans':'TEN','Washington Commanders':'WAS',
};
const codeAlias:Record<string,string>={LAR:'LA',WSH:'WAS'};
const divisions=[['BUF','MIA','NE','NYJ'],['BAL','CIN','CLE','PIT'],['HOU','IND','JAX','TEN'],['DEN','KC','LAC','LV'],['DAL','NYG','PHI','WAS'],['CHI','DET','GB','MIN'],['ATL','CAR','NO','TB'],['ARI','LA','SF','SEA']];
const sameDivision=(a:string,b:string)=>divisions.some(group=>group.includes(a)&&group.includes(b));
const centralDate=(timestamp:string)=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(timestamp)),at=(type:string)=>parts.find(row=>row.type===type)!.value;return`${at('year')}-${at('month')}-${at('day')}`;};
const code=(name:string,value:string|null)=>codeAlias[value??'']??value??teamCodes[name]??null;

interface LockedResources {spreadGames:NflSpreadGame[];totalGames:NflTotalGame[];spreadModel:RidgeModel;totalModel:TotalRidgeModel;spreadDecision:string;totalDecision:string;}
const resourceCache=new Map<string,LockedResources>();
function lockedResources(projectRoot:string):LockedResources {
  const root=path.resolve(projectRoot),old=resourceCache.get(root);if(old)return old;
  const source=gunzipSync(fs.readFileSync(path.join(root,'research','nfl-spread-phase3a','sources','games.csv.gz'))).toString('utf8');
  const spreadArtifact=JSON.parse(fs.readFileSync(path.join(root,'research','nfl-spread-phase3a','artifact.json'),'utf8'));
  const totalArtifact=JSON.parse(fs.readFileSync(path.join(root,'research','nfl-total-phase3b','artifact.json'),'utf8'));
  const result={spreadGames:parseNflSpreadSourceCsv(source).games,totalGames:parseNflTotalSourceCsv(source).games,spreadModel:spreadArtifact.selected.lockedModel,totalModel:totalArtifact.selected.lockedModel,spreadDecision:String(spreadArtifact.decision),totalDecision:String(totalArtifact.decision)};
  resourceCache.set(root,result);return result;
}
const restDays=(games:NflSpreadGame[],team:string,date:string)=>{const at=Date.parse(date),latest=games.filter(row=>row.gameType==='REG'&&(row.homeId===team||row.awayId===team)&&Date.parse(row.date)<at).at(-1);return latest?Math.max(0,Math.round((at-Date.parse(latest.date))/86400_000)):null;};

export function independentGameForecast(input:PredictiveGameInput,projectRoot:string):IndependentFootballForecast {
  const home=code(input.homeName,input.homeCode),away=code(input.awayName,input.awayCode);
  if(input.seasonType!=='REG')return{status:'FORECAST_UNAVAILABLE',homeScore:null,awayScore:null,homeMargin:null,total:null,rawMargin:null,rawTotal:null,winner:null,version:'LOCKED_PHASE3_RESEARCH_MODELS',latestInputDate:null,currentSeasonSamples:0,reconciliation:'Not performed.',reason:'Only regular-season forecasts are supported by the locked research models.'};
  if(!home||!away||home===away)return{status:'FORECAST_UNAVAILABLE',homeScore:null,awayScore:null,homeMargin:null,total:null,rawMargin:null,rawTotal:null,winner:null,version:'LOCKED_PHASE3_RESEARCH_MODELS',latestInputDate:null,currentSeasonSamples:0,reconciliation:'Not performed.',reason:'IDENTITY_UNRESOLVED: canonical nflverse team mapping is unavailable.'};
  try{
    const resources=lockedResources(projectRoot),date=`${centralDate(input.kickoff)}T12:00:00.000Z`,base:NflSpreadGame={id:`board:${input.id}`,season:2026,gameType:'REG',week:input.week??1,date,weekday:'',awayId:away,homeId:home,awayScore:0,homeScore:0,neutral:input.neutral,overtime:false,awayRest:restDays(resources.spreadGames,away,date),homeRest:restDays(resources.spreadGames,home,date),spreadLine:null,awaySpreadOdds:null,homeSpreadOdds:null,divisional:sameDivision(home,away),roof:null,temperature:null,wind:null,awayQbId:null,homeQbId:null,awayCoach:null,homeCoach:null,stadiumId:null};
    const spreadPolicy={teamRatingRidge:20,teamRatingHalfLifeDays:365,priorSeasonShrinkGames:8,currentSeasonBlendGames:4,rollingGames:4,minimumPriorGamesPerTeam:8};
    const totalPolicy={opponentRidge:20,opponentHalfLifeDays:365,currentSeasonBlendGames:4,rollingGames:4,minimumPriorGamesPerTeam:8};
    const spreadRow=buildNflSpreadFeatureRows([...resources.spreadGames,base],2026,2026,spreadPolicy).rows.find(row=>row.id===base.id);
    const totalTarget:NflTotalGame={...base,totalLine:null,underOdds:null,overOdds:null,primetime:false};
    const totalRow=buildNflTotalFeatureRows([...resources.totalGames,totalTarget],2026,2026,totalPolicy).rows.find(row=>row.id===base.id);
    if(!spreadRow||!totalRow)throw Error('Required prior-team history was unavailable.');
    const rawMargin=predictSpread(resources.spreadModel,spreadRow),rawTotal=predictTotal(resources.totalModel,totalRow),score=reconcilePredictedScore(rawMargin,rawTotal);
    return{status:'PROJECTED',homeScore:score.homeScore,awayScore:score.awayScore,homeMargin:score.homeMargin,total:score.total,rawMargin:score.rawHomeMargin,rawTotal:score.rawTotal,winner:score.homeMargin>=0?input.homeName:input.awayName,version:`${resources.spreadModel.version}+${resources.totalModel.version}; BOTH FAILED RESEARCH GATES`,latestInputDate:[spreadRow.latestInputDate,totalRow.latestInputDate].sort().at(-1)!,currentSeasonSamples:Math.min(spreadRow.currentHomeGames,spreadRow.currentAwayGames,totalRow.currentHomeGames,totalRow.currentAwayGames),reconciliation:score.method,reason:null};
  }catch(error){return{status:'FORECAST_UNAVAILABLE',homeScore:null,awayScore:null,homeMargin:null,total:null,rawMargin:null,rawTotal:null,winner:null,version:'LOCKED_PHASE3_RESEARCH_MODELS',latestInputDate:null,currentSeasonSamples:0,reconciliation:'Not performed.',reason:error instanceof Error?error.message:String(error)};}
}

function quality(snapshot:NflForwardSnapshot):BoardDataQuality {if(snapshot.failures.length||snapshot.criticalFeatureHealth?.status==='DEGRADED')return'FAIL';if(snapshot.criticalFeatureHealth?.status==='PARTIAL')return'PARTIAL';if(snapshot.criticalFeatureHealth?.status==='HEALTHY')return'PASS';return'UNKNOWN';}
function quoteFresh(quotes:NflMarketQuoteEvidence[],now:number){return quotes.some(row=>{const at=Date.parse(row.quoteTimestamp);return Number.isFinite(at)&&at<=now+60_000&&now-at<=NFL_PREDICTIVE_BOARD_POLICY.marketFreshMinutes*60_000;});}
function bestPrice(rows:NflMarketQuoteEvidence[],side:string,linePreference:'HIGH'|'LOW'|'NONE'='NONE'){
  const selected=rows.filter(row=>norm(row.side)===norm(side)&&Number.isFinite(row.price));if(!selected.length)return null;
  const lines=selected.map(row=>row.line).filter((value):value is number=>typeof value==='number'&&Number.isFinite(value)),target=linePreference==='HIGH'?Math.max(...lines):linePreference==='LOW'?Math.min(...lines):null;
  return selected.filter(row=>target===null||row.line===target).sort((a,b)=>b.price-a.price||a.sportsbook.localeCompare(b.sportsbook))[0]??null;
}
export function timestampSafeMovement(inputs:PredictiveGameInput[],market:string,side:string):MovementState {const points=inputs.map(input=>{if(Date.parse(input.capturedAt)>=Date.parse(input.kickoff))return null;const rows=input.quotes.filter(row=>row.market===market&&norm(row.side)===norm(side)&&Date.parse(row.quoteTimestamp)<=Date.parse(input.capturedAt));const values=rows.map(row=>row.line??row.price).filter((value):value is number=>Number.isFinite(value));const value=median(values);return value===null?null:{at:input.capturedAt,value};}).filter((row):row is {at:string;value:number}=>Boolean(row)).sort((a,b)=>a.at.localeCompare(b.at));if(points.length<2)return'UNAVAILABLE';const first=points[0].value,last=points.at(-1)!.value;if(first===last)return'NEUTRAL';if(market==='h2h')return last<first?'SUPPORTS':'OPPOSES';if(norm(side)==='over')return last>first?'SUPPORTS':'OPPOSES';if(norm(side)==='under')return last<first?'SUPPORTS':'OPPOSES';return last<first?'SUPPORTS':'OPPOSES';}
export function crossesNflKeyNumber(from:number,to:number){const low=Math.min(Math.abs(from),Math.abs(to)),high=Math.max(Math.abs(from),Math.abs(to));return NFL_PREDICTIVE_BOARD_POLICY.keyNumbers.filter(key=>low<key&&high>=key);}
const winnerStrength=(margin:number|null)=>margin===null?'UNAVAILABLE':Math.abs(margin)>=10?'CLEAR MODEL FAVORITE':Math.abs(margin)>=6?'MODERATE MODEL FAVORITE':Math.abs(margin)>=3?'SLIGHT MODEL FAVORITE':'CLOSE GAME';
export function predictedGameScript(home:string,away:string,forecast:IndependentFootballForecast){if(forecast.status!=='PROJECTED')return'Game script unavailable because the independent football forecast is unavailable.';const winner=forecast.homeMargin!>=0?home:away,margin=Math.abs(forecast.homeMargin!),pace=forecast.total!>=50?'Higher-scoring environment':forecast.total!<=40?'Lower-scoring environment':'Mid-range scoring environment';return`${pace}; ${margin<3?'a close game is projected':`${winner} is projected to play from ahead`}.`;}

function gradeFor(input:Omit<GradeInput,'roleCertainty'> & {roleCertainty?:GradeInput['roleCertainty']}){return gradeOpportunity({...input,roleCertainty:input.roleCertainty??'UNKNOWN'});}
function opportunity(base:Omit<DecisionOpportunity,'grade'|'tier'|'isProbability'|'components'|'caps'|'recommendable'>,grade:GradeResult,eligible=true):DecisionOpportunity{return{...base,grade:grade.grade,tier:grade.tier,isProbability:false,components:grade.components,caps:grade.caps,recommendable:eligible&&displayedOpportunity(grade.grade)};}

function buildGame(input:PredictiveGameInput,history:PredictiveGameInput[],projectRoot:string,now:number):PredictiveGameBoard {
  const forecast=independentGameForecast(input,projectRoot),started=Date.parse(input.kickoff)<=now,failures:FailureState[]=[];
  if(forecast.status!=='PROJECTED')failures.push(forecast.reason?.startsWith('IDENTITY_UNRESOLVED')?'IDENTITY_UNRESOLVED':'FORECAST_UNAVAILABLE');if(started)failures.push('STARTED_GAME');if(input.failures.some(row=>/leakage/i.test(row)))failures.push('LEAKAGE_VIOLATION');if(input.dataQuality==='FAIL')failures.push('DATA_INVALID');
  const fresh=quoteFresh(input.quotes,now),market=(name:string)=>input.quotes.filter(row=>row.market===name),common={dataQuality:input.dataQuality,availability:'UNKNOWN' as const,stabilitySamples:input.snapshotCount,currentSeasonSamples:forecast.currentSeasonSamples,movement:'UNAVAILABLE' as MovementState,dependencySafe:true,matchupSupport:'UNKNOWN' as const};
  let spread:DecisionOpportunity|null=null,moneyline:DecisionOpportunity|null=null,total:DecisionOpportunity|null=null;
  if(forecast.status==='PROJECTED'){
    const spreadRows=market('spreads'),homeMargins=spreadRows.flatMap(row=>typeof row.line!=='number'?[]:norm(row.side)===norm(input.homeName)?[-row.line]:norm(row.side)===norm(input.awayName)?[row.line]:[]),marketMargin=median(homeMargins);
    if(marketMargin!==null){const homeSide=forecast.homeMargin!>=marketMargin,side=homeSide?input.homeName:input.awayName,q=bestPrice(spreadRows,side,'HIGH'),difference=Math.abs(forecast.homeMargin!-marketMargin),disp=range(homeMargins),keyCross=crossesNflKeyNumber(marketMargin,forecast.homeMargin!),movement=timestampSafeMovement(history,'spreads',side);const g=gradeFor({market:'SPREAD',edgeMagnitude:difference,edgeScale:6,reliability:'FAILED',bookCount:new Set(spreadRows.map(row=>row.sportsbook)).size,dispersion:disp?disp[1]-disp[0]:null,price:q?.price??null,extremeDisagreement:difference>=10,...common,movement});spread=opportunity({id:`${input.id}:spread`,gameId:input.id,type:'SPREAD',label:`${side} ${q?.line==null?'':q.line>0?`+${q.line}`:q.line}`.trim(),direction:side,line:q?.line??null,projection:forecast.homeMargin,difference,price:q?.price??null,sportsbook:q?.sportsbook??null,consensus:marketMargin,range:disp,dataQuality:input.dataQuality,availability:'Team availability unresolved',role:'Not applicable',marketFresh:fresh,why:[`Independent model projects ${input.homeName} by ${forecast.homeMargin} versus market-implied home margin ${round(marketMargin)}.`,`${difference.toFixed(1)}-point model/market difference toward ${side}.`,keyCross.length?`Comparison crosses NFL key number(s) ${keyCross.join(', ')}.`:'No 3/7 key-number crossing in the model/market comparison.',`Timestamp-safe line movement: ${movement}.`],risks:['Phase 3A spread Model B trailed the market on the locked holdout.','Early 2026 team/QB evidence remains incomplete.',...(fresh?[]:['Captured spread price is stale; shop a current line before acting.'])],modelFamily:'LOCKED_PHASE3A_SPREAD_FAILED',thesis:[homeSide?'HOME_STRENGTH':'AWAY_STRENGTH']},g,!started&&fresh&&!failures.includes('LEAKAGE_VIOLATION'));}
    const mlRows=market('h2h'),winner=forecast.winner!,q=bestPrice(mlRows,winner),strength=Math.abs(forecast.homeMargin!),mlMovement=timestampSafeMovement(history,'h2h',winner),gMl=gradeFor({market:'MONEYLINE',edgeMagnitude:strength,edgeScale:10,reliability:'FAILED',bookCount:new Set(mlRows.map(row=>row.sportsbook)).size,dispersion:null,price:q?.price??null,extremeDisagreement:false,...common,movement:mlMovement});if(q)moneyline=opportunity({id:`${input.id}:ml`,gameId:input.id,type:'MONEYLINE',label:`${winner} ML`,direction:winner,line:null,projection:strength,difference:null,price:q.price,sportsbook:q.sportsbook,consensus:median(mlRows.filter(row=>norm(row.side)===norm(winner)).map(row=>row.price)),range:range(mlRows.filter(row=>norm(row.side)===norm(winner)).map(row=>row.price)),dataQuality:input.dataQuality,availability:'Team availability unresolved',role:'Not applicable',marketFresh:fresh,why:[`${winner} is the independent model's projected winner by ${strength.toFixed(1)} points.`,`Moneyline grade separately penalizes the ${q.price} price; winner strength is not moneyline value.`,`Timestamp-safe moneyline movement: ${mlMovement}.`],risks:['No calibrated NFL win probability is used.','Phase 3A failed its research gate.',...(fresh?[]:['Captured moneyline is stale.'])],modelFamily:'LOCKED_PHASE3A_WINNER_FAILED',thesis:[forecast.homeMargin!>=0?'HOME_WIN':'AWAY_WIN']},gMl,!started&&fresh);
    const totalRows=market('totals'),lines=totalRows.map(row=>row.line).filter((value):value is number=>typeof value==='number'),marketTotal=median(lines);if(marketTotal!==null){const over=forecast.total!>marketTotal,side=over?'Over':'Under',q=bestPrice(totalRows,side,over?'LOW':'HIGH'),difference=Math.abs(forecast.total!-marketTotal),disp=range(lines),movement=timestampSafeMovement(history,'totals',side),g=gradeFor({market:'TOTAL',edgeMagnitude:difference,edgeScale:10,reliability:'FAILED',bookCount:new Set(totalRows.map(row=>row.sportsbook)).size,dispersion:disp?disp[1]-disp[0]:null,price:q?.price??null,extremeDisagreement:difference>=10,...common,movement});total=opportunity({id:`${input.id}:total`,gameId:input.id,type:'TOTAL',label:`${side} ${q?.line??round(marketTotal)}`,direction:side,line:q?.line??null,projection:forecast.total,difference,price:q?.price??null,sportsbook:q?.sportsbook??null,consensus:marketTotal,range:disp,dataQuality:input.dataQuality,availability:'Team availability unresolved',role:'Not applicable',marketFresh:fresh,why:[`Reconciled score projects ${forecast.total} points versus ${round(marketTotal)} market consensus.`,`${difference.toFixed(1)}-point difference toward the ${side}.`,`Timestamp-safe total movement: ${movement}.`],risks:['Phase 3B total Model B trailed the market on the locked holdout.','Weather and confirmed availability are incomplete.',...(fresh?[]:['Captured total price is stale.'])],modelFamily:'LOCKED_PHASE3B_TOTAL_FAILED',thesis:[over?'HIGH_SCORING':'LOW_SCORING']},g,!started&&fresh);}
  }
  if(!market('spreads').length||!market('totals').length||!market('h2h').length)failures.push('MARKET_UNAVAILABLE');
  const teamTotals:DecisionOpportunity[]=[];if(forecast.status==='PROJECTED')for(const team of [input.homeName,input.awayName]){const rows=market('team_totals').filter(row=>norm(row.participant??'')===norm(team)),lines=rows.map(row=>row.line).filter((value):value is number=>typeof value==='number'),consensus=median(lines);if(consensus===null)continue;const projection=team===input.homeName?forecast.homeScore!:forecast.awayScore!,over=projection>consensus,side=over?'Over':'Under',q=bestPrice(rows,side,over?'LOW':'HIGH'),difference=Math.abs(projection-consensus),g=gradeFor({market:'TEAM_TOTAL',edgeMagnitude:difference,edgeScale:7,reliability:'FAILED',bookCount:new Set(rows.map(row=>row.sportsbook)).size,dispersion:range(lines)?range(lines)![1]-range(lines)![0]:null,price:q?.price??null,extremeDisagreement:difference>=8,...common});teamTotals.push(opportunity({id:`${input.id}:team-total:${norm(team)}`,gameId:input.id,type:'TEAM_TOTAL',label:`${team} ${side} ${q?.line??consensus}`,direction:side,line:q?.line??null,projection,difference,price:q?.price??null,sportsbook:q?.sportsbook??null,consensus,range:range(lines),dataQuality:input.dataQuality,availability:'Team availability unresolved',role:'Not applicable',marketFresh:fresh,why:[`${team} projects for ${projection} points versus team-total consensus ${round(consensus)}.`],risks:['Team total inherits failed game-model reliability.'],modelFamily:'RECONCILED_TEAM_SCORE_FAILED',thesis:[team===input.homeName?(over?'HOME_SCORING_OVER':'HOME_SCORING_UNDER'):(over?'AWAY_SCORING_OVER':'AWAY_SCORING_UNDER')]},g,!started&&fresh));}
  const playerProps:DecisionOpportunity[]=[];for(const projection of input.propProjections){const rows=input.quotes.filter(row=>row.kind==='PROP'&&row.market===projection.market&&(!projection.playerId||row.canonicalPlayerId===projection.playerId)&&norm(row.participant??'')===norm(projection.player)),lines=rows.map(row=>row.line).filter((value):value is number=>typeof value==='number'),consensus=median(lines);if(consensus===null)continue;const over=projection.projection>consensus,side=over?'Over':'Under',q=bestPrice(rows,side,over?'LOW':'HIGH'),difference=Math.abs(projection.projection-consensus),inactive=projection.availability==='INACTIVE_VERIFIED',availability:GradeInput['availability']=inactive?'INACTIVE':projection.availability==='ACTIVE_VERIFIED'?'VERIFIED_ACTIVE':projection.availability==='STATUS_PENDING'?'PENDING_OR_QUESTIONABLE':'UNKNOWN',g=gradeFor({market:'PLAYER_PROP',edgeMagnitude:difference,edgeScale:/receptions|attempts|completions/.test(projection.market)?3:Math.max(8,consensus*.15),reliability:'BLOCKED',dataQuality:input.dataQuality,availability,roleCertainty:projection.role==='VERIFIED'?'VERIFIED':projection.role==='PARTIAL'?'PARTIAL':'UNKNOWN',stabilitySamples:input.snapshotCount,bookCount:new Set(rows.map(row=>row.sportsbook)).size,dispersion:range(lines)?range(lines)![1]-range(lines)![0]:null,price:q?.price??null,matchupSupport:'UNKNOWN',currentSeasonSamples:forecast.currentSeasonSamples,movement:timestampSafeMovement(history,projection.market,side),dependencySafe:true,extremeDisagreement:difference>=Math.max(10,consensus*.25)});playerProps.push(opportunity({id:`${input.id}:prop:${projection.playerId??norm(projection.player)}:${projection.market}`,gameId:input.id,type:'PLAYER_PROP',label:`${projection.player} ${side} ${q?.line??round(consensus)}`,direction:side,line:q?.line??null,projection:round(projection.projection),difference:round(difference),price:q?.price??null,sportsbook:q?.sportsbook??null,consensus,range:range(lines),dataQuality:input.dataQuality,availability:projection.availability,role:projection.role,marketFresh:fresh,why:[`${projection.player} projects at ${round(projection.projection)} versus ${round(consensus)} market consensus.`,`Direction is ${side}; grade is reduced because Phase 3C is blocked by data quality.`],risks:[inactive?'PLAYER_INACTIVE: normal overs are blocked.':'Game-day availability is not verified.','Point-in-time role and route evidence are incomplete.',...(fresh?[]:['Captured prop price is stale.'])],modelFamily:'LEGACY_PROP_PROJECTION_PHASE3C_BLOCKED',thesis:[`${norm(projection.player)}_${over?'OVER':'UNDER'}`,over?'PLAYER_VOLUME_UP':'PLAYER_VOLUME_DOWN']},g,!started&&fresh&&!inactive));}
  if(playerProps.some(row=>row.availability==='INACTIVE_VERIFIED'))failures.push('PLAYER_INACTIVE');const base=[spread,moneyline,total,...teamTotals,...playerProps].filter((row):row is DecisionOpportunity=>Boolean(row)),consistency=crossMarketConsistency({forecast,opportunities:base}),sgps=buildSgps(input.id,base,consistency.safe),bestGameAngle=[...base].sort((a,b)=>b.grade-a.grade||a.id.localeCompare(b.id))[0]??null;
  const risks=[...new Set([...(bestGameAngle?.risks??[]),...input.failures])].slice(0,4);
  return{gameId:input.id,matchup:`${input.awayName} @ ${input.homeName}`,kickoff:input.kickoff,source:input.source,capturedAt:input.capturedAt,forecast,projectedWinnerStrength:winnerStrength(forecast.homeMargin),gameScript:predictedGameScript(input.homeName,input.awayName,forecast),spread,moneyline,total,teamTotals,playerProps,derivatives:['1H spread','1H moneyline','1H total','1Q spread','1Q moneyline','1Q total'].map(market=>({market,status:'FORECAST_UNAVAILABLE' as const,reason:'No separately validated derivative-market model; full-game projections are not divided mechanically.'})),sgps,bestGameAngle,dataQuality:input.dataQuality,keyRisks:risks,failures:[...new Set(failures)]};
}

export function crossMarketConsistency(input:{forecast:IndependentFootballForecast;opportunities:DecisionOpportunity[]}){const contradictions:string[]=[];if(input.forecast.status==='PROJECTED'){for(const row of input.opportunities){if(row.type==='TOTAL'&&row.projection!==input.forecast.total)contradictions.push(`${row.id}: total projection differs from reconciled score total.`);if(row.type==='SPREAD'&&row.projection!==input.forecast.homeMargin)contradictions.push(`${row.id}: spread projection differs from reconciled score margin.`);}const total=input.opportunities.find(row=>row.type==='TOTAL'),highScore=input.forecast.total!>=50;if(total&&(total.direction==='Over')!==highScore&&Math.abs(total.difference??0)>=10)contradictions.push(`${total.id}: strong total direction conflicts with displayed game script.`);}return{safe:contradictions.length===0,contradictions};}

function negativeCorrelation(a:DecisionOpportunity,b:DecisionOpportunity){const tags=new Set([...a.thesis,...b.thesis]);if(tags.has('HIGH_SCORING')&&tags.has('LOW_SCORING'))return true;if(tags.has('PLAYER_VOLUME_UP')&&tags.has('PLAYER_VOLUME_DOWN')&&a.label.split(' ')[0]===b.label.split(' ')[0])return true;return false;}
function correlated(a:DecisionOpportunity,b:DecisionOpportunity){const tags=new Set([...a.thesis,...b.thesis]);return(tags.has('HIGH_SCORING')&&tags.has('PLAYER_VOLUME_UP'))||(tags.has('HOME_WIN')&&tags.has('HOME_STRENGTH'))||(tags.has('AWAY_WIN')&&tags.has('AWAY_STRENGTH'));}
function comboGrade(legs:DecisionOpportunity[],kind:'SGP'|'PARLAY',dependencySafe:boolean){const minimum=Math.min(...legs.map(row=>row.grade)),average=legs.reduce((sum,row)=>sum+row.grade,0)/legs.length,data=Math.min(...legs.map(row=>({PASS:100,PARTIAL:70,UNKNOWN:50,FAIL:0}[row.dataQuality]))),prices=legs.every(row=>row.price!==null),shared=new Set(legs.map(row=>row.modelFamily)).size<legs.length,positive=kind==='SGP'&&legs.some((row,i)=>legs.slice(i+1).some(other=>correlated(row,other)));let score=.45*minimum+.2*average+.15*data+(dependencySafe?8:0)+(prices?5:1)+(positive?4:0)-(legs.length-2)*4-(shared?6:0);return clamp(Math.round(score),0,96);}
function combinations<T>(rows:T[],size:number){const result:T[][]=[];const walk=(start:number,items:T[])=>{if(items.length===size){result.push(items);return;}for(let i=start;i<rows.length;i++)walk(i+1,[...items,rows[i]]);};walk(0,[]);return result;}
export function buildSgps(gameId:string,opportunities:DecisionOpportunity[],consistencySafe=true){const legs=opportunities.filter(row=>row.gameId===gameId&&row.grade>=70&&row.recommendable),results:DecisionOpportunity[]=[];for(const size of [2,3])for(const group of combinations(legs,size)){if(group.some((row,i)=>group.slice(i+1).some(other=>negativeCorrelation(row,other))))continue;const dependencySafe=consistencySafe,grade=comboGrade(group,'SGP',dependencySafe);if(grade<60)continue;const prices=group.map(row=>row.price).filter((value):value is number=>value!==null),price=prices.length===group.length?decimalAmerican(prices.reduce((value,item)=>value*americanDecimal(item),1)):null;results.push({id:`${gameId}:sgp:${group.map(row=>row.id).sort().join('+')}`,gameId,type:'SGP',label:`${size}-leg SGP: ${group.map(row=>row.label).join(' + ')}`,direction:'COMBINATION',line:null,projection:null,difference:null,grade,tier:gradeTier(grade),isProbability:false,price,sportsbook:null,consensus:null,range:null,dataQuality:group.some(row=>row.dataQuality==='FAIL')?'FAIL':group.some(row=>row.dataQuality!=='PASS')?'PARTIAL':'PASS',availability:'Inherited from legs',role:'Inherited from legs',marketFresh:group.every(row=>row.marketFresh),recommendable:grade>=60&&dependencySafe,why:[positiveCorrelationReason(group),'SGP grade is computed separately from leg grades and is not a win probability.'],risks:[dependencySafe?'Shared game-script risk is penalized.':'Cross-market contradiction detected.'],components:[],caps:[],modelFamily:'MULTI_MARKET_SGP',thesis:[...new Set(group.flatMap(row=>row.thesis))]});}return results.sort((a,b)=>b.grade-a.grade||a.id.localeCompare(b.id)).slice(0,3);}
function positiveCorrelationReason(legs:DecisionOpportunity[]){return legs.some((row,i)=>legs.slice(i+1).some(other=>correlated(row,other)))?'At least one logical positive correlation exists, without treating correlation as value.':'Legs are not credited with positive correlation.';}
export function buildParlays(opportunities:DecisionOpportunity[]){const legs=opportunities.filter(row=>row.grade>=70&&row.recommendable),results:DecisionOpportunity[]=[];for(const size of [2,3])for(const group of combinations(legs,size)){if(new Set(group.map(row=>row.gameId)).size!==group.length)continue;const grade=comboGrade(group,'PARLAY',true);if(grade<60)continue;const prices=group.map(row=>row.price).filter((value):value is number=>value!==null),price=prices.length===group.length?decimalAmerican(prices.reduce((value,item)=>value*americanDecimal(item),1)):null;results.push({id:`parlay:${group.map(row=>row.id).sort().join('+')}`,gameId:'CROSS_GAME',type:'PARLAY',label:`${size}-leg parlay: ${group.map(row=>row.label).join(' + ')}`,direction:'COMBINATION',line:null,projection:null,difference:null,grade,tier:gradeTier(grade),isProbability:false,price,sportsbook:null,consensus:null,range:null,dataQuality:group.some(row=>row.dataQuality!=='PASS')?'PARTIAL':'PASS',availability:'Inherited from legs',role:'Inherited from legs',marketFresh:group.every(row=>row.marketFresh),recommendable:true,why:['Cross-game legs are independently selected at grade 70 or higher.','Parlay grade separately penalizes leg count and shared model-family risk.'],risks:['All legs must win; grade is not a win probability.'],components:[],caps:[],modelFamily:'CROSS_GAME_PARLAY',thesis:[...new Set(group.flatMap(row=>row.thesis))]});}return results.sort((a,b)=>b.grade-a.grade||a.id.localeCompare(b.id)).slice(0,3);}

function board(inputs:PredictiveGameInput[],projectRoot:string,now:number):NflPredictiveBoard {const histories=new Map<string,PredictiveGameInput[]>();for(const row of inputs){const old=histories.get(row.id)??[];old.push(row);histories.set(row.id,old);}const latest=[...histories.values()].map(rows=>[...rows].sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt))[0]),games=latest.map(row=>buildGame(row,histories.get(row.id)!,projectRoot,now)).sort((a,b)=>Date.parse(a.kickoff)-Date.parse(b.kickoff)||a.gameId.localeCompare(b.gameId)),all=games.flatMap(game=>[game.spread,game.moneyline,game.total,...game.teamTotals,...game.playerProps,...game.sgps].filter((row):row is DecisionOpportunity=>Boolean(row))),topOverall=all.filter(row=>row.recommendable&&row.grade>=60).sort((a,b)=>b.grade-a.grade||a.id.localeCompare(b.id)),parlays=buildParlays(topOverall),ranked=[...topOverall,...parlays].sort((a,b)=>b.grade-a.grade||a.id.localeCompare(b.id)),bestByType:Partial<Record<OpportunityType,DecisionOpportunity>>={};for(const row of ranked)if(!bestByType[row.type])bestByType[row.type]=row;const buckets:Record<'60-69'|'70-77'|'78-84'|'85-89'|'90-100',number>={'60-69':0,'70-77':0,'78-84':0,'85-89':0,'90-100':0};for(const row of all)if(row.grade>=90)buckets['90-100']++;else if(row.grade>=85)buckets['85-89']++;else if(row.grade>=78)buckets['78-84']++;else if(row.grade>=70)buckets['70-77']++;else if(row.grade>=60)buckets['60-69']++;
  return{schemaVersion:NFL_PREDICTIVE_BOARD_VERSION,generatedAt:new Date(now).toISOString(),gradeMeaning:'Relative predictability/opportunity evidence score only. It is not a win probability, calibrated probability, stake signal, or guarantee.',collection:{mode:'MANUAL_ONLY',scheduled:'DISABLED_BY_CONFIGURATION',protectedCutoff:NFL_PREDICTIVE_BOARD_POLICY.protectedCutoff,newPaidProviderCalls:0,newPaidCredits:0},games,topOverall:ranked.slice(0,5),bestByType,parlays,gradeDistribution:buckets,below60:all.filter(row=>row.grade<60).length,diagnostics:['Layer 1 uses the locked independent Phase 3A/3B research models and never receives market inputs.','Layer 2 compares that forecast with captured prices and applies explicit reliability/data/availability penalties.','Phase 3A spread and Phase 3B total models failed; Phase 3C player opportunity research is blocked by data quality.','First-half and first-quarter forecasts remain unavailable rather than dividing the full-game forecast.'],finalDecision:'NFL PREDICTIVE BOARD READY WITH KNOWN RESEARCH LIMITATIONS'};
}

export function inputsFromForwardSnapshots(snapshots:NflForwardSnapshot[]):PredictiveGameInput[]{const counts=new Map<string,number>();for(const row of snapshots)counts.set(row.game.canonicalGameId,(counts.get(row.game.canonicalGameId)??0)+1);return snapshots.map(snapshot=>({id:snapshot.game.canonicalGameId,homeName:snapshot.game.home.name,awayName:snapshot.game.away.name,homeCode:snapshot.game.home.abbreviation,awayCode:snapshot.game.away.abbreviation,kickoff:snapshot.game.scheduledKickoff,seasonType:snapshot.game.seasonType,week:snapshot.game.week,neutral:snapshot.game.neutralSite,capturedAt:snapshot.capturedAt,quotes:[...snapshot.gameMarkets,...snapshot.propMarkets],propProjections:snapshot.propUniverse.filter(row=>row.projection!==null&&row.canonicalPlayerId).map(row=>({playerId:row.canonicalPlayerId,player:row.participant,market:row.market,projection:row.projection!,version:row.projectionVersion??'UNKNOWN',availability:row.availability,role:'UNKNOWN'})),dataQuality:quality(snapshot),failures:snapshot.failures.map(row=>row.message),snapshotCount:counts.get(snapshot.game.canonicalGameId)!,source:'FORWARD_ARCHIVE'}));}

export function inputsFromEventSummaries(summaries:EventSummary[]):PredictiveGameInput[]{return summaries.filter(row=>row.sportKey==='americanfootball_nfl').map(event=>{const quotes:NflMarketQuoteEvidence[]=[];for(const [marketKey,market] of Object.entries(event.aggregatedMarkets))for(const side of market.sides)for(const offer of side.offers)if(offer.price!==null)quotes.push({kind:'GAME',canonicalGameId:event.eventId,canonicalPlayerId:null,market:marketKey,participant:null,side:side.outcomeName,line:offer.line,price:offer.price,sportsbook:offer.bookmakerTitle,providerEventId:event.eventId,quoteTimestamp:offer.lastUpdate,captureTimestamp:event.fetchedAt,rawPayloadHash:'0'.repeat(64),label:'CONTEMPORANEOUS_QUOTE'});return{id:event.eventId,homeName:event.homeTeam,awayName:event.awayTeam,homeCode:teamCodes[event.homeTeam]??null,awayCode:teamCodes[event.awayTeam]??null,kickoff:event.startTime,seasonType:'REG',week:null,neutral:false,capturedAt:event.fetchedAt,quotes,propProjections:[],dataQuality:event.dataQualityScore>=.85?'PASS':event.dataQualityScore>=.5?'PARTIAL':'FAIL',failures:[],snapshotCount:1,source:'LIVE_SCAN'};});}

export function buildNflPredictiveBoardFromInputs(inputs:PredictiveGameInput[],projectRoot:string,now=Date.now()){return board(inputs,projectRoot,now);}
export function buildNflPredictiveBoardFromSummaries(summaries:EventSummary[],projectRoot:string,now=Date.now()){return board(inputsFromEventSummaries(summaries),projectRoot,now);}
export function readNflPredictiveBoard(archiveRoot:string,projectRoot:string,now=Date.now(),onlyMatchups?:Array<{homeTeam:string;awayTeam:string;commenceTime:string}>){const archive=new NflForwardArchive(archiveRoot);archive.verify();let inputs=inputsFromForwardSnapshots(archive.load().snapshots);if(onlyMatchups)inputs=inputs.filter(input=>onlyMatchups.some(game=>norm(game.homeTeam)===norm(input.homeName)&&norm(game.awayTeam)===norm(input.awayName)&&centralDate(game.commenceTime)===centralDate(input.kickoff)));return board(inputs,projectRoot,now);}

export function printNflPredictiveBoard(report:NflPredictiveBoard){console.log('\n+==============================================================+');console.log('|  NFL PREDICTIVE BOARD — GRADE IS NOT WIN PROBABILITY');console.log('+==============================================================+');console.log(`  ${report.gradeMeaning}`);console.log(`  TOP OVERALL (60+ only): ${report.topOverall.length?report.topOverall.map((row,i)=>`${i+1}. ${row.label} — ${row.grade}/100 ${row.tier}`).join(' | '):'No opportunity reached 60. Game forecasts still follow.'}`);for(const game of report.games){console.log(`\n  ${game.matchup} — ${game.kickoff}`);if(game.forecast.status==='PROJECTED'){console.log(`  PREDICTED SCORE: ${game.matchup.split(' @ ')[0]} ${game.forecast.awayScore} — ${game.matchup.split(' @ ')[1]} ${game.forecast.homeScore}`);console.log(`  PROJECTED WINNER: ${game.forecast.winner} (${game.projectedWinnerStrength})`);console.log(`  PROJECTED MARGIN: ${game.matchup.split(' @ ')[1]} ${game.forecast.homeMargin!>=0?'+':''}${game.forecast.homeMargin}`);console.log(`  PROJECTED TOTAL: ${game.forecast.total}`);console.log(`  GAME SCRIPT: ${game.gameScript}`);}else console.log(`  FORECAST UNAVAILABLE: ${game.forecast.reason}`);for(const row of [game.bestGameAngle,game.spread,game.moneyline,game.total].filter((value,index,all):value is DecisionOpportunity=>Boolean(value)&&all.indexOf(value)===index)){console.log(`  ${row===game.bestGameAngle?'BEST GAME ANGLE':row.type}: ${row.label} | projection ${row.projection??'n/a'} | difference ${row.difference??'n/a'} | GRADE ${row.grade}/100 ${row.tier} | price ${row.price??'n/a'} ${row.sportsbook??''}`);}for(const row of game.teamTotals)console.log(`  TEAM TOTAL: ${row.label} | model ${row.projection} | difference ${row.difference} | GRADE ${row.grade}/100 ${row.tier}`);for(const prop of game.playerProps.slice(0,3))console.log(`  PROP: ${prop.label} | model ${prop.projection} | difference ${prop.difference} | GRADE ${prop.grade}/100 ${prop.tier}`);for(const [index,row] of game.sgps.entries())console.log(`  ${index===0?'BEST CONSERVATIVE SGP':'SGP'}: ${row.label} | GRADE ${row.grade}/100 ${row.tier}`);console.log(`  DATA QUALITY: ${game.dataQuality}`);console.log(`  KEY RISKS: ${game.keyRisks.join(' | ')||'No additional recorded risk.'}`);console.log(`  MARKET DETAIL: captured ${game.capturedAt}; recommendations require timestamp-fresh prices.`);console.log(`  RESEARCH: ${game.forecast.version}`);}for(const row of report.parlays)console.log(`  PARLAY: ${row.label} | GRADE ${row.grade}/100 ${row.tier}`);console.log(`\n  GRADE DISTRIBUTION: ${Object.entries(report.gradeDistribution).map(([key,value])=>`${key}: ${value}`).join(' | ')} | below 60: ${report.below60}`);console.log(`  API IMPACT: ${report.collection.newPaidProviderCalls} new calls / ${report.collection.newPaidCredits} credits in decision layer.`);console.log(`  ${report.finalDecision}\n`);}
