import {createHash} from 'crypto';

export const NFL_SPREAD_PHASE3A_VERSION='nfl-spread-phase3a-v1';
export type SafetyClass='VERIFIED_POINT_IN_TIME'|'SAFE_HISTORICAL_SNAPSHOT'|'RECONSTRUCTED_WITHOUT_FUTURE_INFO'|'UNAVAILABLE'|'UNSAFE_FUTURE_LEAKAGE';
export type CoverageState='PASS'|'PARTIAL'|'FAIL'|'UNKNOWN';
export type FinalDecision='NFL SPREAD MODEL B PASSES RESEARCH GATE'|'NFL SPREAD MODEL B INCONCLUSIVE — MORE DATA REQUIRED'|'NFL SPREAD MODEL B FAILS RESEARCH GATE'|'NFL SPREAD MODEL B BLOCKED BY DATA QUALITY';
export type FeatureName='TEAM_STRENGTH_DIFF'|'HOME_FIELD'|'PRIOR_STRENGTH_DIFF'|'CURRENT_SCORING_MARGIN_DIFF'|'BLENDED_OFFENSE_DIFF'|'BLENDED_DEFENSE_DIFF'|'ROLLING_MARGIN_DIFF'|'REST_DIFF'|'HOME_SHORT_WEEK'|'AWAY_SHORT_WEEK'|'DIVISIONAL_GAME'|'NEUTRAL_SITE'|'AWAY_ROAD_STREAK';

export interface NflSpreadGame {
  id:string; season:number; gameType:'REG'|'WC'|'DIV'|'CON'|'SB'; week:number; date:string; weekday:string;
  awayId:string; homeId:string; awayScore:number; homeScore:number; neutral:boolean; overtime:boolean;
  awayRest:number|null; homeRest:number|null; spreadLine:number|null; awaySpreadOdds:number|null; homeSpreadOdds:number|null;
  divisional:boolean|null; roof:string|null; temperature:number|null; wind:number|null; awayQbId:string|null; homeQbId:string|null;
  awayCoach:string|null; homeCoach:string|null; stadiumId:string|null;
}
export interface SourceAudit {games:NflSpreadGame[]; excluded:Record<string,number>; seasons:Record<string,{regular:number;playoffs:number}>; columns:string[];}
export interface PregameFeatures {
  TEAM_STRENGTH_DIFF:number; HOME_FIELD:number; PRIOR_STRENGTH_DIFF:number; CURRENT_SCORING_MARGIN_DIFF:number; BLENDED_OFFENSE_DIFF:number; BLENDED_DEFENSE_DIFF:number;
  ROLLING_MARGIN_DIFF:number; REST_DIFF:number; HOME_SHORT_WEEK:number; AWAY_SHORT_WEEK:number;
  DIVISIONAL_GAME:number; NEUTRAL_SITE:number; AWAY_ROAD_STREAK:number;
}
export interface NflSpreadFeatureRow {
  id:string; season:number; week:number; date:string; gameType:'REG'; homeId:string; awayId:string; actualMargin:number;
  marketMargin:number|null; homeSpreadOdds:number|null; awaySpreadOdds:number|null; neutral:boolean; overtime:boolean;
  divisional:boolean|null; homeRest:number|null; awayRest:number|null; features:PregameFeatures; latestInputDate:string;
  currentHomeGames:number; currentAwayGames:number; priorHomeGames:number; priorAwayGames:number;
}
export interface Metric {n:number;mae:number|null;rmse:number|null;bias:number|null;}
export interface RidgeModel {version:string;features:FeatureName[];lambda:number;intercept:number;coefficients:Record<string,number>;means:Record<string,number>;scales:Record<string,number>;trainingN:number;trainingHash:string;}

const finite=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const numberOrNull=(value:string)=>value.trim()===''?null:(Number.isFinite(Number(value))?Number(value):null);
const stable=(value:unknown):string=>{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.keys(value as object).sort().map(key=>`${JSON.stringify(key)}:${stable((value as any)[key])}`).join(',')}}`;};
export const stableHash=(value:unknown)=>createHash('sha256').update(stable(value)).digest('hex');

function parseCsv(text:string){const rows:string[][]=[],row:string[]=[];let current=row,cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(quoted){if(char==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(char==='"')quoted=false;else cell+=char;}else if(char==='"')quoted=true;else if(char===','){current.push(cell);cell='';}else if(char==='\n'){current.push(cell.replace(/\r$/,''));rows.push(current);current=[];cell='';}else cell+=char;}if(cell||current.length){current.push(cell.replace(/\r$/,''));rows.push(current);}if(quoted)throw Error('Unclosed NFL spread CSV field.');return rows;}
const franchise=(id:string)=>({OAK:'LV',SD:'LAC',STL:'LA'} as Record<string,string>)[id]??id;

export function parseNflSpreadSourceCsv(text:string):SourceAudit{
  const data=parseCsv(text),columns=data.shift()??[],required=['game_id','season','game_type','week','gameday','weekday','away_team','away_score','home_team','home_score','location','result','overtime','away_rest','home_rest','spread_line','away_spread_odds','home_spread_odds','div_game','roof','temp','wind','away_qb_id','home_qb_id','away_coach','home_coach','stadium_id'];
  if(required.some(key=>!columns.includes(key)))throw Error('nflverse schedule schema changed for Phase 3A.');
  const at=(key:string)=>columns.indexOf(key),games:NflSpreadGame[]=[],seen=new Set<string>(),excluded:Record<string,number>={},seasons:SourceAudit['seasons']={};
  const skip=(reason:string)=>excluded[reason]=(excluded[reason]??0)+1;
  for(const values of data){if(values.length===1&&!values[0])continue;const gameType=values[at('game_type')] as NflSpreadGame['gameType'];if(!['REG','WC','DIV','CON','SB'].includes(gameType)){skip('UNSUPPORTED_GAME_TYPE');continue;}
    const season=numberOrNull(values[at('season')]),week=numberOrNull(values[at('week')]),homeScore=numberOrNull(values[at('home_score')]),awayScore=numberOrNull(values[at('away_score')]);
    if(season===null||week===null){skip('MISSING_SEASON_OR_WEEK');continue;}if(homeScore===null||awayScore===null){skip('NOT_FINAL');continue;}
    const id=values[at('game_id')],home=franchise(values[at('home_team')]),away=franchise(values[at('away_team')]),day=values[at('gameday')],location=values[at('location')],result=numberOrNull(values[at('result')]);
    if(!id||seen.has(id)||!home||!away||home===away||!/^\d{4}-\d{2}-\d{2}$/.test(day)||!['Home','Neutral'].includes(location)||!Number.isInteger(homeScore)||!Number.isInteger(awayScore)||homeScore<0||awayScore<0||result!==homeScore-awayScore)throw Error(`Invalid or duplicate Phase 3A game: ${id||'missing ID'}.`);
    const optionalInteger=(key:string)=>{const value=numberOrNull(values[at(key)]);return value===null?null:(Number.isInteger(value)?value:null);};
    seen.add(id);games.push({id,season,gameType,week,date:`${day}T12:00:00.000Z`,weekday:values[at('weekday')],awayId:away,homeId:home,awayScore,homeScore,neutral:location==='Neutral',overtime:numberOrNull(values[at('overtime')])===1,awayRest:optionalInteger('away_rest'),homeRest:optionalInteger('home_rest'),spreadLine:numberOrNull(values[at('spread_line')]),awaySpreadOdds:optionalInteger('away_spread_odds'),homeSpreadOdds:optionalInteger('home_spread_odds'),divisional:numberOrNull(values[at('div_game')])===null?null:numberOrNull(values[at('div_game')])===1,roof:values[at('roof')]||null,temperature:numberOrNull(values[at('temp')]),wind:numberOrNull(values[at('wind')]),awayQbId:values[at('away_qb_id')]||null,homeQbId:values[at('home_qb_id')]||null,awayCoach:values[at('away_coach')]||null,homeCoach:values[at('home_coach')]||null,stadiumId:values[at('stadium_id')]||null});
    const key=String(season),summary=seasons[key]??{regular:0,playoffs:0};gameType==='REG'?summary.regular++:summary.playoffs++;seasons[key]=summary;
  }
  games.sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));return{games,excluded,seasons,columns};
}

const teamMargin=(game:NflSpreadGame,team:string)=>game.homeId===team?game.homeScore-game.awayScore:game.awayScore-game.homeScore;
const teamPointsFor=(game:NflSpreadGame,team:string)=>game.homeId===team?game.homeScore:game.awayScore;
const teamPointsAgainst=(game:NflSpreadGame,team:string)=>game.homeId===team?game.awayScore:game.homeScore;
const average=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;

function solve(matrix:number[][],target:number[]){const n=target.length,a=matrix.map((row,i)=>[...row,target[i]]);for(let col=0;col<n;col++){let pivot=col;for(let row=col+1;row<n;row++)if(Math.abs(a[row][col])>Math.abs(a[pivot][col]))pivot=row;if(Math.abs(a[pivot][col])<1e-10)throw Error('Singular research regression.');[a[col],a[pivot]]=[a[pivot],a[col]];const divisor=a[col][col];for(let j=col;j<=n;j++)a[col][j]/=divisor;for(let row=0;row<n;row++)if(row!==col){const factor=a[row][col];for(let j=col;j<=n;j++)a[row][j]-=factor*a[col][j];}}return a.map(row=>row[n]);}

function marginRatings(history:NflSpreadGame[],season:number,asOf:number,ridge:number,halfLifeDays:number){const eligible=history.filter(game=>game.gameType==='REG'&&(game.season===season||game.season===season-1)&&Date.parse(game.date)<asOf),teams=[...new Set(eligible.flatMap(game=>[game.homeId,game.awayId]))].sort(),index=new Map(teams.map((team,i)=>[team,i])),size=2+teams.length,xtx=Array.from({length:size},()=>Array(size).fill(0)),xty=Array(size).fill(0);
  for(const game of eligible){const age=(asOf-Date.parse(game.date))/86400000,weight=(game.season===season?1:.65)*Math.pow(.5,age/halfLifeDays),x=Array(size).fill(0);x[0]=1;x[1]=game.neutral?0:1;x[2+index.get(game.homeId)!]=1;x[2+index.get(game.awayId)!]=-1;const y=game.homeScore-game.awayScore;for(let i=0;i<size;i++)if(x[i]){xty[i]+=weight*x[i]*y;for(let j=0;j<size;j++)if(x[j])xtx[i][j]+=weight*x[i]*x[j];}}
  for(let i=1;i<size;i++)xtx[i][i]+=ridge;if(eligible.length<100)return null;const beta=solve(xtx,xty);return{homeField:beta[1],ratings:new Map(teams.map((team,i)=>[team,beta[2+i]])),n:eligible.length};
}

function roadStreak(history:NflSpreadGame[],team:string){let count=0;for(const game of [...history].reverse()){if(game.homeId===team&&!game.neutral)break;if(game.awayId===team||game.neutral&&(game.homeId===team||game.awayId===team))count++;else if(game.homeId===team)break;}return Math.min(count,4);}

export function buildNflSpreadFeatureRows(games:NflSpreadGame[],fromSeason:number,throughSeason:number,policy:{teamRatingRidge:number;teamRatingHalfLifeDays:number;priorSeasonShrinkGames:number;currentSeasonBlendGames:number;rollingGames:number;minimumPriorGamesPerTeam:number}){
  const regular=games.filter(game=>game.gameType==='REG').sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)),targets=regular.filter(game=>game.season>=fromSeason&&game.season<=throughSeason),rows:NflSpreadFeatureRow[]=[],excluded:Record<string,number>={},ratingCache=new Map<string,ReturnType<typeof marginRatings>>();const skip=(reason:string)=>excluded[reason]=(excluded[reason]??0)+1;
  for(const game of targets){const asOf=Date.parse(game.date.slice(0,10)+'T00:00:00.000Z'),history=regular.filter(row=>Date.parse(row.date)<asOf),homeHistory=history.filter(row=>row.homeId===game.homeId||row.awayId===game.homeId),awayHistory=history.filter(row=>row.homeId===game.awayId||row.awayId===game.awayId),homePrior=homeHistory.filter(row=>row.season===game.season-1),awayPrior=awayHistory.filter(row=>row.season===game.season-1),homeCurrent=homeHistory.filter(row=>row.season===game.season),awayCurrent=awayHistory.filter(row=>row.season===game.season);
    if(homePrior.length<policy.minimumPriorGamesPerTeam||awayPrior.length<policy.minimumPriorGamesPerTeam){skip('INSUFFICIENT_PRIOR_TEAM_HISTORY');continue;}
    const ratingKey=`${game.season}:${game.date.slice(0,10)}`;if(!ratingCache.has(ratingKey))ratingCache.set(ratingKey,marginRatings(regular,game.season,asOf,policy.teamRatingRidge,policy.teamRatingHalfLifeDays));const rating=ratingCache.get(ratingKey),homeRating=rating?.ratings.get(game.homeId),awayRating=rating?.ratings.get(game.awayId);if(!rating||!finite(homeRating)||!finite(awayRating)){skip('TEAM_RATING_UNAVAILABLE');continue;}
    const prior=(rows:NflSpreadGame[],team:string,selector:(g:NflSpreadGame,t:string)=>number)=>average(rows.map(row=>selector(row,team)))!;const blended=(current:number|null,priorValue:number,currentN:number)=>{const weight=Math.min(1,currentN/policy.currentSeasonBlendGames);return(current??priorValue)*weight+priorValue*(1-weight);};
    const homePriorOff=prior(homePrior,game.homeId,teamPointsFor),awayPriorOff=prior(awayPrior,game.awayId,teamPointsFor),homePriorDef=prior(homePrior,game.homeId,teamPointsAgainst),awayPriorDef=prior(awayPrior,game.awayId,teamPointsAgainst),homePriorMargin=prior(homePrior,game.homeId,teamMargin),awayPriorMargin=prior(awayPrior,game.awayId,teamMargin);
    const homeCurrentOff=average(homeCurrent.map(row=>teamPointsFor(row,game.homeId))),awayCurrentOff=average(awayCurrent.map(row=>teamPointsFor(row,game.awayId))),homeCurrentDef=average(homeCurrent.map(row=>teamPointsAgainst(row,game.homeId))),awayCurrentDef=average(awayCurrent.map(row=>teamPointsAgainst(row,game.awayId)));
    const homeRolling=homeHistory.slice(-policy.rollingGames),awayRolling=awayHistory.slice(-policy.rollingGames),priorShrink=(n:number)=>n/(n+policy.priorSeasonShrinkGames),rollingHome=average(homeRolling.map(row=>teamMargin(row,game.homeId)))!,rollingAway=average(awayRolling.map(row=>teamMargin(row,game.awayId)))!;
    const priorStrengthDiff=homePriorMargin*priorShrink(homePrior.length)-awayPriorMargin*priorShrink(awayPrior.length),currentHomeMargin=average(homeCurrent.map(row=>teamMargin(row,game.homeId))),currentAwayMargin=average(awayCurrent.map(row=>teamMargin(row,game.awayId)));
    const features:PregameFeatures={TEAM_STRENGTH_DIFF:homeRating-awayRating,HOME_FIELD:game.neutral?0:1,PRIOR_STRENGTH_DIFF:priorStrengthDiff,CURRENT_SCORING_MARGIN_DIFF:currentHomeMargin===null||currentAwayMargin===null?0:currentHomeMargin-currentAwayMargin,BLENDED_OFFENSE_DIFF:blended(homeCurrentOff,homePriorOff,homeCurrent.length)-blended(awayCurrentOff,awayPriorOff,awayCurrent.length),BLENDED_DEFENSE_DIFF:blended(awayCurrentDef,awayPriorDef,awayCurrent.length)-blended(homeCurrentDef,homePriorDef,homeCurrent.length),ROLLING_MARGIN_DIFF:rollingHome-rollingAway,REST_DIFF:Math.max(-7,Math.min(7,(game.homeRest??7)-(game.awayRest??7))),HOME_SHORT_WEEK:(game.homeRest??7)<7?1:0,AWAY_SHORT_WEEK:(game.awayRest??7)<7?1:0,DIVISIONAL_GAME:game.divisional===true?1:0,NEUTRAL_SITE:game.neutral?1:0,AWAY_ROAD_STREAK:roadStreak(awayHistory,game.awayId)};
    if(Object.values(features).some(value=>!finite(value))){skip('INVALID_DERIVED_FEATURE');continue;}const latest=history.at(-1)?.date;if(!latest||Date.parse(latest)>=asOf)throw Error('Phase 3A chronological feature leakage.');rows.push({id:game.id,season:game.season,week:game.week,date:game.date,gameType:'REG',homeId:game.homeId,awayId:game.awayId,actualMargin:game.homeScore-game.awayScore,marketMargin:game.spreadLine,homeSpreadOdds:game.homeSpreadOdds,awaySpreadOdds:game.awaySpreadOdds,neutral:game.neutral,overtime:game.overtime,divisional:game.divisional,homeRest:game.homeRest,awayRest:game.awayRest,features,latestInputDate:latest,currentHomeGames:homeCurrent.length,currentAwayGames:awayCurrent.length,priorHomeGames:homePrior.length,priorAwayGames:awayPrior.length});
  }
  return{rows,excluded};
}

export function assertIndependentFeatures(features:string[]){const forbidden=/(spread|moneyline|total|odds|market|consensus|implied|line_movement|sportsbook)/i,found=features.filter(name=>forbidden.test(name));if(found.length)throw Error(`Market contamination in independent features: ${found.join(', ')}`);}

export function fitSpreadRidge(rows:NflSpreadFeatureRow[],features:FeatureName[],lambda:number):RidgeModel{
  assertIndependentFeatures(features);if(rows.length<features.length+5||!finite(lambda)||lambda<=0)throw Error('Insufficient or invalid Phase 3A ridge fit.');const means:Record<string,number>={},scales:Record<string,number>={};for(const feature of features){means[feature]=rows.reduce((sum,row)=>sum+row.features[feature],0)/rows.length;const variance=rows.reduce((sum,row)=>sum+(row.features[feature]-means[feature])**2,0)/rows.length;scales[feature]=Math.sqrt(variance)||1;}
  const size=features.length+1,xtx=Array.from({length:size},()=>Array(size).fill(0)),xty=Array(size).fill(0);for(const row of rows){const x=[1,...features.map(feature=>(row.features[feature]-means[feature])/scales[feature])];for(let i=0;i<size;i++){xty[i]+=x[i]*row.actualMargin;for(let j=0;j<size;j++)xtx[i][j]+=x[i]*x[j];}}for(let i=1;i<size;i++)xtx[i][i]+=lambda;const beta=solve(xtx,xty),coefficients:Record<string,number>={};for(let i=0;i<features.length;i++)coefficients[features[i]]=beta[i+1]/scales[features[i]];const intercept=beta[0]-features.reduce((sum,feature)=>sum+coefficients[feature]*means[feature],0);return{version:NFL_SPREAD_PHASE3A_VERSION,features:[...features],lambda,intercept,coefficients,means,scales,trainingN:rows.length,trainingHash:stableHash(rows.map(row=>[row.id,row.date,row.actualMargin,features.map(feature=>row.features[feature])]))};
}
export function predictSpread(model:RidgeModel,row:NflSpreadFeatureRow){return model.intercept+model.features.reduce((sum,feature)=>sum+model.coefficients[feature]*row.features[feature],0);}
export function metrics(actual:number[],predicted:number[]):Metric{if(actual.length!==predicted.length)throw Error('Metric arrays differ.');const errors=actual.map((value,i)=>value-predicted[i]);return{n:errors.length,mae:errors.length?errors.reduce((sum,value)=>sum+Math.abs(value),0)/errors.length:null,rmse:errors.length?Math.sqrt(errors.reduce((sum,value)=>sum+value*value,0)/errors.length):null,bias:errors.length?errors.reduce((sum,value)=>sum+value,0)/errors.length:null};}
export function evaluateRidge(model:RidgeModel,rows:NflSpreadFeatureRow[]){return metrics(rows.map(row=>row.actualMargin),rows.map(row=>predictSpread(model,row)));}

export function fitIncrementalMarket(rows:NflSpreadFeatureRow[],model:RidgeModel){const eligible=rows.filter(row=>finite(row.marketMargin));if(eligible.length<20)throw Error('Insufficient market rows.');const synthetic=eligible.map(row=>({...row,features:{...row.features,TEAM_STRENGTH_DIFF:row.marketMargin!,HOME_FIELD:predictSpread(model,row)}})),fit=fitSpreadRidge(synthetic,['TEAM_STRENGTH_DIFF','HOME_FIELD'],1e-6);return{intercept:fit.intercept,marketCoefficient:fit.coefficients.TEAM_STRENGTH_DIFF,modelCoefficient:fit.coefficients.HOME_FIELD,trainingN:eligible.length,trainingHash:fit.trainingHash,predict:(row:NflSpreadFeatureRow)=>fit.intercept+fit.coefficients.TEAM_STRENGTH_DIFF*row.marketMargin!+fit.coefficients.HOME_FIELD*predictSpread(model,row)};}

export function selectEnsembleWeight(validation:NflSpreadFeatureRow[],model:RidgeModel,step=.01){const rows=validation.filter(row=>finite(row.marketMargin));if(!rows.length)throw Error('No validation market rows.');let best={weight:0,rmse:Infinity,mae:Infinity};for(let weight=0;weight<=1+1e-9;weight+=step){const w=Math.round(weight*1000000)/1000000,pred=rows.map(row=>w*predictSpread(model,row)+(1-w)*row.marketMargin!),m=metrics(rows.map(row=>row.actualMargin),pred);if(m.rmse!<best.rmse-1e-12||Math.abs(m.rmse!-best.rmse)<1e-12&&w<best.weight)best={weight:w,rmse:m.rmse!,mae:m.mae!};}return best;}

export function disagreementAnalysis(rows:NflSpreadFeatureRow[],model:RidgeModel){const eligible=rows.filter(row=>finite(row.marketMargin)),bucketDefs:[[number,number|null],...Array<[number,number|null]>]=[[0,1.5],[1.5,3],[3,5],[5,7],[7,10],[10,null]],buckets=bucketDefs.map(([from,to])=>{const selected=eligible.filter(row=>{const d=Math.abs(predictSpread(model,row)-row.marketMargin!);return d>=from&&(to===null||d<to);});return{from,to,...metrics(selected.map(row=>row.actualMargin),selected.map(row=>predictSpread(model,row)))};});const disagreement=eligible.map(row=>predictSpread(model,row)-row.marketMargin!),error=eligible.map(row=>row.actualMargin-predictSpread(model,row)),meanD=average(disagreement)??0,meanE=average(error)??0,cov=disagreement.reduce((sum,value,i)=>sum+(value-meanD)*(error[i]-meanE),0),varD=disagreement.reduce((sum,value)=>sum+(value-meanD)**2,0),varE=error.reduce((sum,value)=>sum+(value-meanE)**2,0);return{n:eligible.length,buckets,correlation:varD&&varE?cov/Math.sqrt(varD*varE):null,regressionSlope:varD?cov/varD:null};}

export function atsDiagnostic(rows:NflSpreadFeatureRow[],model:RidgeModel){let wins=0,losses=0,pushes=0,units=0,priced=0;const prices:number[]=[];for(const row of rows){if(!finite(row.marketMargin))continue;const home=predictSpread(model,row)>row.marketMargin,price=home?row.homeSpreadOdds:row.awaySpreadOdds;if(!finite(price)||price===0)continue;priced++;prices.push(price);const atsMargin=home?row.actualMargin-row.marketMargin:row.marketMargin-row.actualMargin;if(atsMargin===0){pushes++;continue;}if(atsMargin>0){wins++;units+=price>0?price/100:100/Math.abs(price);}else{losses++;units-=1;}}
  const decisions=wins+losses,winRate=decisions?wins/decisions:null,z=1.96,den=decisions?1+z*z/decisions:1,center=decisions?(winRate!+z*z/(2*decisions))/den:null,half=decisions?z*Math.sqrt(winRate!*(1-winRate!)/decisions+z*z/(4*decisions*decisions))/den:null;return{priced,wins,losses,pushes,winRate,units,roi:priced?units/priced:null,meanBreakEven:prices.length?average(prices.map(price=>price>0?100/(price+100):Math.abs(price)/(Math.abs(price)+100))):null,wilson95:decisions?[center!-half!,center!+half!]:null,label:'RECONSTRUCTED NFLVERSE SPREAD-LINE/PRICE DIAGNOSTIC — NOT AN ACTIONABLE BACKTEST'};}

export function coverage(state:CoverageState,n:number,total:number,note:string){return{state,n,total,percent:total?100*n/total:null,note};}
