import {CollegeResult,fitCollegeScores} from './collegeScoreModel';
import {Metric,NflSpreadGame,metrics,parseNflSpreadSourceCsv,stableHash} from './nflSpreadPhase3A';

export const NFL_TOTAL_PHASE3B_VERSION='nfl-total-phase3b-v1';
export type TotalDecision='NFL TOTAL MODEL B PASSES RESEARCH GATE'|'NFL TOTAL MODEL B INCONCLUSIVE — MORE DATA REQUIRED'|'NFL TOTAL MODEL B FAILS RESEARCH GATE'|'NFL TOTAL MODEL B BLOCKED BY DATA QUALITY';
export type TotalFeatureName='BLENDED_OFFENSE_SUM'|'BLENDED_DEFENSE_SUM'|'OPPONENT_ADJUSTED_TOTAL'|'RECENT_COMBINED_TOTAL'|'REST_SUM'|'HOME_SHORT_WEEK'|'AWAY_SHORT_WEEK'|'DIVISIONAL_GAME'|'NEUTRAL_SITE'|'PREVIOUS_OVERTIME_COUNT';
export interface NflTotalGame extends NflSpreadGame {totalLine:number|null;underOdds:number|null;overOdds:number|null;primetime:boolean;}
export interface TotalFeatures {BLENDED_OFFENSE_SUM:number;BLENDED_DEFENSE_SUM:number;OPPONENT_ADJUSTED_TOTAL:number;RECENT_COMBINED_TOTAL:number;REST_SUM:number;HOME_SHORT_WEEK:number;AWAY_SHORT_WEEK:number;DIVISIONAL_GAME:number;NEUTRAL_SITE:number;PREVIOUS_OVERTIME_COUNT:number;}
export interface NflTotalFeatureRow {id:string;season:number;week:number;date:string;homeId:string;awayId:string;actualTotal:number;marketTotal:number|null;underOdds:number|null;overOdds:number|null;neutral:boolean;overtime:boolean;divisional:boolean|null;roof:string|null;primetime:boolean;features:TotalFeatures;priorCombinedTotal:number;simpleOffenseDefenseTotal:number;latestInputDate:string;currentHomeGames:number;currentAwayGames:number;}
export interface TotalRidgeModel {version:string;features:TotalFeatureName[];lambda:number;intercept:number;coefficients:Record<string,number>;means:Record<string,number>;scales:Record<string,number>;trainingN:number;trainingHash:string;}
const finite=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const numeric=(value:string)=>value.trim()===''?null:(Number.isFinite(Number(value))?Number(value):null);
function csv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(quoted){if(char==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(char==='"')quoted=false;else cell+=char;}else if(char==='"')quoted=true;else if(char===','){row.push(cell);cell='';}else if(char==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=char;}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}if(quoted)throw Error('Unclosed NFL totals CSV field.');return rows;}

export function parseNflTotalSourceCsv(text:string){const spread=parseNflSpreadSourceCsv(text),data=csv(text),headers=data.shift()??[],required=['game_id','gametime','total_line','under_odds','over_odds'];if(required.some(key=>!headers.includes(key)))throw Error('nflverse totals schema changed.');const at=(key:string)=>headers.indexOf(key),market=new Map<string,{totalLine:number|null;underOdds:number|null;overOdds:number|null;primetime:boolean}>();for(const row of data){const id=row[at('game_id')];if(!id)continue;const time=row[at('gametime')],hour=/^\d{1,2}:\d{2}$/.test(time)?Number(time.split(':')[0]):null;market.set(id,{totalLine:numeric(row[at('total_line')]),underOdds:numeric(row[at('under_odds')]),overOdds:numeric(row[at('over_odds')]),primetime:hour!==null&&hour>=20});}return{...spread,games:spread.games.map(game=>({...game,...(market.get(game.id)??{totalLine:null,underOdds:null,overOdds:null,primetime:false})}) as NflTotalGame)};}
const pointsFor=(game:NflTotalGame,team:string)=>game.homeId===team?game.homeScore:game.awayScore;
const pointsAgainst=(game:NflTotalGame,team:string)=>game.homeId===team?game.awayScore:game.homeScore;
const avg=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;
const college=(game:NflTotalGame):CollegeResult=>({id:game.id,date:game.date,season:game.season,homeId:game.homeId,awayId:game.awayId,homeName:game.homeId,awayName:game.awayId,homeScore:game.homeScore,awayScore:game.awayScore,neutral:game.neutral});

export function buildNflTotalFeatureRows(games:NflTotalGame[],fromSeason:number,throughSeason:number,policy:{opponentRidge:number;opponentHalfLifeDays:number;currentSeasonBlendGames:number;rollingGames:number;minimumPriorGamesPerTeam:number}){const regular=games.filter(game=>game.gameType==='REG').sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)),targets=regular.filter(game=>game.season>=fromSeason&&game.season<=throughSeason),rows:NflTotalFeatureRow[]=[],excluded:Record<string,number>={},fitCache=new Map<string,ReturnType<typeof fitCollegeScores>>(),collegeGames=regular.map(college),skip=(reason:string)=>excluded[reason]=(excluded[reason]??0)+1;
  for(const game of targets){const asOf=Date.parse(game.date.slice(0,10)+'T00:00:00.000Z'),history=regular.filter(row=>Date.parse(row.date)<asOf),homeHistory=history.filter(row=>row.homeId===game.homeId||row.awayId===game.homeId),awayHistory=history.filter(row=>row.homeId===game.awayId||row.awayId===game.awayId),homePrior=homeHistory.filter(row=>row.season===game.season-1),awayPrior=awayHistory.filter(row=>row.season===game.season-1),homeCurrent=homeHistory.filter(row=>row.season===game.season),awayCurrent=awayHistory.filter(row=>row.season===game.season);if(homePrior.length<policy.minimumPriorGamesPerTeam||awayPrior.length<policy.minimumPriorGamesPerTeam){skip('INSUFFICIENT_PRIOR_TEAM_HISTORY');continue;}
    const key=`${game.season}:${game.date.slice(0,10)}`;if(!fitCache.has(key))fitCache.set(key,fitCollegeScores(collegeGames,asOf,{ridge:policy.opponentRidge,halfLifeDays:policy.opponentHalfLifeDays}));const projection=fitCache.get(key).predict(game.homeId,game.awayId,game.neutral);if(!projection){skip('OPPONENT_ADJUSTED_TOTAL_UNAVAILABLE');continue;}
    const prior=(items:NflTotalGame[],team:string,selector:(g:NflTotalGame,t:string)=>number)=>avg(items.map(item=>selector(item,team)))!,blend=(current:number|null,old:number,n:number)=>{const weight=Math.min(1,n/policy.currentSeasonBlendGames);return(current??old)*weight+old*(1-weight);},homePriorOff=prior(homePrior,game.homeId,pointsFor),awayPriorOff=prior(awayPrior,game.awayId,pointsFor),homePriorDef=prior(homePrior,game.homeId,pointsAgainst),awayPriorDef=prior(awayPrior,game.awayId,pointsAgainst),homeOff=blend(avg(homeCurrent.map(row=>pointsFor(row,game.homeId))),homePriorOff,homeCurrent.length),awayOff=blend(avg(awayCurrent.map(row=>pointsFor(row,game.awayId))),awayPriorOff,awayCurrent.length),homeDef=blend(avg(homeCurrent.map(row=>pointsAgainst(row,game.homeId))),homePriorDef,homeCurrent.length),awayDef=blend(avg(awayCurrent.map(row=>pointsAgainst(row,game.awayId))),awayPriorDef,awayCurrent.length),recent=[...homeHistory.slice(-policy.rollingGames),...awayHistory.slice(-policy.rollingGames)],latest=history.at(-1)?.date;
    if(!latest||Date.parse(latest)>=asOf)throw Error('Phase 3B chronological feature leakage.');const features:TotalFeatures={BLENDED_OFFENSE_SUM:homeOff+awayOff,BLENDED_DEFENSE_SUM:homeDef+awayDef,OPPONENT_ADJUSTED_TOTAL:projection.total,RECENT_COMBINED_TOTAL:avg(recent.map(row=>row.homeScore+row.awayScore))!,REST_SUM:Math.max(-14,Math.min(14,(game.homeRest??7)+(game.awayRest??7)-14)),HOME_SHORT_WEEK:(game.homeRest??7)<7?1:0,AWAY_SHORT_WEEK:(game.awayRest??7)<7?1:0,DIVISIONAL_GAME:game.divisional===true?1:0,NEUTRAL_SITE:game.neutral?1:0,PREVIOUS_OVERTIME_COUNT:(homeHistory.at(-1)?.overtime?1:0)+(awayHistory.at(-1)?.overtime?1:0)};if(Object.values(features).some(value=>!finite(value))){skip('INVALID_DERIVED_FEATURE');continue;}rows.push({id:game.id,season:game.season,week:game.week,date:game.date,homeId:game.homeId,awayId:game.awayId,actualTotal:game.homeScore+game.awayScore,marketTotal:game.totalLine,underOdds:game.underOdds,overOdds:game.overOdds,neutral:game.neutral,overtime:game.overtime,divisional:game.divisional,roof:game.roof,primetime:game.primetime,features,priorCombinedTotal:(avg(homePrior.map(row=>row.homeScore+row.awayScore))!+avg(awayPrior.map(row=>row.homeScore+row.awayScore))!)/2,simpleOffenseDefenseTotal:(homeOff+awayDef+awayOff+homeDef)/2,latestInputDate:latest,currentHomeGames:homeCurrent.length,currentAwayGames:awayCurrent.length});}
  return{rows,excluded};}

export function assertIndependentTotalFeatures(features:string[]){const found=features.filter(name=>/(spread|moneyline|total_line|market|odds|consensus|implied|line_movement|sportsbook)/i.test(name));if(found.length)throw Error(`Market contamination in independent total features: ${found.join(', ')}`);}
export function assertWeatherPointInTime(observedAt:string,forecastAt:string){if(!Number.isFinite(Date.parse(observedAt))||!Number.isFinite(Date.parse(forecastAt))||Date.parse(observedAt)>Date.parse(forecastAt))throw Error('Unsafe future weather evidence.');return true;}
function solve(matrix:number[][],target:number[]){const n=target.length,a=matrix.map((row,i)=>[...row,target[i]]);for(let col=0;col<n;col++){let pivot=col;for(let row=col+1;row<n;row++)if(Math.abs(a[row][col])>Math.abs(a[pivot][col]))pivot=row;if(Math.abs(a[pivot][col])<1e-10)throw Error('Singular totals regression.');[a[col],a[pivot]]=[a[pivot],a[col]];const divisor=a[col][col];for(let j=col;j<=n;j++)a[col][j]/=divisor;for(let row=0;row<n;row++)if(row!==col){const factor=a[row][col];for(let j=col;j<=n;j++)a[row][j]-=factor*a[col][j];}}return a.map(row=>row[n]);}
export function fitTotalRidge(rows:NflTotalFeatureRow[],features:TotalFeatureName[],lambda:number):TotalRidgeModel{assertIndependentTotalFeatures(features);if(rows.length<features.length+5||!finite(lambda)||lambda<=0)throw Error('Insufficient or invalid Phase 3B ridge fit.');const means:Record<string,number>={},scales:Record<string,number>={};for(const feature of features){means[feature]=rows.reduce((sum,row)=>sum+row.features[feature],0)/rows.length;scales[feature]=Math.sqrt(rows.reduce((sum,row)=>sum+(row.features[feature]-means[feature])**2,0)/rows.length)||1;}const size=features.length+1,xtx=Array.from({length:size},()=>Array(size).fill(0)),xty=Array(size).fill(0);for(const row of rows){const x=[1,...features.map(feature=>(row.features[feature]-means[feature])/scales[feature])];for(let i=0;i<size;i++){xty[i]+=x[i]*row.actualTotal;for(let j=0;j<size;j++)xtx[i][j]+=x[i]*x[j];}}for(let i=1;i<size;i++)xtx[i][i]+=lambda;const beta=solve(xtx,xty),coefficients:Record<string,number>={};for(let i=0;i<features.length;i++)coefficients[features[i]]=beta[i+1]/scales[features[i]];const intercept=beta[0]-features.reduce((sum,feature)=>sum+coefficients[feature]*means[feature],0);return{version:NFL_TOTAL_PHASE3B_VERSION,features:[...features],lambda,intercept,coefficients,means,scales,trainingN:rows.length,trainingHash:stableHash(rows.map(row=>[row.id,row.date,row.actualTotal,features.map(feature=>row.features[feature])]))};}
export const predictTotal=(model:TotalRidgeModel,row:NflTotalFeatureRow)=>model.intercept+model.features.reduce((sum,feature)=>sum+model.coefficients[feature]*row.features[feature],0);
export const evaluateTotal=(model:TotalRidgeModel,rows:NflTotalFeatureRow[])=>metrics(rows.map(row=>row.actualTotal),rows.map(row=>predictTotal(model,row)));
export function fitIncrementalTotalMarket(rows:NflTotalFeatureRow[],model:TotalRidgeModel){const eligible=rows.filter(row=>finite(row.marketTotal));if(eligible.length<20)throw Error('Insufficient total market rows.');const x=eligible.map(row=>[1,row.marketTotal!,predictTotal(model,row)]),size=3,xtx=Array.from({length:size},()=>Array(size).fill(0)),xty=Array(size).fill(0);for(let r=0;r<x.length;r++)for(let i=0;i<size;i++){xty[i]+=x[r][i]*eligible[r].actualTotal;for(let j=0;j<size;j++)xtx[i][j]+=x[r][i]*x[r][j];}xtx[1][1]+=1e-6;xtx[2][2]+=1e-6;const beta=solve(xtx,xty);return{intercept:beta[0],marketCoefficient:beta[1],modelCoefficient:beta[2],trainingN:eligible.length,trainingHash:stableHash(eligible.map(row=>[row.id,row.actualTotal,row.marketTotal,predictTotal(model,row)]))};}
export function selectTotalEnsembleWeight(validation:NflTotalFeatureRow[],model:TotalRidgeModel,step=.01){const rows=validation.filter(row=>finite(row.marketTotal));let best={weight:0,rmse:Infinity,mae:Infinity};for(let value=0;value<=1+1e-9;value+=step){const weight=Math.round(value*1000000)/1000000,m=metrics(rows.map(row=>row.actualTotal),rows.map(row=>weight*predictTotal(model,row)+(1-weight)*row.marketTotal!));if(m.rmse!<best.rmse-1e-12||Math.abs(m.rmse!-best.rmse)<1e-12&&weight<best.weight)best={weight,rmse:m.rmse!,mae:m.mae!};}return best;}
export function totalDisagreement(rows:NflTotalFeatureRow[],model:TotalRidgeModel){const eligible=rows.filter(row=>finite(row.marketTotal)),defs:[[number,number|null],...Array<[number,number|null]>]=[[0,1.5],[1.5,3],[3,5],[5,7],[7,10],[10,null]],buckets=defs.map(([from,to])=>{const selected=eligible.filter(row=>{const value=Math.abs(predictTotal(model,row)-row.marketTotal!);return value>=from&&(to===null||value<to);});return{from,to,...evaluateTotal(model,selected)};}),d=eligible.map(row=>predictTotal(model,row)-row.marketTotal!),e=eligible.map(row=>row.actualTotal-predictTotal(model,row)),dm=avg(d)??0,em=avg(e)??0,cov=d.reduce((sum,value,i)=>sum+(value-dm)*(e[i]-em),0),dv=d.reduce((sum,value)=>sum+(value-dm)**2,0),ev=e.reduce((sum,value)=>sum+(value-em)**2,0);return{n:eligible.length,buckets,correlation:dv&&ev?cov/Math.sqrt(dv*ev):null,regressionSlope:dv?cov/dv:null};}
export function totalOuDiagnostic(rows:NflTotalFeatureRow[],model:TotalRidgeModel){let wins=0,losses=0,pushes=0,units=0,priced=0;const prices:number[]=[];for(const row of rows){if(!finite(row.marketTotal))continue;const over=predictTotal(model,row)>row.marketTotal,price=over?row.overOdds:row.underOdds;if(!finite(price)||price===0)continue;priced++;prices.push(price);const margin=over?row.actualTotal-row.marketTotal:row.marketTotal-row.actualTotal;if(margin===0){pushes++;continue;}if(margin>0){wins++;units+=price>0?price/100:100/Math.abs(price);}else{losses++;units-=1;}}const decisions=wins+losses,winRate=decisions?wins/decisions:null;return{priced,wins,losses,pushes,winRate,units,roi:priced?units/priced:null,meanBreakEven:prices.length?avg(prices.map(price=>price>0?100/(price+100):Math.abs(price)/(Math.abs(price)+100))):null,label:'RECONSTRUCTED NFLVERSE TOTAL-LINE/PRICE DIAGNOSTIC — NOT AN ACTIONABLE BACKTEST'};}
