[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npx tsc || true"]

[start]
cmd = "node -r ts-node/register/transpile-only server.ts"
